import json,pathlib,hashlib,struct
out=pathlib.Path(__file__).parent;m=json.load(open('games/melee/state/knowledge_v2/semantic-sweep-20260908/manifest.json'));rev=m['head_revision'];tu='main/melee/gr/grtluigi';src='src/melee/gr/grtluigi.c';root=pathlib.Path(m['checkout_root']);rows=json.load(open(out/'facts.json'))
def ev(p,a,b,why):return {'kind':'code','locator':f'code://{rev}/{p}#L{a}-L{b}','why':why}
ranges={'.data':(11,47),'file':(1,142),'grTLuigi_80221C10':(49,49),'grTLuigi_80221C14':(51,54),'grTluigi_UnkStage0_OnLoad':(56,56),'grTluigi_UnkStage0_OnStart':(58,61),'grTLuigi_80221CAC':(63,66),'grTLuigi_80221CB4':(68,82),'grTLuigi_80221D9C':(84,88),'grTLuigi_80221DC8':(90,93),'grTLuigi_80221DD0':(95,95),'grTLuigi_80221DD4':(97,97),'grTLuigi_80221DD8':(99,102),'grTLuigi_80221E28':(104,107),'grTLuigi_80221E30':(109,113),'grTLuigi_80221E64':(115,115),'grTLuigi_80221E68':(117,120),'grTLuigi_80221EB8':(122,125),'grTLuigi_80221EC0':(127,130),'grTLuigi_80221EE0':(132,132),'grTLuigi_80221EE4':(134,137),'grTLuigi_80221EEC':(139,142)}
foreign=[('src/melee/gr/inlines.h',24,85),('src/melee/gr/types.h',131,185),('src/melee/gr/ground.c',817,884),('src/melee/gr/ground.c',1676,1737),('src/melee/gr/granime.c',988,1051),('src/melee/gr/grzakogenerator.c',313,362),('src/melee/lb/lb_00F9.c',939,994)]
extras={k:[] for k in ranges}
for k in ranges:extras[k]+=[ev(src,11,47,'Owned callback-table and lifecycle slot bindings.'),ev('src/melee/gr/types.h',131,171,'Current callback record and stage descriptor field order; no shared type changes proposed.'),ev('src/melee/gr/inlines.h',33,62,'Installer consumes init/proc/callback3, while target initializer requests IDs 0,1,2.')]
for k in ['grTLuigi_80221DD8','grTLuigi_80221E68']:extras[k].append(ev('src/melee/gr/inlines.h',24,30,'Inline performs joint setup and animation initialization.'))
extras['file'].append(ev('src/melee/gr/grzakogenerator.c',313,329,'Shared manager creation.'))
extras['grTLuigi_80221CB4'].append(ev('src/melee/gr/ground.c',817,858,'Ground GObj allocation and failure behavior.'))
extras['.data'].append(ev(src,68,82,'Diagnostic literals in source.'))
extras['grTLuigi_80221D9C'].append(ev('src/melee/gr/granime.c',988,1048,'Independent animation setup body.'))
for k in ['grTLuigi_80221E30','grTLuigi_80221EC0']:extras[k].append(ev('src/melee/gr/ground.c',1676,1732,'Collision joint processing only with zero per-map flag.'))
extras['grTLuigi_80221E30'].append(ev('src/melee/lb/lb_00F9.c',939,992,'Timed record scale, count, recycling and aggregate state.'))
extras['grTluigi_UnkStage0_OnStart'].append(ev('src/melee/gr/grzakogenerator.c',313,329,'Manager creation and failure cleanup.'))
changes={
('.data','inferred_type'):('Writable object .data contains an 80-byte StageCallbacks[4] at offset 0, the /GrTLg.dat string at offset 80, a 52-byte grTLg_StageData at offset 92, and diagnostic strings after offset 144. Three rows are populated and the fourth is zero-initialized. Existing source and split objects have section sizes 191 and 192 bytes respectively.','Object symbols and bytes disprove a structures-only or directly adjacent layout. Object provenance is recorded separately; no build was run.'),
('grTLuigi_80221CB4','data_flow'):('The argument indexes grTLg_803E8DF0 and is passed to Ground_GetStageGObj. A successful allocation is passed to Ground_SetupStageCallbacks, which clears x8/xC callbacks, configures the GX link, stores callback3, invokes on_init and schedules gobj_proc at priority 4. This installer does not consume callback1 or table flags. Failure logs the ID and returns NULL.','The current inline installs selected fields, not the entire record. Ground_GetStageGObj creates a new GObj.'),
('grTLuigi_80221CB4','state_behavior'):('No local range check precedes indexing the four-entry callback table. Normal Ground_InitTargetStage calls use IDs 0, 1 and 2. If Ground_GetStageGObj returns NULL, setup is skipped, a diagnostic is printed and NULL is returned; otherwise initialization executes before the process is scheduled.','Clarifies the caller-supplied index invariant and setup ordering.'),
('grTLuigi_80221C14','state_behavior'):('Calls the common target-stage initializer, which sets stage_info.unk8C.b4=false and b5=true, invokes the supplied local object installer for IDs 0,1,2, then calls Ground_801C39C0, Ground_801C3BB4, Ground_801C4210 and Ground_801C42AC in order. The wrapper returns no value and owns no timer.','Independent inline read exposes the concrete initialization sequence.'),
('grTLuigi_80221E30','state_behavior'):('Every invocation updates the shared LB records first, then calls Ground_801C2FE0 for the supplied GObj. The LB update decrements positive lifetimes and recycles records at zero. Ground collision work runs when Ground_804D6950[map_id] equals zero; its Boolean result is discarded.','Replace ambiguous disabled-state wording with the exact zero-flag guard.'),
('grTluigi_UnkStage0_OnStart','inferred_type'):('void(void) stage-start callback. It returns normally after calling grZakoGenerator_801CAE04(NULL), whose returned GObj pointer it discards.','The inherited non-returning wording could imply noreturn; the wrapper has ordinary void return semantics.'),
('file','purpose'):('Implements the TLuigi target-stage controller: exports the stage descriptor and callback array, initializes Ground objects 0,1,2 through the common target-stage helper, installs their selected callbacks and starts the shared Zako generator manager with a NULL spawn descriptor.','The source starts a shared manager, not a proven target-specific generator.'),
('file','state_behavior'):('Defines three populated component rows and a fourth zero-initialized row. The initializer explicitly requests only IDs 0,1,2; it does not scan for a terminator. Component 0 initializes animation, components 1 and 2 perform joint/animation setup, and component 2 adds the LB update before collision processing. All callback1 bodies return false; the local installer does not consume callback1 or table flags. The stage dynamics hook returns NULL and shadow-render hook returns true.','A zero row exists but terminator semantics are not established by this initializer.'),
('grTLuigi_80221EEC','purpose'):('Implements the StageData.on_check_shadow_render callback as an unconditional true result; none of its three arguments is inspected or mutated.','Current StageData field order identifies this previously generic stage predicate as the shadow-render check.'),
('grTLuigi_80221EEC','inferred_type'):('bool(Vec3*, int, HSD_JObj*) callback stored in StageData.on_check_shadow_render. The implementation ignores every argument; no finer selector domain follows from this body.','Retain exact signature and current slot identity without inventing a selector meaning.')}
for name,idx in [('grTLuigi_80221DC8',0),('grTLuigi_80221EB8',1),('grTLuigi_80221E28',2)]:
 changes[(name,'data_flow')]=(f'The function occupies callback1 in grTLg_803E8DF0[{idx}]. Its Ground_GObj argument is ignored and its only output is false. The local Ground_SetupStageCallbacks path does not install or invoke callback1; no active dispatch of this slot is established here.','Distinguish table membership from actual consumption by the current inline installer.')
proposal={'tu':tu,'proposal':{'facts':[],'links':[],'entities':[],'merges':[],'follow_ups':[]}};subjects=[];names=[]
for row in rows:
 key=next(iter(row['subject'].values()));name='file' if key==src else key.split(':')[-1].split('#')[0];a,b=ranges[name];e=[ev(src,a,b,'Complete owned definition or declaration.')]+extras[name]
 item={'subject':row['subject'],'canonical_range':[a,b],'facts':[]}
 if not row['facts']:
  item['disposition']='reviewed_no_existing_facts';item['review']='Parameter exists in canonical signature. '+('Unused by the body.' if name not in ['grTLuigi_80221CB4','grTLuigi_80221D9C','grTLuigi_80221DD8','grTLuigi_80221E30','grTLuigi_80221E68','grTLuigi_80221EC0'] else 'Flows into the local operations documented for its parent function.')
 for f in row['facts']:
  ch=changes.get((name,f['type']));d='supersede' if ch else 'retain';reason=ch[1] if ch else 'Current canonical implementation, table position and independently read helpers support this claim.'
  if not ch and f['type']=='game_mapping' and any(x in f['value'] for x in ['Stadium','Classic Mode','GameCube']):d='unresolved';reason='TLuigi target-stage role is supported; specific mode placement and visual course geometry require separately owned game-mode or asset evidence.'
  if name in ['grTLuigi_80221DC8','grTLuigi_80221EB8','grTLuigi_80221E28'] and f['type'] in ['inferred_type','purpose','state_behavior','game_mapping']:
   reason='Retain as callback-table slot/body description only. No actual invocation by the current installer is claimed.'
  if f['type']=='inferred_name':
   reason='Descriptive inferred alias is consistent with current callback-table slot. It is not an attested canonical rename.';names.append({'canonical':name,'alias':f['value'],'disposition':d,'fact_id':f['id'],'version':f['updated_at'],'evidence':e})
  item['facts'].append({'id':f['id'],'version':{'updated_at':f['updated_at'],'numeric_version':None},'type':f['type'],'value':f['value'],'disposition':d,'reason':reason,'evidence':e})
  if ch:proposal['proposal']['facts'].append({'subject':row['subject'],'type':f['type'],'op':'write','value':ch[0],'rationale':ch[1],'confidence':0.98,'evidence':e})
 subjects.append(item)
# Object evidence retained as artifact-level evidence because proposal helper accepts canonical code locators.
objects=[]
for suffix in ['obj','src']:
 p=root/f'build/GALE01/{suffix}/melee/gr/grtluigi.o';raw=p.read_bytes();h=struct.unpack_from('>16sHHIIIIIHHHHHH',raw);ss=[struct.unpack_from('>IIIIIIIIII',raw,h[6]+i*h[11]) for i in range(h[12])];d=raw[ss[2][4]:ss[2][4]+ss[2][5]];objects.append({'path':str(p),'sha256':hashlib.sha256(raw).hexdigest(),'section':'.data','flags':ss[2][2],'size':len(d),'symbols':{'grTLg_803E8DF0':{'offset':0,'size':80},'grTLg_StageData':{'offset':92,'size':52}},'archive_string':{'offset':80,'bytes':repr(d[80:92])},'tail_after_structures':{'offset':144,'bytes':repr(d[144:])},'provenance':'Existing checkout object, not rebuilt. Source revision correspondence not independently reproduced.'})
receipts=[]
for p,b in [(src,143),('src/melee/gr/grtluigi.h',35)]:
 a=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908/units/main__melee__gr__grtluigi/pages')/(p.replace('/','__')+f'.1-{b}.json');r=json.load(open(a))['rendered'];receipts.append({'path':p,'canonical_range':[1,b],'rendered_range':[1,b],'source_sha256':next(f['sha256'] for f in m['files'] if f['path']==p),'artifact':str(a),'render_metadata':r})
counts={'targets':21,'entities':19,'facts':sum(len(s['facts']) for s in subjects),'proposals':len(proposal['proposal']['facts'])}
counts['dispositions']={d:sum(f['disposition']==d for s in subjects for f in s['facts']) for d in ['retain','supersede','reject','unresolved']}
coverage={'campaign':m['campaign_id'],'tu':tu,'revision':rev,'reader':'grtluigi_leaf','subjects':subjects,'read_receipts':receipts,'supporting_canonical_reads':[{'path':p,'canonical_range':[a,b],'rendered_ranges':[],'sha256':hashlib.sha256((root/p).read_bytes()).hexdigest()} for p,a,b in foreign],'object_evidence':objects,'counts':counts,'exceptions':['Owned files fully exhausted; render final blank lines143/35 correspond to physical newline counts142/34.','Existing object source provenance not rebuilt; split object has one extra padding byte.'],'status':'complete local review; unresolved external mode/asset claims preserved for family review'}
(out/'coverage.json').write_text(json.dumps(coverage,indent=2)+'\n');(out/'proposal.json').write_text(json.dumps(proposal,indent=2)+'\n');(out/'object-evidence.json').write_text(json.dumps(objects,indent=2)+'\n')
text=['# Luigi Target Stage Review','',f'Pinned revision `{rev}`. Full canonical and rendered source L1-143 and header L1-35 reviewed.','', '## Functionality','', 'StageData binds Gr_Kind_TLuigi to /GrTLg.dat and a four-row callback array. Target-stage initialization sets two stage flags, creates IDs 0,1,2 through the local installer and runs four common setup helpers. Ground_GetStageGObj allocates a new GObj; failures are returned without callback setup. The local installer indexes before any bounds check, so its callers must provide valid IDs.','', 'The setup inline stores callback3, invokes on_init, and schedules gobj_proc after setting the GX link. It does not consume callback1 or the table flags. Three false-returning callback1 functions are registered in data, but that alone does not prove runtime dispatch. The zero fourth row is not scanned as a terminator by this initializer.','', 'Component 0 sets animation resources from its map ID. Components 1 and 2 use the joint initialization inline, then collision processing as their process callback; component 2 first services the global LB timed-record list. Empty process/cleanup callbacks have no effects. The dynamics query returns NULL; the shadow-render check always returns true. OnLoad is empty. OnStart calls the common Zako manager with NULL and ignores allocation failure.','', '## Data Section','', 'Existing source object .data is191 bytes; the split object is192. The callback array occupies offsets0-79, archive string begins at80, and StageData occupies92-143. Diagnostic strings follow. Object hashes and exact paths are in object-evidence.json. These files were inspected without building; source-to-object provenance was not reproduced.','', '## Per-Subject Review','']
for s in subjects:
 text+=['### '+next(iter(s['subject'].values())),'']
 if not s['facts']:text += [s['review'],'No existing facts.','']
 for f in s['facts']:text += [f"- `{f['id']}` at `{f['version']['updated_at']}`: {f['disposition']} {f['type']}. {f['reason']}"]
 text += ['']
(out/'findings.md').write_text('\n'.join(text)+'\n')
t=['# Naming Table','','| Canonical | Inferred alias | Disposition |','|---|---|---|']
for row in rows:
 if 'target_stable_key' not in row['subject']:continue
 k=row['subject']['target_stable_key'].split(':')[-1];f=next((x for x in row['facts'] if x['type']=='inferred_name'),None);t.append(f"| {k} | {f['value'] if f else 'none'} | {'retain inferred role; no source rename' if f else 'retain canonical identity'} |")
t+=['','Generic stageGObj aliases remain local reading hypotheses. Their global collision suitability is not accepted for source promotion. OnLoad and OnStart keep their existing canonical names. Exact alias IDs/timestamps/evidence are in coverage.json.'];(out/'naming-table.md').write_text('\n'.join(t)+'\n')
(out/'unresolved.md').write_text('# Unresolved and Family Boundaries\n\nSpecific Stadium/Classic placement and GameCube-shaped course geometry require independent game-mode/asset evidence. Each inherited claim is marked unresolved by fact ID in coverage.json.\n\nCallback1 runtime dispatch and flag consumption are not established by the local installer. The zero row has no demonstrated terminator role here. Generic stageGObj alias collision checks are required before any source-name promotion.\n\nShared StageData, StageCallbacks, Ground and LB record type naming remains with family owners. Existing object provenance was not reproduced by a build.\n');print(json.dumps(counts))
