import { useEffect, useMemo, useRef, useState } from "react";
import { fetchKnowledgeEntities, fetchKnowledgeRecord, fetchKnowledgeSearch, fetchKnowledgeUnitTargets, type KnowledgeEntity, type KnowledgeEvidence, type KnowledgeFact, type KnowledgeRecordResponse, type KnowledgeSearchHit, type KnowledgeUnitTargets, type SubjectIdentity } from "./api";
import { asTarget, codeLines, proposalConfidence, FACT_LABELS, identityExplanation, label, recordQuery, targetFromKey, type SourceFile, type SourceFileView, type SourceManifest } from "./browser-model";
import "./browser.css";

async function sourceJson<T>(game: string, file: string): Promise<T> {
  const response = await fetch(`/knowledge-source/${encodeURIComponent(game)}/${file.split("/").map(encodeURIComponent).join("/")}.json`);
  if (!response.ok || !response.headers.get("content-type")?.includes("json")) throw new Error("Source preview unavailable. Refresh the source export for this game.");
  return response.json() as Promise<T>;
}
const errorText = (error: unknown) => error instanceof Error ? error.message : String(error);
const pretty = (text: string) => text.replaceAll("_", " ");
const number = (n: number) => n.toLocaleString();
const date = (s: string) => new Date(s).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"});

function Notice({children, error=false}: {children: React.ReactNode; error?: boolean}) { return <div className={`kb-notice ${error ? "is-error" : ""}`} role={error ? "alert" : "status"}>{children}</div>; }

function Navigator({game,manifest,onFile,onSubject,file,close,aliases}: {aliases:Record<string,string>;game:string;manifest:SourceManifest|null;onFile:(f:SourceFile)=>void;onSubject:(s:SubjectIdentity)=>void;file:string;close:()=>void}) {
  const [section,setSection]=useState("files"); const [query,setQuery]=useState(""); const [limit,setLimit]=useState(60);
  const [hits,setHits]=useState<KnowledgeSearchHit[]|null>(null); const [entities,setEntities]=useState<KnowledgeEntity[]|null>(null); const [error,setError]=useState("");
  useEffect(()=>{let live=true;setLimit(60);setError("");setHits(null);setEntities(null);const timer=setTimeout(()=>{
    if(section==="search" && query.trim().length>=2) void fetchKnowledgeSearch(query,game).then(r=>{if(live)setHits(r.hits)},e=>{if(live)setError(errorText(e))});
    else if(section!=="files" && section!=="search") void fetchKnowledgeEntities(section as Parameters<typeof fetchKnowledgeEntities>[0],game,{q:query,limit:500}).then(r=>{if(live)setEntities(r.entities)},e=>{if(live)setError(errorText(e))});
  },200);return()=>{live=false;clearTimeout(timer)}},[section,query,game]);
  const files=useMemo(()=>manifest?.files.filter(f=>f.path.toLowerCase().includes(query.toLowerCase()))??[],[manifest,query]);
  return <div className="kb-navigator">
    <div className="kb-panel-heading"><strong>Browse knowledge</strong><button className="kb-icon-button" onClick={close} aria-label="Close browser">×</button></div>
    <label className="kb-search"><span>⌕</span><input aria-label="Filter knowledge browser" value={query} onChange={e=>setQuery(e.target.value)} placeholder={section==="files"?"Find a file…":"Find a name or idea…"}/></label>
    <select className="kb-select" aria-label="Browse category" value={section} onChange={e=>setSection(e.target.value)}>
      <option value="files">Source files</option><option value="search">Search all knowledge</option><option value="game_concept">Game concepts</option><option value="pattern">Implementation patterns</option><option value="struct">Structures</option><option value="struct_field">Structure fields</option><option value="parameter">Function parameters</option><option value="translation_unit">Translation units</option>
    </select>
    <div className="kb-nav-list">
      {error?<Notice error>{error}</Notice>:section==="files"?<><div className="kb-small-label">{number(files.length)} files · source snapshot</div>{files.slice(0,limit).map(f=><button className={`kb-file ${f.path===file?"selected":""}`} key={f.path} onClick={()=>onFile(f)}><span className="kb-file-icon">{f.path.endsWith(".h")?"H":"C"}</span><span><strong>{f.path.split("/").at(-1)}</strong><small>{f.path.replace(/^src\//,"").split("/").slice(0,-1).join("/")}</small></span><em>{f.targets||""}</em></button>)}{files.length===0&&manifest?<Notice>No files match this filter.</Notice>:null}{!manifest?<Notice>Loading source catalog…</Notice>:null}{limit<files.length?<button className="kb-more" onClick={()=>setLimit(n=>n+100)}>Show next 100 files</button>:null}</>:section==="search"?<>{query.trim().length<2?<Notice>Search by canonical name, proposed name, or what something does.</Notice>:hits===null?<Notice>Searching…</Notice>:hits.length===0?<Notice>No matching knowledge.</Notice>:<><div className="kb-small-label">{hits.length} results{hits.length===100?" · refine to narrow":""}</div>{hits.map((hit,i)=><button className="kb-search-hit" key={`${hit.subject.id}:${i}`} onClick={()=>onSubject(hit.subject)}><small>{pretty(hit.subject.kind)}{hit.fact_type?` · ${FACT_LABELS[hit.fact_type]??pretty(hit.fact_type)}`:""}</small><strong>{label(hit.subject)}</strong>{aliases[hit.subject.subjectKind==="target"?hit.subject.stableKey:hit.subject.locator]?<span className="kb-alias">Proposed: {aliases[hit.subject.subjectKind==="target"?hit.subject.stableKey:hit.subject.locator]}</span>:null}<p>{hit.snippet.replace(/<[^>]*>/g,"")}</p></button>)}</>}</>:entities===null?<Notice>Loading records…</Notice>:<><div className="kb-small-label">{entities.length} results{entities.length===500?" · filter to find more":""}</div>{entities.slice(0,limit).map(entity=><button className="kb-search-hit" key={entity.id} onClick={()=>onSubject({subjectKind:"entity",id:entity.id,kind:entity.kind,locator:entity.locator,identityStatus:entity.identity_status})}><strong>{entity.locator.split(/[/:]/).filter(Boolean).at(-1)}</strong>{aliases[entity.locator]?<span className="kb-alias">Proposed: {aliases[entity.locator]}</span>:null}<small>{entity.fact_count} facts · {entity.link_count} relationships</small><p>{entity.locator}</p></button>)}{entities.length===0?<Notice>No records match this filter.</Notice>:null}{limit<entities.length?<button className="kb-more" onClick={()=>setLimit(n=>n+100)}>Show more records</button>:null}</>}
    </div>
  </div>;
}

function FileTree({files,selected,onFile,aliases}: {files:SourceFile[];selected:string;onFile:(file:SourceFile)=>void;aliases:Record<string,string>}) {
  const [filter,setFilter]=useState("");
  const [expanded,setExpanded]=useState<Set<string>>(()=>new Set(["src","src/melee","src/melee/cm"]));
  useEffect(()=>{setExpanded(current=>{const next=new Set(current);const parts=selected.split("/");for(let i=1;i<parts.length;i++)next.add(parts.slice(0,i).join("/"));return next})},[selected]);
  const visible=useMemo(()=>files.filter(f=>f.path.toLowerCase().includes(filter.toLowerCase())),[files,filter]);
  function branch(prefix:string,depth:number):React.ReactNode {
    const children=new Map<string,SourceFile|null>();
    for(const file of visible){if(!file.path.startsWith(prefix))continue;const rest=file.path.slice(prefix.length);const slash=rest.indexOf("/");children.set(slash<0?rest:rest.slice(0,slash),slash<0?file:null)}
    return [...children].sort(([a,af],[b,bf])=>Number(!!af)-Number(!!bf)||a.localeCompare(b)).map(([name,file])=>{const path=prefix+name;const open=!!filter||expanded.has(path);return file?<button key={path} className={`kb-tree-row ${selected===path?"selected":""}`} style={{paddingLeft:12+depth*14}} title={path} aria-current={selected===path?"page":undefined} onClick={()=>onFile(file)}><span className="kb-tree-file-icon">{name.endsWith(".h")?"h":"c"}</span><span>{name}{aliases[path]?<small className="kb-alias"> → {aliases[path]} <em>proposed</em></small>:null}</span></button>:<div key={path}><button className="kb-tree-row kb-tree-folder" style={{paddingLeft:12+depth*14}} aria-expanded={open} onClick={()=>setExpanded(current=>{const next=new Set(current);if(next.has(path))next.delete(path);else next.add(path);return next})}><span>{open?"⌄":"›"}</span><span>{name}</span></button>{open?branch(path+"/",depth+1):null}</div>})
  }
  return <><div className="kb-panel-heading"><strong>EXPLORER</strong><span>{files.length} files</span></div><input className="kb-tree-filter" aria-label="Filter files" placeholder="Filter files" value={filter} onChange={e=>setFilter(e.target.value)}/><nav className="kb-tree" aria-label="Source files">{branch("",0)}{!visible.length?<Notice>No matching files.</Notice>:null}</nav></>;
}

function SourceReader({source,error,selected,onSubject,jumpLine,onLine,compact=false}: {source:SourceFileView|null;error:string;selected:SubjectIdentity|null;onSubject:(s:SubjectIdentity)=>void;jumpLine:number;onLine:(n:number)=>void;compact?:boolean}) {
  const codeScroll=useRef<HTMLDivElement>(null);
  const [proposed,setProposed]=useState(true); const [find,setFind]=useState("");
  const [scrollTop,setScrollTop]=useState(0);const [viewportHeight,setViewportHeight]=useState(800);
  const lastMatch=useRef(-1);const lineHeight=21;
  const lines=useMemo(()=>source?codeLines(proposed?source.rendered:source.canonical,source.symbols,proposed):[],[source,proposed]);
  useEffect(()=>{const container=codeScroll.current;if(!container)return;const observer=new ResizeObserver(()=>setViewportHeight(container.clientHeight));observer.observe(container);setViewportHeight(container.clientHeight);return()=>observer.disconnect()},[source]);
  useEffect(()=>{setFind("");lastMatch.current=-1;setScrollTop(0);if(codeScroll.current){codeScroll.current.scrollTop=0;codeScroll.current.scrollLeft=0}},[source?.path]);
  useEffect(()=>{if(jumpLine&&codeScroll.current)codeScroll.current.scrollTop=Math.max(0,(jumpLine-3)*lineHeight)},[source?.path,jumpLine]);
  const active=selected?.subjectKind==="target"?selected.stableKey:null;
  const start=Math.max(0,Math.floor(scrollTop/lineHeight)-30);
  const end=Math.min(lines.length,start+Math.ceil(viewportHeight/lineHeight)+60);
  const shown=lines.slice(start,end);
  const sourceWidth=useMemo(()=>Math.max(80,...lines.map(line=>line.reduce((n,t)=>n+t.text.replaceAll("\t","    ").length,0))),[lines]);
  function findNext(){if(!find.trim())return;const lower=find.toLowerCase();const matches=lines.map(line=>line.map(t=>t.text).join("").toLowerCase());let match=matches.findIndex((line,i)=>i>lastMatch.current&&line.includes(lower));if(match<0)match=matches.findIndex(line=>line.includes(lower));if(match>=0){lastMatch.current=match;onLine(match+1);if(codeScroll.current)codeScroll.current.scrollTop=Math.max(0,(match-2)*lineHeight)}}
  if(error)return <Notice error>{error}</Notice>;if(!source)return <Notice>Loading source…</Notice>;
  return <section className="kb-source" aria-label="Source reader">
    <div className="kb-source-toolbar"><div><span className="kb-small-label">{source.path.endsWith(".h")?"Header":"C source"}</span><strong>{source.path.split("/").at(-1)}</strong></div><div className="kb-toggle" aria-label="Source naming"><button aria-pressed={!proposed} onClick={()=>setProposed(false)}>Canonical</button><button aria-pressed={proposed} onClick={()=>setProposed(true)}>Proposed names</button></div></div>
    <div className="kb-name-legend"><span>Canonical identifier</span><span className="kb-alias">Proposed name · hover for confidence</span></div><form className="kb-find" onSubmit={e=>{e.preventDefault();findNext()}}><input aria-label="Find in source" placeholder="Find in this file…" value={find} onChange={e=>{setFind(e.target.value);lastMatch.current=-1}}/><button type="submit">Find next</button><span>{number(lines.length)} lines</span></form>
    <div className="kb-code-scroll" ref={codeScroll} onScroll={e=>setScrollTop(e.currentTarget.scrollTop)} tabIndex={0} aria-label="Scrollable source file"><pre className="kb-code" style={{height:lines.length*lineHeight,padding:0,minWidth:`calc(${sourceWidth}ch + 80px)`,position:"relative"}}><div style={{position:"absolute",top:start*lineHeight,left:0,right:0}}>{shown.map((tokens,i)=>{const n=start+i+1;return <div key={n} data-line={n} className={`kb-code-line ${n===jumpLine?"jump-line":""}`}><span className="kb-line-number">{n}</span><code>{tokens.map((token,j)=>token.subject?<button key={j} className={`kb-code-symbol ${token.text!==token.canonical?"is-proposed":"is-canonical"} ${token.subject===active?"active":""}`} title={`${token.text!==token.canonical?"Proposed: "+token.text+" · "+proposalConfidence(token.confidence)+" · Canonical: ":"Canonical: "}${token.canonical} · Open knowledge`} onClick={()=>{onLine(0);onSubject(targetFromKey(token.subject!))}}>{token.text}</button>:<span key={j} className={`kb-token-${token.tone}`}>{token.text}</span>)}</code></div>})}</div></pre></div>
    <div className="kb-pagination"><span>{number(lines.length)} lines · Read-only</span><span>{proposed?"Proposed names":"Canonical names"}</span></div>
  </section>;
}

function Fact({type,fact,onEvidence}: {type:string;fact:KnowledgeFact;onEvidence:(e:KnowledgeEvidence)=>void}) { const [open,setOpen]=useState(false);return <details className="kb-fact"><summary className="kb-fact-label"><h3>{FACT_LABELS[type]??pretty(type)}</h3><span className={fact.confidence<0.7?"uncertain":""} title="Recorded confidence, not a guarantee of correctness">{Math.round(fact.confidence*100)}% confidence</span></summary><div className={`kb-fact-value ${type==="inferred_name"||type==="inferred_type"?"mono":""}`}>{fact.value}</div>{type==="inferred_name"?<small className="kb-muted">A hypothesis for reading; the canonical symbol is unchanged.</small>:null}<button className="kb-text-button" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?"Hide reasoning & sources":"Reasoning & sources"} <span>{fact.evidence.length}</span></button>{open?<div className="kb-fact-proof">{fact.rationale?<p>{fact.rationale}</p>:null}{fact.evidence.map((e,i)=><button className="kb-evidence-link" key={e.id} onClick={()=>onEvidence(e)}><span>{String(i+1).padStart(2,"0")}</span><div><strong>{pretty(e.kind)}</strong><small>{e.why||e.locator}</small></div><span>↗</span></button>)}<small className="kb-muted">Updated {date(fact.updated_at)}</small></div>:null}</details>}

function RecordInspector({record,loading,error,onSubject,onEvidence,mode="panel",aliases,children}: {aliases:Record<string,string>;children?:React.ReactNode;record:KnowledgeRecordResponse|null;loading:boolean;error:string;onSubject:(s:SubjectIdentity)=>void;onEvidence:(e:KnowledgeEvidence)=>void;mode?:"panel"|"article"}) {
  const [tab,setTab]=useState("facts");const [relatedLimit,setRelatedLimit]=useState(12);
  useEffect(()=>{setTab("facts");setRelatedLimit(12)},[record?.subject.id]);
  if(loading)return <Notice>Loading the knowledge record…</Notice>;if(error)return <Notice error>{error}</Notice>;if(!record)return <Notice>Select a function, data target, type, or game concept.</Notice>;
  const {subject}=record;const facts=Object.entries(record.facts).sort(([a],[b])=>Object.keys(FACT_LABELS).indexOf(a)-Object.keys(FACT_LABELS).indexOf(b));
  return <section className={`kb-inspector kb-inspector-${mode}`} aria-label="Selected knowledge">
    <header className="kb-record-header"><span className="kb-eyebrow">{subject.subjectKind==="target"?"Target":"Entity"} / {pretty(subject.kind)}</span><span className="kb-canonical-label">Canonical name</span><h2>{label(subject)}</h2>{record.facts.inferred_name?<div className="kb-proposed">Proposed name · hypothesis <strong>{record.facts.inferred_name.value}</strong><span className="kb-proposal-confidence">{proposalConfidence(record.facts.inferred_name.confidence)}</span><small className="kb-proposal-explainer">A possible name, not a confirmed identity. Low-confidence proposals remain visible.</small></div>:null}<div className="kb-record-meta"><span>{facts.length} facts</span><span>{record.links.length} relationships</span>{record.target_status?.match_pct!=null?<span className="kb-matched">{String(record.target_status.match_pct)}% matched</span>:null}</div></header>
    <div className="kb-record-tabs" role="tablist" aria-label="Knowledge details">{[["facts","Overview"],["relations","Related"],["history","History"],["identity","Identity"]].map(([id,name])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{name}</button>)}</div>
    <div className="kb-record-body">
      {tab==="facts"?<><div className="kb-overview-identity"><code>{subject.subjectKind==="target"?subject.stableKey:subject.locator}</code>{!record.facts.inferred_name?<p className="kb-muted">No proposed name recorded. The displayed name is canonical.</p>:null}<p className="kb-muted">Knowledge below contains recorded interpretations and confidence scores, not canonical source declarations.</p></div>{children}<div className="kb-overview-heading">Collected knowledge</div>{facts.length?facts.map(([type,fact])=><Fact key={fact.id} type={type} fact={fact} onEvidence={onEvidence}/>):<Notice>No facts have been recorded for this subject yet. Its identity and history are still available.</Notice>}<details className="kb-members" key={`related:${subject.id}`}><summary>Related knowledge · {record.links.length}</summary>{record.links.slice(0,relatedLimit).map(link=><button className="kb-relation" key={link.direction+link.id} onClick={()=>onSubject(link.other)}><small>{pretty(link.role)} · {pretty(link.other.kind)}</small><strong>{label(link.other)}</strong>{aliases[link.other.subjectKind==="target"?link.other.stableKey:link.other.locator]?<span className="kb-alias">Proposed: {aliases[link.other.subjectKind==="target"?link.other.stableKey:link.other.locator]}</span>:null}<p>{link.why}</p></button>)}{record.links.length>relatedLimit?<button className="kb-more" onClick={()=>setRelatedLimit(n=>n+30)}>Show more relationships</button>:null}</details></>:null}
      {tab==="relations"?<><p className="kb-help">Follow a relationship to inspect the connected record. These are recorded knowledge links, not a complete call graph.</p>{record.links.slice(0,relatedLimit).map(link=><button className="kb-relation" key={`${link.direction}:${link.id}`} onClick={()=>onSubject(link.other)}><small>{link.direction==="incoming"?"←":"→"} {pretty(link.role)} · {pretty(link.other.kind)}</small><strong>{label(link.other)}</strong><p>{link.why}</p></button>)}{!record.links.length?<Notice>No relationships recorded.</Notice>:null}{record.links.length>relatedLimit?<button className="kb-more" onClick={()=>setRelatedLimit(n=>n+30)}>Show more relationships · {record.links.length-relatedLimit} remaining</button>:null}</>:null}
      {tab==="identity"?<><div className="kb-definition"><h3>What is this?</h3><p>{identityExplanation(subject)}</p></div><dl className="kb-identity"><dt>Canonical identity</dt><dd>{subject.subjectKind==="target"?subject.stableKey:subject.locator}</dd><dt>Status</dt><dd>{pretty(subject.identityStatus||"current")}</dd>{subject.subjectKind==="target"?<><dt>Translation unit</dt><dd>{subject.unit}</dd><dt>Address</dt><dd>{subject.address??"Not recorded"}</dd></>:null}<dt>Last librarian review</dt><dd>{record.indexed_at?date(record.indexed_at):"Not yet reviewed"}</dd></dl></>:null}
      {tab==="history"?<><p className="kb-help">{record.ledger.total_count} historical entries. {record.ledger.total_count>record.ledger.entries.length?`The API supplies the latest ${record.ledger.entries.length}.`:""}</p>{record.ledger.entries.map(entry=><article className="kb-history" key={`${entry.type}:${entry.id}`}><small>{date(entry.timestamp)} · {pretty(entry.type)}</small><p>{entry.type==="submission"?entry.description:entry.summary}</p>{entry.type==="pull_request"?<a href={`https://github.com/doldecomp/melee/pull/${entry.prRef.match(/\d+$/)?.[0]??""}`} target="_blank" rel="noreferrer">{entry.prRef} ↗</a>:null}</article>)}{!record.ledger.entries.length?<Notice>No history recorded.</Notice>:null}</>:null}
    </div>
  </section>;
}

export function KnowledgeBrowser({game: requestedGame}:{game?:string}) {
  const game=requestedGame||"melee";

  const [index,setIndex]=useState<{aliases:Record<string,string>;entities:Array<{id:string;kind:string;locator:string;parent:string|null}>}>({aliases:{},entities:[]});
  const [manifest,setManifest]=useState<SourceManifest|null>(null);const [catalogError,setCatalogError]=useState("");
  const [file,setFile]=useState<SourceFile|null>(null);const [source,setSource]=useState<SourceFileView|null>(null);const [sourceError,setSourceError]=useState("");const [unit,setUnit]=useState<KnowledgeUnitTargets|null>(null);
  const [selected,setSelected]=useState<SubjectIdentity|null>(null);const [record,setRecord]=useState<KnowledgeRecordResponse|null>(null);const [loading,setLoading]=useState(false);const [recordError,setRecordError]=useState("");
  const [browse,setBrowse]=useState(false);const [jumpLine,setJumpLine]=useState(0);const [evidence,setEvidence]=useState<KnowledgeEvidence|null>(null);const [copied,setCopied]=useState(false);const [refresh,setRefresh]=useState(0);const [history,setHistory]=useState<SubjectIdentity[]>([]);
  useEffect(()=>{let live=true;void sourceJson<typeof index & {confidence?:Record<string,number>}>(game,"knowledge-index").then(i=>{if(live)setIndex({...i,aliases:Object.fromEntries(Object.entries(i.aliases).map(([key,name])=>[key,`${name} · ${proposalConfidence(i.confidence?.[key])}`]))})},()=>{});return()=>{live=false}},[game,refresh]);
  useEffect(()=>{let live=true;setSelected(null);setRecord(null);setManifest(null);setFile(null);setHistory([]);setCatalogError("");void sourceJson<SourceManifest>(game,"manifest").then(m=>{if(!live)return;setManifest(m);setFile(m.files.find(f=>f.path==="src/melee/cm/camera.c")??m.files.find(f=>f.unit)??m.files[0]??null)},e=>{if(live)setCatalogError(errorText(e))});return()=>{live=false}},[game]);
  useEffect(()=>{let live=true;setSource(null);setSourceError("");setUnit(null);if(!file)return;void sourceJson<SourceFileView>(game,file.path).then(s=>{if(live)setSource(s)},e=>{if(live)setSourceError(errorText(e))});if(file.unit)void fetchKnowledgeUnitTargets(file.unit,game).then(u=>{if(!live)return;setUnit(u);setSelected(current=>current??(u.unit_entity?{subjectKind:"entity",id:u.unit_entity.id,kind:"translation_unit",locator:u.unit_entity.locator,identityStatus:"active"}:null))},e=>{if(live)setSourceError(errorText(e))});return()=>{live=false}},[file,game]);
  useEffect(()=>{let live=true;setRecord(null);setRecordError("");setEvidence(null);if(!selected){setLoading(false);return}setLoading(true);void fetchKnowledgeRecord(game,recordQuery(selected)).then(r=>{if(live)setRecord(r)},e=>{if(live)setRecordError(errorText(e))}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[selected,game,refresh]);
  function openSubject(subject:SubjectIdentity,keepFile=false){if(selected)setHistory(h=>[...h.slice(-19),selected]);setSelected(subject);setJumpLine(0);const found=manifest?.files.find(f=>subject.subjectKind==="target"?f.unit===subject.unit:f.path===subject.locator);if(!keepFile&&found&&found.path!==file?.path)setFile(found);setBrowse(false)}
  function openFile(f:SourceFile){setJumpLine(0);if(f.path===file?.path){if(unit?.unit_entity)setSelected({subjectKind:"entity",id:unit.unit_entity.id,kind:"translation_unit",locator:unit.unit_entity.locator,identityStatus:"active"});setBrowse(false);return}setSelected(null);setFile(f);setBrowse(false);setHistory([])}

  function back(){const previous=history.at(-1);if(!previous)return;setHistory(h=>h.slice(0,-1));setSelected(previous);const found=manifest?.files.find(f=>previous.subjectKind==="target"?f.unit===previous.unit:f.path===previous.locator);if(found)setFile(found)}
  function showEvidence(e:KnowledgeEvidence){setEvidence(e);setCopied(false)}
  const entityChildren=index.entities.filter(e=>selected?.subjectKind==="target"?e.locator.startsWith(selected.stableKey+"#"):selected?.subjectKind==="entity"?e.parent===selected.locator:false);
  const ownedTargets=selected?.subjectKind==="entity"&&selected.kind==="translation_unit"?unit?.targets??[]:[];
  const contents=<details className="kb-members"><summary>{ownedTargets.length?"Functions and data":"Members and parameters"} · {ownedTargets.length+entityChildren.length}</summary><div className="kb-subject-list">{ownedTargets.map(t=><button key={t.stable_key} onClick={()=>openSubject(asTarget(unit!.unit,t))}><small>{t.kind} · {t.fact_count} facts</small><strong>{t.symbol}</strong><span className={index.aliases[t.stable_key]?"kb-alias":"kb-muted"}>{index.aliases[t.stable_key]?"Proposed: "+index.aliases[t.stable_key]:"No proposed name"}</span></button>)}{entityChildren.map(e=><button key={e.id} onClick={()=>openSubject({subjectKind:"entity",...e,identityStatus:"active"})}><small>{pretty(e.kind)}</small><strong>{e.locator.split("#").at(-1)}</strong><span className={index.aliases[e.locator]?"kb-alias":"kb-muted"}>{index.aliases[e.locator]?"Proposed: "+index.aliases[e.locator]:"No proposed name"}</span></button>)}</div></details>;
  const inspector=<RecordInspector aliases={index.aliases} children={contents} record={record} loading={loading} error={recordError} onSubject={openSubject} onEvidence={showEvidence} mode="panel"/>;
  const reader=<SourceReader key={file?.path??"empty"} source={source?.path===file?.path?source:null} error={sourceError} selected={selected} onSubject={s=>openSubject(s,true)} jumpLine={jumpLine} onLine={setJumpLine}/>;
  const codeEvidence=evidence? /^code:\/\/([^/]+)\/(.+?)#L(\d+)(?:-L?(\d+))?$/.exec(evidence.locator):null;
  return <div className="kb-lab kb-editor">
    <div className="kb-editor-title"><strong>Knowledge</strong><span>{game}</span><span className="kb-revision">Source snapshot {manifest?.revision.slice(0,10)??"…"} · KB live</span></div>
    {catalogError?<Notice error>{catalogError}</Notice>:null}
    <div className="kb-editor-layout">
      <aside className="kb-explorer"><FileTree aliases={index.aliases} files={manifest?.files??[]} selected={file?.path??""} onFile={openFile}/><button className="kb-explorer-search" onClick={()=>setBrowse(true)}>Search knowledge…</button></aside>
      <main className="kb-editor-main"><div className="kb-editor-tab">{file?.path.split("/").at(-1)??"Source"}<span>Canonical file · read-only</span>{file&&index.aliases[file.path]?<span className="kb-alias">Proposed: {index.aliases[file.path]}</span>:null}</div><div className="kb-editor-path">{file?.path}</div>{reader}</main>
      <aside className="kb-inspector-rail"><div className="kb-panel-heading"><strong>KNOWLEDGE</strong><div><button className="kb-icon-button" onClick={back} disabled={!history.length} aria-label="Back to previous knowledge record">←</button><button className="kb-icon-button" onClick={()=>setRefresh(n=>n+1)} aria-label="Refresh selected knowledge">↻</button></div></div><select className="kb-symbol-select" aria-label="File symbols" value={selected?.subjectKind==="target"?selected.stableKey:""} onChange={e=>{const target=unit?.targets.find(t=>t.stable_key===e.target.value);if(target)openSubject(asTarget(unit!.unit,target));else if(file)openFile(file)}}><option value="">File overview</option>{unit?.targets.map(t=><option key={t.stable_key} value={t.stable_key}>{t.symbol??t.kind}{index.aliases[t.stable_key]?" → "+index.aliases[t.stable_key]+" [proposed]":" [canonical]"}</option>)}</select>{inspector}</aside>
    </div>
    {browse?<><button className="kb-nav-scrim" aria-label="Close knowledge browser" onClick={()=>setBrowse(false)}/><aside className="kb-nav-overlay"><Navigator aliases={index.aliases} game={game} manifest={manifest} file={file?.path??""} onFile={openFile} onSubject={openSubject} close={()=>setBrowse(false)}/></aside></>:null}
    {evidence?<div className="kb-evidence-modal" role="dialog" aria-modal="true" aria-label="Evidence details" onKeyDown={e=>{if(e.key==="Escape")setEvidence(null);if(e.key==="Tab"){const buttons=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>("button:not(:disabled)"));const first=buttons[0];const last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><button className="kb-modal-scrim" aria-label="Close evidence" onClick={()=>setEvidence(null)}/><section className="kb-evidence-sheet"><div className="kb-panel-heading"><strong>{pretty(evidence.kind)} evidence</strong><button autoFocus className="kb-icon-button" aria-label="Close evidence details" onClick={()=>setEvidence(null)}>×</button></div><h2>Why this supports the claim</h2><p>{evidence.why||"No additional explanation recorded."}</p><code className="kb-evidence-locator">{evidence.locator}</code><small className="kb-muted">Captured {date(evidence.captured_at)}</small><div className="kb-evidence-actions"><button onClick={()=>{void navigator.clipboard.writeText(evidence.locator).then(()=>setCopied(true),()=>setCopied(false))}}>{copied?"Copied":"Copy reference"}</button>{codeEvidence?<button onClick={()=>{const f=manifest?.files.find(f=>f.path===codeEvidence[2]);if(f){setFile(f);setJumpLine(Number(codeEvidence[3]));setEvidence(null)}}} disabled={!manifest?.files.some(f=>f.path===codeEvidence[2])}>Open current source at line {codeEvidence[3]}</button>:null}</div>{codeEvidence?<p className="kb-help">Citation revision: {codeEvidence[1]}. The source reader shows snapshot {manifest?.revision.slice(0,10)}; changed lines may differ.</p>:<p className="kb-help">This is the stored citation and its rationale. Copy its reference to resolve the complete archival record with the knowledge tools.</p>}</section></div>:null}
  </div>;
}
