from pathlib import Path
import json,hashlib,datetime
p=Path(__file__).parent;r=Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');m=json.loads((r/'manifest.json').read_text());tu='main/sysdolphin/baselib/sislib';task=next(t for t in m['tasks'] if t['tu']==tu);state=r/'units'/task['id'];src=task['source_path'];rev=m['head_revision'];groups=json.loads((p/'baseline-facts.json').read_text());facts=[dict(f,subject=g['subject']) for g in groups for f in g['facts']];eh=hashlib.sha256((p/'compiled-evidence.json').read_bytes()).hexdigest();b='src/sysdolphin/baselib/'
changes={
4:'Five archive/SIS-pointer pairs start NULL. Loading stores the new archive and then public symbol before checking either result; failures report and panic. Loading an occupied slot does not release its old archive. Cleanup clears both pointers only when the archive pointer is non-NULL; an inconsistent NULL-archive/non-NULL-SIS slot is left unchanged. Font indices are not validated.',
7:'Existing source .data is 212 bytes and split .data is 216 bytes: two 20-byte HSD_WObjDesc records at offsets 0 and 20, one 56-byte HSD_CameraDescPerspective at 40, and six diagnostic/file-name strings starting at 96,116,128,144,160,188. Split allocation adds four trailing zero padding bytes. This section contains no glyph atlas or kerning array.',
8:'Stores the default eye/interest and camera descriptors plus allocation, camera-lookup and archive diagnostic strings and the sislib.c panic filename. The camera descriptor is consumed by optional context-camera creation. Glyph atlas ownership is separate in sislib_font.c.',
13:'Initialization creates one free block and clears all object roots. Reset requests text and context destruction, clears context and used roots and rebuilds the saved arena. Text-list emptying depends on GObj destruction callbacks: GObj removal may defer for the current object. Shutdown frees the saved arena without clearing its pointer. These routines do not establish safe arbitrary reentrant lifecycle use.',
14:'The four f32 constants 0,1,-480,640 feed explicit text defaults, active width/height reset and HSD_CObjSetOrtho. Constructor position and box fields come from caller arguments, not zero/unit literals. The existing source and split pools are 16 identical bytes.',
15:'Supplies text defaults and fallback orthographic camera bounds for SisLib UI presentation. This 16-byte pool does not own the split renderer scalar set.',
16:'Four compiler-emitted f32 values at offsets 0,4,8,12: 0,1,-480,640. Existing source and split .sdata2 are both 16 bytes with identical contents. Source ELF flags include WRITE; split flags are ALLOC only. No owned code writes these constants.',
17:'Supplies scalar 0,1,-480,640 for text-state initialization and optional 640-by-480 orthographic camera setup. The current unit has no glyph-rendering implementation.',
27:'Allocates and partially initializes an HSD_Text, appends it to the global text list, and optionally configures a rendering GObj from a selected per-font context. It sets construction defaults but leaves active working fields such as x60, current_width/current_height, x78/x80, x88, active_color, x90/x92, x94/x98 and active fitting/kerning/alignment for later setup.',
28:'Negative context_id skips lookup and leaves entity NULL. Nonnegative IDs count matching font entries, but cam_entry->xA is read before the NULL test, so missing contexts do not have a safe NULL-return path. GObj_Create is passed to GX setup without a local NULL check. Text construction sets visible/white/transparent/unit-scale defaults and truncates font_idx to u8; it is not full-structure zero initialization.',
34:'No matching text means no change. On a match, entity-less text is unlinked/freed directly. Otherwise GObj removal is requested and curr->entity is then cleared. The generic removal routine can either invoke the registered text destructor immediately or defer current-GObj removal. Thus this body can write entity after the text storage has been returned to the arena, or clear entity while callback removal remains pending.',
40:'Visits saved successors until NULL. Each entity-less node is directly removed. Entity-bearing nodes request GObj removal followed by an entity=NULL write; generic GObj removal can defer, so completion does not by itself prove the text list is empty. Immediate callback removal returns text storage to the private arena before that field write.',
45:'Requests destruction of font-matching texts and camera GObjs and frees matching context entries. The context phase unconditionally advances last to curr even after freeing it; consecutive matches therefore repair links through released storage and need not leave a correctly unlinked live context list.',
51:'Requests removal of all active texts, destroys/frees context records, clears the context and used-block roots and rebuilds one free block from the saved arena. It retains font resource slots and backing allocation. It does not directly clear the text-list root, and its safe use requires outstanding GObj callbacks not to outlive the arena reset.',
52:'Text removal is requested first, then contexts are freed and context_head/used_head become NULL. free_head is reset to the saved arena and its payload capacity becomes arena_size-12. GObj removal can defer current-object destruction, so an empty text list and completed callbacks are not unconditional postconditions. No initialization, reentrancy or arena-size guard exists.',
54:'Provides per-font archive unloading for SisLib text presentation, after requesting cleanup of matching texts and contexts. The source orders these operations but deferred GObj callbacks and the context predecessor bug prevent an unconditional claim that all dependent runtime objects are safely gone.',
57:'Calls font-filtered runtime cleanup, then releases a non-NULL archive and clears its archive/SIS slot pair. The pair is unchanged when the archive is NULL. Runtime cleanup has deferred-callback and consecutive-context-removal limitations, so this is not a guarantee of complete safe teardown for every state.',
64:'Requests global reset, releases occupied archive slots and clears their SIS pairs, then frees the saved backing arena. Empty archive slots are skipped. Arena roots are not cleared after release, and reset can encounter deferred GObj removal; repeated shutdown and arbitrary callback-time shutdown are not made safe here.',
74:'Canonical signature int(int font_idx,HSD_GObj* parent_gobj,u16 class_id,u8 p_link,u8 p_prio,u8 gx_link,u8 gx_prio,u32 render_prio). parent_gobj is only null-tested and is not retained. Returns the count of prior entries whose stored u16 font tag equals the original int argument; stores font_idx through u16 truncation. Intended valid font indices avoid truncation differences.',
76:'Appends a context before attempting optional camera creation. Non-NULL parent_gobj suppresses owned-camera creation without retaining that pointer. NULL parent attempts GObj/CObj construction; either allocation failure can leave an appended context with NULL camera, while success configures ortho bounds, a (u64)1<<gx_link mask and callback. gx_link is not range-checked and user-data kind receives class_id through u8 conversion.',
82:'Stores each load/lookup result before its NULL panic guard. No font-index check, fallback, rollback or success value exists. Loading an already occupied slot overwrites the prior archive pointer without releasing it.',
83:'Selects SIS** via text->font_idx and conditionally writes sis_buffer from sis_idx. Resets measured width/height, copies active color, x34/x3C, x44/x46 and default modes into working fields, clears selected progress fields, and replaces string_buffer with sixteen zero bytes. It does not copy pos_x/pos_y or box_size fields and does not reset every HSD_Text field.',
87:'Conditionally binds an authored SIS entry, resets selected formatting and cursor fields from stored defaults, and replaces the mutable string buffer with a zeroed 16-byte allocation. NULL SIS table leaves sis_buffer unchanged. This routine does not clear every working field; x88 and x9F, for example, are untouched.',
91:'Canonical signature void*(s32 size). Positive byte counts are the intended domain and are rounded to four-byte granularity. Only size==0 is explicitly rejected; negative sizes and signed rounding overflow are unguarded, and comparisons against u32 block sizes use unsigned conversion. Returns best->data on the successful path.',
93:'Zero size reports/panics. The free-list loop dereferences free_head before any NULL check. Selection stops at an exact size or chooses the smallest larger block. If selected block is the head, it always reserves a new 12-byte header; exact-fit head and head remainder below 12 panic even though payload size matched. Non-head blocks move whole without splitting. Negative size/overflow are unvalidated.',
98:'Unknown payload leaves state unchanged. A block immediately before free_head merges with that head and leaves one larger free block. Other matches append after the free-list tail only if a tail exists, then unlink from used_head and clear next. If free_head is NULL, the fallback does not set it, so the released block becomes unreachable. Normal allocator operation preserves a head block.',
104:'Clears only the first matching context x4 pointer and returns; no match is a no-op. For the normally unique non-NULL registered GObj, a repeated call cannot change the already-cleared entry. General idempotence is not guaranteed if multiple entries share the same pointer; a NULL argument matches the first already-null x4.',
108:'Initialization overwrites roots with a new arena and empty registries. Reset requests text/context cleanup and rebuilds the saved arena while retaining font slots. Final shutdown additionally releases occupied archives and backing memory without clearing the arena pointer. Per-font cleanup filters runtime objects and archive slots but has a consecutive-context predecessor bug. Deferred GObj callbacks impose a lifecycle boundary requirement.'}
ranges={'.bss':[(60,61),(432,476),(549,604)],'.data':[(19,47),(76,109),(254,269),(524,564)],'.sbss':[(31,52),(405,476)],'.sdata':[(76,79),(107,109),(122,124),(553,564)],'.sdata2':[(285,325),(524,539),(568,604)],'HSD_SisLib_Alloc':[(63,146)],'HSD_SisLib_Free':[(148,200),(219,229)],'HSD_SisLib_803A5A2C':[(202,235),(282,284)],'HSD_SisLib_803A5ACC':[(237,326)],'HSD_SisLib_803A5CC4':[(328,344)],'HSD_SisLib_803A5D30':[(346,359)],'HSD_SisLib_803A5DA0':[(361,403)],'HSD_SisLib_803A5E70':[(407,430)],'HSD_SisLib_803A5F50':[(432,443)],'HSD_SisLib_803A5FBC':[(445,457)],'HSD_SisLib_803A6048':[(459,476)],'fn_803A60EC':[(478,489),(524,545)],'HSD_SisLib_803A611C':[(491,547),(254,284)],'HSD_SisLib_803A62A0':[(549,566)],'HSD_SisLib_803A6368':[(568,604)],'FILE':[(63,200),(237,326),(361,476),(491,604)]}
def ev(f,a,z):return {'kind':'code','locator':f'code://{rev}/{f}#L{a}-L{z}','why':'Reviewed pinned canonical implementation, owned header or bounded consumer.'}
foreign={'HSD_SisLib_803A6048':[('src/melee/gm/gm_1A3F.c',49,65)],'HSD_SisLib_803A5D30':[('src/melee/mn/mnname.c',575,592)],'HSD_SisLib_803A62A0':[('src/melee/gm/gmprogressive.c',33,69),(b+'hsd_3A76.c',966,974)],'HSD_SisLib_803A6368':[('src/melee/gm/gmprogressive.c',71,114),('src/melee/gr/grpstadium.c',1792,1819)],'HSD_SisLib_803A611C':[('src/melee/ty/tylist.c',902,967)],'HSD_SisLib_803A5CC4':[('src/melee/mn/mndiagram.c',2034,2042)],'HSD_SisLib_803A5ACC':[(b+'hsd_3A64.c',81,102)],'.data':[(b+'sislib_font.c',1,5)]}
destructors={'HSD_SisLib_803A5CC4','HSD_SisLib_803A5D30','HSD_SisLib_803A5DA0','HSD_SisLib_803A5E70','HSD_SisLib_803A5F50','HSD_SisLib_803A5FBC','fn_803A60EC','.sbss','FILE'}
def evidence(sym):
 e=[ev(src,a,z) for a,z in ranges[sym]]+[ev(f,a,z) for f,a,z in foreign.get(sym,[])]
 if sym in destructors:e += [ev(b+'gobjplink.c',103,110),ev(b+'gobjuserdata.c',6,25)]
 if sym in ['.data','.sdata2','FILE']:e += [ev(b+'hsd_3A76.c',442,478),ev(b+'sislib_font.c',1,5)]
 if sym in ['HSD_SisLib_803A5ACC','HSD_SisLib_803A6368','HSD_SisLib_Alloc','HSD_SisLib_803A611C']:e += [ev(b+'sislib.h',30,104)]
 return e
props=[];disp=[]
for i,f in enumerate(facts):
 sym='FILE' if f['subject']==src else f['subject'].split(':')[-1];e=evidence(sym);d='supersede' if i in changes else 'retain';why='Full canonical and rendered owned-file review through EOF; exact control-flow and bounded consumer evidence refreshed.'
 if sym.startswith('.') or sym=='FILE':why+=f' Existing objects inspected in compiled-evidence.json SHA-256 {eh}; no compilation or runtime test.'
 if f['type']=='inferred_name':why+=' Inherited semantic hypothesis only; independent review required, no attested original spelling.'
 if i==25:d='unresolved';why='HSD_SisLib_CreateText collides with the inherited name on hsd_3A64:HSD_SisLib_803A6754. That wrapper calls this constructor and adds mutable buffers. Defer naming reconciliation; no write or clear.'
 else:props.append({'subject':{'entity_locator' if sym=='FILE' else 'target_stable_key':f['subject']},'type':f['type'],'op':'write','value':changes.get(i,f['value']),'rationale':why,'confidence':min(f['confidence'],.98) if d=='supersede' else f['confidence'],'evidence':e})
 disp.append({'subject':f['subject'],'fact_id':f['id'],'updated_at':f['updated_at'],'version':f['updated_at'],'type':f['type'],'disposition':d,'action':why,'evidence':e})
stale=[]
for subject in task['writable_subjects']:
 k=subject.get('target_stable_key',subject.get('entity_locator'))
 if any(f['subject']==k for f in facts):continue
 sym=k.split(':')[-1].split('#')[0];moved=sym not in ranges
 if moved:stale.append(k)
 e=[ev(b+'sislib.h',116,153)] if moved else evidence(sym)
 disp.append({'subject':k,'fact_id':None,'updated_at':None,'version':None,'disposition':'unresolved' if moved else 'retain','action':'No inherited facts. Stale parameter locator refers to a split-owned declaration; identity migration and body review belong to its current TU.' if moved else 'No inherited facts; canonical subject inspected. No new fact proposed.','evidence':e})
proposal={'tu':tu,'proposal':{'facts':props,'links':[],'entities':[],'merges':[],'follow_ups':[]}};(p/'proposal.json').write_text(json.dumps(proposal,indent=2)+'\n')
lp=r/'baseline-links'/f"{task['id']}.json";links=json.loads(lp.read_text());ld=[]
for l in links:
 sym='FILE' if l['from_entity_id'] else l['from_target_id'].split(':')[-1];d='retain';why='Current owned implementation and bounded consumers support the text-presentation lifecycle relationship.'
 if sym in ['.sdata','.data','.sdata2','FILE']:
  d='reject';why={'FILE':'Exact inherited rationale assigns interpreter/font-atlas ownership to this TU after source split. Current lifecycle support is real but does not validate the full stored claim.','.data':'Exact inherited rationale assigns glyph atlas and kerning data to this section. Current .data contains camera descriptors and diagnostic strings.','.sdata':'Private arena size/base are in .sbss; existing .sdata contains a one-byte empty string plus split padding, not pool metadata.','.sdata2':'Exact inherited rationale assigns renderer decoding, clipping and texture mapping to this section. Current pool is four scalar defaults/camera bounds.'}[sym]
 if sym in destructors:why+=' Destruction requests may defer for the current GObj; this edge does not guarantee immediate complete cleanup.'
 ld.append({'link_id':l['id'],'baseline':l,'disposition':d,'reason':why,'evidence':evidence(sym)})
ldoc={'tu':tu,'revision':rev,'baseline_path':str(lp),'baseline_sha256':hashlib.sha256(lp.read_bytes()).hexdigest(),'link_count':len(ld),'retained':sum(x['disposition']=='retain' for x in ld),'rejected':sum(x['disposition']=='reject' for x in ld),'unresolved':0,'db_link_changes':False,'links':ld};(p/'link-dispositions.json').write_text(json.dumps(ldoc,indent=2)+'\n')
reads=[json.loads(x) for x in (state/'reads.jsonl').read_text().splitlines()];start=min(x['at'] for x in reads if x.get('reader')=='sislib_complete_review');end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');files=[dict(f,canonical_ranges=[[1,f['lines']]],rendered_ranges=[[1,f['lines']]]) for f in m['files'] if f['path'] in task['files']];fr=json.loads((p/'foreign-ranges.json').read_text())
cov={'tu':tu,'subjects':disp,'files':files,'started_at':start,'research_start':start,'research_end':end,'completed_at':end,'fact_count':len(facts),'reviewed_subject_count':len(task['writable_subjects']),'fact_version_kind':'updated_at','render_exceptions':['Header has shadowed bindings, including the CreateText collision; canonical symbols used in proposals.'],'render_metadata':{'source':{'parse_errors':0,'substitutions_by_page':[0,5,17],'next_line':None},'header':{'parse_errors':0,'substitutions':25,'next_line':None},'static_header':{'parse_errors':0,'substitutions':0,'next_line':None}},'foreign_reads':[{'path':f,'canonical_ranges':rs} for f,rs in fr.items()],'search_exceptions':['Initial full fact dump truncated; all 109 values/rationales reread in two indexed batches. Guessed foreign file paths absent; actual evidence paths located and read.'],'links_reviewed':len(ld),'link_dispositions':'link-dispositions.json','stale_parameter_subjects':stale,'owned_header_coverage':[{'path':b+'sislib.h','range':[1,157],'detail':'Complete types, globals, declarations and unresolved header comments inspected. HSD_Text fields are not all initialized by constructor. Header includes foreign font type definition, not owned atlas bytes.'},{'path':b+'sislib.static.h','range':[1,13],'detail':'Complete shared inline byte-pointer identity conversion and guard inspected.'}]};(p/'coverage.json').write_text(json.dumps(cov,indent=2)+'\n')
summary={'tu':tu,'status':'draft_pending_independent_review','started_at':start,'research_start':start,'research_end':end,'completed_at':end,'files_reviewed':3,'canonical_lines':sum(f['lines'] for f in files),'rendered_lines':sum(f['lines'] for f in files),'subjects_reviewed':len(task['writable_subjects']),'existing_facts_reviewed':len(facts),'retained_facts':len(facts)-len(changes)-1,'superseded_facts':len(changes),'unresolved_facts':1,'new_facts':0,'proposal_facts':len(props),'retained_name_hypotheses':sum(f['type']=='inferred_name' for f in facts)-1,'unresolved_name_hypotheses':1,'proposed_names':0,'clears':0,'compiled_evidence_sha256':eh,'report_sha256':m['report_sha256'],'proposal_sha256':hashlib.sha256((p/'proposal.json').read_bytes()).hexdigest(),'links_reviewed':len(ld),'links_retained':ldoc['retained'],'links_rejected':ldoc['rejected'],'links_unresolved':0,'stale_parameter_subjects':len(stale)};(p/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
(p/'unresolved.json').write_text(json.dumps({'tu':tu,'items':[{'topic':'CreateText collision','status':'pending_family_naming_review','fact_id':facts[25]['id'],'updated_at':facts[25]['updated_at'],'detail':'Both this constructor and hsd_3A64 wrapper HSD_SisLib_803A6754 inherit HSD_SisLib_CreateText. No write or clear for constructor name.'},{'topic':'Stale parameter identities','status':'family_followup','subjects':stale,'detail':'Header declares split-owned functions; current bodies belong to hsd_3A64/hsd_3A76. No facts on these stale entities.'},{'topic':'Lifecycle conditions','status':'source_observed_pending_family_review','detail':'GObj removal may defer, while sislib resets arena immediately; ordinary immediate callback returns text storage before entity=NULL write. Context removal advances predecessor to freed storage. No runtime reachability claim or source fix.'},{'topic':'Partial initialization and type comments','status':'source_observed','detail':'Constructor omits active fields. HSD_Text font index is u8; context font tag is u16. Header guessed field comments and sisLib_803A7664_t/SisBlock relationship remain uncertain; no struct merge.'}]},indent=2)+'\n')
(p/'naming.md').write_text('# Naming Review\n\nNo new names or canonical renames. Existing hypotheses require independent review.\n\n| Canonical | Inherited Hypothesis | Disposition |\n|---|---|---|\n'+''.join(f"| {f['subject'].split(':')[-1]} | {f['value']} | {'unresolved collision; no write' if i==25 else 'retain hypothesis'} |\n" for i,f in enumerate(facts) if f['type']=='inferred_name')+'\nHSD_SisLib_BytePtr is a canonical static inline byte-pointer identity conversion. The header also retains unresolved lbl/func declarations; they are not grounds for inventing new callable identities.\n')
print(json.dumps(summary))
