import json,pathlib,hashlib,datetime,struct,shutil
D=pathlib.Path('docs/.drafts/melee-semantic-20260908/main__melee__ft__kinds__ftCommon__ftCo_AttackS4');S=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');M=json.load(open(S/'manifest.json'));R=M['head_revision'];root=pathlib.Path(M['checkout_root']);C=json.load(open(D/'context.json'));X=json.load(open(D/'baseline-facts.json'));tu=C['task']['tu'];P=C['task']['source_path'];U=S/'units'/C['task']['id'];start='2026-09-08T15:59:04Z'
def c(p,a,b):
 assert 1<=a<=b<=len((root/p).read_text().splitlines()),(p,a,b)
 return f'code://{R}/{p}#L{a}-L{b}'
foreign=[]
def add(p,*pairs):
 for a,b in pairs:foreign.append(('src/melee/'+p,a,b))
add('ft/ft_084E.c',(55,89));add('ft/ft_081B.c',(1043,1050));add('ft/ft_08A1.c',(54,98));add('ft/ftanim.c',(380,386));add('ft/ftmotionstates.c',(773,826));add('ft/ftcommon.c',(606,614));add('ft/ftdata.c',(1837,1847));add('ft/inlines.h',(43,47));add('ft/ft_0DF1.c',(14,32));add('ft/ftattacks4combo.c',(8,47));add('ft/kinds/ftCommon/ftCo_Attack100.c',(44,101));add('ft/kinds/ftCommon/ftCo_Dash.c',(83,103));add('ft/kinds/ftNess/ftnessattacks4.c',(29,56));add('ft/kinds/ftPeach/ftpeachattacks4.c',(17,33));add('ft/kinds/ftGameWatch/ftgamewatchattacks4.c',(107,119));add('ft/ftswing.c',(63,99));add('ft/ft_0CDD.c',(14,33));add('it/it_26B1.c',(120,124),(301,320))
fr=[]
for p,a,b in foreign:
 c(p,a,b);t=(root/p).read_text();fr.append(dict(path=p,start_line=a,end_line=b,sha256=hashlib.sha256(t.encode()).hexdigest(),canonical_read=True,rendered_read=False,ownership='foreign evidence only'));(D/(p.replace('/','__')+f'.{a}-{b}.txt')).write_text('\n'.join(f'{i}: {l}' for i,l in enumerate(t.splitlines(),1) if a<=i<=b))
E=[c(P,1,244)]+[c(p,a,b) for p,a,b in foreign]
report=root/'build/GALE01/report.json';rh=hashlib.sha256(report.read_bytes()).hexdigest();assert rh==M['report_sha256'];unit=next(u for u in json.load(open(report))['units'] if u['name']==tu);objects=[]
for typ in ['src','obj']:
 p=root/f'build/GALE01/{typ}/melee/ft/kinds/ftCommon/ftCo_AttackS4.o';b=p.read_bytes();e='>' if b[5]==2 else '<';off=struct.unpack_from(e+'I',b,32)[0];sz,n,si=struct.unpack_from(e+'HHH',b,46);sh=[struct.unpack_from(e+'10I',b,off+i*sz) for i in range(n)];st=sh[si];names=b[st[4]:st[4]+st[5]]
 for s in sh:
  if names[s[0]:].split(b'\0')[0]in [b'.sdata2',b'.data']:objects.append(dict(path=str(p),sha256=hashlib.sha256(b).hexdigest(),section=names[s[0]:].split(b'\0')[0].decode(),size=s[5],elf_flags=s[2],writable=bool(s[2]&1),allocated=bool(s[2]&2),bytes_hex=b[s[4]:s[4]+s[5]].hex()))
asm=root/'build/GALE01/asm/melee/ft/kinds/ftCommon/ftCo_AttackS4.s'
json.dump(dict(report_path=str(report),report_sha256=rh,pinned_report_hash_matches=True,unit=unit,objects=objects,assembly=dict(path=str(asm),sha256=hashlib.sha256(asm.read_bytes()).hexdigest(),read='data sections and complete decideFighter dispatch assembly',finding='17-entry jump table for kinds 8..24 (68 bytes), plus split four-byte gap. Literal pool: f32 zero, one, minus one; split includes trailing four zero bytes.'),permission_limit='Object flags do not prove final runtime protection.'),open(D/'section-evidence.json','w'),indent=2)
O={}
def replace(n,t,v,why,ev):O[n,t]=(v,why,ev)
replace('.sdata2','inferred_type','The split section is 16 bytes: f32 zero, one and minus one at offsets 0, 4 and 8 plus four zero bytes. The existing source object contains the three literal words in 12 bytes. Source flags are WRITE|ALLOC and split flags ALLOC; final runtime protection is not established. This is compiler literal storage, not a gameplay aggregate.','Existing objects distinguish source/split size and flags; the read-only assertion is not true of the source ELF.',[c(P,64,115),c(P,170,198)])
replace('.sdata2','purpose','Provides the TU literals used for input-sign comparisons, normalized facing direction and initial motion frame, speed and blend. Local code reads the pool; source/split section permissions are recorded separately.','Read usage does not establish read-only object storage.',[c(P,64,115),c(P,170,198)])
replace('.data','data_flow','decideFighter reads Fighter.kind and dispatches through a 17-entry switch table covering kinds 8 through 24, using the default path outside that range. Ness, Peach and GameWatch receive only the fighter object after facing has been assigned; they do not receive the supplied stick angle. Pikachu/Pichu use common doEnter with stick_angle and then install effect hitlag callbacks; remaining kinds use common doEnter with stick_angle.','The old final sentence attributed angle consumption to every selected branch, but only common doEnter receives the angle.',[c(P,145,198)])
replace('ftCo_AttackS4_IASA','state_behavior','When allow_interrupt is set, initial priority is side special, up special via ftCo_Attack100_CheckInput, neutral special via ftCo_800D6824, down special via ftCo_800D68C0, then grab. If no earlier return occurs, ftCo_800CECE8 checks the command-gated A-button forward-smash follow-up independently of allow_interrupt. If interruption is allowed and no earlier check succeeds, the remaining order is forward/up/down smash; forward/up/down tilt; neutral attack; ftCo_80091A4C; ftCo_800DE9D8; jump; dash; ftCo_800D5FB0; turn; walk. Each true result ends processing.','The Attack100-named helpers call the SpecialHi/SpecialN/SpecialLw tables, not rapid-jab logic. The independently gated follow-up is reached only without an earlier return.',[c(P,207,234),c('src/melee/ft/kinds/ftCommon/ftCo_Attack100.c',44,101),c('src/melee/ft/ftattacks4combo.c',8,47)])

rows=[];disp=[];facts=[]
for s in X:
 name=next(iter(s['subject'].values())).split(':')[-1];rows.append(dict(subject=s['subject'],status='reviewed' if s['facts'] else 'reviewed_no_existing_facts',fact_count=len(s['facts']),evidence=E,notes='Parameter records are empty; no ABI register-to-source mapping promoted.'))
 for f in s['facts']:
  q=O.get((name,f['type']));new,why,ev=q if q else (None,'Complete owned canonical/rendered source and bounded dependencies support the existing value. Historical citations are preserved, not asserted re-read.',E)
  disp.append(dict(subject=s['subject'],fact_id=f['id'],version=f['updated_at'],type=f['type'],old_value=f['value'],disposition='supersede' if q else 'retain',reason=why,replacement=new,evidence=ev))
  if q:facts.append(dict(subject=s['subject'],type=f['type'],op='write',value=new,rationale=why,confidence=0.97,evidence=[dict(kind='code',locator=e,why=why) for e in ev]))
end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');reads=[json.loads(l) for l in open(U/'reads.jsonl') if json.loads(l).get('reader')=='AttackS4'];L=S/'baseline-links'/f'{C["task"]["id"]}.json';links=json.load(open(L));ld=[]
for l in links:
 ld.append(dict(link_id=l['id'],baseline_record=l,from_target_id=l['from_target_id'],from_entity_id=l['from_entity_id'],to_target_id=l['to_target_id'],to_entity_id=l['to_entity_id'],role=l['role'],prior_rationale=l['why'],version_or_digest=l.get('digest'),disposition='retain',reconciliation_owner='/root/semantic_coordinator',reason='AttackS4 callback registration, left/C-stick input, item priority, character switch, angle selection, dash caller, animation completion, interrupt gate and grounded movement/collision support these relationships. Jump-table links are additionally backed by section-evidence.json and dispatch assembly. Complete original record retained; historical wiki and old-revision resources not asserted re-read.',evidence=E))
def dump(n,v):json.dump(v,open(D/n,'w'),indent=2)
dump('proposal.json',dict(tu=tu,proposal=dict(facts=facts,links=[],entities=[],merges=[],follow_ups=[])))
dump('fact-dispositions.json',dict(revision=R,start_utc=start,end_utc=end,counts=dict(retain=len(disp)-len(facts),supersede=len(facts)),dispositions=disp))
dump('link-dispositions.json',dict(revision=R,input_path=str(L),input_sha256=hashlib.sha256(L.read_bytes()).hexdigest(),expected_count=len(links),reviewed_count=len(ld),counts=dict(retain=len(ld)),reconciliation_owner='/root/semantic_coordinator',dispositions=ld))
dump('coverage.json',dict(campaign=M['campaign_id'],tu=tu,revision=R,role='TU librarian',model=M['model'],reasoning_effort=M['reasoning_effort'],start_utc=start,end_utc=end,input_files=C['files'],canonical_and_rendered_receipts=reads,foreign_evidence_reads=fr,subjects=rows,counts=dict(targets=11,source_entities=1,parameter_entities=13,existing_facts=len(disp),outgoing_links=len(ld),proposal_facts=len(facts),owned_lines=261),exceptions=[],section_evidence='section-evidence.json'))
dump('unresolved.json',dict(unresolved=[],family_followups=['Source/split .sdata2 are 12/16 bytes; .data are 68/72 bytes. Runtime protection not established.','Source retains surprising MS enum spellings as motion-data indices in angle guards; record exact lookup-to-selected-state mapping without renaming foreign enums.','No ABI parameter mapping promoted. Historical locators preserved, not re-read; coordinator owns link reconciliation.']))
(D/'functionality.md').write_text(f"""# Common forward smash

Revision `{R}`. All canonical/rendered C1-245 and H1-16 read; three receipts, no parser errors. Terminal empty lines count toward rendering totals, while new code citations stop at C244/H15.

General input gives A plus horizontal magnitude/timer qualification priority over C-stick. The C-stick helper requires previous absolute X below and current absolute X at/above the common threshold. Angles use atan2(Y, abs(X)). The Dash-specific predicate accepts A toward existing facing without a tilt timer; its alternate C-stick route may choose either side. Dash calls it within the opening phase after special, immediate item throw and grab checks. The name hypothesis CheckInputFromDash remains supported.

Held-item override first handles LR, class zero, class three with depleted-item predicate, or the C-stick-permission predicate. It selects F4/B4 by requested sign times current facing. Otherwise class two writes facing then dispatches swing variant two; class three writes facing then calls shooting entry, whose own pickup opportunity and item-kind branches remain delegated. No handled item means facing is written before character dispatch. Ness, Peach and GameWatch specialized routines receive the object only: respectively bat setup, a random weapon motion excluding the previous choice, and torch accessory setup. Pikachu/Pichu run common angle entry then pause/resume effect hitlag callbacks. Other kinds use common entry.

The switch table covers kinds 8..24 with seventeen four-byte relocated code destinations. Ness/Peach/GameWatch and Pikachu/Pichu destinations differ from default. Existing source .data is 68 bytes, split is 72 with a four-byte gap; both have WRITE|ALLOC. Raw zero words in relocatable objects are not null dispatch entries: assembly and relocations identify their targets.

Angle selection preserves the exact current lookup spellings: angle > xB8 plus AttackS4S lookup x8 selects Hi; > xBC plus AttackS4LwS lookup selects HiS; < xC4 plus AttackLw4 lookup selects Lw; < xC0 plus AttackHi4 lookup selects LwS; otherwise S. The lookup returns indexed motion data, with a Nana-to-Popo fallback under its own conditions. It does not translate the supplied enum through the motion-state table. Common entry clears allow_interrupt, command zero and throw flags, changes the chosen state at frame zero/speed one/zero blend, then runs animation setup.

Anim delegates natural completion to the common neutral dispatcher. IASA checks side/up/neutral/down specials then grab when interruptible, checks the A-plus-command Link/Young Link forward-smash follow-up if no prior return, and then checks remaining attacks and movement when interruptible. Attack100 is a misleading canonical name here; its checked body dispatches SpecialHi. Phys selects above-walk-scaled friction, but the lower helper chooses animation-driven acceleration when x594_b0 is set. Coll performs shared ground checking/Fall entry. Motion states 58..62 register all four callbacks.

Literal pool contains zero, one and minus one. Source is 12 bytes WRITE|ALLOC; split is 16 bytes ALLOC including a trailing zero word. Frozen report hash matches. No build ran.

All {len(disp)} existing fact versions and {len(ld)} exact outgoing records have individual dispositions. Original links remain complete, including historical locators and repeated endpoints. No source or shared KB writes.
""")
(D/'naming.md').write_text('# Naming review\n\nRetain ftCo_AttackS4_CheckInputFromDash as the hypothesis for ftCo_AttackS4_8008C114: Dash caller and same-facing A path confirm its role. Preserve all canonical names. Foreign Attack100 helper aliases are verified against their special-dispatch bodies; no foreign facts are proposed. Local checkLStick/checkFacingDir lack manifest identities but are fully reviewed.\n')
(D/'README.md').write_text(f'# AttackS4 review packet\n\nRevision `{R}`. UTC `{start}` to `{end}`. Model `{M["model"]}`, role TU librarian.\n\n25 owned subjects: eleven targets, source entity and thirteen empty parameters. {len(disp)} facts: {len(disp)-len(facts)} retain, {len(facts)} corrections. All {len(ld)} exact outgoing records retained. Three complete owned render receipts, no parser errors.\n\nNo source/shared KB/build edits. Dry-run proposal only.\n')
print(len(disp),len(facts),len(ld),end)
