import json,pathlib,hashlib,datetime
out=pathlib.Path(__file__).parent;m=json.load(open('games/melee/state/knowledge_v2/semantic-sweep-20260908/manifest.json'));tu='main/melee/lb/lbsnap';rev=m['head_revision'];src='src/melee/lb/lbsnap.c';rows=json.load(open(out/'facts.json'));unit=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908/units/main__melee__lb__lbsnap');support=json.load(open(out/'supporting-reads.json'))
def ev(p,a,b,why):return {'kind':'code','locator':f'code://{rev}/{p}#L{a}-L{b}','why':why}
def nk(row):
 k=next(iter(row['subject'].values()));return 'file' if k==src else k.split(':')[-1].split('#')[0].removeprefix('lbSnap_')
data={'.bss':(24,67,'0x60-byte singleton binds caller-owned workspaces, description, icon data and card state.'),'.data':(61,74,'Mutable save descriptor followed by strings in existing objects;44-byte descriptor,20-byte icon header and two CardEntry records.'),'.sdata':(140,178,'Three-byte %u decimal filename format, independently identified in existing object bytes.'),'8001D2BC':(76,86,'Poll channels0/1, store each CARDProbe result and latch change on inequality; equal results preserve the flag.'),'8001D338':(88,91,'Return unchecked channel change flag without acknowledgement.'),'8001D350':(93,100,'Mutating cached-result query: zero plus pending change becomes8; return cached result.'),'8001D394':(102,105,'Return unchecked cached catalog count.'),'8001D3B0':(107,110,'Return unchecked cached free blocks.'),'8001D3CC':(112,115,'Return unchecked cached free-file capacity.'),'8001D3E8':(117,120,'Return unchecked selected entry block count.'),'8001D40C':(122,138,'Clear change flag, refresh catalog/capacities synchronously, count sentinel entries only on success.'),'8001D4A4':(140,162,'Generate decimal whole-second filename unique within cached catalog; clear33-byte output.'),'8001D5FC':(180,197,'Guard cached result, invalidate to8, submit indexed timestamp-file deletion.'),'8001D7B0':(199,220,'Guard cached result, format two names and unused temporary name, invalidate to8, submit three renames.'),'8001DA5C':(222,335,'Nearest source sampling of448x204 region at96,138 into64x32 opaque RGB5A3 pixels centered in96x32 banner; existing margins untouched.'),'8001DC0C':(340,377,'Set type4,640x480, scene fields and encoder mode3; encode with256000 capacity; always create banner and localized timestamp label.'),'8001DE8C':(379,390,'Decode only type4; flush metadata width*height*2 bytes even on decoder failure; return booleanized decoder result.'),'8001DF20':(392,409,'Write payload size plus0x38 and snapshot pointer into descriptor; calculate card-layout block requirement.'),'8001DF6C':(414,435,'Guard and invalidate cached slot, build unique name and descriptor, submit save.'),'8001E058':(437,455,'Guard slot, format selected name, install destination pointer and submit load; successful submission does not set cached slot result8.'),'8001E204':(457,460,'Return256064-byte snapshot allocation requirement.'),'8001E210':(462,465,'Return2112-byte catalog allocation requirement; two0x408 records require2064 bytes.'),'8001E218':(467,475,'Bind caller workspaces, set both card results8 and load MemSnapIconData; does not initialize all other fields.'),'8001E27C':(477,481,'Null only snapshot and slot pointers, without freeing storage.'),'8001E290':(483,491,'Null icon pointer, probe two channels and clear first two change flags; leave workspaces and third flag untouched.'),'file':(1,491,'Snapshot metadata/image preparation, card catalogs and asynchronous persistence requests.')}
changes={
('.data','data_flow'):'The block-requirement query and save-submission routine write compressed length plus0x38 and the active snapshot pointer into the first descriptor entry. Load installs the destination pointer but does not recompute file_size. Preparation itself writes the snapshot record, banner and description, not the descriptor.',
('.data','inferred_type'):'Initialized writable data begins with a0x2C-byte descriptor:20 icon-metadata bytes and two12-byte CardEntry records, terminated by file_size=-1. Existing source/split objects contain228/232 bytes including diagnostics, localized labels, timestamp format and archive/resource strings; the four-byte difference is trailing padding. Objects were inspected without rebuilding.',
('8001D2BC','inferred_type'):'void lbSnap_8001D2BC(void). Polls two card_state elements and the first two elements of the three-element state_changed array. Communicates through the singleton, without using the third change slot.',
('8001D40C','data_flow'):'Clears the selected change flag and passes the127-entry catalog and capacity outputs to lb_8001BFD8. The lower layer filters current-disc company/game identifiers and filenames whose first character is a digit, parses their numeric prefix with strtoul, sorts descending timestamps and writes file_no=-1 sentinels. This is not validation that the entire filename is decimal. On success the wrapper counts through the first sentinel, capped at127.',
('8001DC0C','data_flow'):'Receives the capture buffer supplied by Camera Mode, writes type4,640x480, stage and item/fighter metadata, encoder mode3 and compressed result into the snapshot work record. It invokes banner generation to place64x32 sampled pixels inside a96x32 banner, then writes a localized description with month/day/time. The Camera Mode caller next calculates required card blocks.',
('8001DC0C','purpose'):'Prepares the captured image for snapshot storage: initializes metadata, encodes the640x480 image with a256000-byte capacity, generates a64x32 image inside the96x32 Memory Card banner, and formats a localized timestamp description.',
('8001DC0C','state_behavior'):'Writes the snapshot fields and calls the encoder. Nonzero encoder result yields1, zero yields0. Banner generation and description formatting run in either case; failure does not roll back metadata or other writes. Camera Mode advances to state2 after1 and returns to state0 after0.',
('8001DE8C','purpose'):'For type4 snapshots, attempts JPEG decoding into the supplied destination, then flushes snapshot-metadata width*height*2 bytes regardless of decoder success. The flush range is not derived from JPEG dimensions and does not establish that all decoded pixels are covered.',
('8001DE8C','inferred_type'):'int lbSnap_8001DE8C(void* dst), returning1 for nonzero decoder result and0 otherwise. For normal640x480 images the tiled RGB565 output occupies614400 bytes. Decoder writes follow dimensions parsed from JPEG and use16-pixel block rounding, while this wrapper flushes dimensions from snapshot metadata; it does not check their agreement or destination capacity.',
('8001DE8C','state_behavior'):'Non-type4 returns0 without decode or cache flush. Type4 invokes the decoder and then flushes snapshot width*height*2 bytes even on decoder failure. JPEG dimensions determine decoder traversal and are not compared to snapshot dimensions. The decoder has nonlocal error returns, but this wrapper supplies no independent bounds or format validation.',
('8001E218','state_behavior'):'Unconditionally installs both pointers, sets only card_result for slots0/1 to8, and loads the icon resource. It does not initialize catalog counts, entries, capacities, description, probe states or change flags and has no local null/duplicate-setup guard. Separate lifecycle routines clear work pointers or reset icon/probe state.',
('8001E27C','inferred_type'):'void lbSnap_8001E27C(void), a returning routine with no return value. It writes NULL to the snapshot-work and slot-array pointers; it neither frees those caller-owned allocations nor resets the rest of the singleton.',
('8001D4A4','state_behavior'):'Increment the unsigned-second candidate on a cached timestamp collision and restart scanning until no match remains. Uniqueness is relative to the supplied cached catalog, not a fresh card scan. Only the output buffer is explicitly written; preserving catalog state requires that output not alias it.',
('8001D3E8','game_mapping'):'Supplies the selected snapshot block count to the album copy-capacity guard; the caller, not this accessor, compares it with destination free blocks and decides whether to proceed.'}
for nn in ['8001E218','8001E290']:
 old=next(f['value'] for r in rows if nk(r)==nn and 'target_stable_key' in r['subject'] for f in r['facts'] if f['type']=='inferred_type')
 changes[nn,'inferred_type']=old.replace('no-return subsystem initializer','void-returning subsystem initializer').replace('no-return','void-returning')+' The routine returns normally with no return value.'
additions={('8001D5FC','inferred_type'):None}
# The shared inline formatter has only an upper-bound assertion, not a nonnegative-index check.
for n in ['8001D5FC','8001D7B0','8001E058']:
 old=next(f['value'] for r in rows if nk(r)==n and 'target_stable_key' in r['subject'] for f in r['facts'] if f['type']=='inferred_type')
 changes[n,'inferred_type']=old+' The inline formatter asserts only index<num; negative indices and invalid channels are not rejected by that condition. Callers must supply valid nonnegative catalog indices and channels.'
proposal={'tu':tu,'proposal':{'facts':[],'links':[],'entities':[],'merges':[],'follow_ups':[]}};subjects=[]
for row in rows:
 n=nk(row);a,b,desc=data[n];e=[ev(src,a,b,desc)]
 # Local neighbors substantiate inputs, consumers and lifecycle state.
 if n in ['.bss','.data','file','8001E204','8001E210','8001E218','8001E27C','8001E290']:e += [ev(src,340,491,'Preparation, descriptor writes, allocation sizes and lifecycle.')]
 if n in ['8001D2BC','8001D338','8001D350','8001D394','8001D3B0','8001D3CC','8001D3E8','8001D40C','.sdata']:e += [ev(src,76,220,'Probes, accessors, catalog refresh and indexed operation guards.')]
 if n in ['8001D5FC','8001D7B0','8001E058']:e += [ev(src,164,178,'Shared upper-bound-only indexed filename formatter.')]
 if n=='8001DC0C':e += [ev(src,250,335,'Exact banner dimensions and sampling.')]
 # Attach independently read foreign support by function family.
 for r in support:
  p=r['path'];aa,bb=r['canonical_range'];include=False
  if p.endswith('lbcardnew.c'):include=n in ['.data','.sdata','file','8001D40C','8001D5FC','8001D7B0','8001DF20','8001DF6C','8001E058']
  if p.endswith('mnsnap.c'):include=n in ['file','8001D338','8001D350','8001D394','8001D3B0','8001D3CC','8001D3E8','8001D40C','8001DE8C','8001E058']
  if p.endswith('gmcamera.c'):include=n in ['file','.bss','8001D338','8001D3B0','8001D3CC','8001DC0C','8001DF20']
  if p.endswith('gmmenumode.c'):include=n in ['8001E204','8001E210','8001E218']
  if p.endswith('gm_1A3F.c'):include=n=='8001E27C'
  if p.endswith('hsd_3B5C.c'):include=n=='8001DE8C'
  if p.endswith('hsd_3B34.c'):include=n=='8001DC0C'
  if p.endswith('hsd_3A94.c'):include=n=='8001DF20'
  if p.endswith('hsd_3B27.c'):include=n=='8001E058'
  if include:e.append(ev(p,aa,bb,'Independently read supporting implementation or current consumer; foreign ownership not claimed.'))
 s={'subject':row['subject'],'canonical_range':[a,b],'review':desc,'facts':[]}
 if not row['facts']:s.update(disposition='reviewed_no_existing_facts',parameter_review='Current signature and parameter role reviewed; unchecked channels/indices require caller validity. No new parameter claims.')
 for f in row['facts']:
  value=changes.get((n,f['type']));disp='supersede' if value else 'retain';why='Correct inherited dimensions, mutation, validation or type claim using pinned canonical evidence.' if value else 'Pinned implementation and independently read consumers support the claim; inferred names remain descriptive hypotheses.'
  if n=='8001DE8C' and f['type'] in ['data_flow','game_mapping']:disp='unresolved';why='Album decode/display is verified; inherited internal debug-preview consumer was not independently read. Preserve pending family review.'
  if n=='8001E058' and f['type'] in ['data_flow','game_mapping']:disp='unresolved';why='Album load path is verified; internal preview consumer remains unreviewed.'
  s['facts'].append({'id':f['id'],'version':{'updated_at':f['updated_at'],'numeric_version':None},'type':f['type'],'value':f['value'],'disposition':disp,'reason':why,'evidence':e})
  if value:proposal['proposal']['facts'].append({'subject':row['subject'],'type':f['type'],'op':'write','value':value,'rationale':why,'confidence':0.98,'evidence':e})
 subjects.append(s)
receipts=[]
for p,a,b,phys in [(src,1,240,240),(src,241,480,480),(src,481,492,491),('src/melee/lb/lbsnap.h',1,32,31)]:
 artifact=unit/'pages'/(p.replace('/','__')+f'.{a}-{b}.json');r=json.load(open(artifact));receipts.append({'path':p,'canonical_range':[a,phys],'rendered_range':[a,b],'source_sha256':next(f['sha256'] for f in m['files'] if f['path']==p),'artifact':str(artifact),'render_metadata':r['rendered']})
logs=[json.loads(l) for l in (unit/'reads.jsonl').read_text().splitlines() if json.loads(l).get('reader')=='lbsnap_leaf'];started=min(x['at'] for x in logs);completed=datetime.datetime.now(datetime.timezone.utc).isoformat();counts={'targets':sum('target_stable_key' in r['subject'] for r in rows),'entities':sum('entity_locator' in r['subject'] for r in rows),'facts':sum(len(r['facts']) for r in rows),'proposals':len(proposal['proposal']['facts']),'dispositions':{d:sum(f['disposition']==d for s in subjects for f in s['facts']) for d in ['retain','supersede','reject','unresolved']}}
coverage={'campaign':m['campaign_id'],'tu':tu,'revision':rev,'started_at':started,'completed_at':completed,'reader':'lbsnap_leaf','subjects':subjects,'read_receipts':receipts,'supporting_canonical_reads':support,'object_evidence':json.load(open(out/'object-evidence.json')),'counts':counts,'exceptions':['Owned physical C491/H31 and rendered C492/H32 exhausted; phantom final blank excluded from citations.','C renderer reports6 parse errors and zero substitutions; hypotheses inspected in symbol footer and header with21 substitutions, no canonical-name substitution assumed.','Existing objects inspected without rebuild or exact current-source correspondence certification.'],'unresolved':['Four inherited facts mention internal preview consumers not independently read; album use verified.','Shared item/fighter types and low-level card/JPEG ownership remain with their family owners.','Decoder failure handling does not establish memory safety for arbitrary malformed input.']}
for name,obj in [('coverage.json',coverage),('proposal.json',proposal)]: (out/name).write_text(json.dumps(obj,indent=2)+'\n')
text=['# Snapshot Functionality','',f'Revision `{rev}`. Read started {started}; completed {completed}.','','## State and Card Catalogs','','The0x60-byte singleton holds caller-owned snapshot/slot pointers,64-byte description, icon resource pointer, two probe results and three change flags. Runtime polling uses only two flags. Initialization does not clear all workspace fields. ClearWorkPointers nulls only two pointers and frees nothing.','','Polling latches changed CARDProbe results. Refresh clears the latch before querying the card and replaces cached count only on success. Delete, swap and save invalidate cached success to8 before submission; load preserves zero on allowed submission. These return immediate task status, not persistence completion. Channels and accessor indices are unchecked; the filename formatter asserts only index<num and therefore permits negative indices through that condition.','','The lower catalog layer recognizes current-disc company/game files beginning with a digit, parses decimal prefixes and sorts by descending parsed time. It does not prove filenames are wholly numeric or snapshots valid. Unique names are unique only against the cached timestamps.','','## Image and Metadata','','Capture preparation stores type4,640x480, stage/item/fighter metadata and mode3; the encoder receives256000 bytes of payload capacity. Banner generation samples source coordinates96+floor(448*x/64),138+floor(204*y/32), converting RGB565 to opaque RGB5A3. It writes64x32 pixels at banner columns16-79; the96x32 banner margins remain untouched. It does not create a32x32 icon. Both banner and timestamp description are updated even if the encoder returns zero.','','Decode accepts only type4, forwards payload to the JPEG decoder and always flushes metadata width*height*2 after that call. Decoder traversal uses dimensions parsed from JPEG with16-pixel block rounding. The wrapper neither compares dimensions nor validates destination capacity. For normal640x480 images the output is614400 bytes.','','## Persistence and Ownership','','Required-block and save paths install payload length+0x38 and work pointer into the descriptor; load replaces the pointer without recalculating that size. Snapshot allocation is256064 bytes; catalog allocation2112 bytes contains two1032-byte records with48 spare bytes. Existing objects confirm96-byte BSS,3-byte %u small data and descriptor/string data with four bytes of split padding. No rebuild establishes current source-to-object equivalence.','','Foreign card implementations substantiate task dispatch, delete/rename operations and synchronous refresh. Current menu consumers substantiate copy guards, allocation and album load/decode. Internal preview references remain unresolved. No shared type claims or source renames are proposed.','','## Entry Points','']
for n,d in data.items():text += [f'- `{n}`: {d[2]} Evidence: code://{rev}/{src}#L{d[0]}-L{d[1]}.']
(out/'functionality.md').write_text('\n'.join(text)+'\n');find=['# Findings','','All fact IDs, versions, dispositions and evidence are in coverage.json.','']
for s in subjects:
 find += ['## '+next(iter(s['subject'].values())),'',s['review'],'']
 for f in s['facts']:find += [f"- {f['id']} @ {f['version']['updated_at']}: {f['disposition']} {f['type']}. {f['reason']}"]
 if not s['facts']:find += [s['parameter_review']]
 find+=['']
(out/'findings.md').write_text('\n'.join(find)+'\n');nt=['# Naming Table','','| Canonical target | Inferred alias | Decision and independent support |','|---|---|---|']
for row in rows:
 if 'target_stable_key' not in row['subject']:continue
 n=nk(row);f=next((f for f in row['facts'] if f['type']=='inferred_name'),None);nt += [f"| {next(iter(row['subject'].values())).split(':')[-1]} | {f['value'] if f else 'none'} | Retain {'hypothesis' if f else 'canonical'}; {data[n][2]} |"]
(out/'naming-table.md').write_text('\n'.join(nt)+'\n');(out/'unresolved.md').write_text('# Unresolved\n\nFour facts contain unreviewed internal preview consumers; their IDs and timestamps are in coverage.json. Current album consumers are verified. Shared type and low-level card/JPEG semantics remain with family owners.\n\nC renderer returned six parse errors and zero substitutions; canonical C and complete rendered footer were read. Header substitutions are hypotheses only. Existing object files were not rebuilt. Independent proposal review is pending.\n')
summary={'tu':tu,'revision':rev,'started_at':started,'completed_at':completed,'status':'research_complete_pending_review','counts':counts,'artifacts':{n:str(out/n) for n in ['functionality.md','findings.md','naming-table.md','coverage.json','unresolved.md','proposal.json']},'proposal_sha256':hashlib.sha256((out/'proposal.json').read_bytes()).hexdigest()}
for p in [out/'summary.json',unit/'summary.json']:p.write_text(json.dumps(summary,indent=2)+'\n')
print(json.dumps(summary))
