from pathlib import Path
import json,hashlib,datetime,sqlite3,shutil
p=Path(__file__).parent;r=Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');m=json.load(open(r/'manifest.json'));tu='main/melee/db/dbitem';t=next(t for t in m['tasks'] if t['tu']==tu);state=r/'units'/t['id'];src=t['source_path'];hdr='src/melee/db/dbitem.static.h';rev=m['head_revision'];groups=json.load(open(p/'baseline-facts.json'));facts=[dict(f,subject=g['subject']) for g in groups for f in g['facts']];eh=hashlib.sha256((p/'compiled-evidence.json').read_bytes()).hexdigest()
changes={
2:'Existing source object .bss is 116 bytes: an 80-byte text buffer followed by 36-byte menu state, with eight 32-bit scalar fields and a bitfield allocation unit. The split object adds four bytes of trailing padding for 120 bytes. These are existing-object observations, not a fresh compilation.',
4:'DisplayStatus 0 requests creation, 1 is treated as visible, and 2 reuses hidden text. A change records player and timer120. That player decrements positive timers; an already-zero timer hides on the following call. Allocation failure still records status1 and subsequent DevText_Erase dereferences the NULL pointer. Setup resets only selected fields, not the pointer, timer, player, coin flag or spawn enable.',
13:'The BSS text pointer is assigned each creation attempt and reused only for status2; setup does not reset it. Mode is initialized1 and valid-state toggles cycle1,2,3. Global application ORs the mode without clearing existing low bits, whereas toggling and fighter-owned application clear the low two bits first.',
18:'Packed color constants 0x8040FFFF and 0x000000FF feed DevText styling. Float12 and16 feed scale; float60 offsets spawn y; float0 clears z and velocity. Source and split .sdata2 bytes agree.',
20:'A 24-byte allocated read-only small-data section: two packed 32-bit color constants followed by four f32 constants12,16,60,0. It is mixed compiler-pooled constants, not six floating-point values.',
21:'Provides compiler-emitted packed menu colors and floating-point scale and spawn-position/velocity constants.',
23:'Applies the global item model/collision display setting on the ownerless initialization path. It ORs the mode into the prior byte, so exact inheritance requires suitable prior low bits; an existing1 combined with mode2 becomes3.',
26:'ORs the shared item collision-display mode into an item diagnostic byte; the owner argument is unused. It preserves existing low bits as well as unrelated flags rather than replacing the mode.',
28:'For NULL or nonfighter owner, ORs the global mode into xDAA_byte without clearing low bits. For fighter owner, clears low two bits, reads the full debug byte with fn_8022697C, and when that byte is nonzero ORs its low-two-bit mask. A nonzero full byte can still contribute zero low bits.',
32:'Applies collision-display bits according to runtime owner classification. Nonfighter owners use bitwise OR of the global mode; fighter owners replace low two bits from the fighter debug byte. The fallback is not an unconditional exact mode replacement.',
39:'Reads held and pressed buttons and the selected item kind. On accepted Down, fills selected fields of a local SpawnItem with player position plus60y, z/velocity0, facing from position, NULL parents, damage0, x40=0 and x44_flag.b0=1. It does not clear the entire descriptor. Successful creation receives global mode by OR into xDAA_byte and effect0x420.',
40:'Implements unmodified D-pad Down manual spawning of the selected item above the player. The Pokémon menu selection is consumed separately by the Poké Ball release path; this function does not directly spawn that selected Pokémon.',
42:'Handles the developer selected-item drop command, with availability and capacity checks. Pokémon selection affects the separate Poké Ball release path. The automatic random-spawn enable flag is not checked here.',
43:'Requires pressed Down and none of the other tested held buttons. Checks subsystem availability and common-item count for common kinds. The CZako count test applies to every kind below Octarock_Stone, including common kinds. Old_Kuri through pre-Arwing_Laser requires a nonzero availability entry. M_Ball is Poké Ball and is suppressed when it_8026C704 is nonzero. Success ORs mode and emits effect0x420; unassigned descriptor fields remain outside this function contract.',
45:'Clears the gate for ordinary automatic random item drops. Manual developer selected-item spawning does not read this flag.',
47:'Disables the normal random-item spawn schedule by clearing its outer enable guard, without changing selected item or Pokémon. It does not disable the manual developer Down command.',
56:'s32 db_GetCurrentlySelectedPokemon(void) returns the stored menu code without validation. Setup plus valid navigation maintains0..30; the consumer treats0 as random and maps nonzero code-1 into the Pokémon item domain.',
60:'Implements repeatable bounded L-plus-D-pad item and Pokémon navigation. Choices stop at the ends; they do not wrap as a full cycle.',
63:'From initialized state, reachable item ranges are0x00..0x22,0x2B..0x2E,0xD0..0xE9 inclusive. Up jumps22->2B and2E->D0; Down reverses those gaps. Pokémon stays0..0x1E under valid navigation. Four independent branches run Up, Down, Right, Left, so opposing directions can both execute. Corrupt prior state is not sanitized. Adventure choices0xDD..0xE9 select NULL label entries.',
65:'Exposes the persistent item-side coin diagnostic state. The item renderer tests xDAA_flag.b0 on It_Kind_Unk4, additional coin-state flags and the collision-draw result. This getter does not itself establish fighter-side sphere rendering.',
73:'Returns the persistent stomp-display bit. Setup and disable clear it; enable sets xDAA_flag.b3 only for items eligible through xDD0_flag.b0, while disable clears that named field on every item. b3 is bitfield declaration notation, not numeric mask1<<3.',
74:'Enable and disable write the shared ShowItemPickupRange bit and Item.xDAA_flag.b4 on all active items. The getter only returns the shared bit. Named field b4 must not be confused with numeric bit4.',
75:'Exposes item pickup-range diagnostic state. The item renderer additionally requires xDC8_word.flags.x15 and submits xBCC_unk geometry with RGBA FF408080. Fighter-side pickup geometry is a separate dependency.',
80:'Implements an exact-Develop B-plus-new-Right maintenance command that copies twelve current item-category counts into paired limit slots. Item initialization loads destination limits from common parameters; allocation code increments source counts and compares them against the paired destinations.',
82:'Copies twelve current item-system category counters into paired capacity limits on the Develop-only B-plus-Right command. This changes limits to current counts, not merely an opaque diagnostic snapshot.',
108:'Clears the item-side pickup-range diagnostic selected by the miscellaneous fighter-visual cycle. The renderer uses RGBA FF408080 for eligible item geometry; this routine only changes the display state.',
113:'Enables the coin-item diagnostic bit and global latch. The item renderer draws the coin collision primitive only when additional item-state predicates hold; fighter-side coin-detection spheres are not implemented here.',
124:'Enables the item-side pickup geometry diagnostic. Its renderer uses RGBA FF408080 and an additional pickup eligibility flag. Fighter white/blue pickup boxes and their interaction semantics remain a separate family review.',
133:'Called by debug setup when DbLevel>=DebugRom. Sets display0, current/last item0x22, current/last Pokémon0, collision mode1, stomp/pickup flags0. It does not reset the coin flag, spawn-enable flag, player, timer, text pointer or text buffer, so it is not a full lifecycle reset.',
137:'Attempts to reveal retained hidden text or allocate and configure a developer selection panel. It sets display status1 even if allocation fails; it does not guarantee that a usable visible panel exists.',
147:'Processes selection input and, on change, records player, resets timer120, attempts show/create unless status1, erases text and prints selected labels. It does not guarantee allocation success or nonNULL labels.',
148:'Unchanged selections skip display updates. Changed selections reset player/timer and refresh text. Table dispatch checks upper bounds but does not reject invalid gaps/lower indices; reachable0xDD..0xE9 uses thirteen NULL Adventure labels. At or above Arwing_Laser it loops forever. Allocation failure can leave status1 with NULL text, which DevText_Erase dereferences.',
151:'Implements developer item/Pokémon navigation, manual selected-item drops and item range/collision display propagation. Also owns the separate automatic random-spawn enable gate. The exact-Develop B-plus-Right command copies twelve current category counts into paired allocation limits.',
152:'Display states0/1/2 drive create/visible/hidden-reuse behavior, but failed creation still writes1. Selection changes reload timer120; matching-player calls decrement to0 and hide on the next call. Valid collision toggles cycle1..3; global application uses OR while fighter-owned updates replace low bits. Setup is partial and automatic spawning has a separate enable gate.'
}
fr={'src/melee/db/dbanim.c':[[1,100],[130,190]],'src/melee/db/dbinit.c':[[60,95],[145,245]],'src/melee/it/itspawn.c':[[120,240]],'src/melee/it/it_279C.c':[[1430,1510]],'src/melee/it/types.h':[[689,715]],'src/melee/it/forward.h':[[327,391]],'src/melee/it/item.c':[[112,146],[401,470],[705,720]],'src/melee/ft/ftlib.c':[[427,435]],'src/melee/gm/gmmain.c':[[130,140],[180,220]],'src/melee/it/itdraw.c':[[1,150],[200,235]],'src/melee/if/textlib.c':[[266,303],[336,354]]}
# End line360 was not emitted; only the displayed printf body is claimed.
fr['src/melee/if/textlib.c']=[[266,303],[336,354]]
# The tool printed exactly25 lines starting336, through360.
ranges={'.bss':[(17,29),(243,295),(297,363),(421,444)],'.data':[(321,363)],'.sdata':[(321,363)],'.sbss':[(17,29),(178,225),(297,363),(421,444)],'.sdata2':[(297,319),(365,419)],'db_80225D64':[(178,182)],'db_80225DD8':[(210,225)],'db_AreItemSpawnsEnabled':[(163,176)],'db_CheckAndSpawnItem':[(365,419)],'db_DisableItemSpawns':[(163,176),(365,419)],'db_EnableItemSpawns':[(163,176)],'db_GetCurrentlySelectedPokemon':[(158,161),(280,295)],'db_HandleItemPokemonMenuInput':[(243,295)],'db_ShowCoinPickupRange':[(53,56),(68,98)],'db_ShowEnemyStompRange':[(58,61),(100,128)],'db_ShowItemPickupRange':[(63,66),(130,156)],'fn_80225A54':[(31,51)],'fn_80225E6C':[(210,241)],'fn_CheckItemAndPokemonMenu':[(421,444)],'fn_DisableShowCoinPickupRange':[(84,98)],'fn_DisableShowEnemyStompRange':[(116,128)],'fn_DisableShowItemPickupRange':[(144,156)],'fn_EnableShowCoinPickupRange':[(68,82)],'fn_EnableShowEnemyStompRange':[(100,114)],'fn_EnableShowItemPickupRange':[(130,142)],'fn_SetupItemAndPokemonMenu':[(17,29)],'fn_ShowOrCreateItemAndPokemonMenu':[(297,319)],'fn_ToggleItemCollisionBubbles':[(189,205),(438,443)],'fn_UpdateItemAndPokemonMenu':[(243,363)],'FILE':[(17,51),(53,182),(189,241),(243,363),(365,444)]}
def ev(f,a,z,why='Reviewed pinned canonical implementation or declaration.'):
 return {'kind':'code','locator':f'code://{rev}/{f}#L{a}-L{z}','why':why}
def evidence(sym):
 es=[ev(src,a,z) for a,z in ranges[sym]]
 if sym.startswith('.') or sym in ['FILE','fn_UpdateItemAndPokemonMenu','db_HandleItemPokemonMenuInput']:es += [ev(hdr,1,102)]
 if sym in ['FILE','fn_SetupItemAndPokemonMenu','fn_CheckItemAndPokemonMenu']:es += [ev('src/melee/db/dbinit.c',60,95),ev('src/melee/db/dbinit.c',163,245)]
 if 'ItemSpawns' in sym or sym in ['FILE','.bss']:es += [ev('src/melee/it/itspawn.c',153,195),ev('src/melee/gm/gmmain.c',209,214)]
 if sym in ['db_GetCurrentlySelectedPokemon','db_CheckAndSpawnItem','FILE']:es += [ev('src/melee/it/it_279C.c',1434,1510)]
 if sym in ['db_CheckAndSpawnItem','FILE']:es += [ev('src/melee/it/types.h',689,707)]
 if sym in ['fn_ShowOrCreateItemAndPokemonMenu','fn_UpdateItemAndPokemonMenu','.bss','FILE']:es += [ev('src/melee/if/textlib.c',275,278)]
 if sym in ['fn_80225A54','FILE']:es += [ev('src/melee/it/item.c',118,144),ev('src/melee/it/item.c',401,470)]
 if 'Range' in sym or sym in ['fn_80225E6C','db_80225DD8','fn_ToggleItemCollisionBubbles','db_80225D64','.sbss','FILE']:es += [ev('src/melee/db/dbanim.c',1,87),ev('src/melee/db/dbanim.c',150,190),ev('src/melee/it/itdraw.c',76,142),ev('src/melee/it/itdraw.c',216,235)]
 if 'PickupRange' in sym:es += [ev('src/melee/it/itdraw.c',12,12)]
 if sym in ['db_80225DD8','fn_80225E6C']:es += [ev('src/melee/ft/ftlib.c',427,434)]
 return es
props=[];disp=[]
for i,f in enumerate(facts):
 sym='FILE' if f['subject']==src else f['subject'].split(':')[-1];d='supersede' if i in changes else 'retain';es=evidence(sym);why=('Corrected branch, layout, consumer or scope claim after current canonical/rendered review.' if d=='supersede' else 'Current canonical/rendered review independently supports this retained fact.')
 if sym.startswith('.') or sym=='FILE':why+=f' Existing-object companion compiled-evidence.json SHA-256 {eh}; no rebuild or runtime verification.'
 if f['type']=='inferred_name':why+=' Hypothesis pending independent review; no canonical rename. Frozen baseline collision check is recorded.'
 props.append({'subject':{'entity_locator' if sym=='FILE' else 'target_stable_key':f['subject']},'type':f['type'],'op':'write','value':changes.get(i,f['value']),'rationale':why,'confidence':.94 if d=='supersede' else f['confidence'],'evidence':es})
 disp.append({'subject':f['subject'],'fact_id':f['id'],'updated_at':f['updated_at'],'version':f['updated_at'],'type':f['type'],'disposition':d,'action':why,'evidence':es})
for sub in t['writable_subjects']:
 k=next(iter(sub.values()))
 if any(f['subject']==k for f in facts):continue
 sym=k.split(':')[-1].split('#')[0];disp.append({'subject':k,'fact_id':None,'updated_at':None,'version':None,'disposition':'retain','action':'No inherited fact. Canonical parameter use reviewed; no new parameter fact proposed.','evidence':evidence(sym)})
def write(name,x): (p/name).write_text(json.dumps(x,indent=2)+'\n')
write('proposal.json',{'tu':tu,'proposal':{'facts':props,'links':[],'entities':[],'merges':[],'follow_ups':[]}})
lp=r/'baseline-links'/f"{t['id']}.json";links=json.load(open(lp));ld=[]
for i,l in enumerate(links):
 sym='FILE' if l['from_entity_id'] else l['from_target_id'].split(':')[-1];d='retain';reason='Current owned behavior and reviewed canonical consumers support this exact relationship, independently of archived naming/wiki assertions.'
 if i==16:d='reject';reason='Incorrect spawn facility association: this setter disables the ordinary random-spawn schedule, not the manual developer selected-item path.'
 if i==37:d='unresolved';reason='Selected-item state supports this relationship, but stored rationale wrongly attributes the automatic spawn-enable flag to the manual path. Reconcile exact rationale reversibly.'
 if i==0:d='unresolved';reason='Manual item spawning is supported; stored rationale can imply direct Pokémon creation. Pokémon selection is consumed by the later Poké Ball release path. Reconcile rationale.'
 if i in [27,35]:d='unresolved';reason='Collision-display participation is supported, but global fallback ORs rather than replaces low bits. Exact inheritance needs prior-state qualification in the rationale.'
 if i==26:reason='Current renderer independently supports model bit plus collision bit mode combinations1/2/3, subject to renderer eligibility flags. Archived labels remain shorthand, not proof every item draws all geometry.'
 ld.append({'link_id':l['id'],'baseline':l,'disposition':d,'reason':reason,'evidence':evidence(sym)})
write('link-dispositions.json',{'tu':tu,'revision':rev,'baseline_path':str(lp),'baseline_sha256':hashlib.sha256(lp.read_bytes()).hexdigest(),'link_count':len(ld),'retained':sum(x['disposition']=='retain' for x in ld),'rejected':sum(x['disposition']=='reject' for x in ld),'unresolved':sum(x['disposition']=='unresolved' for x in ld),'db_link_changes':False,'links':ld})
db=sqlite3.connect('file:'+m['baseline_db']+'?mode=ro',uri=True);coll=[]
for f in facts:
 if f['type']=='inferred_name':
  v=f['value'];hits=db.execute("SELECT t.stable_key,t.symbol,f.value FROM target t LEFT JOIN fact f ON f.target_id=t.id AND f.type='inferred_name' WHERE t.identity_status='current' AND (t.symbol=? OR f.value=?) AND t.stable_key<>?",(v,v,f['subject'])).fetchall();coll.append({'subject':f['subject'],'candidate':v,'other_current_matches':hits})
write('naming-collisions.json',coll)
reads=[json.loads(x) for x in (state/'reads.jsonl').read_text().splitlines()];start=min(x['at'] for x in reads if x.get('reader')=='dbitem_complete_review');end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');files=[dict(f,canonical_ranges=[[1,f['lines']]],rendered_ranges=[[1,f['lines']]]) for f in m['files'] if f['path'] in t['files']]
write('foreign-ranges.json',fr)
write('coverage.json',{'tu':tu,'subjects':disp,'files':files,'started_at':start,'research_start':start,'research_end':end,'completed_at':end,'fact_count':len(facts),'reviewed_subject_count':len(t['writable_subjects']),'fact_version_kind':'updated_at','render_exceptions':['Manifest/render includes a trailing empty line: header page1..103; canonical validation counts102 non-trailing lines. Evidence ends at102.'],'render_metadata':{'source_parse_errors':0,'header_parse_errors':0,'source_substitutions_per_page':8,'header_substitutions':0,'next_line':None},'foreign_reads':[{'path':f,'canonical_ranges':rs} for f,rs in fr.items()],'links_reviewed':len(ld),'link_dispositions':'link-dispositions.json','owned_header_coverage':[{'path':hdr,'canonical_ranges':[[1,103]],'rendered_ranges':[[1,103]]}]})
summary={'tu':tu,'status':'draft_pending_independent_review','started_at':start,'research_start':start,'research_end':end,'completed_at':end,'files_reviewed':2,'canonical_lines':548,'rendered_lines':548,'subjects_reviewed':42,'existing_facts_reviewed':153,'retained_facts':153-len(changes),'superseded_facts':len(changes),'new_facts':0,'proposal_facts':153,'retained_name_hypotheses':len(coll),'proposed_names':0,'clears':0,'compiled_evidence_sha256':eh,'report_sha256':m['report_sha256'],'proposal_sha256':hashlib.sha256((p/'proposal.json').read_bytes()).hexdigest(),'links_reviewed':41,'links_retained':sum(x['disposition']=='retain' for x in ld),'links_rejected':sum(x['disposition']=='reject' for x in ld),'links_unresolved':sum(x['disposition']=='unresolved' for x in ld)};write('summary.json',summary)
write('unresolved.json',{'tu':tu,'items':[{'topic':'NULL Adventure labels','status':'source_observed','detail':'Valid navigation reaches0xDD..0xE9 with NULL table labels; formatter NULL-string policy has not been reviewed. No crash assertion for these strings.'},{'topic':'Failed DevText allocation','status':'cross_file_review_required','detail':'Show/create writes status1 even on NULL; updater calls DevText_Erase which dereferences text. No runtime reproduction.'},{'topic':'Descriptor and family scope','status':'family_review','detail':'SpawnItem is partially initialized. Full Item_80268B18 consumer contract, fighter-side coin/pickup geometry and all allocation-category semantics are outside this owned TU.'},{'topic':'Initialization and mode OR','status':'source_observed','detail':'Setup is partial. Global collision application preserves prior low bits; renderer states are valid-state shorthand. Parent frame dispatcher permits DebugRom and higher; only maintenance explicitly requires exact Develop.'},{'topic':'Validation limits','status':'not_executed','detail':'No compilation, matching, runtime, publication or KB apply. Existing object provenance is recorded; split padding differs from source object.'}]})
(p/'naming.md').write_text('# Naming review\n\nSeven inherited names remain hypotheses pending independent review. No source rename or new name proposed.\n\n| Canonical | Hypothesis | Disposition |\n|---|---|---|\n'+''.join(f"| {f['subject'].split(':')[-1]} | {f['value']} | retain hypothesis |\n" for f in facts if f['type']=='inferred_name')+'\nSee naming-collisions.json for frozen baseline lookup results.\n')
print(json.dumps(summary));assert len(facts)==153 and len(ld)==41 and len({d['subject'] for d in disp})==42
