import pathlib,json,markdown
O=pathlib.Path(__file__).resolve().parents[2]/'analysis/reports/melee-contributions-2026-09-07'
body=markdown.markdown((O/'report.md').read_text(),extensions=['tables','fenced_code','toc'])
body=body.replace('<table>','<div class="tablewrap"><table>').replace('</table>','</table></div>')
data=(O/'ledgers.json').read_text().replace('</','<\\/')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Melee Contributions · fjooord</title>
<style>
:root{--ink:#172b42;--muted:#506078;--blue:#235fcc;--paper:#f5f7fa;--line:#d7dfe9}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.6 system-ui,-apple-system,sans-serif}a{color:var(--blue)}header{padding:44px max(24px,calc((100vw - 1280px)/2));background:#142c46;color:white}header p{color:#cedaeb;margin:8px 0}h1{font-size:clamp(28px,4vw,46px);line-height:1.13;letter-spacing:-1px;margin:0 0 18px}h2{font-size:26px;line-height:1.3;margin-top:46px;scroll-margin-top:70px}h3{font-size:20px}nav{position:sticky;top:0;z-index:2;background:white;border-bottom:1px solid var(--line);padding:12px 24px;display:flex;gap:24px;flex-wrap:wrap}nav a{text-decoration:none;font-weight:650}main{max-width:1330px;padding:24px;margin:auto}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:14px;margin:8px 0 28px}.card{background:white;border:1px solid var(--line);padding:20px;border-radius:10px}.card strong{display:block;font-size:34px;line-height:1.2}.card span{font-size:14px;color:var(--muted)}.note{padding:16px 20px;background:#e8f0ff;border-left:4px solid var(--blue);border-radius:4px}article{background:white;border:1px solid var(--line);border-radius:10px;padding:8px 28px 28px}article>h1{display:none}article>p:first-of-type{color:var(--muted);font-size:14px}.tablewrap{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:13px;margin:14px 0 22px}th{text-align:left;background:#eaf0f8;color:#16345a;white-space:nowrap}th,td{padding:10px 12px;border-bottom:1px solid var(--line);vertical-align:top}td{overflow-wrap:anywhere}tbody tr:nth-child(even){background:#f8fafc}code{font-size:13px;overflow-wrap:anywhere}button,select,input{font:inherit;padding:9px 12px;border:1px solid #abbcd0;border-radius:5px;background:white;color:var(--ink)}button{cursor:pointer}button.active{background:var(--blue);color:white;border-color:var(--blue)}.controls{display:flex;gap:10px;flex-wrap:wrap;margin:12px 0}.controls input{min-width:240px;flex:1}.small{font-size:13px;color:var(--muted)}#explorer{margin:32px 0;padding:24px;background:white;border:1px solid var(--line);border-radius:10px}#explorer h2{margin-top:0}#grid td{max-width:340px}#grid a{word-break:break-word}.pager{display:flex;align-items:center;gap:14px}@media(max-width:850px){.cards{grid-template-columns:repeat(2,1fr)}main{padding:12px}article{padding:8px 16px 20px}nav{gap:14px;font-size:14px}header{padding:30px 20px}}@media print{nav,#explorer{display:none}body{background:white}article{border:0}h2{break-after:avoid}tr{break-inside:avoid}.cards{grid-template-columns:repeat(5,1fr)}header{padding:16px;color:black;background:white}header p{color:black}}
</style>
<header><p>GAMECUBE DECOMP HARNESS / CONTRIBUTION AUDIT</p><h1>Your Melee matches,<br>with the evidence attached.</h1><p>fjooord · June–September 2026 · Snapshot September 7, 2026</p></header>
<nav><a href="#results">Results</a><a href="#explorer">Search the ledgers</a><a href="#the-3259-overlap">#3259 attribution</a><a href="#every-merged-pr">Every merged PR</a><a href="#evidence-and-counting-rules">Method</a></nav>
<main><section id="results" class="cards"><div class="card"><strong>57</strong><span>personal PRs merged</span></div><div class="card"><strong>551+</strong><span>distinct functions matched in merged evidence</span></div><div class="card"><strong>665+</strong><span>distinct matches including Harness discoveries</span></div><div class="card"><strong>88</strong><span>files gained ≥1,000 exact bytes in one merge</span></div><div class="card"><strong>24</strong><span>earlier Harness matches in #3259</span></div></section>
<p class="note">The 665-function total includes the 551 merged functions. Data sections are counted separately. Earlier runner results establish discovery dates; explicit source credit and shared-function overlap are separate evidence categories.</p>
<section id="explorer"><h2>Search the Contribution Ledgers</h2><div id="tabs" class="controls"></div><div class="controls"><input id="search" placeholder="Search a function, file, PR, author, or date" aria-label="Search ledger"><select id="sort" aria-label="Sort column"></select><button id="direction">Ascending</button></div><p id="description" class="small"></p><div class="tablewrap" id="grid"></div><div class="pager"><button id="prev">Previous</button><span id="count" class="small"></span><button id="next">Next</button></div><p class="small">Evidence paths point to the original local validation records. The #3259 runner records are also preserved in this report's evidence/db-runner folder. Raw tables: <a href="ledgers.json">ledgers.json</a> · <a href="summary.json">summary.json</a> · <a href="report.md">Markdown report</a></p></section>
<article>'''+body+'''</article></main><script id="data" type="application/json">'''+data+'''</script><script>
const data=JSON.parse(document.querySelector('#data').textContent);let view='PRs',page=0,ascending=true;
const descriptions={'PRs':'All 57 merged personal PRs. Function counts from older visible bot tables are lower bounds.','Functions':'665 distinct exact functions. Merged + Harness means the function occurs in both groups. Harness-only discoveries are not automatically accepted upstream patches.','Files':'C source paths and measured function movements. Exact-byte totals cover only the 44 surviving CI pairs. Rows without numerical movement may still contain source or supporting changes.','Credited PRs':'13 merged implementation PRs whose descriptions explicitly credit or describe reuse of your work.','DB overlap':'All 26 function matches in #3259, including 24 with earlier passed exact Harness evidence.','Other overlaps':'Earlier passed Harness exact results followed by another author’s merged bot match. This is a candidate list, not proof of copying or independent additive credit.'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={CodeBytes:'Net exact code bytes',ExactFunctions:'Distinct exact functions',ImprovedFunctions:'Distinct improved functions',NetExactBytesFrom44CI:'Net exact bytes · 44 CI pairs',LargestWholeFileGain:'Largest whole-file gain',GainPP:'Gain · pp',MergedPRs:'Personal merged PRs',FirstRunnerExact:'First verified runner exact · UTC',BeforeDB:'Earlier runner time · UTC',HarnessScore:'Best earlier runner score',RunnerExact:'Runner exact · UTC',PROpened:'PR opened · UTC'};
function cell(v,k,row){if(!v&&v!==0)return '—';if(k==='PR')return `<a href="${esc(row.URL)}" target="_blank" rel="noreferrer">${esc(v)}</a>`;if(k==='URL'||k==='Evidence'||k==='RunnerEvidence'){const path=String(v);let href=path.startsWith('https://')?path:path.startsWith('/')?'file://'+path:path;return `<a href="${esc(href)}" target="_blank" rel="noreferrer">${k==='URL'?'GitHub':k==='RunnerEvidence'?'Runner record':path.startsWith('https://')?'PR evidence':'Runner record'}</a>`;}return esc(v)}
function render(){const q=document.querySelector('#search').value.toLowerCase();let rows=data[view].filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(q)));const key=document.querySelector('#sort').value;rows.sort((a,b)=>(typeof a[key]==='number'?a[key]-b[key]:String(a[key]??'').localeCompare(String(b[key]??'')))*(ascending?1:-1));const keys=Object.keys(data[view][0]).filter(k=>k!=='Identity'&&k!=='GainPP'&&!(k==='URL'&&view!=='Functions'));page=Math.min(page,Math.max(0,Math.ceil(rows.length/40)-1));document.querySelector('#grid').innerHTML='<table><thead><tr>'+keys.map(k=>'<th>'+esc(labels[k]||k)+'</th>').join('')+'</tr></thead><tbody>'+rows.slice(page*40,(page+1)*40).map(r=>'<tr>'+keys.map(k=>'<td>'+cell(r[k],k,r)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';document.querySelector('#count').textContent=rows.length?`${page*40+1}–${Math.min((page+1)*40,rows.length)} of ${rows.length} records`:'No matching records';document.querySelector('#prev').disabled=page===0;document.querySelector('#next').disabled=(page+1)*40>=rows.length;document.querySelector('#description').textContent=descriptions[view]}
function choose(name){view=name;page=0;document.querySelector('#search').value='';document.querySelector('#tabs').innerHTML=Object.keys(data).map(n=>`<button class="${n===view?'active':''}" data-view="${esc(n)}">${esc(n)} · ${data[n].length}</button>`).join('');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>choose(b.dataset.view));document.querySelector('#sort').innerHTML=Object.keys(data[view][0]).filter(k=>!k.includes('Evidence')&&k!=='URL').map(k=>`<option>${esc(k)}</option>`).join('');render()}
document.querySelector('#search').oninput=()=>{page=0;render()};document.querySelector('#sort').onchange=()=>{page=0;render()};document.querySelector('#direction').onclick=()=>{ascending=!ascending;document.querySelector('#direction').textContent=ascending?'Ascending':'Descending';render()};document.querySelector('#prev').onclick=()=>{page--;render()};document.querySelector('#next').onclick=()=>{page++;render()};choose('PRs');
</script></html>'''
(O/'report.html').write_text(page)
print('Wrote',O/'report.html',len(page),'characters')
