import runpy,json,pathlib,hashlib,datetime
out=pathlib.Path(__file__).parent;g=runpy.run_path(str(out/'build.py'));ev=g['ev'];evidence=g['evidence'];rows=g['rows'];name=g['name'];src=g['src'];rev=g['rev'];p=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908/baseline-links/main__melee__lb__lbaudio_ax.json');links=json.load(open(p));result=[]
reject={4:'The archived rationale says interpolation between requested endpoints. The decreasing branch starts at end_vol and ends at 2*end_vol-start_vol; zero duration is also unchecked. Reject this wording pending a narrowed relation.',36:'This operation pauses the singleton path-selected stream, not the driver-wide sound-effect set. The stored SFX-pausing rationale is misleading; defer a stream-specific replacement to family ownership.',92:'lbl_804D3884 feeds only the group-1 calculation; the archived rationale claims multiple Synth groups.',95:'The delay heap assertion requests type 2 using an AXFX_DELAY object, while installation uses type 4. The stored claim that both processors are verified to fit is unsupported.'}
deferred={33:'Match-outcome caller not independently read.',44:'Metadata gating and saved index are verified; Trophy Gallery restoration consumer not independently read.',46:'Key-off entry and immediate volume update verified; bounded ramp/reclamation internals not exhausted.',53:'EntryStart consumer not independently read.',62:'Release wrapper verified; exact Super Star status identity and expiration consumer pending fighter/item review.',65:'Local suppression and restoration verified; disc-error consumer not independently read.',68:'Fade affects groups1-7 locally; claimed repeated scene-controller use not independently read.',77:'Selective pause operation verified; match-pause caller not independently read.',78:'Selective pause operation verified; Camera Mode caller not independently read.',110:'Fighter status-duration registration verified; exact Super Star item identity pending.',112:'Restoration operation verified; disc-error teardown consumer not independently read.'}
for k,l in enumerate(links):
 n=(l['from_target_id'] or l['from_entity_id']).split(':')[-1];i=99 if n==src else next(j for j,r in enumerate(rows[:99]) if name(r)==n);es=evidence(i);disp='reject' if k in reject else 'unresolved' if k in deferred else 'retain';reason=reject.get(k,deferred.get(k,'The relation is supported by the pinned implementation and independently read supporting records.'))
 if k in [3,7,10,16,29,30,41,107,138]:reason+=' Retained as the normal finite-arithmetic behavior only: unequal-endpoint zero-duration pan and zero-duration volume divisions are unguarded; no total-function safety claim is accepted.'
 if k in [9,122]:reason+=' The ID guard is upper-only and doubling precedes saturation; this does not validate every possible signed input.'
 if k==15:reason+=' Current source names the descriptor lbl_80433710 directly, not lbl_80433710.alloc.'
 if k in [13,42,49,50,118,158,159,160]:reason+=' A stored handle different from -1 is forwarded; the wrapper does not establish actual driver liveness or successful key-off.'
 if k in [75,164]:reason+=' Common mask augmentation is unsigned addition, not bitwise OR.'
 if i==99:
  concept=(l['to_entity_id'] or '').split(':')[-1]
  if 'bank' in concept:es=[ev(src,1529,1966,'Complete bank selection, accounting, load and localization path.')]
  elif 'volume' in concept or 'panning' in concept:es=[ev(src,728,802,'Mixer state'),ev(src,1032,1416,'Controller arithmetic and propagation.')]
  elif 'stream' in concept:es=[ev(src,379,435,'Indexed path and stream selection.'),ev('src/sysdolphin/baselib/axdriver.c',1276,1321,'Stream singleton implementation.')]
  elif 'playback' in concept:es=[ev(src,1269,1527,'Controller creation, update and teardown.')]
  elif 'auxiliary' in concept:es=[ev(src,728,802,'Aux send application'),ev(src,2090,2154,'Effect installation and type mismatch.')]
 if k in [57]:es += [ev('src/melee/mn/mncharsel.c',2163,2184,'Character selector invokes announcer dispatcher.'),ev('src/melee/gm/gm_1601.c',3940,4028,'Index-to-announcer-ID dispatch.')]
 if k in [61,80,84,86,151,152,155,156]:es += [ev('src/melee/db/dbsound.c',46,138,'Developer overlay samples counts and emits control bits.')]
 if k in [87]:es += [ev('src/melee/ft/kinds/ftCommon/ftCo_HammerWait.c',104,214,'Hammer registration and expiration release.'),ev('src/melee/ft/ft_0877.c',435,450,'Per-fighter/global count wrapper.')]
 result.append({'id':l['id'],'baseline_record':l,'version':{'updated_at':None,'record_sha256':hashlib.sha256(json.dumps(l,sort_keys=True,separators=(',',':')).encode()).hexdigest()},'disposition':disp,'reason':reason,'evidence':es})
payload={'tu':g['tu'],'revision':rev,'baseline_path':str(p),'baseline_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'reviewed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'counts':{'total':len(result),**{d:sum(r['disposition']==d for r in result) for d in ['retain','reject','unresolved']}},'links':result,'policy':'Draft dispositions only. No shared KB link mutation or deletion.'};(out/'link-dispositions.json').write_text(json.dumps(payload,indent=2)+'\n');print(payload['counts'])
