import json,pathlib,hashlib,datetime,struct,shutil
D=pathlib.Path(__file__).parent;S=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');M=json.load(open(S/'manifest.json'));R=M['head_revision'];root=pathlib.Path(M['checkout_root']);tu='main/melee/ft/kinds/ftCommon/ftCo_CliffEscape';P='src/melee/ft/kinds/ftCommon/ftCo_CliffEscape.c';C=json.load(open(D/'context.json'));X=json.load(open(D/'baseline-facts.json'));start='2026-09-08T15:26:04Z';U=S/'units'/C['task']['id']
def c(p,a,b):return f'code://{R}/{p}#L{a}-L{b}'
foreign=[('src/melee/ft/kinds/ftCommon/ftCo_CliffClimb.c',1,137),('src/melee/ft/ftcliffcommon.c',110,126),('src/melee/ft/ftmotionstates.c',2972,2993),('src/melee/ft/kinds/ftCommon/ftCo_CliffAttack.c',69,86),('src/melee/ft/kinds/ftCommon/ftCo_CliffWait.c',43,50),('src/melee/ft/ftcommon.c',596,604),('src/melee/ft/ftcommon.c',906,909),('src/melee/ft/ftanim.c',380,386),('src/melee/ft/types.h',330,338)]
fr=[]
for p,a,b in foreign:
 t=(root/p).read_text();fr.append(dict(path=p,start_line=a,end_line=b,sha256=hashlib.sha256(t.encode()).hexdigest(),canonical_read=True,rendered_read=False,ownership='foreign evidence only'));(D/(p.replace('/','__')+f'.{a}-{b}.txt')).write_text('\n'.join(f'{i}: {l}' for i,l in enumerate(t.splitlines(),1) if a<=i<=b))
E=[c(P,13,41)]+[c(p,a,b) for p,a,b in foreign]
report=root/'build/GALE01/report.json';rh=hashlib.sha256(report.read_bytes()).hexdigest();assert rh==M['report_sha256'];unit=next(u for u in json.load(open(report))['units'] if u['name']==tu);objects=[]
for typ in ['src','obj']:
 p=root/f'build/GALE01/{typ}/melee/ft/kinds/ftCommon/ftCo_CliffEscape.o';b=p.read_bytes();e='>' if b[5]==2 else '<';off=struct.unpack_from(e+'I',b,32)[0];sz,n,si=struct.unpack_from(e+'HHH',b,46);sh=[struct.unpack_from(e+'10I',b,off+i*sz) for i in range(n)];st=sh[si];names=b[st[4]:st[4]+st[5]]
 for s in sh:
  if names[s[0]:].split(b'\0')[0]==b'.sdata2':objects.append(dict(path=str(p),sha256=hashlib.sha256(b).hexdigest(),section='.sdata2',size=s[5],elf_flags=s[2],elf_flags_hex=hex(s[2]),writable=bool(s[2]&1),allocated=bool(s[2]&2),bytes_hex=b[s[4]:s[4]+s[5]].hex()))
json.dump(dict(report_path=str(report),report_sha256=rh,pinned_report_hash_matches=True,unit=unit,objects=objects),open(D/'section-evidence.json','w'),indent=2)
print('section evidence',objects,unit.get('sections'))
asm=root/'build/GALE01/asm/melee/ft/kinds/ftCommon/ftCo_CliffEscape.s';se=json.load(open(D/'section-evidence.json'));se['assembly']=dict(path=str(asm),sha256=hashlib.sha256(asm.read_bytes()).hexdigest(),read='complete',finding='@233 f32 zero; @234 f32 one; @236 f64 4503601774854144. Entry loads signed common x488, XORs sign bit, combines 0x4330 high word, subtracts @236 and compares to percent.');se['permission_limit']='Source object .sdata2 flags 0x3 W|A, split object flags 0x2 A. Runtime memory protection is not established by either.';json.dump(se,open(D/'section-evidence.json','w'),indent=2)
O={('.sdata2','inferred_type'):'Sixteen-byte compiler literal pool containing f32 0.0, f32 1.0 and f64 4503601774854144 (0x4330000080000000), the bias used for signed-integer-to-floating conversion of the common damage threshold. It is not solely an f32 pool or a structured gameplay record.',('.sdata2','data_flow'):'Entry uses f32 zero for initial frame and blend, f32 one for animation speed, and a double conversion bias to convert signed common x488 for comparison with fighter damage. The TU does not write these literals. This read usage does not imply nonwritable ELF flags or runtime memory protection.',('.sdata2','purpose'):'Supplies compiler literals for CliffEscape motion initialization and signed common-threshold conversion. These are numeric implementation constants, not an authored gameplay table. The observed source object permits writes to the allocated section, while the split object marks it allocated without SHF_WRITE; final runtime protection is not established.',('ftCo_8009B040','purpose'):'Enters CliffEscapeQuick or CliffEscapeSlow according to fighter damage, initializes animation and common state, sets two flags and immediately runs cliff-catch physics. That helper positions the fighter relative to the held ledge when its ledge-validity test succeeds, and enters Fall when the test fails.'}
rows=[];disp=[];facts=[]
for s in X:
 key=next(iter(s['subject'].values()));name=key.split(':')[-1];rows.append(dict(subject=s['subject'],status='reviewed' if s['facts'] else 'reviewed_no_existing_facts',fact_count=len(s['facts']),evidence=E,notes='All functions accept one source gobj parameter; no speculative register mapping.'))
 for f in s['facts']:
  new=O.get((name,f['type']));reason='Canonical implementation, ledge-wait input caller and paired state-table entries support existing semantics; preserve without citation-only rewriting.'
  if new:reason='Existing object/report/assembly evidence shows a 16-byte mixed float/double pool and different source/split flags; see hashed section-evidence.json. Canonical signed x488 comparison establishes conversion use.' if name=='.sdata2' else 'Immediate cliff-catch physics has a Fall fallback when the ledge test fails; entry does not guarantee continued ledge attachment.'
  disp.append(dict(subject=s['subject'],fact_id=f['id'],version=f['updated_at'],type=f['type'],old_value=f['value'],disposition='supersede' if new else 'retain',reason=reason,replacement=new,evidence=E))
  if new:
   ev=[c(P,13,25),c('src/melee/ft/types.h',330,338)] if name=='.sdata2' else [c(P,13,25),c('src/melee/ft/ftcliffcommon.c',110,126)]
   facts.append(dict(subject=s['subject'],type=f['type'],op='write',value=new,rationale=reason,confidence=0.95,evidence=[dict(kind='code',locator=e,why=reason) for e in ev]))
end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');reads=[json.loads(l) for l in open(U/'reads.jsonl') if json.loads(l).get('reader')=='CliffEscape'];L=S/'baseline-links'/f'{C["task"]["id"]}.json';links=json.load(open(L));ld=[]
for l in links:
 ld.append(dict(link_id=l['id'],baseline_record=l,from_target_id=l['from_target_id'],from_entity_id=l['from_entity_id'],to_target_id=l['to_target_id'],to_entity_id=l['to_entity_id'],role=l['role'],prior_rationale=l['why'],version_or_digest=l.get('digest'),disposition='retain',reconciliation_owner='/root/semantic_coordinator',reason='Retain semantic ledge-roll relationship: ledge-wait IASA dispatches LR-triggered escape entry, the entry selects quick/slow CliffEscape states, and both table rows install this callback suite. Historical PR/Discord text is not independently reattested; current canonical implementation supports the relationship. Empty IASA is a registered no-op phase. Duplicate records remain individually accounted for.',evidence=[c(P,13,41),c('src/melee/ft/kinds/ftCommon/ftCo_CliffWait.c',43,50),c('src/melee/ft/kinds/ftCommon/ftCo_CliffAttack.c',69,86),c('src/melee/ft/ftmotionstates.c',2972,2993),c('src/melee/ft/kinds/ftCommon/ftCo_CliffClimb.c',90,137)]))
json.dump(dict(revision=R,input_path=str(L),input_sha256=hashlib.sha256(L.read_bytes()).hexdigest(),expected_count=len(links),reviewed_count=len(ld),counts=dict(retain=len(ld)),reconciliation_owner='/root/semantic_coordinator',dispositions=ld),open(D/'link-dispositions.json','w'),indent=2)
json.dump(dict(tu=tu,proposal=dict(facts=facts,links=[],entities=[],merges=[],follow_ups=[])),open(D/'proposal.json','w'),indent=2)
json.dump(dict(revision=R,start_utc=start,end_utc=end,counts=dict(retain=len(disp)-len(facts),supersede=len(facts)),dispositions=disp),open(D/'fact-dispositions.json','w'),indent=2)
json.dump(dict(campaign=M['campaign_id'],tu=tu,revision=R,role='TU librarian',model=M['model'],reasoning_effort=M['reasoning_effort'],start_utc=start,end_utc=end,input_files=C['files'],canonical_and_rendered_receipts=reads,foreign_evidence_reads=fr,subjects=rows,counts=dict(targets=6,source_entities=1,parameter_entities=5,existing_facts=len(disp),outgoing_links=len(ld),proposal_facts=len(facts),owned_lines=56),exceptions=[],section_evidence='section-evidence.json',link_dispositions='link-dispositions.json'),open(D/'coverage.json','w'),indent=2)
json.dump(dict(unresolved=[],family_followups=['Source object .sdata2 SHF_WRITE differs from split object; neither determines runtime memory protection.','Historical PR/Discord wording was not re-read; links retained on current canonical semantic evidence. Root owns any later link deletion/deduplication.','Shared field types, ledge validity and common movement callbacks are foreign evidence only.']),open(D/'unresolved.json','w'),indent=2)
(D/'functionality.md').write_text(f'# Ledge escape and shared climb processing\n\nDraft at `{R}`.\n\nLedge-wait IASA tries attack, escape, jump and climb/drop checks in order. The escape check accepts LR input or its shared secondary predicate and calls ftCo_8009B040. Entry selects Quick only for damage strictly below signed common x488; equal-or-greater values select Slow. It requests flags zero, frame zero, speed one, blend zero and no alternate source, runs animation initialization, stores 32 in x1A6A, sets x221D_b7/b5 and immediately invokes cliff-catch physics. A valid ledge is used for pose-relative position; a failed ledge test enters Fall instead.\n\nBoth escape state-table entries install the four canonical callbacks. Anim forwards to CliffClimb animation completion, which invokes ftCommon_8007D92C when frames end; that helper chooses Fall while airborne and common action-end handling while grounded. IASA is empty and provides no input-driven interruption. Phys and Coll forward unchanged to shared CliffClimb processing. Airborne physics places the fighter using ledge geometry and animation translation, converts to ground when both translation components are nonnegative, and falls if the ledge becomes invalid. Grounded physics delegates to ft_80084FA8. Collision branches on ground/air and delegates its tests/transitions; the wrapper adds no policy.\n\nThe five signatures agree with the header. Existing ftCo_CliffEscape_Enter remains a supported hypothesis; canonical callback names are preserved.\n\n## Literal pool and permissions\n\nBoth existing objects have the same 16 bytes: `000000003f8000004330000080000000`. These are two f32 values (0 and 1), followed by the f64 signed-conversion bias 4503601774854144. Assembly loads signed x488, flips its sign bit and subtracts that bias before the damage comparison. The old description as a single-precision pool omitted this double.\n\nSource object flags are 0x3 (WRITE|ALLOC); split-object flags are 0x2 (ALLOC). The source reads literals and never writes them, but that does not make the source-object section nonwritable or prove final runtime protection. Hashed ELF, assembly and frozen-report evidence is recorded separately. No build ran.\n\nAll outgoing links are individually retained using canonical ledge-input, state-table and callback evidence. Their historical rationale/locator is preserved without claiming the PR or Discord message was re-read.\n\n## Canonical evidence\n\n'+'\n'.join('- '+e for e in E)+'\n')
(D/'naming.md').write_text('# Naming review\n\n| Canonical subject | Existing hypothesis | Decision |\n|---|---|---|\n| ftCo_8009B040 | ftCo_CliffEscape_Enter | Retain: ledge-wait escape dispatch and state table establish entry. |\n| CliffEscape_Anim / IASA / Phys / Coll | None | Preserve canonical names. |\n| Source entity / .sdata2 | None | No new name needed. |\n\nNo canonical names or files changed.\n')
(D/'README.md').write_text(f'# CliffEscape review packet\n\nRevision `{R}`. UTC `{start}` to `{end}`. Model `{M["model"]}`, role TU librarian.\n\nComplete canonical and rendered coverage: C1-43, H1-13. Six targets, source entity and five empty parameter entities covered. {len(disp)} facts: {len(disp)-len(facts)} retained, {len(facts)} corrections proposed. All {len(ld)} outgoing link records individually retained. No failed/empty renders or parser errors.\n\nRead functionality.md and naming.md; audit coverage.json, fact-dispositions.json, link-dispositions.json, section-evidence.json and unresolved.json. No source, KB or build edits.\n')
print('facts',len(disp),'links',len(ld),'writes',len(facts),'end',end)
