import { DEFAULT_PI_MODEL, DEFAULT_PI_PROVIDER, DEFAULT_PI_THINKING_LEVEL, DEFAULT_STATE_DIR_NAME } from "./defaults.js";

export function usage(): string {
  return [
    "Usage:",
    "  decomp-orchestrator [global flags] init-run [--goal-kind kind] [--goal-value n] [--desired-workers n] [--candidate-limit n]",
    "  decomp-orchestrator [global flags] tick [--run-id id] [--candidate-limit n] [--candidate-window n] [--queue-target-size n]",
    "  decomp-orchestrator [global flags] worker [--run-id id] [--worker-id id] [--report-type type] [--base-rev rev] [--ttl-seconds n] [--repair-attempts n] [--post-return-check-command cmd]",
    "  decomp-orchestrator [global flags] trigger-agent [--run-id id] [--max-workers n] [--worker-thinking-level level] [--idle-sleep-ms n] [--max-iterations n] [--max-idle-iterations n] [queue/refill flags] [replan flags]",
    "  decomp-orchestrator [global flags] bootstrap [same flags as trigger-agent]",
    "  decomp-orchestrator [global flags] babysit [--run-id id] [trigger flags] [--max-restarts n] [--restart-delay-ms n]",
    "  decomp-orchestrator [global flags] recover-leases [--run-id id] [--force] [--lease-id id] [--worker-id id] [--reason text]",
    "  decomp-orchestrator [global flags] regression-check [--run-id id] [--target changes_all] [--report-title title] [--report-max-rows n]",
    "  decomp-orchestrator [global flags] pr-split-plan [--base-ref ref] [--group-mode melee-subsystem|top-dir] [--max-files-per-pr n] [--slice-check-command cmd] [--json] [--output path]",
    "  decomp-orchestrator [global flags] kg-sources",
    "  decomp-orchestrator [global flags] kg-status [--graph-db path]",
    "  decomp-orchestrator [global flags] kg-import-agent-state [--input db] [--output jsonl]",
    "  decomp-orchestrator [global flags] kg-curate [--run-id id] [--output jsonl] [--worker-limit n] [--pr-limit n] [--progress-only]",
    "  decomp-orchestrator [global flags] kg-maintain [--run-id id] [--run-pr-agent] [--run-curator-agent] [--curator-agent-record-limit n] [--curator-agent-batch-size n] [--curator-agent-jobs n] [--pr-limit n] [--pr-jobs n] [--no-pr-index] [--no-tool-runners] [--no-tool-index] [--no-rebuild]",
    "  decomp-orchestrator [global flags] kg-rebuild-graph [--graph-db path] [--sources all-or-comma-list] [--agent-state-enrichment jsonl] [--knowledge-curator-enrichment jsonl]",
    "  decomp-orchestrator [global flags] kg-search --query text [--source id] [--limit n] [--graph-db path] [--rebuild]",
    "  decomp-orchestrator [global flags] kg-smoke [--graph-db path] [--rebuild] [--strict]",
    "  decomp-orchestrator [global flags] kg-file-card --source path [--graph-db path] [--rebuild]",
    "  decomp-orchestrator [global flags] kg-rank-features [--limit n] [--candidate-limit n] [--graph-db path] [--rebuild]",
    "  decomp-orchestrator [global flags] status",
    "",
    "Global flags:",
    "  --repo-root <path>          default: current working directory",
    `  --state-dir <path>         default: <repo-root>/${DEFAULT_STATE_DIR_NAME}`,
    "  --dry-run-agents           do not call Pi SDK; write prompts as outputs",
    `  --provider <name>          default: ${DEFAULT_PI_PROVIDER}`,
    `  --model <name>             default: ${DEFAULT_PI_MODEL}`,
    `  --thinking-level <level>   default: ${DEFAULT_PI_THINKING_LEVEL}`,
    "  --agent-timeout-seconds n  bound each live Pi session; default: no timeout",
    "",
    "Queue/refill flags:",
    "  --candidate-limit n           ready queue target when --queue-target-size is omitted; default: 50",
    "  --queue-target-size n         maintain at least n queued targets; default: candidate limit",
    "  --candidate-window n          board candidates scanned for fresh refill work; default: max(candidate limit, queue target * 4)",
    "",
    "Trigger replan flags:",
    "  --queue-low-watermark n        wake director when total queued work is at/below n while workers are active; default: 25% of queue target size",
    "  --schedulable-low-watermark n  wake director when unlocked distinct-file work is at/below n while underfilled; default: max workers",
    "  --active-low-watermark n       long-tail active worker threshold; default: 75% of max workers",
    "  --long-tail-replan-ms n        wake director after underfilled long tail persists; default: 300000",
    "  --replan-interval-ms n         periodic director replan while workers are active; default: 0 disabled",
    "  --replan-cooldown-ms n         minimum delay between trigger-produced replan events; default: 300000",
    "  --no-blocked-queue-replan      do not wake director when queued work is blocked by active file locks",
    "",
    "Worker validation flags:",
    "  --repair-attempts n             worker repair turns after failed post-return gate; default: 2 live, 0 dry-run",
    "  --post-return-check-command c   optional shell command run after accepted progress/score_candidate; placeholders: {repo_root} {state_dir} {worker_log_dir} {lease_id} {source_path} {unit} {symbol} {write_set}",
    "",
    "PR split planning flags:",
    "  --base-ref ref                  branch-diff base for handoff planning; default: origin/master",
    "  --group-mode mode               grouping strategy: melee-subsystem or top-dir; default: melee-subsystem",
    "  --max-files-per-pr n            warn and refine directory groups above this size; default: 30",
    "  --branch-prefix name            branch prefix for suggested slice branches; default: pr-split",
    "  --title-prefix text             PR title prefix for suggested slices; default: Melee decomp",
    "  --slice-check-command cmd       command run inside an isolated slice worktree; default: python configure.py --require-protos && ninja changes_all",
    "  --committed-only                ignore dirty worktree status",
    "  --worktree-only                 ignore committed branch diff",
    "  --no-untracked                  omit untracked files from worktree planning",
    "  --json                          print the split plan as JSON",
    "  --output path                   also write the rendered plan to a file under repo root",
    "",
    "Knowledge maintenance flags:",
    "  --knowledge-maintenance-interval-ms n  background kg-maintain interval in trigger-agent; live default: 300000, dry-run default: 0",
    "  --no-knowledge-maintenance             disable trigger-agent background knowledge maintenance",
    "  --run-pr-agent                         let kg-maintain call the PR review agent for pending PR postmortems; trigger-agent live maintenance enables this by default",
    "  --no-run-pr-agent                      keep trigger-agent background PR indexing deterministic",
    "  --run-curator-agent                    let kg-maintain call the knowledge-curator agent for proposal review",
    "  --curator-agent-record-limit n         sampled deterministic records sent to the curator agent; default: 40",
    "  --curator-agent-batch-size n           deterministic records per curator-agent batch; default: record limit",
    "  --curator-agent-jobs n                 concurrent curator-agent batches; default: 16",
    "  --pr-limit n                           max pending PRs or PR lessons considered by maintenance; 0 means no PR indexing limit",
    "  --pr-jobs n                            concurrent PR postmortem workers; default: 16",
    "  --no-tool-runners                      skip live knowledge tool runner refresh during kg-maintain",
    "",
    "Babysit flags:",
    "  --system-command <name>    child system command: bootstrap or trigger-agent; default: bootstrap",
    "  --max-restarts n           incident restarts; 0 means unlimited",
    "  --max-system-runs n        stop after n child runs; 0 means unlimited",
    "  --restart-delay-ms n       delay before a restart; default: 1000",
    "  --restart-on-clean-exit    restart even after a clean child exit",
    "  --force-recover-leases     force all active leases on non-worker incidents",
    "  --no-recover-leases        skip guardian lease recovery",
    "  --worker-thinking-level l  pass a different thinking level to worker subprocesses",
  ].join("\n");
}
