import json,pathlib,hashlib,datetime,struct,shutil
D=pathlib.Path(__file__).parent;S=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');M=json.load(open(S/'manifest.json'));R=M['head_revision'];root=pathlib.Path(M['checkout_root']);tu='main/melee/ft/kinds/ftCommon/ftCo_CaptureYoshi';P='src/melee/ft/kinds/ftCommon/ftCo_CaptureYoshi.c';C=json.load(open(D/'context.json'));X=json.load(open(D/'baseline-facts.json'));start='2026-09-08T15:16:55Z';U=S/'units'/C['task']['id']
def c(p,a,b):return f'code://{R}/{p}#L{a}-L{b}'
foreign=[('src/melee/ft/ftcommon.c',657,668),('src/melee/ft/ftcommon.c',906,939),('src/melee/ft/ftcommon.c',515,525),('src/melee/ft/ftcommon.c',895,904),('src/melee/ft/kinds/ftCommon/ftCo_Lift.c',201,211),('src/melee/ft/kinds/ftCommon/ftCo_Throw.c',57,70),('src/melee/ft/kinds/ftCommon/ftCo_CapturePulled.c',334,367),('src/melee/ft/ftanim.c',380,386),('src/melee/ft/ftmotionstates.c',3170,3191),('src/melee/ft/kinds/ftYoshi/ftyoshispecialn.c',129,163),('src/melee/ft/kinds/ftYoshi/ftyoshispecialn.c',355,450),('src/melee/ft/kinds/ftCommon/ftCo_YoshiEgg.c',33,38),('src/melee/ft/kinds/ftCommon/ftCo_YoshiEgg.c',91,156)]
fr=[]
for p,a,b in foreign:
 t=(root/p).read_text();fr.append(dict(path=p,start_line=a,end_line=b,sha256=hashlib.sha256(t.encode()).hexdigest(),canonical_read=True,rendered_read=False,ownership='foreign evidence only'));(D/(p.replace('/','__')+f'.{a}-{b}.txt')).write_text('\n'.join(f'{i}: {l}' for i,l in enumerate(t.splitlines(),1) if a<=i<=b))
E=[c(P,13,41)]+[c(p,a,b) for p,a,b in foreign]
report=root/'build/GALE01/report.json';rh=hashlib.sha256(report.read_bytes()).hexdigest();assert rh==M['report_sha256'];unit=next(u for u in json.load(open(report))['units'] if u['name']==tu);objects=[]
for typ in ['src','obj']:
 p=root/f'build/GALE01/{typ}/melee/ft/kinds/ftCommon/ftCo_CaptureYoshi.o';b=p.read_bytes();e='>' if b[5]==2 else '<';off=struct.unpack_from(e+'I',b,32)[0];sz,n,si=struct.unpack_from(e+'HHH',b,46);sh=[struct.unpack_from(e+'10I',b,off+i*sz) for i in range(n)];st=sh[si];names=b[st[4]:st[4]+st[5]]
 for s in sh:
  if names[s[0]:].split(b'\0')[0]==b'.sdata2':objects.append(dict(path=str(p),sha256=hashlib.sha256(b).hexdigest(),section='.sdata2',size=s[5],bytes_hex=b[s[4]:s[4]+s[5]].hex()))
json.dump(dict(report_path=str(report),report_sha256=rh,pinned_report_hash_matches=True,unit=unit,objects=objects),open(D/'section-evidence.json','w'),indent=2)
print('section evidence',objects,unit.get('sections'))
rows=[];disp=[]
for s in X:
 rows.append(dict(subject=s['subject'],status='reviewed' if s['facts'] else 'reviewed_no_existing_facts',fact_count=len(s['facts']),evidence=E,notes='Entry has captured and attacker gobj inputs; callbacks each ignore gobj. No source-to-register mapping promoted.'))
 for f in s['facts']:
  status='retain';reason='Canonical entry, no-op callback bodies, Yoshi capture registration and egg-transition caller support the existing claim; preserve without citation-only rewriting.'
  if next(iter(s['subject'].values())).endswith(':ftCo_CaptureYoshi_IASA') and f['type']=='game_mapping':status='unresolved';reason='No input or escape originates in this empty IASA hook, and YoshiEgg demonstrably applies mash reduction. The global claim that no other capture-phase machinery can respond to mashing was not exhaustively attested; retain history without promoting that stronger exclusion.'
  disp.append(dict(subject=s['subject'],fact_id=f['id'],version=f['updated_at'],type=f['type'],old_value=f['value'],disposition=status,reason=reason,evidence=E))
end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');reads=[json.loads(l) for l in open(U/'reads.jsonl') if json.loads(l).get('reader')=='CaptureYoshi'];L=S/'baseline-links'/f'{C["task"]["id"]}.json';links=json.load(open(L));ld=[]
for l in links:
 ld.append(dict(link_id=l['id'],baseline_record=l,version_or_digest=l.get('digest'),disposition='retain',reason='Yoshi grounded/aerial neutral-special setup registers this victim entry, the motion table registers all four inert callbacks, and the attacker later enters the victim into YoshiEgg. Implements denotes the registered capture phase, not nonempty work in every callback. Duplicate historical records are individually retained; no deduplication mutation proposed.',evidence=[c(P,13,41),c('src/melee/ft/ftmotionstates.c',3170,3180),c('src/melee/ft/kinds/ftYoshi/ftyoshispecialn.c',129,163),c('src/melee/ft/kinds/ftYoshi/ftyoshispecialn.c',414,445),c('src/melee/ft/kinds/ftCommon/ftCo_YoshiEgg.c',91,128)]))
json.dump(dict(revision=R,input_path=str(L),input_sha256=hashlib.sha256(L.read_bytes()).hexdigest(),expected_count=len(links),reviewed_count=len(ld),counts=dict(retain=len(ld)),dispositions=ld),open(D/'link-dispositions.json','w'),indent=2)
json.dump(dict(tu=tu,proposal=dict(facts=[],links=[],entities=[],merges=[],follow_ups=[])),open(D/'proposal.json','w'),indent=2)
json.dump(dict(revision=R,start_utc=start,end_utc=end,counts=dict(retain=len(disp)-1,unresolved=1),dispositions=disp),open(D/'fact-dispositions.json','w'),indent=2)
json.dump(dict(campaign=M['campaign_id'],tu=tu,revision=R,role='TU librarian',model=M['model'],reasoning_effort=M['reasoning_effort'],start_utc=start,end_utc=end,input_files=C['files'],canonical_and_rendered_receipts=reads,foreign_evidence_reads=fr,subjects=rows,counts=dict(targets=6,source_entities=1,parameter_entities=6,existing_facts=len(disp),outgoing_links=len(ld),proposal_facts=0,owned_lines=56),exceptions=[],section_evidence='section-evidence.json',link_dispositions='link-dispositions.json'),open(D/'coverage.json','w'),indent=2)
json.dump(dict(unresolved=['Global no-mash-escape claim exceeds the local IASA and bounded egg-phase review; exact fact ID recorded in fact-dispositions.json.'],family_followups=['Capture constraint internals, Yoshi attacker state, egg escape and fighter shared layout were read as evidence only.','Header address comments and guard say 09D6E8-family addresses, differing from current symbol/report BBB8C-family addresses; declarations themselves match. No source edit proposed.']),open(D/'unresolved.json','w'),indent=2)
(D/'functionality.md').write_text(f'# Yoshi victim capture setup\n\nDraft at `{R}`.\n\n`ftCo_800BBB8C` takes the captured fighter first and capturing fighter second. Yoshi grounded and aerial neutral-special setup register it as grabbed_cb. It invokes common cleanup (including existing damage/death callbacks), heavy-item handling and prior grab/throw cleanup before overwriting the victim relationship. It stores the attacker in both x1A5C and victim_gobj, clears x221B_b5/b7, and sets facing opposite the attacker.\n\nThe capture helper attaches the victim XRotN joint to attacker TransN2 only when its constraint flag is clear. Entry then requests CaptureYoshi with flags zero, frame zero, speed one and zero blend. It installs ftCo_800DB464 as accessory1_cb, makes the victim airborne, stores 0x1FF in x1A6A, advances common animation/action setup and zeros movement/knockback vectors. The accessory callback updates cur_pos from the constrained joint plus scale/facing-adjusted offsets, forcing Z to zero. No null or fighter-kind validation occurs locally.\n\nThe common state table maps CaptureYoshi to the CapturePulledLw animation and the four canonical callbacks. Anim, IASA, Phys and Coll are all empty: they perform no local input checks, animation-completion transition, physics or collision correction. This does not mean the fighter has no ongoing behavior: attachment runs through accessory1_cb, and Yoshi attacker animation commands call ftCo_800BBED4 to enter the linked victim into YoshiEgg. Egg Anim later reduces grab_timer normally and through mash input, then exits when the timer expires. The packet does not establish a global no-mash theorem for every capture-phase subsystem.\n\nHeader types match all five definitions; historical address comments and include guard are stale relative to canonical symbol identities. Existing canonical callback names are preserved, and the entry alias remains an inference. The .sdata2 object bytes and frozen report corroborate float zero and one for entry arguments; no build ran.\n\nAll 11 historical outgoing Egg Lay links are individually retained with fresh canonical evidence. Repeated links are not treated as distinct game mechanisms and no deduplication is proposed.\n\n## Evidence\n\n'+'\n'.join('- '+e for e in E)+'\n')
(D/'naming.md').write_text('# Naming review\n\n| Canonical subject | Existing hypothesis | Decision |\n|---|---|---|\n| ftCo_800BBB8C | ftCo_CaptureYoshi_Enter | Retain: victim entry registered by Yoshi neutral special. |\n| CaptureYoshi_Anim / IASA / Phys / Coll | None | Preserve canonical names and document no-op behavior. |\n| Source entity / .sdata2 | None | No new name needed. |\n\nThe rendered helper aliases are reading aids only. No canonical source names changed.\n')
(D/'README.md').write_text(f'# CaptureYoshi review packet\n\nRevision `{R}`. UTC `{start}` to `{end}`. Model `{M["model"]}`, role TU librarian.\n\nComplete canonical and separate rendered coverage: C1-42, H1-14. Six targets, source entity and six empty parameter entities covered. {len(disp)} facts: {len(disp)-1} retained, one unresolved broader input-escape claim. All {len(ld)} outgoing link records retained with canonical evidence. No writes proposed; zero parser errors and no failed/empty renders.\n\nRead functionality.md and naming.md; audit coverage.json, fact-dispositions.json, link-dispositions.json, section-evidence.json and unresolved.json. No source, KB or build edits.\n')
print('facts',len(disp),'links',len(ld),'end',end)
