import json,hashlib
from pathlib import Path
D=Path('docs/.drafts/melee-semantic-20260908/main__melee__lb__lb_020A');M=Path('games/melee/state/knowledge_v2/semantic-sweep-20260908/manifest.json');m=json.loads(M.read_text());c=json.loads((D/'context.json').read_text());fs=json.loads((D/'facts.json').read_text());tu=c['task']['tu'];path=c['task']['source_path'];rev=m['head_revision']
rows={'fn_80020AEC':(33,123,'Builds an output matrix from a joint-relative matrix and its ancestor chain. For each subject column, uses reciprocal magnitude above1e-10 and otherwise the magnitude itself, then multiplies by the corresponding current joint-matrix column length. For ancestors, reciprocal normalization occurs above1e-5; tiny columns instead multiply by their magnitude. Concatenates ancestor transforms into out. This is not guaranteed orthonormal or scale-free.'),'lbBgFlash_80020E38':(127,191,'Returns for zero direction, otherwise sets up the joint matrix and computes its Z-column magnitude. A nonzero magnitude yields atan2(-dir.x * mtx[2][2]/magnitude,dir.y), then sequential upper max_angle and lower -min_angle limits. Adds Euler Z rotation or composes a quaternion with a Z rotation, marks dirty in the quaternion branch and sets up the matrix again. dir.z only participates in the zero-vector guard; the fifth argument is unused.'),'fn_8002113C':(193,224,'Sets up the joint matrix, obtains fn_80020AEC output, transposes it and transforms axis through PSMTXMultVec. Builds an axis rotation using negative angle, composes with the current rotation matrix and converts back through Euler-path HSD_QuatLib_8037EB28 or quaternion MatToQuat according to JOBJ_USE_QUATERNION. Both branches write through HSD_JObjSetRotation.'),'lbBgFlash_80021410':(244,429,'Derives and normalizes an axis from jobj1 matrix Z column, projects pos4,pos0,pos1 onto the plane through pos1, measures current angles and distances, overwrites len0/len1 with measured segment lengths, applies nonlinear reach limiting above10/11 of their sum, clamps two law-of-cosines results, modifies the second angle near straight extension and applies corrections to jobj0/jobj1 through fn_8002113C.'),'file':(22,429,'Joint-transform and planar two-segment IK utilities. One helper reconstructs a hierarchy-dependent matrix, one adjusts bounded Z rotation, one composes an external-axis rotation and one updates IKState positions/lengths and both referenced joints. No source-owned global state is declared; section membership of compiler-emitted material remains unverified.'),'.data':(1,20,'No explicit initialized object is declared in this source. The frozen target exists but exact compiler-emitted .data contents need object evidence.'),'.sdata':(22,43,'No explicit small-data object is declared. Exact .sdata contents require compiler/object evidence.'),'.sdata2':(226,242,'Numeric literals support matrix thresholds, square-root refinement and IK angles/reach; exact .sdata2 membership and layout are not established from canonical C.')}
for n,(a,b,v) in list(rows.items()):rows[n]=(a,b,v.replace('above1e','above 1e').replace('above10/11','above 10/11').replace('pos4,pos0,pos1','pos4, pos0, pos1'))
def ev(n):
 a,b,_=rows[n];rr=[(path,a,b)];rr+= {'fn_80020AEC':[(path,22,28)],'fn_8002113C':[(path,33,123)],'lbBgFlash_80021410':[(path,226,242),(path,193,224)],'file':[('src/melee/lb/lb_020A.h',16,19)]}.get(n,[])
 return [{'kind':'code','locator':f'code://{rev}/{p}#L{a}-L{b}','why':'Canonical arithmetic, helper use or writes establish this claim and its limits.'} for p,a,b in rr]
proposal={'tu':tu,'proposal':{'facts':[],'links':[],'entities':[],'merges':[],'follow_ups':[]}};dd=[];ss=[]
for s,rr in fs.items():
 subj={'entity_locator':s} if s==path or '#' in s else {'target_stable_key':s};n='file' if s==path else s.split(':')[-1];ss.append({'subject':subj,'fact_count':len(rr),'disposition':'reviewed_empty' if not rr else 'reviewed','summary':rows[n][2] if n in rows else 'Parameter entity has no inherited facts.'})
 for f in rr:
  t=f['type'];d='retain';v=None;reason='Canonical local behavior supports the inherited claim.'
  if t=='purpose':d='supersede';v=rows[n][2];reason='State exact numeric operations and mutable state without stronger geometric guarantees.'
  elif n=='fn_80020AEC' and t in ['data_flow','state_behavior']:d='supersede';v=rows[n][2];reason='Tiny columns are multiplied by their magnitude rather than normalized; preserved subject scale prevents universal orthonormality.'
  elif n=='fn_80020AEC' and t=='game_mapping':d='unresolved';reason='Scale-isolated local-frame claim requires matrix-family conventions and preconditions beyond local source.'
  elif n=='lbBgFlash_80021410' and t=='data_flow':d='supersede';v=rows[n][2]+' The earlier len0 multiplication at332 is overwritten at362 before final angle solving.';reason='Separate directly written IK fields from unreviewed caller leg/ground labels and capture overwritten length.'
  elif n=='lbBgFlash_80021410' and t=='game_mapping':d='unresolved';reason='File comment mentions planted fighter legs, but actual terrain-conforming caller setup was not independently reviewed.'
  elif n=='lbBgFlash_80021410' and t=='state_behavior':d='supersede';v='Writes projected positions and measured lengths in place. With S=10*(len0+len1)/11 and d=distance(pos0,pos4), d>S replaces d by11*S/10 - S^11/(10*d^10). Two cosine quotients are clamped by comparisons before acos. If pi-acos2 is below0.1745329201221466, the formula blends from2.9670597334676465 toward acos2 using abs(pi-acos2)/0.1745329201221466. No zero-denominator or NaN guard is present.';reason='Preserve exact reach and near-extension formula without claiming a universal angle floor.'
  elif n=='lbBgFlash_80020E38' and t=='state_behavior':d='supersede';v='Zero direction returns before setup. A nonzero direction calls HSD_JObjSetupMatrix even if the resulting Z-column magnitude is zero; only the rotation adjustment is skipped then. Otherwise sequential upper/lower limits feed Euler or quaternion updates and another matrix setup. Limits are not validated for ordering.';reason='Matrix setup can occur before zero-column rejection; no-transform-change wording was too broad.'
  elif t=='inferred_name':v=f['value'];reason='Retain behavior-supported reading aid; canonical names stay authoritative. Orientation name does not imply an orthonormal matrix.'
  dd.append({'subject':subj,'fact_id':f['id'],'fact_version':{'updated_at':f['updated_at']},'type':t,'prior_value':f['value'],'disposition':d,'reason':reason,'evidence':ev(n)})
  if v is not None:
   for a,b in [('at332','at 332'),('at362','at 362'),('by11','by 11'),('below0.','below 0.'),('from2.','from 2.')]:v=v.replace(a,b)
   proposal['proposal']['facts'].append({'subject':subj,'type':t,'op':'write','value':v,'rationale':reason,'confidence':f['confidence'] if t=='inferred_name' else 0.96,'evidence':ev(n)})
# File entity is owned and empty; add one source-grounded synthesis fact.
proposal['proposal']['facts'].append({'subject':{'entity_locator':path},'type':'purpose','op':'write','value':rows['file'][2],'rationale':'Source-grounded synthesis of all four public definitions and declarations.','confidence':0.97,'evidence':ev('file')})
reads=[]
for ext,a,b in [('c',1,240),('c',241,430),('h',1,22)]:
 p=M.parent/'units'/c['task']['id']/'pages'/f'src__melee__lb__lb_020A.{ext}.{a}-{b}.json';r=json.loads(p.read_text())['rendered'];reads.append({'path':r['path'],'canonical_range':[a,b],'rendered_range':[a,b],'artifact':str(p),'artifact_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'source_sha256':r['source_sha256'],'status':r['status'],'next_line':r['next_line'],'parse_errors':r['parse_errors'],'substitutions':r['substitutions']})
counts={'files_expected':2,'files_reviewed':2,'canonical_lines':452,'rendered_lines':452,'targets_expected':7,'targets_reviewed':7,'functions':4,'data_sections':3,'subjects_expected':19,'subjects_reviewed':19,'empty_parameter_entities':11,'other_empty_subjects':4,'inherited_facts':len(dd),'proposal_operations':len(proposal['proposal']['facts']),'dispositions':{d:sum(x['disposition']==d for x in dd) for d in ['retain','supersede','reject','unresolved']}}
followups=[{'topic':'Joint/matrix and vector conventions','status':'pending_family','reason':'Verify null-parent matrix access, transpose/axis transform conventions, Euler conversion and zero-vector normalization in foreign baselib/lbvector owners.'},{'topic':'IKState and terrain callers','status':'pending_family','reason':'File documentation attests a fighter-leg intent but exact position roles and terrain setup need caller/type ownership.'},{'topic':'Compiler data sections','status':'reviewed_empty_unresolved_contents','reason':'All three section targets have zero inherited facts and no explicit global declarations; compiled contents remain unclaimed.'}]
j={'campaign':m['campaign_id'],'tu':tu,'head_revision':rev,'utc_start':(D/'start.txt').read_text().strip(),'manifest_sha256':hashlib.sha256(M.read_bytes()).hexdigest(),'files':c['files'],'reads':reads,'read_exceptions':[],'targets':[{'canonical_name':n,'range':[a,b],'summary':v,'evidence':ev(n)} for n,(a,b,v) in rows.items() if n!='file'],'subjects':ss,'fact_dispositions':dd,'followups':followups,'counts':counts,'uncertainty':['Initial len0 scaling is overwritten by measured length.','Tiny-column thresholds do not guarantee normalized or orthonormal output.','No explicit zero segment-length, zero denominator or NaN handling in IK solver.','min/max-angle ordering is unchecked; dir.z affects only zero-vector guard.'],'status':'local_review_complete_pending_independent_review'}
for n,v in [('findings.json',j),('proposal.json',proposal),('followups.json',followups)]:(D/n).write_text(json.dumps(v,indent=2)+'\n')
print(counts)
