import json,hashlib
from pathlib import Path
D=Path('docs/.drafts/melee-semantic-20260908/main__melee__lb__lbarq');M=Path('games/melee/state/knowledge_v2/semantic-sweep-20260908/manifest.json');m=json.loads(M.read_text());c=json.loads((D/'context.json').read_text());fs=json.loads((D/'facts.json').read_text());tu=c['task']['tu'];path=c['task']['source_path'];rev=m['head_revision']
rows={'.bss':(9,33,'Named singleton lbArq_804316C0 contains storage for ten lbArqNode records and three lists indexed FREE, PENDING and DONE. The initializer makes only nodes[0..8] reachable. Association with .bss follows the frozen inventory; compiled placement was not independently verified.'),'.sdata':(120,126,'Canonical submission contains HSD_ASSERT(0x67,rp) for free-pool exhaustion. Exact compiler-emitted metadata and its .sdata placement require object evidence.'),'lbArq_80014ABC':(41,44,'Returns the supplied node state unchanged. The blocking submission loop repeatedly calls this accessor until DONE; no scheduler-yield or memory-ordering guarantee follows from this C function alone.'),'lbArq_80014AC4':(49,105,'Reads handle->node, removes the node from its state-selected list under interrupt exclusion and appends it as DONE. Restores the saved interrupt state, calls the optional client callback, then under another exclusion removes the node from its current list and appends it as FREE. Without a callback it remains DONE for the blocking submitter.'),'lbArq_80014BD0':(107,161,'Invalidates the destination cache range, requires a free node, stores callback metadata and moves the node to PENDING under interrupt exclusion. Calls ARQPostRequest with embedded request, node owner, literal type1 and priority0, source/destination/length and internal completion callback. With no client callback, restores saved interrupts, polls until DONE, then recycles to FREE under exclusion before returning; otherwise completion handles recycling.'),'lbArq_80014D2C':(163,184,'Clears three list heads and roots FREE at nodes[0]. The loop assigns nodes[0] through nodes[8], then overwrites nodes[8].next with NULL. Thus nine nodes are reachable despite ten-record storage; node9 is not initialized or linked by this routine. No active-transfer guard or interrupt masking appears.'),'file':(9,184,'Implements a fixed request pool with FREE, PENDING and DONE queues around Dolphin ARQ submission. Supports optional client callbacks or busy-wait completion; both paths recycle requests after DONE. Stores ten nodes but initialization links only nine. Queue mutations mask interrupts and restore saved state; callback code runs after restoration.')}
def ev(n):
 a,b,_=rows[n];rr=[(path,a,b)];rr+= {'.bss':[(path,163,181)],'lbArq_80014ABC':[(path,143,159)],'lbArq_80014BD0':[('src/melee/lb/lbarq.h',6,9)]}.get(n,[])
 return [{'kind':'code','locator':f'code://{rev}/{p}#L{a}-L{b}','why':'Canonical structure, queue transition, registration or polling loop supports this local claim.'} for p,a,b in rr]
proposal={'tu':tu,'proposal':{'facts':[],'links':[],'entities':[],'merges':[],'follow_ups':[]}};dd=[];ss=[]
for s,rr in fs.items():
 subj={'entity_locator':s} if s==path or '#' in s else {'target_stable_key':s};n='file' if s==path else s.split(':')[-1];ss.append({'subject':subj,'fact_count':len(rr),'disposition':'reviewed_empty' if not rr else 'reviewed','summary':rows[n][2] if n in rows else 'Empty parameter entity.'})
 for f in rr:
  t=f['type'];d='retain';v=None;reason='Canonical local operations independently support this behavior.'
  if n=='.sdata':d='unresolved';reason='Exact generated assertion metadata and .sdata membership are not established by the owned C text.'
  elif t=='game_mapping':d='unresolved';reason='ARAM-to-main-memory direction and consumer role require Dolphin ARQ type and caller-family evidence.'
  elif t=='purpose':d='supersede';v=rows[n][2];reason='Describe exact local behavior and initialization capacity without unreviewed consumer semantics.'
  elif t=='inferred_name':v=f['value'];reason='Retain source-supported state-accessor reading aid; canonical name remains authoritative.'
  elif n=='.bss' and t=='inferred_type':d='supersede';v='Canonical lbArqGlobal has nodes[10] and list[3]. lbArqNode declares next, state, embedded ARQRequest, callback and callback_arg, with source offset comments through0x2C. Exact compiled sizes and .bss placement require external object/type evidence.';reason='Distinguish source structure and offset comments from independently verified object layout.'
  elif n in ['file','lbArq_80014BD0'] and t=='data_flow':d='supersede';v=rows[n][2];reason='Preserve literal ARQ request arguments without assuming external enum meanings.'
  elif n=='lbArq_80014BD0' and t=='inferred_type':d='supersede';v='Exact signature void lbArq_80014BD0(unsigned int source,void* dest,size_t length,lbArqCallback callback,void* callback_arg). The header defines lbArqCallback as void(*)(void*). Source, destination and length are forwarded to ARQPostRequest; null callback selects blocking polling.';reason='Use canonical signature without unverified transfer-direction typing.'
  elif n=='lbArq_80014AC4' and t=='state_behavior':d='supersede';v=rows[n][2];reason='OSRestoreInterrupts restores prior state; it does not necessarily enable interrupts before client code.'
  if n=='.bss':reason+=' Claims attach to the named singleton; exact section placement remains unverified.'
  dd.append({'subject':subj,'fact_id':f['id'],'fact_version':{'updated_at':f['updated_at']},'type':t,'prior_value':f['value'],'disposition':d,'reason':reason,'evidence':ev(n)})
  if v is not None:proposal['proposal']['facts'].append({'subject':subj,'type':t,'op':'write','value':v.replace('through0x','through 0x').replace('type1','type 1').replace('priority0','priority 0').replace('node9','node 9'),'rationale':reason,'confidence':f['confidence'] if t=='inferred_name' else 0.97,'evidence':ev(n)})
reads=[]
for ext,b in [('c',185),('h',12)]:
 p=M.parent/'units'/c['task']['id']/'pages'/f'src__melee__lb__lbarq.{ext}.1-{b}.json';r=json.loads(p.read_text())['rendered'];reads.append({'path':r['path'],'canonical_range':[1,b],'rendered_range':[1,b],'artifact':str(p),'artifact_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'source_sha256':r['source_sha256'],'status':r['status'],'next_line':r['next_line'],'parse_errors':r['parse_errors'],'substitutions':r['substitutions']})
followups=[{'topic':'Dolphin ARQ ABI and type semantics','status':'pending_family','reason':'Confirm type1 direction, priority0 semantics and completion handle layout mapping through the embedded ARQRequest; canonical TU supplies casts and handle->node access but not foreign ABI proof.'},{'topic':'Compiled diagnostic section','status':'unresolved','reason':'The four .sdata facts require compiled metadata and placement evidence.'},{'topic':'Blocking interrupt context','status':'pending_family','reason':'The blocking path restores the caller saved interrupt state before polling. Caller context and lower-layer completion delivery establish whether progress is possible.'}]
counts={'files_expected':2,'files_reviewed':2,'canonical_lines':197,'rendered_lines':197,'targets_expected':6,'targets_reviewed':6,'functions':4,'data_sections':2,'subjects_expected':14,'subjects_reviewed':14,'empty_parameter_entities':7,'inherited_facts':len(dd),'proposal_operations':len(proposal['proposal']['facts']),'dispositions':{d:sum(x['disposition']==d for x in dd) for d in ['retain','supersede','reject','unresolved']}}
j={'campaign':m['campaign_id'],'tu':tu,'head_revision':rev,'utc_start':(D/'start.txt').read_text().strip(),'manifest_sha256':hashlib.sha256(M.read_bytes()).hexdigest(),'files':c['files'],'reads':reads,'read_exceptions':[],'targets':[{'canonical_name':n,'range':[a,b],'summary':v,'evidence':ev(n)} for n,(a,b,v) in rows.items() if n!='file'],'subjects':ss,'fact_dispositions':dd,'followups':followups,'counts':counts,'uncertainty':['Initializer exposes nine nodes, not all ten declared storage entries.','Client callback runs after restoring prior interrupt state, not necessarily with interrupts enabled.','No reinitialization-in-flight guard or free-pool waiting exists.','No volatile state or portable compiler ordering assertion follows from the noninline workaround comment.'],'status':'local_review_complete_pending_independent_review'}
for n,v in [('findings.json',j),('proposal.json',proposal),('followups.json',followups)]:(D/n).write_text(json.dumps(v,indent=2)+'\n')
print(counts)
