import json,pathlib,hashlib,datetime
out=pathlib.Path(__file__).parent;camp=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');base=camp/'baseline-links/main__sysdolphin__baselib__axdriver.json';ls=json.load(open(base));cov=json.load(open(out/'coverage.json'));subs=cov['subjects'];links=[]
reject={3:'The wrapper tests only sentinel -1 and forwards a singleton path-selected stream handle; it does not validate liveness. The stored validation claim is unsupported.',21:'Per-record aux updates require independent low-bit API permission, not that the bus effect is enabled. The exact stored reason conflates those states.',60:'The actual delay caller passes type2 with an AXFX_DELAY object, then installs type4. It does not perform a valid effect-specific delay capacity check; the heap-size helper also does not validate parameter ranges.',68:'The routine ignores rejected per-record updates. It always saves the default, but does not necessarily distribute the byte to every current sound when the API permission gate denies updates.'}
for i,l in enumerate(ls):
 ident=l['from_target_id'] or l['from_entity_id'];n=ident.split(':')[-1];idx=44 if ident.startswith('translation_unit:') else next(j for j,s in enumerate(subs[:44]) if next(iter(s['subject'].values())).split(':')[-1]==n)
 d='reject' if i in reject else 'retain';why=reject.get(i,'Pinned local behavior and independently read support establish this relationship. Scope is the local mechanism, with input and progress limits preserved.')
 if i==18:why='Retain individual logical pause-control relationship. The no-voice branch records a timing bit; the x30==-1 first-schedule exception means the pending marker does not guarantee zero initial command execution.'
 if i==48:why='Accessor is sampled for the PVoice peak tracker. It counts associated Synth nodes, and the current-value text in both rows uses the later virtual-count x; retained relationship does not certify a literal physical-voice count.'
 if i==71:why='Packed requested effect types select teardown/replacement; after initialization failure the nibble can be nonzero with no callback. Retain routing relationship without treating it as a successful-effect status.'
 links.append({'id':l['id'],'baseline_record':l,'version':{'updated_at':None,'record_sha256':hashlib.sha256(json.dumps(l,sort_keys=True).encode()).hexdigest()},'disposition':d,'reason':why,'evidence':subs[idx]['evidence']})
ledger={'tu':cov['tu'],'revision':cov['revision'],'baseline_path':str(base),'baseline_sha256':hashlib.sha256(base.read_bytes()).hexdigest(),'reviewed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'counts':{'total':len(ls),'retain':len(ls)-len(reject),'reject':len(reject),'unresolved':0},'object_evidence':str(out/'object-evidence.json'),'links':links};(out/'link-dispositions.json').write_text(json.dumps(ledger,indent=2)+'\n');s=json.load(open(out/'summary.json'));s['link_counts']=ledger['counts'];(out/'summary.json').write_text(json.dumps(s,indent=2)+'\n');print(ledger['counts'])
