import json,pathlib,re,datetime,hashlib,collections
D=pathlib.Path(__file__).parent; S=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908'); M=json.load(open(S/'manifest.json'));R=M['head_revision'];P='src/melee/ft/ftcoll.c';tu='main/melee/ft/ftcoll';root=pathlib.Path(M['checkout_root']);src=(root/P).read_text().splitlines();X=json.load(open(D/'baseline-facts.json'));start='2026-09-08T14:44:58Z'
def c(p,a,b):return f'code://{R}/{p}#L{a}-L{b}'
foreign=[('src/melee/lb/lbcollision.c',1786,1835),('src/melee/ft/ftdynamics.c',382,419),('src/melee/ft/types.h',1320,1340),('src/melee/ft/fighter.c',1448,1508),('src/melee/ft/fighter.c',2816,2861)]
fr=[]
for p,a,b in foreign:
 t=(root/p).read_text();fr.append(dict(path=p,start_line=a,end_line=b,sha256=hashlib.sha256(t.encode()).hexdigest(),canonical_read=True,rendered_read=False,ownership='foreign evidence only'));(D/(p.replace('/','__')+f'.{a}-{b}.txt')).write_text('\n'.join(f'{i}: {l}' for i,l in enumerate(t.splitlines(),1) if a<=i<=b))
O={}
def change(s,t,v,reason):O[(s,t)]=(v,reason)
change('8007AF60','data_flow','Reads the Fighter from gobj and rechecks fp->x166C in each loop condition. For each x1670 entry, lb_8000B1CC transforms local v1 through its joint into world-space x18. The dynamics caller updates this array before passing it and x166C to lb_8001044C for its dynamic-bone sets.','The count is not snapshotted in the canonical loop.')
change('8007B320','data_flow','Reads default hurt descriptors from ft_data->x30 and dynamics descriptors from ft_data->x2C. It copies hurt count and per-capsule bone index, height, grabbability, enabled state, joint, endpoint offsets and scale. After that pass it checks and copies the dynamics count, then copies each dynamics bone index, resolves its joint, and copies Vec3 v1 and scalar float v2.','The dynamics record contains one vector and one scalar, not two vectors.')
change('8007B320','state_behavior','First asserts if the hurt descriptor count exceeds 15, then populates and enables the hurt array. Only after that pass does it assert if the dynamics count exceeds 11 and populate the dynamics array. Neither loop clears hurt-capsule position-cache flags; the routine owns no timer or action-state transition.','The dynamics limit check occurs after hurt-array population, not before either array is populated.')
change('8007B7A4','inferred_type','void(Fighter_GObj* gobj, int duration). The signed duration request replaces x1994 only when greater than its existing value. The routine does not validate nonnegativity; ordinary callers use it as a protection countdown.','Canonical input is signed and no nonnegative precondition is enforced locally.')
change('8007B868','inferred_type','Read-only query s32(Fighter_GObj* gobj), returning max(x221D_b6 ? 1 : 0, x1988, x198C). Normal status producers use levels 0, 1 and 2, but this query does not clamp arbitrary stored values to that domain.','The whole-body setter stores arbitrary states, so the return domain is not guaranteed to be exactly {0,1,2}.')
change('8007B868','state_behavior','Performs no state transition and returns the maximum of the Boolean source mapped to 0 or 1 and the two explicit status fields. Normal 0/1/2 inputs follow their usual precedence; values greater than 2 remain visible and negative explicit values cannot reduce the result below the Boolean source.','Qualifies the claimed enum behavior for unconstrained stored state.')
change('8007B868','inferred_name','ftColl_GetFighterHitStatus','The previous alias ftColl_GetHitStatus collides with a distinct canonical local inline function at lines 3456-3466; this qualified hypothesis avoids that collision.')
change('8007B8A8','purpose','Detaches a HitCapsule from its model joint and copies the supplied vector into b_offset. It does not immediately write the current or previous world-space endpoints; those are maintained by the separate position-update lifecycle.','Distinguishes writing a detached offset from immediately placing the cached world-space capsule.')
change('8007BC90','purpose','Finds the eligible item with the smallest absolute horizontal distance among items overlapping an active fighter catch capsule. It scans item availability, ground/air targeting, history and hurtbox overlap, records each overlapping item, and stores the best target; equal distances keep the first candidate.','Nearest must explicitly mean absolute X distance, not Euclidean distance.')
EF={'8007AF60':[c('src/melee/ft/ftdynamics.c',395,413)],'8007B320':[c('src/melee/ft/types.h',1324,1332)],'8007AFC8':[c('src/melee/lb/lbcollision.c',1786,1789)],'8007AFF8':[c('src/melee/lb/lbcollision.c',1786,1789)],'8007B064':[c('src/melee/lb/lbcollision.c',1791,1807)],'8007B868':[c(P,3292,3307),c(P,3456,3466)],'8007B8A8':[c(P,3028,3066)],'8007BE3C':[c('src/melee/ft/fighter.c',2844,2849)]}
for n in ['8007B6A0','8007B6EC','8007B760','8007B7A4','8007B7FC']:EF[n]=[c('src/melee/ft/fighter.c',1464,1498)]
# Claims with external specifics remain in baseline history but are not promoted as re-attested.
external={
'8007AB48':['data_flow','game_mapping','purpose','state_behavior'], '8007AB80':['data_flow','game_mapping','inferred_name','inferred_type','purpose','state_behavior'],
'8007ABD0':['data_flow','game_mapping','purpose','state_behavior'], '8007AC68':['data_flow','game_mapping','state_behavior'], '8007AC9C':['data_flow','game_mapping','purpose','state_behavior'],
'8007AEE0':['game_mapping','purpose','state_behavior'],'8007AEF8':['game_mapping','state_behavior'],'8007AF10':['game_mapping','state_behavior'],'8007AF28':['data_flow','state_behavior'],
'8007AFC8':['game_mapping'],'8007AFF8':['game_mapping'],'8007B064':['game_mapping'],'8007B0C0':['game_mapping'],'8007B128':['game_mapping'],'8007B1B8':['game_mapping'],
'8007B320':['game_mapping'],'8007B4E0':['game_mapping','state_behavior'],'8007B62C':['game_mapping','inferred_type','purpose'],
'8007B6A0':['game_mapping'],'8007B6EC':['game_mapping'],'8007B760':['game_mapping'],'8007B7A4':['game_mapping'],'8007B7FC':['data_flow','game_mapping','inferred_type','purpose','state_behavior'],
'8007B868':['data_flow','game_mapping'],'8007B8A8':['data_flow','game_mapping','state_behavior'],'8007B8CC':['data_flow','game_mapping','state_behavior'],'8007B8E8':['game_mapping','purpose'],
'8007BA0C':['game_mapping','state_behavior'],'8007BAC0':['data_flow','game_mapping','state_behavior'],'8007BBCC':['data_flow','game_mapping','purpose','state_behavior'],'8007BC90':['data_flow','game_mapping'],
'8007BE3C':['data_flow','game_mapping','purpose','state_behavior'],'CreateAbsorbHit':['game_mapping'],'CreateReflectHit':['game_mapping'],'GetWindOffsetVec':['data_flow','game_mapping']}
rows=[];disp=[];proposal=[]
for s in X:
 key=next(iter(s['subject'].values()));name=key.split(':')[-1].split('#')[0];short=name.split('_')[-1];delegated=False
 if 'entity_locator' in s['subject']:
  rows.append(dict(subject=s['subject'],status='delegated_to_capsule_state' if delegated else 'reviewed_no_existing_facts',fact_count=0,reason='Source parameters reviewed with parent body; no register-to-source ABI correspondence promoted.'));continue
 a=next(i+1 for i,l in enumerate(src) if re.match(r'^(?:void|s32|bool|float) '+name+r'\(',l));b=a
 while src[b-1]!='}':b+=1
 ev=[c(P,a,b)]+EF.get(short,[])
 behavior=O.get((short,'purpose'),(next((f['value'] for f in s['facts'] if f['type']=='purpose'),'See source.'),''))[0]
 rows.append(dict(subject=s['subject'],status='delegated_to_capsule_state' if delegated else 'reviewed',range=[a,b],behavior=behavior,evidence=ev,fact_count=len(s['facts'])))
 for f in s['facts']:
  pair=(short,f['type']);status='retain';reason='Canonical implementation supports the local operation; inferred labels remain hypotheses.';replacement=None
  if f['type'] in external.get(short,[]):status='unresolved';reason='Local operation verified, but the existing fact also asserts external caller, consumer, gameplay or callee semantics not fully re-attested in this bounded review. Preserve history; no rewrite solely to replace citations.'
  if delegated:status='unresolved';reason='Wrapper ownership belongs to capsule_state; parent must consume that librarian disposition, not this overlap inventory.'
  elif pair in O:status='supersede';replacement,reason=O[pair]
  disp.append(dict(subject=s['subject'],fact_id=f['id'],version=f['updated_at'],type=f['type'],old_value=f['value'],disposition=status,reason=reason,replacement=replacement,evidence=ev))
  if replacement:proposal.append(dict(subject=s['subject'],type=f['type'],op='write',value=replacement,rationale=reason,confidence=0.94,evidence=[dict(kind='code',locator=e,why=reason) for e in ev]))
end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');counts=dict(collections.Counter(d['disposition'] for d in disp));reads=[json.loads(l) for l in open(S/'units/main__melee__ft__ftcoll/reads.jsonl') if json.loads(l).get('reader')=='capsule_lifecycle'];rh=hashlib.sha256(json.dumps(reads,sort_keys=True).encode()).hexdigest()
json.dump({'tu':tu,'proposal':dict(facts=proposal,links=[],entities=[],merges=[],follow_ups=[])},open(D/'proposal.json','w'),indent=2)
json.dump(dict(campaign=M['campaign_id'],revision=R,start_utc=start,end_utc=end,counts=counts,dispositions=disp),open(D/'fact-dispositions.json','w'),indent=2)
json.dump(dict(campaign=M['campaign_id'],revision=R,tu=tu,cluster='capsule_lifecycle',start_utc=start,end_utc=end,input_files=json.load(open(D/'context.json'))['files'],owned_range=[2973,3762],reviewed_source_range=[2973,3762],canonical_and_rendered_receipts=reads,receipt_sha256=rh,foreign_evidence_reads=fr,subjects=rows,counts=dict(owned_targets=39,owned_parameter_entities=63,owned_facts=230,overlap_targets=0,overlap_facts=0,inventory_facts=len(disp),proposal_facts=len(proposal)),exceptions=[],family_followups=['External-specific claims marked unresolved per fact; shared layouts are evidence only.','Historical ftcoll.dox declarations differ from current C/H; source entity belongs to TU lead.']),open(D/'coverage.json','w'),indent=2)
md=f'# Capsule lifecycle review\n\nDraft at `{R}`. UTC {start} to {end}. Complete canonical and separate rendered reads: C2973-3762, H1-108, DOX1-112. No read/render failures or parser errors. AB48/AB80 belong to this assignment, confirmed by the TU lead. 39 owned targets, 63 empty parameter entities, 230 owned existing facts.\n\n## Target findings\n\n'
for row in rows:
 if 'range' in row:md+=f"- `{next(iter(row['subject'].values())).split(':')[-1]}` ({row['range'][0]}-{row['range'][1]}): {row['behavior']} Status: {row['status']}. Evidence: {row['evidence'][0]}.\n\n"
md+='## Invariants and contradictions\n\nB128 changes only the first matching bone and neither invalidates its position cache nor clears the aggregate flag when enabling it. Shield, reflect and absorb constructors replace geometry without clearing skip_update_pos. HurtboxInit also leaves that cache flag untouched; B4E0 explicitly clears it and rebuilds only the current runtime hurt count. BC90 resets target_item_gobj and best distance, not x1A64 or x221B_b6, and records all overlapping items while choosing by absolute X distance. BE3C computes the integer pending amount before absorption; exact exhaustion stays absorbed, strictly negative pool becomes excess damage. The fighter caller establishes delay-expired/no-applied-knockback timing.\n\nThe renderer alias ftColl_GetHitStatus for B868 conflicts with the canonical local inline at C3456. A distinct qualified alias is proposed for independent review. Current canonical named functions CreateAbsorbHit, CreateReflectHit, GetWindOffsetVec and HurtboxInit are preserved. DOX is historical evidence: B868 bool differs from s32, HurtboxInit capsule type differs, AC68 signed angle differs from u32, B128 omits its Fighter argument, AF60 is unresolved there, and B8A8 position wording is broader than its immediate writes. These are source-family followups, not canonical edits.\n\n## Dispositions\n\n'+str(counts)+f'. {len(proposal)} substantive corrections proposed. Unresolved dispositions preserve baseline history and explicitly avoid asserting foreign specifics as re-attested. All 63 owned parameter entities had zero facts. No ABI speculation promoted.\n'
(D/'findings.md').write_text(md);print(counts,'writes',len(proposal),'end',end)
