import json,pathlib,hashlib,datetime
out=pathlib.Path(__file__).parent;m=json.load(open('games/melee/state/knowledge_v2/semantic-sweep-20260908/manifest.json'));tu='main/melee/lb/lbvector';rev=m['head_revision'];src='src/melee/lb/lbvector.c';root=pathlib.Path(m['checkout_root']);rows=json.load(open(out/'facts.json'))
def ev(p,a,b,why):return {'kind':'code','locator':f'code://{rev}/{p}#L{a}-L{b}','why':why}
data={'.data':(382,385,'Source filename and coordinate-range assertion diagnostics.'),'.sdata':(382,382,'The pos3d pointer-assertion string, identified in existing object bytes.'),'.sdata2':(123,151,'Pooled scalar coefficients, tolerances and projection literals.'),'file':(1,524,'Caller-owned vector and matrix arithmetic, planar and spatial geometry, orientation conversion and projection.'),'Normalize':(18,31,'Normalize XYZ in place unless computed length equals zero; return the computed original length.'),'NormalizeXY':(33,45,'Normalize XY and preserve Z; exact computed-zero check.'),'Add':(47,53,'Accumulate XYZ and return the first pointer.'),'Add_xy':(55,60,'Accumulate XY without reading or changing Z.'),'Sub':(62,68,'Subtract XYZ in place and return the first pointer.'),'Diff':(70,76,'Write a minus b componentwise; exact alias with either input is supported.'),'CrossprodNormalized':(78,83,'Compute a cross b and normalize the output; a zero cross product remains zero.'),'Angle':(85,102,'Unsigned 3D angle; length product must exceed 1e-10, otherwise zero; clamp cosine before acos.'),'AngleXY':(104,121,'Unsigned XY angle; only exact zero product is rejected, unlike Angle threshold.'),'RotateAboutUnitAxis':(153,216,'In-place approximate rotation about an assumed unit axis, with a near-X alignment shortcut.'),'Rotate':(218,246,'Principal-axis approximate rotation for selectors exactly 1,2,4. Other selectors leave local outputs uninitialized.'),'Mirror':(255,264,'Planar reflection update using a supplied unit XY normal; Z preserved.'),'CosAngle':(266,272,'XY cosine ratio with no zero check or clamp.'),'Lerp':(274,285,'Unclamped affine interpolation when result does not alias the first endpoint; destructive intermediate writes matter.'),'8000DE38':(287,311,'Evaluate the quadratic through three packed Vec3 samples at parameters0,0.5,1; clamp ordered inputs to0..1.'),'EulerAnglesFromONB':(313,334,'Extract XYZ Euler angles from basis arranged b,c,a; exact b.z endpoints choose singular branches.'),'EulerAnglesFromPartialONB':(336,348,'Normalize c cross a as b, then extract Euler angles; a and c are not normalized or orthogonalized.'),'ApplyEulerRotation':(350,357,'Rotate v successively about X,Y,Z; angles are read between mutations.'),'sqrtf_accurate':(359,363,'Delegate scalar sqrt to the configured math helper.'),'sqrtf__Ff':(18,31,'Emitted ordinary sqrtf helper used by inline vector length; canonical implementation resides in math_ppc.h.'),'WorldToScreen':(365,447,'Project through perspective or orthographic HSD camera; unsupported modes return NULL; near-depth adjustment precedes GXProject.'),'CreateEulerMatrix':(449,485,'Construct approximate Rz Ry Rx linear matrix and clear translation; Quaternion.w is unused.'),'8000E838':(487,524,'Project onto an infinite line, return residual length and write closest point; tiny direction falls back to a.')}
def namekey(key):return 'file' if key==src else key.split(':')[-1].split('#')[0].removeprefix('lbVector_')
extra={k:[] for k in data}
for k in ['Normalize','Angle','8000E838','sqrtf__Ff']:extra[k]+=[ev('src/melee/lb/lbvector.h',10,18,'Inline length helpers.'),ev('src/MSL/math_ppc.h',11,26,'Ordinary target sqrt implementation.')]
extra['sqrtf_accurate']=[ev('src/MSL/math_ppc.h',32,48,'Extra refinement and nonpositive pass-through.'),ev('src/placeholder.h',12,17,'Non-Gekko fallback remaps helper to ordinary sqrtf.')]
extra['CrossprodNormalized']=[ev('extern/dolphin/src/dolphin/mtx/vec.c',210,229,'All input loads precede destination stores; exact alias supported.')]
extra['8000DE38']=[ev('src/melee/if/ifstock.c',240,267,'Steal-icon caller passes packed data, factor0.1*counter and translates output.')]
for k in ['Rotate','RotateAboutUnitAxis','ApplyEulerRotation','CreateEulerMatrix']:extra[k].append(ev(src,128,151,'Quintic approximation with at most one tau correction, not general argument reduction.'))
for k in ['.data','.sdata']:extra[k]+=[ev('src/sysdolphin/baselib/debug.h',16,33,'Assertion macro stringification.'),ev('src/sysdolphin/baselib/debug.c',39,43,'Failed assertion reports and panics.')]
changes={
('.data','inferred_type'):('Assertion-string pool containing lbvector.c and three component-range expressions. Existing split object .data is136 bytes including padding; existing source object is130 bytes. The pos3d pointer-expression string is in .sdata, not this pool.','Separates the observed object sections and their padding; object hashes are attached to the review.'),
('.data','purpose'):('Holds the source-filename and X/Y/Z coordinate-range diagnostic strings for WorldToScreen assertions. The pointer-condition text pos3d belongs to the separate small-data section.','Correct the inherited inclusion of pointer-assertion text in .data.'),
('.sdata','inferred_type'):('NUL-terminated assertion-expression string pos3d. Existing source object stores six bytes; the split object contributes eight bytes including padding. No vector or persistent gameplay state is demonstrated.','Existing object bytes resolve the formerly unknown small-data payload.'),
('.sdata','purpose'):('Supplies the failed-expression text for the WorldToScreen assertion that pos3d is non-NULL.','The macro stringifies the source condition and existing object bytes identify this section.'),
('Lerp','data_flow'):('Writes b-a into result, scales result by f, then adds the current contents of a. The intended a+f*(b-a) requires result not to alias a. Exact alias with b is safe if a is distinct. If result==a, the difference overwrites a before the final addition, producing twice the scaled difference instead. The factor is not clamped.','Sequential writes expose an alias restriction omitted from the inherited generic interpolation account.'),
('8000E838','data_flow'):('Computes b-a and c-a in temporaries. For squared direction length strictly between -1e-5 and1e-5, writes d=a and returns the stored c-a length. Otherwise computes an unclamped line parameter, writes d=a+(b-a)*t, rereads c to subtract d and returns the residual length. Therefore d must not alias c for the nondegenerate distance result; input-preservation statements require disjoint output storage.','The inherited unconditional no-input-mutation claim overlooks output aliasing and the late c read.'),
('WorldToScreen','purpose'):('Projects a bounded input position into an HSD camera viewport for perspective or orthographic projection. It adjusts points whose view-depth exceeds -0.01 before GXProject and returns the output pointer; unsupported projection types return NULL. It does not guarantee finite coordinates for arbitrary camera matrices or projection parameters.','The position assertions do not validate camera parameters or establish finite output.'),
('WorldToScreen','state_behavior'):('Supports perspective and orthographic projection only. Nonzero d rebuilds a look-at matrix; zero reuses the camera viewing matrix. If depth z exceeds -0.01, adds the third-row direction times -z-0.01 to the source copy. This places depth at -0.01 only for a unit-length depth row; no such validation occurs locally. Unsupported modes return NULL before writing coordinates.','Qualify the inherited exact depth result by the mathematical matrix invariant.'),
('WorldToScreen','data_flow'):('Reads projection/viewport data into GXProject parameter arrays and selects a rebuilt or stored view matrix according to d. It copies the input position, conditionally offsets the copy along the matrix third row, then writes GXProject results into screenCoords. The camera-depth correction assumes the view row has unit length for its intended -0.01 depth.','Remove an unconditional exact-depth claim while retaining the full local data path.'),
('sqrtf__Ff','purpose'):('Provides the target math header ordinary single-precision sqrt path used by vector lengths: positive inputs use reciprocal-square-root refinement, while inputs failing x>0 are returned unchanged. In particular, negative input is passed through rather than converted to a mathematical square-root result.','Independent header read limits the inherited all-input square-root claim.'),
('sqrtf__Ff','data_flow'):('Under the target math_ppc implementation, positive x goes through __frsqrte and three double-precision Newton steps before a float-rounded return. Values that fail x>0 return x unchanged. Vector length callers pass sums of squares, and Normalize checks the resulting length for exact zero before reciprocal scaling.','Record the actual target helper branches and refinements.'),
('sqrtf_accurate','purpose'):('Exposes sqrtf_accurate as an out-of-line entry point. The target math_ppc helper uses four reciprocal-square-root refinements for positive x and returns other x unchanged; the non-Gekko placeholder path aliases it to sqrtf.','The higher-refinement behavior is target-configuration-specific.'),
('EulerAnglesFromONB','data_flow'):('For b.z not exactly +/-1, writes Y=asin(-b.z), X=atan2(c.z,a.z), Z=atan2(b.y,b.x). At -1 or+1, writes Y=+/-pi/2, derives X from c.x and c.y, and fixes Z=0. Inputs are assumed orthonormal and asin input is not clamped. Output should be distinct from basis vectors because component writes precede later reads.','The inherited flow omitted singular formulas and overstated input preservation under aliasing.'),
('Sub','data_flow'):('Subtracts b from a componentwise and returns a. Only a is explicitly written; if a==b and components are finite, the shared vector is zeroed, so b is preserved only when it is distinct storage.','Clarify the alias-dependent preservation statement.')}
changes[('EulerAnglesFromPartialONB','inferred_type')]=('Vec3* helper with signature lbVector_EulerAnglesFromPartialONB(Vec3* result_angles, Vec3* a, Vec3* c), returning result_angles. It constructs normalized c cross a in a temporary and writes Euler angles through result_angles. The supplied a and c are preserved only when output storage is disjoint from them; aliasing can affect later reads in EulerAnglesFromONB.','Qualify input preservation by output aliasing.')
changes[('sqrtf__Ff','inferred_type')]=('Single-precision scalar helper with signature float(float). In the target math_ppc implementation positive inputs receive reciprocal-square-root refinement to approximate sqrt; inputs failing x>0 are returned unchanged.','Restrict mathematical square-root semantics to the positive-input branch.')
additions={
('Rotate','state_behavior'):('Accepts only exact axis selectors1,2,4. With another selector the switch assigns none of x,y,z before storing them, so source behavior is undefined. Sine/cosine are quintic approximations with at most one +/-tau adjustment; arbitrarily large angles are not fully reduced, and exact norm preservation is not guaranteed.','Capture invalid-selector and approximation limits directly visible in source.'),
('Lerp','state_behavior'):('No endpoint shortcut or factor clamp exists. At f=1, cancellation may lose a small b relative to a. result must not alias a for intended interpolation, because the final addition reads a after result is overwritten.','Source comment and call order expose endpoint-rounding and alias behavior.'),
('CosAngle','state_behavior'):('Uses XY only and divides by the product of XY lengths without checking zero or clamping the quotient. Zero XY length and nonfinite inputs have no special fallback.','Distinguish this routine from the guarded Angle and AngleXY helpers.'),
('EulerAnglesFromPartialONB','state_behavior'):None}
proposal={'tu':tu,'proposal':{'facts':[],'links':[],'entities':[],'merges':[],'follow_ups':[]}};subjects=[]
for row in rows:
 key=next(iter(row['subject'].values()));k=namekey(key);a,b,review=data[k];e=[ev(src,a,b,'Complete owned implementation or relevant source literal site.')]+extra[k]
 item={'subject':row['subject'],'canonical_range':[a,b],'review':review,'facts':[]}
 if not row['facts']:item.update(disposition='reviewed_no_existing_facts',parameter_review='Canonical parameter slot reviewed in its function signature; input/output roles follow the parent function account. No new entity claims.')
 for f in row['facts']:
  ch=changes.get((k,f['type']));disp='supersede' if ch else 'retain';why=ch[1] if ch else 'Current complete canonical arithmetic and independently read helper evidence support the stated normal-input behavior.'
  if f['type']=='game_mapping' and k in ['Mirror','RotateAboutUnitAxis','WorldToScreen','8000DE38']:
   if k!='8000DE38':disp='unresolved';why='Specific external gameplay consumers were not independently read; preserve this inherited caller claim pending family review.'
   else:disp='unresolved';why='Stock animation use is verified, but raised-midpoint construction and transfer-between-player semantics were not independently read.'
  if f['type']=='inferred_name':why='Retain descriptive hypothesis supported by the arithmetic; canonical symbol remains unchanged.'
  if k=='sqrtf__Ff' and f['type']=='inferred_name':why='sqrtf is attested in the included target math header; retain as source spelling for the emitted mangled symbol, not a rename of the canonical target key.'
  item['facts'].append({'id':f['id'],'version':{'updated_at':f['updated_at'],'numeric_version':None},'type':f['type'],'value':f['value'],'disposition':disp,'reason':why,'evidence':e})
  if ch:proposal['proposal']['facts'].append({'subject':row['subject'],'type':f['type'],'op':'write','value':ch[0],'rationale':why,'confidence':0.98,'evidence':e})
 if 'target_stable_key' in row['subject']:
  for (kk,typ),ch in additions.items():
   if kk==k and ch:proposal['proposal']['facts'].append({'subject':row['subject'],'type':typ,'op':'write','value':ch[0],'rationale':ch[1],'confidence':0.98,'evidence':e})
 subjects.append(item)
receipts=[]
unit=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908/units/main__melee__lb__lbvector')
for p,a,b in [(src,1,240),(src,241,480),(src,481,525),('src/melee/lb/lbvector.h',1,52)]:
 artifact=unit/'pages'/(p.replace('/','__')+f'.{a}-{b}.json');r=json.load(open(artifact))['rendered'];receipts.append({'path':p,'canonical_range':[a,b],'rendered_range':[a,b],'source_sha256':next(f['sha256'] for f in m['files'] if f['path']==p),'artifact':str(artifact),'render_metadata':r})
counts={'targets':sum('target_stable_key' in r['subject'] for r in rows),'entities':sum('entity_locator' in r['subject'] for r in rows),'facts':sum(len(r['facts']) for r in rows),'proposals':len(proposal['proposal']['facts']),'dispositions':{d:sum(f['disposition']==d for s in subjects for f in s['facts']) for d in ['retain','supersede','reject','unresolved']}}
readlog=[json.loads(l) for l in (unit/'reads.jsonl').read_text().splitlines() if json.loads(l).get('reader')=='lbvector_leaf'];started=min(x['at'] for x in readlog);completed=datetime.datetime.now(datetime.timezone.utc).isoformat()
support=json.load(open(out/'supporting-reads.json'));support.append({'path':'src/sysdolphin/baselib/debug.c','canonical_range':[39,45],'sha256':hashlib.sha256((root/'src/sysdolphin/baselib/debug.c').read_bytes()).hexdigest()})
coverage={'campaign':m['campaign_id'],'tu':tu,'revision':rev,'started_at':started,'completed_at':completed,'reader':'lbvector_leaf','subjects':subjects,'read_receipts':receipts,'supporting_canonical_reads':support,'object_evidence':json.load(open(out/'object-evidence.json')),'counts':counts,'exceptions':['Source physical lines524 plus renderer trailing blank525; header physical51 plus trailing blank52. All assigned views exhausted.','sqrtf__Ff has no standalone owned C definition; inspected included target math_ppc implementation and recorded configuration limit.','Existing objects inspected without rebuild; byte layout does not establish exact current source-to-object provenance.','src/math.h probe failed; actual implementation was read at src/MSL/math_ppc.h.'],'unresolved':['Four inherited gameplay-mapping clauses need external caller/asset review.','Shared camera and vector type naming is outside this TU.','Polynomial approximations and invalid input behavior are described from source, not runtime numerical certification.']}
(out/'coverage.json').write_text(json.dumps(coverage,indent=2)+'\n');(out/'proposal.json').write_text(json.dumps(proposal,indent=2)+'\n')
text=['# Vector Functionality','',f'Pinned revision `{rev}`. Review started {started}; completed {completed}.','', '## Data and Mutation','', 'The unit operates on caller-owned vectors and matrices. Add/Sub update the first vector; Diff writes a separate result; normalized cross product uses the SDK cross product and then local normalization. XY helpers deliberately preserve or ignore Z. No named module runtime state is declared. Existing object bytes identify .data as filename/range diagnostics, .sdata as pos3d, and .sdata2 as pooled floating literals.','', 'Lerp computes a+f*(b-a) without clamping or endpoint shortcuts, but its output must not alias a. Point-to-line distance uses an infinite line with no segment clamp; the residual calculation rereads c after writing d, so d==c corrupts the nondegenerate returned distance. General input preservation assumes output storage is distinct.','', '## Angles and Rotation','', 'Normalize tests computed length for exact zero. Angle uses a1e-10 product threshold; AngleXY tests exact product zero. Both clamp cosine, while CosAngle does neither a zero check nor a clamp. Euler extraction assumes an orthonormal basis and recognizes singularities only at exact b.z=+/-1. Partial basis conversion normalizes only c cross a, leaving a and c unchanged and unvalidated.','', 'Rotation helpers use a local quintic sine approximation and phase-shifted cosine with at most one tau correction. They are approximate and do not guarantee exact norm preservation. Rotate accepts exactly1,2,4; other selectors use uninitialized local outputs. ApplyEulerRotation reads successive angle components between mutations, so callers should keep angle and vector storage distinct. The matrix constructor reads Quaternion.x/y/z as Euler angles and ignores w.','', '## Interpolation and Projection','', 'Quadratic interpolation interprets nine packed floats as points at parameter0,0.5,1. Its local clamp applies to ordered values; NaN is not repaired. A current stock-icon caller supplies a0.1-scaled counter and subtracts the root translation after evaluation.','', 'WorldToScreen checks the source pointer and strict coordinate bounds, supports perspective/orthographic modes and chooses rebuilt or stored viewing state. The depth correction reaches -0.01 only when the viewing row has unit length. Camera parameters, output pointer and finite result are not validated here. Unsupported projection types return NULL before output writes.','', '## Square Roots and Section Evidence','', 'The target math header ordinary and accurate paths use three and four reciprocal-square-root refinements respectively for positive input. Inputs failing x>0 pass through unchanged. Non-Gekko placeholder macros select a different fallback. Existing split/source objects differ in diagnostic padding; hashes and bytes are captured, without any build or binary acceptance claim.']
(out/'functionality.md').write_text('\n'.join(text)+'\n');find=['# Vector Findings','','Key corrections: Lerp output aliasing, line-distance output aliasing, projection finite-result/depth assumptions, invalid rotation selectors, and identified small-data diagnostic text.','','## Fact Dispositions','']
for s in subjects:
 find+=['### '+next(iter(s['subject'].values())),'',s['review'],'']
 if not s['facts']:find += ['No existing facts. '+s['parameter_review'],'']
 for f in s['facts']:find += [f"- `{f['id']}` at `{f['version']['updated_at']}`: {f['disposition']} {f['type']}. {f['reason']}"]
 find+=['']
(out/'findings.md').write_text('\n'.join(find)+'\n');nt=['# Naming Table','','| Canonical target | Inferred alias | Decision |','|---|---|---|']
for row in rows:
 if 'target_stable_key' not in row['subject']:continue
 k=row['subject']['target_stable_key'].split(':')[-1];f=next((f for f in row['facts'] if f['type']=='inferred_name'),None);nt.append(f"| {k} | {f['value'] if f else 'none'} | {'retain; no canonical rename' if f else 'retain canonical'} |")
(out/'naming-table.md').write_text('\n'.join(nt)+'\n');(out/'unresolved.md').write_text('# Unresolved\n\nFour gameplay mapping claims remain pending independent callers: Mirror collision rebounds, arbitrary-axis Ness use, broad WorldToScreen consumers, and full raised stock-transfer arc construction. Their IDs and timestamps are explicit in coverage.json.\n\nNo shared type renaming or runtime numerical certification is proposed. Existing object files were not rebuilt. Canonical names remain unchanged.\n')
summary={'tu':tu,'revision':rev,'started_at':started,'completed_at':completed,'status':'research_complete_pending_review','counts':counts,'artifacts':{n:str(out/n) for n in ['functionality.md','findings.md','naming-table.md','coverage.json','unresolved.md','proposal.json']},'proposal_sha256':hashlib.sha256((out/'proposal.json').read_bytes()).hexdigest()};(out/'summary.json').write_text(json.dumps(summary,indent=2)+'\n');(unit/'summary.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps(summary))
