import json,hashlib,shutil
from pathlib import Path
D=Path('docs/.drafts/melee-semantic-20260908/main__sysdolphin__baselib__hsd_3B2E');M=Path('games/melee/state/knowledge_v2/semantic-sweep-20260908/manifest.json');m=json.loads(M.read_text());fs=json.loads((D/'facts.json').read_text());c=json.loads((D/'context.json').read_text());tu=c['task']['tu'];path=c['task']['source_path'];rev=m['head_revision']
rows={'.data':(5,8,'Contains static s32 lbl_80430BD0[13] with byte-valued constants 0x26,0xFF,0xE8,0xEF,0x42,0xD6,0x01,0x54,0x14,0xA3,0x80,0xFD,0x6E. Both byte helpers select a value using the previous byte modulo 13. No code in this TU writes the table.'),'fn_803B2E04':(14,61,'Maps a current byte to its forward transformed value by XORing it with the previous byte and lbl_80430BD0[prev % 13], then applying one of seven bit permutations selected by prev % 7. In the buffer loop the previous byte is the already-transformed predecessor, initially prefix byte data[15].'),'fn_803B302C':(89,140,'Applies the inverse of the selected forward byte permutation using the low byte of prev modulo 7, then XORs with the table entry selected by low-byte prev modulo 13 and with prev. In the buffer caller prev and cur carry byte values and this reverses fn_803B2E04.'),'hsd_803B2FA0':(66,83,'Rejects null data with -1. Otherwise passes data+16, len-16 and data to hsd_803B2B20, then transforms bytes at indices 16 through len-1 in place through fn_803B2E04 using each preceding already-transformed byte. Returns zero without validating len or a foreign-helper status.'),'hsd_803B31CC':(145,176,'Rejects null data with -1. Seeds chaining from data[15], inversely transforms the payload in place while preserving each original encoded byte for the next step, calls hsd_803B2B20 on the recovered payload into check[16], and compares all 16 check bytes with the unchanged prefix. Returns -1 on first mismatch and zero when all match; failure does not restore the payload.'),'file':(1,176,'Defines paired in-place chained byte transforms with a 16-byte prefix used for verification. Forward processing delegates prefix generation to hsd_803B2B20 before transforming payload bytes; inverse processing restores payload bytes before recomputing and comparing that prefix. A private 13-entry table and seven mutually inverse byte permutations implement the chain.')}
def ev(n):
 a,b,_=rows[n]; ranges=[(a,b)];ranges+= {'fn_803B2E04':[(75,80)],'fn_803B302C':[(14,61),(158,165)],'.data':[(20,23),(137,139)]}.get(n,[])
 return [{'kind':'code','locator':f'code://{rev}/{path}#L{a}-L{b}','why':'Current canonical table, helper arithmetic, or buffer loop supports the claim.'} for a,b in ranges]
proposal={'tu':tu,'proposal':{'facts':[],'links':[],'entities':[],'merges':[],'follow_ups':[]}};disps=[];subjects=[]
for s,rr in fs.items():
 subj={'entity_locator':s} if s==path or '#' in s else {'target_stable_key':s};n='file' if s==path else s.split(':')[-1]
 subjects.append({'subject':subj,'fact_count':len(rr),'disposition':'reviewed_empty' if not rr else 'reviewed','summary':rows[n][2] if n in rows else 'Parameter entity with no inherited facts.'})
 for f in rr:
  typ=f['type'];d='retain';reason='Current canonical behavior supports this local claim.';v=None
  if typ=='inferred_name' or typ=='game_mapping':d='unresolved';reason='Memory-card consumer attribution requires external caller evidence; keep canonical names authoritative and do not promote the inherited alias.'
  elif typ=='purpose':d='supersede';v=rows[n][2];reason='Describe local buffer arithmetic and verification without unreviewed memory-card attribution.'
  elif typ=='inferred_type' and n=='fn_803B2E04':d='supersede';v='Private direct-call helper with exact signature static int fn_803B2E04(u8 prev, s32 cur). Its sole local caller supplies byte-valued current input, and all seven reachable cases return a u8 value through int. It is not registered as a callback.';reason='Remove unsupported callback characterization.'
  elif typ=='inferred_type' and n in ['hsd_803B2FA0','hsd_803B31CC']:
   d='supersede';v=f'Exact signature int {n}(u8* data, int len). data is mutable and len is the total buffer length including a 16-byte prefix. The routine checks null but does not validate len >= 16 or buffer capacity. '+('Returns zero after its forward pass.' if n=='hsd_803B2FA0' else 'Returns zero only after all 16 prefix comparisons match; otherwise returns -1 after payload mutation.');reason='Use canonical signature and distinguish checked input from implicit preconditions.'
  elif typ=='inferred_type' and n=='file':d='supersede';v='Buffer-transform TU with one static s32[13] table, two private inverse byte helpers and two public int(u8* data,int len) entry points. Both reject null; neither checks the total length, and only the inverse entry point compares the verification prefix.';reason='Remove unreviewed consumer identity and broad invalid-input claim.'
  elif typ=='data_flow' and n in ['file','hsd_803B2FA0','hsd_803B31CC']:d='supersede';v=rows[n][2];reason='Use exact delegated calls and visible prefix comparison without claiming a checksum algorithm.'
  disps.append({'subject':subj,'fact_id':f['id'],'fact_version':{'updated_at':f['updated_at']},'type':typ,'prior_value':f['value'],'disposition':d,'reason':reason,'evidence':ev(n)})
  if v is not None:proposal['proposal']['facts'].append({'subject':subj,'type':typ,'op':'write','value':v,'rationale':reason,'confidence':0.97,'evidence':ev(n)})
reads=[]
for ext,end in [('c',177),('h',10)]:
 p=M.parent/'units'/c['task']['id']/'pages'/f'src__sysdolphin__baselib__hsd_3B2E.{ext}.1-{end}.json';r=json.loads(p.read_text())['rendered'];reads.append({'path':r['path'],'canonical_range':[1,end],'rendered_range':[1,end],'artifact':str(p),'artifact_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'source_sha256':r['source_sha256'],'status':r['status'],'next_line':r['next_line'],'parse_errors':r['parse_errors'],'substitutions':r['substitutions']})
followups=[{'topic':'Memory-card caller attribution','status':'unresolved','reason':'All five inherited naming hypotheses and six game mappings depend on external consumer evidence not read in this owned TU.'},{'topic':'hsd_803B2B20 verification algorithm and size preconditions','status':'family_review','reason':'This TU calls it with payload and output pointers. The foreign implementation must establish its output-write extent, checksum algorithm, and behavior for zero/negative lengths.'}]
counts={'files_expected':2,'files_reviewed':2,'canonical_lines':187,'rendered_lines':187,'targets_expected':5,'targets_reviewed':5,'functions':4,'data_sections':1,'subjects_expected':14,'subjects_reviewed':14,'empty_parameter_entities':8,'inherited_facts':len(disps),'proposal_operations':len(proposal['proposal']['facts']),'dispositions':{d:sum(x['disposition']==d for x in disps) for d in ['retain','supersede','reject','unresolved']}}
findings={'campaign':m['campaign_id'],'tu':tu,'head_revision':rev,'manifest_sha256':hashlib.sha256(M.read_bytes()).hexdigest(),'files':c['files'],'reads':reads,'read_exceptions':[],'subjects':subjects,'targets':[{'canonical_name':n,'subject':{'target_stable_key':tu+':'+n},'range':[a,b],'summary':v,'evidence':ev(n)} for n,(a,b,v) in rows.items() if n!='file'],'fact_dispositions':disps,'counts':counts,'verification':json.loads((D/'inverse-check.json').read_text()),'followups':followups,'uncertainty':['Inverse helper is proven for byte-valued inputs supplied by the local caller; full u32 arguments may preserve high prev bits after XOR.','Length >=16 is an unchecked precondition, not a handled failure.','Payload is mutated before inverse verification and remains changed after mismatch.'],'status':'local_review_complete_pending_independent_review'}
for fn,obj in [('findings.json',findings),('proposal.json',proposal),('followups.json',followups)]: (D/fn).write_text(json.dumps(obj,indent=2)+'\n')
print(counts)
