import json,hashlib
from pathlib import Path
D=Path('docs/.drafts/melee-semantic-20260908/main__melee__cm__camera'); M=Path('games/melee/state/knowledge_v2/semantic-sweep-20260908/manifest.json'); m=json.loads(M.read_text()); fs=json.loads((D/'geometry.facts.json').read_text()); tu='main/melee/cm/camera'; path='src/melee/cm/camera.c'
rows=[
('Camera_Init',163,227,'Initializes game_camera and transform_copy from the perspective descriptor, selects CAMERA_STANDARD, resets flags and quake storage, allocates and clears n_subjects CmSubject records, chains the free pool through prev, and clears active-list endpoints. The final indexed write requires a positive capacity; allocation failure is not checked.'),
('Camera_80028F5C',229,256,'Initializes a non-null CmSubject with the supplied state, zero position, bone position, facing, flags, timer and auxiliary vectors, horizontal extents (-1,1), vertical extents (1,-1,1), and identical target extents. List links are untouched.'),
('Camera_80029020',258,261,'Returns Camera_80029044(0), allocating and initializing one pooled subject with state value zero.'),
('Camera_80029044',263,284,'Pops the free-list head, appends the subject to the active-list tail, initializes it with the supplied integer state through Camera_80028F5C, and returns it. Exhaustion reports an error and loops forever.'),
('Camera_800290D4',286,302,'Unlinks the supplied active subject, repairs neighboring links and active-list endpoints, and prepends it to the free list through prev. It neither frees heap storage nor validates null or membership.'),
('Camera_80029124',304,345,'Returns directional CAM_BOUNDS flags for strict X/Y crossings of the stage camera rectangle expanded by distance. The effective bottom is max(Stage_GetCamBoundsBottomOffset(), first Ground_801C4368 output + 1); Z is unused.'),
('Camera_8002928C',352,385,'Returns subject eligibility while mutating cooldown state. Inactive or force_inactive subjects fail; auto subjects with nonzero state_timer decrement it and fail. Otherwise auto subjects must lie within normalized [0.35,0.65] on both stage axes; leaving after prior acceptance clears was_framed and sets the timer to 600. Accepted subjects set was_framed true.'),
('Camera_800293E0',387,462,'Traverses active subjects backward, invokes the stateful eligibility test, and moves each accepted subject\'s five current extent components toward corresponding target extents by at most 0.5 per invocation.'),
('Camera_8002958C',464,676,'Counts eligible subjects, chooses count-dependent extent scaling times Stage_GetCamTrackRatio, then tests eligibility again while collecting stage-clamped X/Y extent samples. With no subjects accepted in the final pass it uses a rectangle of +/-40 around the stage camera offset. Writes bounds and subject count, stores absolute camera position Z, and lowers y_min by 10 to 400 based on that Z.'),
('Camera_80029AAC',701,743,'Approaches target_interest in X/Y only. Chooses follow speed from maximum bounds span, or 99999 when empty, multiplies caller speed by reciprocal game_camera.x2BC with a 1000 fallback, clamps the factor to [0.0001,1], and updates interest.'),
('Camera_80029BC4',749,766,'Computes max(height/tan(target_fov radians), width/(aspect*tan(target_fov radians))), applies the stage zoom-rate floor followed by maximum-depth ceiling, and writes bounds->z_pos. This path uses the full target_fov argument, unlike the half-FOV transform solver.'),
('Camera_80029C88',768,787,'Updates all three current-position components by (target_position-position)*min(cm_803BCCA0.x3C*arg_scale,1). The bounds parameter is unused and the coefficient has no lower clamp.'),
('Camera_80029CF8',806,908,'Computes target_interest and target_position from rectangular bounds, current FOV, aspect, stage offsets and pan tuning. Spread-dependent vertical bias and bounded angles feed tangent-based horizontal and vertical distances. The larger distance receives stage depth limits, target interest Z is zero, and compensating X/Y offsets place the target eye.'),
('Camera_ApplyQuake',910,966,'Scales pending quake_offset X/Y by quake_scale, 10, game_camera.x2BC and cm_803BCCA0.xE8 when gm_8016B41C returns nonzero. Converts through depth, FOV, aspect and viewport dimensions, applies interpolated axis tuning, calls Camera_80030DE4 with the resulting pair, and clears the pending offset.'),
('Camera_SetQuakeOffset',968,972,'Replaces game_camera.quake_offset.x and .y with the supplied values for later consumption by Camera_ApplyQuake.'),
('Camera_UpdateQuakes',974,1000,'Copies 16 quakes[0] records into quakes[1], clears each source kind, and decrements each nonzero quake_frames_left entry. Calls HSD_GObjPLink_80390228 on quake_gobj and clears the pointer only when some timer was nonzero before decrement, the object exists, and QuakeKind_Loop is zero afterward. The bounds parameter is unused.'),
('Camera_8002A4AC',1032,1085,'Installs camera state into the GObj\'s CObj according to game_camera.mode. Standard/fixed update both primary and secondary transforms; free updates the primary. Pause clamps a temporary eye Y using selected stage floor callbacks. Pause/training/clear/boss modes use fixed clipping; debug modes use dedicated vectors and FOV, including the follow field names being passed in reversed eye/interest roles.')]
R={n:(a,b,v) for n,a,b,v in rows}
def evidence(n):
 a,b,_=R[n]; out=[{'kind':'code','locator':f'code://{m["head_revision"]}/{path}#L{a}-L{b}','why':'Canonical implementation establishes the inputs, state writes and branch conditions described.'}]
 extra={'Camera_80029020':(263,284),'Camera_8002928C':(347,350),'Camera_800293E0':(352,385),'Camera_8002958C':(352,385),'Camera_80029AAC':(678,699),'Camera_80029CF8':(792,804),'Camera_SetQuakeOffset':(910,966),'Camera_8002A4AC':(1002,1030)}
 if n in extra:
  a,b=extra[n]; out.append({'kind':'code','locator':f'code://{m["head_revision"]}/{path}#L{a}-L{b}','why':'Supporting local helper or consumer establishes the delegated behavior.'})
 return out
proposal={'tu':tu,'proposal':{'facts':[],'links':[],'entities':[],'merges':[],'follow_ups':[]}}
dispositions=[]; targets=[]
unsupported={('Camera_80029020','data_flow'),('Camera_80029020','game_mapping'),('Camera_80029044','game_mapping'),('Camera_800290D4','game_mapping'),('Camera_800293E0','data_flow'),('Camera_800293E0','game_mapping'),('Camera_ApplyQuake','game_mapping'),('Camera_Init','game_mapping'),('Camera_SetQuakeOffset','data_flow'),('Camera_SetQuakeOffset','game_mapping'),('Camera_SetQuakeOffset','state_behavior'),('Camera_UpdateQuakes','game_mapping'),('Camera_8002928C','inferred_type')}
updates={
('Camera_8002928C','state_behavior'): R['Camera_8002928C'][2]+' Timer units are eligibility invocations, not established frames: Camera_8002958C can call this test in two passes.',
('Camera_8002958C','state_behavior'): R['Camera_8002958C'][2]+' Each eligibility invocation can decrement an auto subject timer, so the two passes need not accept identical subject sets.',
('Camera_80029AAC','data_flow'): R['Camera_80029AAC'][2],
('Camera_8002A4AC','data_flow'): R['Camera_8002A4AC'][2],
('Camera_ApplyQuake','data_flow'): R['Camera_ApplyQuake'][2],
('Camera_ApplyQuake','state_behavior'): 'Consumes the pending X/Y quake offset and clears it after calling Camera_80030DE4. A stage depth span below 0.001 selects ratio 0.5; otherwise ratio=(bounds->z_pos-Stage_GetCamZoomRate())/span, without clamping. gm_8016B41C() != 0 enables the xE8 scale; the predicate\'s game-mode meaning requires its owner\'s review.',
('Camera_Init','inferred_type'): 'Exact signature void Camera_Init(int n_subjects). n_subjects supplies contiguous CmSubject pool capacity and must be positive for the final indexed link write; the function does not validate it.',
('Camera_SetQuakeOffset','inferred_type'): 'Exact signature void Camera_SetQuakeOffset(f32 x, f32 y). Both scalars are copied into the camera\'s pending quake offset.',
('Camera_UpdateQuakes','inferred_type'): 'Exact signature void Camera_UpdateQuakes(CameraBounds* bounds). bounds is unused; the function copies 16 quake records between singleton arrays, decrements quake timers, and conditionally releases the retained quake GObj.',
('Camera_UpdateQuakes','data_flow'): R['Camera_UpdateQuakes'][2],
('Camera_UpdateQuakes','state_behavior'): R['Camera_UpdateQuakes'][2]}
named={'Camera_Init','Camera_ApplyQuake','Camera_SetQuakeOffset','Camera_UpdateQuakes'}
for n,a,b,v in rows:
 s=tu+':'+n; aliases=[]
 for f in fs[s]:
  typ=f['type']; disposition='retain'; reason='Current canonical implementation supports this local behavior.'; replacement=None; op='write'
  if typ=='purpose': disposition='supersede'; replacement=v; reason='Use precise current canonical names and implementation limits.'
  elif (n,typ) in updates: disposition='supersede'; replacement=updates[n,typ]; reason='Correct stale spelling, layout or semantic overstatement using current canonical code.'
  elif (n,typ) in unsupported: disposition='unresolved'; reason='Local behavior is supported, but caller-specific game mapping, foreign predicate semantics or header field width needs family review.'
  elif typ=='inferred_name':
   aliases.append(f['value'])
   if n in named: disposition='reject'; replacement=''; op='clear'; reason='Canonical semantic name is authoritative; inherited hypothesis is redundant or unnecessarily replaces it.'
   else: replacement=f['value']; reason='Retain this noncanonical reading aid; implementation independently supports the name.'
  dispositions.append({'subject':{'target_stable_key':s},'fact_id':f['id'],'fact_version':{'updated_at':f['updated_at']},'type':typ,'prior_value':f['value'],'disposition':disposition,'reason':reason,'evidence':evidence(n)})
  if replacement is not None:
   proposal['proposal']['facts'].append({'subject':{'target_stable_key':s},'type':typ,'op':op,'value':replacement,'rationale':reason,'confidence':0.97 if typ!='inferred_name' else (0.99 if op=='clear' else f['confidence']),'evidence':evidence(n)})
 targets.append({'canonical_name':n,'stable_key':s,'range':[a,b],'summary':v,'inherited_names':aliases,'canonical_name_authoritative':True,'evidence':evidence(n)})
reads=[]
for a,b in [(1,240),(241,480),(481,720),(721,960),(961,1086)]:
 p=M.parent/'units/main__melee__cm__camera/pages'/f'src__melee__cm__camera.c.{a}-{b}.json'; j=json.loads(p.read_text()); r=j['rendered']; reads.append({'canonical_range':[a,b],'rendered_range':[a,b],'artifact':str(p),'artifact_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'source_sha256':r['source_sha256'],'status':r['status'],'knowledge_status':r['knowledge_status'],'parse_errors':r['parse_errors'],'substitutions':r['substitutions']})
globals=[('game_camera','Shared camera transform, mode, clipping, quake and pool-adjacent runtime state.',163,227),('cm_804D645C','Allocated pool base.',214,223),('cm_804D6458','Free subject-list head, using prev as the free-chain link.',263,302),('cm_804D6460 / cm_804D6468','Active subject-list head / tail; framing walks backward from the tail.',263,302),('cm_804D6464','Secondary CObj receiving transform_copy in standard/fixed modes.',1039,1046),('cm_803BCB9C','Extent weights indexed by eligible count: 1.5,1.32,1.16,1.0 for one through four; counts >=5 use 1.0.',491,507),('cm_803BCB18 / cm_803BCB64','Mode callback table followed by descriptor storage; descriptor initializes camera and supplies aspect and viewport for geometry.',57,90),('cm_803BCCA0','Offset-addressed tuning consumed by follow interpolation, angle/bias limits, eye smoothing, and quake scaling. Do not generalize all fields from this cluster.',678,743)]
findings={'campaign':m['campaign_id'],'tu':tu,'cluster':'camera-geometry','head_revision':m['head_revision'],'manifest_sha256':hashlib.sha256(M.read_bytes()).hexdigest(),'assignment':{'path':path,'range':[1,1086],'headers_owned':[],'previous_range':[1,2352],'repartitioned_by_parent':True},'reads':reads,'exceptions':[],'targets':targets,'fact_dispositions':dispositions,'entity_subjects':[{'entity_locator':s,'facts':len(f),'disposition':'reviewed_empty'} for s,f in fs.items() if '#' in s],'globals':[{'symbol':n,'meaning':v,'evidence':[{'kind':'code','locator':f'code://{m["head_revision"]}/{path}#L{a}-L{b}'}]} for n,v,a,b in globals],'uncertainty':['State timers advance per eligibility invocation, not a proven 600 rendered frames.','Ground_801C4368 first output supplies a bottom floor; its broader physical meaning is foreign ownership.','gm_8016B41C game-mode meaning and Camera_80030DE4 downstream effect require owner review.','Camera_8002A4AC passes follow_eye_pos to interest and follow_int_pos to eye; retain exact behavior without inferring which field is misnamed.','Camera_80029BC4 uses tan(full target_fov), whereas Camera_80029CF8 uses half current fov; no geometric-equivalence assertion.'],'family_followups':['Confirm fighter/item/stage caller mapping, subject field timer width, and stage quake animation producers for unresolved inherited facts.','Review stage floor callback outputs for Castle, Corneria, Zebes, Garden, KinokoRoute and Homerun.'],'counts':{'canonical_lines':1086,'rendered_lines':1086,'pages':5,'targets':17,'entity_subjects':26,'inherited_facts':len(dispositions),'proposal_facts':len(proposal['proposal']['facts']),'dispositions':{d:sum(x['disposition']==d for x in dispositions) for d in ['retain','supersede','reject','unresolved']}}}
(D/'geometry.findings.json').write_text(json.dumps(findings,indent=2)+'\n'); (D/'geometry.proposal.json').write_text(json.dumps(proposal,indent=2)+'\n');print(findings['counts'])
