import json,hashlib
from pathlib import Path
D=Path('docs/.drafts/melee-semantic-20260908/main__melee__lb__lb_0146');M=Path('games/melee/state/knowledge_v2/semantic-sweep-20260908/manifest.json');m=json.loads(M.read_text());c=json.loads((D/'context.json').read_text());fs=json.loads((D/'facts.json').read_text());tu=c['task']['tu'];path=c['task']['source_path'];rev=m['head_revision']
rows={'.sdata':(54,58,'Source declares exported opaque white/black GXColors and private opaque red, alpha64 red and opaque yellow. Local rendering reads red/translucent_red/yellow; no local writes occur. Compiled .sdata placement and consecutiveness are not independently established.'),'.sdata2':(35,49,'Source uses 0.01 and 1.0 in the near-zero vertical-span case and 0.0 in comparisons and emitted vertex Z coordinates. Exact .sdata2 constant membership, size and padding require object evidence.'),'lb_80014638':(17,52,'Copies two interval samples and a target sample, offsets only the first sample by unk_x in both horizontal components and unk_y in height, and rejects ascending order or a target height outside the closed vertical span. Interpolates horizontal edges at target height, using fraction1 when absolute span is below0.01, and accepts inclusive horizontal overlap. Neither input is changed.'),'lb_80014770':(60,129,'Only selector2 emits GX commands. Configures alpha-blended untextured vertex colors with depth test but no alpha/depth writes, loads current camera view matrix, and emits five triangle-strip vertices in XY with Z0. Higher sample is near_pt; sample1 always supplies opaque red and sample0 alpha64 red regardless of height order. Returns true after drawing and false otherwise, without restoring GX state.'),'lb_800149E0':(131,154,'Only selector0 calls HSD_StateInitDirect(0,2), loads the current camera view matrix, sets line-width argument12 and emits two yellow line-strip vertices at X=arg0[0][2] and arg0[0][3], shared Y=arg0[1][0], Z0. Returns true after drawing and false otherwise; the matrix-shaped input is read as packed coordinates.'),'file':(17,154,'Provides a pure descending swept-interval overlap predicate, a selector2 red triangle-strip draw helper, a selector0 yellow horizontal-line draw helper and five declared GXColors. The draw helpers mutate GX state and report whether a primitive was submitted. Fighter/item ownership and consumer gameplay roles require caller review.')}
def clean(s):
 for a,b in [('alpha64','alpha 64'),('fraction1','fraction 1'),('below0.01','below 0.01'),('selector2','selector 2'),('selector0','selector 0'),('Z0','Z 0'),('sample1','sample 1'),('sample0','sample 0'),('argument12','argument 12')]:s=s.replace(a,b)
 return s
rows={n:(a,b,clean(v)) for n,(a,b,v) in rows.items()}
def ev(n):
 a,b,_=rows[n];rr=[(path,a,b)];rr+= {'lb_80014770':[(path,54,58)],'lb_800149E0':[(path,54,58)],'file':[('src/melee/lb/lb_0146.h',10,15)]}.get(n,[])
 return [{'kind':'code','locator':f'code://{rev}/{p}#L{a}-L{b}','why':'Canonical arithmetic, color declarations or GX submission sequence support this local claim.'} for p,a,b in rr]
proposal={'tu':tu,'proposal':{'facts':[],'links':[],'entities':[],'merges':[],'follow_ups':[]}};dd=[];ss=[]
for s,rr in fs.items():
 subj={'entity_locator':s} if s==path or '#' in s else {'target_stable_key':s};n='file' if s==path else s.split(':')[-1];ss.append({'subject':subj,'fact_count':len(rr),'disposition':'reviewed_empty' if not rr else 'reviewed','summary':rows[n][2] if n in rows else 'Empty parameter entity.'})
 for f in rr:
  t=f['type'];d='retain';v=None;reason='Canonical code supports this local claim.'
  if n in ['.sdata','.sdata2']:d='unresolved';reason='Source declarations and literals are attested, but exact section membership/size and inherited consumer roles require compiled or family evidence.'
  elif t=='game_mapping':d='unresolved';reason='Fighter/item mechanic and ownership claims require external callers not read in this TU.'
  elif t in ['purpose','data_flow']:d='supersede';v=rows[n][2];reason='Use exact local behavior without foreign caller assumptions.'
  elif n=='lb_80014770' and t=='state_behavior':d='supersede';v=rows[n][2];reason='Correct color assignment: sample index determines opacity, and no caller GX cache invalidation is established locally.'
  elif n=='file' and t=='inferred_type':d='supersede';v='Three Boolean functions: a pure two-record interval predicate, bool lb_80014770(Vec3*,int), and bool lb_800149E0(Mtx,u32). Five GXColor declarations and floating-point literals support the implementation; exact compiled constant-pool layout is not established.';reason='Separate canonical declarations from compiled constant pool assumptions.'
  elif n=='lb_800149E0' and t=='state_behavior':d='supersede';v=rows[n][2];reason='Describe literal line-width argument rather than assuming its physical units.'
  dd.append({'subject':subj,'fact_id':f['id'],'fact_version':{'updated_at':f['updated_at']},'type':t,'prior_value':f['value'],'disposition':d,'reason':reason,'evidence':ev(n)})
  if v is not None:proposal['proposal']['facts'].append({'subject':subj,'type':t,'op':'write','value':v,'rationale':reason,'confidence':0.97,'evidence':ev(n)})
reads=[]
for ext,b in [('c',155),('h',18)]:
 p=M.parent/'units'/c['task']['id']/'pages'/f'src__melee__lb__lb_0146.{ext}.1-{b}.json';r=json.loads(p.read_text())['rendered'];reads.append({'path':r['path'],'canonical_range':[1,b],'rendered_range':[1,b],'artifact':str(p),'artifact_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'source_sha256':r['source_sha256'],'status':r['status'],'next_line':r['next_line'],'parse_errors':r['parse_errors'],'substitutions':r['substitutions']})
followups=[{'topic':'Fighter/item interval ownership and consumer behavior','status':'pending_family','reason':'Item jumped-on mapping, Fighter.dmg.x1930, Item.xB54, input sample chronology and caller GX cache handling need external callers.'},{'topic':'Compiled palette and literal sections','status':'unresolved','reason':'Canonical colors and float uses are visible; all eight section facts need exact .sdata/.sdata2 object evidence.'}]
counts={'files_expected':2,'files_reviewed':2,'canonical_lines':173,'rendered_lines':173,'targets_expected':5,'targets_reviewed':5,'functions':3,'data_sections':2,'subjects_expected':12,'subjects_reviewed':12,'empty_parameter_entities':6,'inherited_facts':len(dd),'proposal_operations':len(proposal['proposal']['facts']),'dispositions':{d:sum(x['disposition']==d for x in dd) for d in ['retain','supersede','reject','unresolved']}}
j={'campaign':m['campaign_id'],'tu':tu,'head_revision':rev,'utc_start':(D/'start.txt').read_text().strip(),'manifest_sha256':hashlib.sha256(M.read_bytes()).hexdigest(),'files':c['files'],'reads':reads,'read_exceptions':[],'targets':[{'canonical_name':n,'range':[a,b],'summary':v,'evidence':ev(n)} for n,(a,b,v) in rows.items() if n!='file'],'subjects':ss,'fact_dispositions':dd,'followups':followups,'counts':counts,'uncertainty':['Red opacity follows sample index, not universally higher versus lower height.','The predicate accepts exact vertical/horizontal boundaries and uses endpoint1 for spans below0.01 after ordering tests.','Draw-helper bool means accepted selector and emitted primitive, not collision result.'],'status':'local_review_complete_pending_independent_review'}
for n,v in [('findings.json',j),('proposal.json',proposal),('followups.json',followups)]:(D/n).write_text(json.dumps(v,indent=2)+'\n')
print(counts)
