import json,pathlib,hashlib
out=pathlib.Path(__file__).parent;m=json.load(open('games/melee/state/knowledge_v2/semantic-sweep-20260908/manifest.json'));rev=m['head_revision'];tu='main/melee/ft/ftcamera';src='src/melee/ft/ftcamera.c';root=pathlib.Path(m['checkout_root']);rows=json.load(open(out/'facts.json'))
def e(p,a,b,why):return {'kind':'code','locator':f'code://{rev}/{p}#L{a}-L{b}','why':why}
ranges={'ftCamera_UpdateCameraBox':(49,87),'ftCamera_800762F4':(89,93),'ftCamera_80076320':(95,114)}
extra={
'ftCamera_UpdateCameraBox':[e(src,10,18,'All six metadata floats are scaled; owned claims remain on the updater only.'),e('src/melee/ft/ftlib.c',325,331,'Bone anchor delegation.')],
'ftCamera_800762F4':[e('src/melee/ft/ftlib.c',293,297,'Returns the configured part joint.'),e('src/melee/ft/ftlib.c',325,331,'Selects camera_zoom_target_bone and co_attrs.x170 offset.'),e('src/melee/lb/lb_00B0.c',105,140,'Transforms the local offset into the destination, or copies the offset for a null joint.'),e('src/melee/ft/kinds/ftCommon/ftCo_WarpStar.c',120,123,'Jump camera callback.'),e('src/melee/ft/kinds/ftCommon/ftCo_WarpStar.c',232,235,'Fall camera callback.'),e('src/melee/ft/kinds/ftCommon/ftCo_Throw.c',438,446,'Kirby motion-ID branch chooses bone-only update.'),e('src/melee/ft/kinds/ftCommon/ftCo_Thrown.c',121,131,'Thrown camera callback selects by referenced fighter kind and motion.')],
'ftCamera_80076320':[e('src/melee/ft/ft_0D31.c',697,700,'Named DeadUpStar camera callback.'),e('src/melee/ft/ft_0D4D.c',50,53,'Named DeadUpFall camera callback.'),e('src/melee/gr/stage.c',132,137,'Stage camera offset vector.')]
}
changes={
('ftCamera_800762F4','data_flow'):('Receives a fighter GObj, obtains its CmSubject, and delegates writing bone_pos to ftLib_800866DC. That helper selects ft_data->x0->camera_zoom_target_bone, obtains fp->parts[index].joint, and transforms co_attrs.x170 into the destination. A null selected joint copies the local offset directly; the wrapper does not rewrite other CmSubject fields.','Adds independently read joint selection and local-offset behavior, including the null-joint fallback.'),
('ftCamera_800762F4','game_mapping'):('Used by WarpStarJump_Cam and WarpStarFall_Cam for bone-position-only updates. ThrowHi_Cam chooses it for Kirby with motion ID 221; ThrownHi_Cam chooses it when the fighter referenced by victim_gobj is Kirby in ftCo_MS_ThrowHi. Both throw callbacks otherwise call ftCamera_UpdateCameraBox.','Replace an inferred offscreen condition with the exact callback selection conditions.'),
('ftCamera_80076320','game_mapping'):('Provides specialized camera-subject positioning for the DeadUpStar and DeadUpFall camera callbacks. It pins subject Y to the stage top blast-zone offset and multiplies subject X by the ratio of top camera-bound height to top blast-zone height, each measured relative to the stage camera Y offset.','Named callers support DeadUp. The source establishes a ratio but does not guarantee its magnitude is below one, so the inherited compression assertion is removed.')}
proposal={'tu':tu,'proposal':{'facts':[],'links':[],'entities':[],'merges':[],'follow_ups':[]}};subjects=[]
for r in rows:
 key=next(iter(r['subject'].values()));symbol=key.split(':')[-1].split('#')[0];a,b=ranges[symbol];evidence=[e(src,a,b,'Complete owned definition.')]+extra[symbol]
 item={'subject':r['subject'],'canonical_symbol':symbol,'canonical_range':[a,b],'facts':[]}
 if 'entity_locator' in r['subject']:
  item['disposition']='reviewed_no_existing_facts';item['review']='r3 is the HSD_GObj* gobj input; valid Fighter userdata and attached camera subject are required. No new entity or field-type claim.'
 for f in r['facts']:
  change=changes.get((symbol,f['type']));decision='supersede' if change else 'retain';why=change[1] if change else 'Current canonical definition and independently read helper/callers support the existing claim.'
  if f['type']=='inferred_name':why='Retain as inferred only. Canonical symbol is unchanged; current local behavior and named callers support this descriptive alias.'
  item['facts'].append({'id':f['id'],'version':{'updated_at':f['updated_at'],'numeric_version':None},'type':f['type'],'value':f['value'],'disposition':decision,'reason':why,'evidence':evidence})
  if change:proposal['proposal']['facts'].append({'subject':r['subject'],'type':f['type'],'op':'write','value':change[0],'rationale':why,'confidence':0.98,'evidence':evidence})
 subjects.append(item)
receipts=[]
for p,a,b in [(src,49,115),('src/melee/ft/ftcamera.h',1,15)]:
 artifact=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908/units/main__melee__ft__ftcamera/pages')/(p.replace('/','__')+f'.{a}-{b}.json');page=json.load(open(artifact));render=page['rendered'];receipts.append({'path':p,'canonical_range':[a,b],'rendered_range':[render['start_line'],render['end_line']],'source_sha256':next(x['sha256'] for x in m['files'] if x['path']==p),'artifact':str(artifact),'render_metadata':render})
external=json.load(open(out/'external-reads.json'))
for p,rs in [('src/melee/ft/ftlib.c',[[293,350]]),('src/melee/lb/lb_00B0.c',[[105,150]])]:
 external=[x for x in external if x['path']!=p];external.append({'path':p,'canonical_ranges':rs,'rendered_ranges':[],'sha256':hashlib.sha256((root/p).read_bytes()).hexdigest()})
coverage={'campaign':m['campaign_id'],'tu':tu,'cluster':'update','revision':rev,'reader':'camera_update','read_receipts':receipts,'supporting_canonical_reads':external,'subjects':subjects,'counts':{'targets':3,'entities':3,'facts':17,'retain':14,'supersede':3,'reject':0,'unresolved':0,'proposals':3},'exceptions':['Renderer exposes final empty C line115 and header line15; physical newline-terminated counts are114 and14.','Supporting canonical helper reads are separate from assigned canonical/rendered coverage.'],'family_deferred':['No shared CmSubject/Fighter type or field rename proposed. Matrix-helper implementation can update joint matrix caches; camera-subject-only statements do not claim global purity.'],'status':'complete local review; independent review and application pending'}
(out/'coverage.json').write_text(json.dumps(coverage,indent=2)+'\n');(out/'proposal.json').write_text(json.dumps(proposal,indent=2)+'\n')
text=['# Fighter Camera Update Review','',f'Pinned revision `{rev}`. Source canonical/rendered L49-115 and full header L1-15 read.','', '## Behavior','', 'The ordinary updater scales six metadata floats but consumes only the first triplet. Facing exactly +1 chooses one horizontal arrangement; all other values choose the negated mirror and store -1. It copies the current position with a vertical metadata offset, clears on_ledge, and refreshes bone_pos. It assumes valid Fighter, camera subject and metadata pointers.','', 'The bone-only helper updates bone_pos using the configured camera joint and co_attrs.x170 offset. A null selected joint yields the offset itself. It leaves subject position, extents, facing and ledge fields alone. Warp Star callbacks always use it; throw callbacks select it using explicit Kirby and motion conditions.','', 'The DeadUp helper first performs the full update, then replaces subject X using the boundary-height ratio and pins Y to the top blast-zone offset. It preserves the full updater\'s Z and other writes. The assertion rejects a zero denominator. It does not subtract the stage camera X offset, and no local invariant guarantees horizontal compression.','', '## Naming','', '`ftCamera_UpdateCameraBox` is canonical and has no inherited alias. Retain inferred `ftCamera_UpdateCameraBonePosition` and `ftCamera_UpdateDeadUpCameraBox`; the two latter canonical symbols remain address-based. The DeadUpStar and DeadUpFall callback names independently establish the specialized role. No source renames proposed.','', '## Fact Dispositions','']
for i in subjects:
 text += ['### '+next(iter(i['subject'].values())),'']
 if not i['facts']:text += [i['review'],'No existing facts.','']
 for f in i['facts']:text += [f"- `{f['id']}` at `{f['version']['updated_at']}`: {f['disposition']} {f['type']}. {f['reason']}"]
 text += ['']
text+=['## Review Boundary','','Three category-specific proposals extend bone data flow and narrow two game mappings. All 17 existing facts have explicit ID and timestamp dispositions in coverage.json. Shared type naming remains outside this cluster. No canonical or shared-KB writes occurred.']
(out/'findings.md').write_text('\n'.join(text)+'\n');print(coverage['counts'])
