from pathlib import Path
import json,hashlib,datetime
p=Path(__file__).parent;r=Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');m=json.loads((r/'manifest.json').read_text());tu='main/sysdolphin/baselib/hsd_3A76';task=next(t for t in m['tasks'] if t['tu']==tu);state=r/'units'/task['id'];src=task['source_path'];rev=m['head_revision'];groups=json.loads((p/'baseline-facts.json').read_text());facts=[dict(f,subject=g['subject']) for g in groups for f in g['facts']];eh=hashlib.sha256((p/'compiled-evidence.json').read_bytes()).hexdigest();b='src/sysdolphin/baselib/'
changes={
0:'The encoder in hsd_3A64 searches 287 paired external-code/internal-code entries and emits the corresponding internal code. All three owned arrays have 288 two-byte slots, with a final zero pair. The third array provides default glyph metric pairs. Measurement and rendering use it for codes below 0x4000; custom-code metric pairs are read through the SIS field named textures, while custom texture bytes come through the field named kerning.',
1:'Existing source/split .data is 1944 bytes with identical raw bytes. Two 108-byte compiler jump tables at offsets 0 and 108 have 27 relocations each into measurement and rendering functions. Three u8[576] arrays follow at offsets 216,792,1368: internal character codes, external character codes, default metric pairs. Each has 288 pairs including a final zero pair; the conversion loop searches only 287.',
2:'Supplies two compiler dispatch tables plus character-code conversion and default glyph-metric data for SIS text measurement/rendering. Glyph image bytes are owned by the separate sislib_font TU, not this data section.',
3:'Reads one selected state value and appends a payload plus trailing flags to string_buffer using u16 x6C and x6E. If capacity is insufficient it allocates old capacity+16, copies the entire old capacity, zero-fills up to the new u16 capacity and frees the old buffer. Capacity and used length can wrap at 16 bits; one growth step and no validation are used. No extra terminator byte is reserved or explicitly written after a record.',
6:'Canonical signature void(HSD_Text* text,const u8* cursor,u8 flags). flags&0x7F selects 1: signed 8.8 spacing pair, 2: RGB, 3: unsigned 8.8 scale pair, 4: alignment byte, 5: 32-bit cursor address. Payload bytes precede the complete flags byte; sizes are 5,4,5,2,5. Float conversions and pointer truncation assume valid 32-bit target values and are not checked.',
8:'Recognized types append payload and full flags; others do nothing. Growth is a single 16-byte increment stored through u16, without overflow or malformed-used-length checks. A record may fill capacity exactly, leaving no readable spare byte guaranteed for the reverse scanner that starts at x6C. Initial/reset zero filling supplies a sentinel only while spare capacity remains.',
12:'Canonical signature s32(HSD_Text* text,s32 flags). Low seven bits select types1-5; bit7 controls deletion only. Type1 restores two signed s16/256 spacing values, type3 two unsigned u16/256 scale values, type2 RGB without alpha, type4 alignment, and type5 returns a signed32-bit cursor bit pattern. Typed loads can be unaligned and require valid buffer layout.',
14:'Starts by reading string_buffer[x6C], not x6C-1. It scans backward by trailing type and payload width, restores the first matching low-seven-bit type and stops even when bit7 differs. Equal high bits additionally compact/delete the record and zero the vacated tail. A normal no-match returns zero. There is no capacity, record-start or alignment validation; exact fill can read past the allocation, and malformed trailing types can move payload reads below zero.',
15:'Accumulates a line fragment using x80.x times nominal32+spacing, subtracting scaled left+right-2 when kerning is enabled; opcode26 contributes16+spacing. Height starts at32*x80.y and tracks larger encountered glyph heights. At termination it subtracts the current x78.x once without multiplying by x80.x. Thus empty input can return negative width and trailing-spacing correction does not generally match a fully scaled advance. Custom metrics use sis->textures bytes.',
16:'Provides line measurements used by the renderer for alignment and fit-to-box. It emits dimensions rather than GX geometry, but its raw trailing-spacing subtraction and partial state restoration mean it is not a general pure or exact final-geometry measurement API.',
19:'Measures one SIS line fragment until boundary opcodes or a terminal return, applying selected scale/spacing/kerning controls and following embedded pointers. It writes width and maximum nominal glyph height without drawing. Measurement can allocate or mutate the auxiliary stack and does not restore every field it can affect.',
20:'Opcodes1,2,3,7 terminate the walk; opcode0 resumes a type5 continuation when nonzero, otherwise exits. Other commands change temporary scale/spacing, local kerning or cursor. Exit restores x80.x/y, x78.x and x6C and zeroes from restored length to capacity. It does not restore x78.y, which a type1 restore can change. Buffer allocation and lower stack bytes are not rolled back. Cursor cycles, truncated operands and absent custom metric data have no guards.',
21:'GObj mode reads text user data and optional font-slot resources; direct mode receives text through pass and leaves custom-resource locals NULL. SIS field named textures supplies custom metric bytes and field named kerning supplies custom texture bytes, contrary to their names. Glyphs use 32-by-32 I4 texture blocks and colored GX quads. Optional clipping changes positions/UVs, but horizontal UV divisions use glyph_w before fit factor x88 even though quad width includes that factor.',
26:'GObj mode rejects passes other than2; hidden or NULL-SIS text skips work. x60 with x4B stops, while x60 with x94 decrements the countdown and stops. Replay skip count avoids advancing already processed items. Opcode6 loads locals from x90/x92 defaults; glyph/space progression uses the first delay, newline uses the second. Reset/restart may move sis_buffer and replace saved state. Exit invalidates HSD state cache and restores saved RGB, scale, spacing, modes and x6C, then clears the stack tail; it does not restore actual prior GX state, all text fields, or stack allocation.',
38:'Unconditionally delegates teardown. The delegate asserts non-NULL archive and HSD_ARCHIVE_DONT_FREE, frees archive->data-0x20 through heap0 and then frees the descriptor. It does not validate backing-image provenance or clear caller pointers. A malformed descriptor with NULL data passes the two stated guards but cannot supply a valid derived image base.',
39:'SIS commands, text fields and font resources feed measurement and drawing. Measurement returns line dimensions but may grow/mutate the stack and can change x78.y despite restoring x78.x/y scale and used length. Rendering updates cursor, delay, pause and progress while sending background/glyph geometry to GX; it restores a selected formatting subset and invalidates HSD state caches without restoring prior hardware state.'}
# Correct the explicit field list in the aggregate measurement description.
changes[39]=changes[39].replace('restoring x78.x/y scale and used length','restoring x80.x/y, x78.x and used length')
ranges={'.data':[(306,405),(634,939),(976,1127)],'.sdata2':[(49,54),(201,229),(303,407),(420,439),(503,526),(797,807)],'HSD_SisLib_803A7684':[(23,177),(179,271)],'HSD_SisLib_803A7F0C':[(179,272),(33,56)],'HSD_SisLib_803A8134':[(274,418)],'HSD_SisLib_803A84BC':[(420,553),(557,623),(624,815),(816,964)],'HSD_SisLib_803A945C':[(966,969)],'HSD_SisLib_803A947C':[(971,974)],'FILE':[(23,56),(179,272),(274,418),(420,553),(624,815),(816,974)]}
def ev(f,a,z):return {'kind':'code','locator':f'code://{rev}/{f}#L{a}-L{z}','why':'Pinned canonical implementation or bounded foreign consumer reviewed.'}
foreign={'.data':[(b+'hsd_3A64.c',137,219),(b+'sislib_font.h',6,10)],'HSD_SisLib_803A7684':[(b+'sislib.h',46,93),(b+'sislib.c',568,604)],'HSD_SisLib_803A7F0C':[(b+'sislib.h',46,93)],'HSD_SisLib_803A8134':[(b+'sislib.h',20,28)],'HSD_SisLib_803A84BC':[(b+'sislib.h',20,93),(b+'sislib.c',254,284),(b+'sislib.static.h',6,10),(b+'sislib_font.h',6,10)],'HSD_SisLib_803A945C':[('src/melee/lb/lbarchive.c',17,35),('src/melee/lb/lbarchive.c',58,74),(b+'archive.c',18,67)],'HSD_SisLib_803A947C':[('src/melee/lb/lbarchive.c',147,153)],'FILE':[(b+'sislib.c',254,284),(b+'sislib.h',20,93)]}
def evidence(sym):return [ev(src,a,z) for a,z in ranges[sym]]+[ev(f,a,z) for f,a,z in foreign.get(sym,[])]
props=[];disp=[]
for i,f in enumerate(facts):
 sym='FILE' if f['subject']==src else f['subject'].split(':')[-1];e=evidence(sym);d='supersede' if i in changes else 'retain';why='Full owned canonical and rendered EOF review; actual branches and bounded foreign consumers independently checked.'
 if sym.startswith('.') or sym=='FILE':why+=f' Existing objects and source arrays inventoried in compiled-evidence.json SHA-256 {eh}; no build or execution.'
 if f['type']=='inferred_name':why+=' Retained semantic hypothesis only, no canonical rename. Frozen baseline current-name lookup found no duplicate candidate; independent review remains required.'
 props.append({'subject':{'entity_locator' if sym=='FILE' else 'target_stable_key':f['subject']},'type':f['type'],'op':'write','value':changes.get(i,f['value']),'rationale':why,'confidence':min(f['confidence'],.97) if d=='supersede' else f['confidence'],'evidence':e})
 disp.append({'subject':f['subject'],'fact_id':f['id'],'updated_at':f['updated_at'],'version':f['updated_at'],'type':f['type'],'disposition':d,'action':why,'evidence':e})
for subject in task['writable_subjects']:
 k=subject.get('target_stable_key',subject.get('entity_locator'))
 if any(f['subject']==k for f in facts):continue
 sym=k.split(':')[-1].split('#')[0];disp.append({'subject':k,'fact_id':None,'updated_at':None,'version':None,'disposition':'retain','action':'No inherited facts; canonical parameter or data-section role inspected. No new fact proposed.','evidence':evidence(sym)})
(p/'proposal.json').write_text(json.dumps({'tu':tu,'proposal':{'facts':props,'links':[],'entities':[],'merges':[],'follow_ups':[]}},indent=2)+'\n')
lp=r/'baseline-links'/f"{task['id']}.json";links=json.loads(lp.read_text());ld=[]
for l in links:
 sym='FILE' if l['from_entity_id'] else l['from_target_id'].split(':')[-1];ld.append({'link_id':l['id'],'baseline':l,'disposition':'retain','reason':'Current owned body and inspected consumers/delegates support the stored relationship. Bounds and partial-restoration limitations are recorded separately; no stronger safety or purity claim is implied.','evidence':evidence(sym)})
(p/'link-dispositions.json').write_text(json.dumps({'tu':tu,'revision':rev,'baseline_path':str(lp),'baseline_sha256':hashlib.sha256(lp.read_bytes()).hexdigest(),'link_count':len(ld),'retained':len(ld),'rejected':0,'unresolved':0,'db_link_changes':False,'links':ld},indent=2)+'\n')
asset={'path':'build/GALE01/include/sysdolphin/baselib/sislib_font.inc','bytes':881664,'sha256':'10fd9b518f8f71285e857aa92c68d603a3ad986ee41c2db5ea0049f29efeb847','owner':'main/sysdolphin/baselib/sislib_font','status':'excluded_foreign_generated_asset','inspection':'Hashed only; no glyph artwork or generated byte source review claimed.'}
reads=[json.loads(x) for x in (state/'reads.jsonl').read_text().splitlines()];start=min(x['at'] for x in reads if x.get('reader')=='hsd3A76_complete_review');end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');files=[dict(f,canonical_ranges=[[1,f['lines']]],rendered_ranges=[[1,f['lines']]]) for f in m['files'] if f['path'] in task['files']];fr=json.loads((p/'foreign-ranges.json').read_text())
cov={'tu':tu,'subjects':disp,'files':files,'started_at':start,'research_start':start,'research_end':end,'completed_at':end,'fact_count':len(facts),'reviewed_subject_count':len(task['writable_subjects']),'fact_version_kind':'updated_at','render_exceptions':['One parser error in each page metadata; M2C_BITWISE call at line473 marked parse_uncertain. Canonical text and both MUST_MATCH branches inspected.'],'render_metadata':{'source':{'parse_errors':1,'substitutions_by_page':[1,8,1,14,4,0],'next_line':None}},'foreign_reads':[{'path':f,'canonical_ranges':rs} for f,rs in fr.items()],'links_reviewed':len(ld),'link_dispositions':'link-dispositions.json','excluded_assets':[asset],'owned_header_coverage':[]};(p/'coverage.json').write_text(json.dumps(cov,indent=2)+'\n')
summary={'tu':tu,'status':'draft_pending_independent_review','started_at':start,'research_start':start,'research_end':end,'completed_at':end,'files_reviewed':1,'canonical_lines':1128,'rendered_lines':1128,'subjects_reviewed':len(task['writable_subjects']),'existing_facts_reviewed':len(facts),'retained_facts':len(facts)-len(changes),'superseded_facts':len(changes),'new_facts':0,'proposal_facts':len(props),'retained_name_hypotheses':6,'proposed_names':0,'clears':0,'compiled_evidence_sha256':eh,'report_sha256':m['report_sha256'],'proposal_sha256':hashlib.sha256((p/'proposal.json').read_bytes()).hexdigest(),'links_reviewed':len(ld),'links_retained':len(ld),'links_rejected':0,'links_unresolved':0};(p/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
(p/'unresolved.json').write_text(json.dumps({'tu':tu,'items':[{'topic':'Font fields','status':'family_type_followup','detail':'SIS names are semantically inverted in renderer: kerning supplies texture bytes, textures supplies metric bytes. Preserve declarations pending independent family review.'},{'topic':'State buffer invariants','status':'source_observed','detail':'Reverse scan reads x6C; exact capacity fill lacks spare sentinel. Growth and indices truncate to u16; malformed stacks/unaligned payload reads not validated.'},{'topic':'Measurement side effects','status':'source_observed','detail':'Only x78.x restored; type1 restore can change x78.y. Stack length reset does not restore overwritten lower records or allocation. Width subtracts unscaled trailing spacing.'},{'topic':'Renderer limits','status':'source_observed','detail':'Fitted horizontal UV clipping uses unfitted denominator. Custom glyphs lack required data in direct mode. No stream/glyph bound or cyclic-jump guard. MUST_MATCH matrix stack offsets not runtime validated.'},{'topic':'Foreign generated font','status':'excluded','asset':asset}]},indent=2)+'\n')
(p/'naming.md').write_text('# Naming Review\n\nSix inherited hypotheses retained pending independent review. No current candidate collision found in frozen baseline. No canonical names changed.\n\n| Canonical | Hypothesis | Disposition |\n|---|---|---|\n'+''.join(f"| {f['subject'].split(':')[-1]} | {f['value']} | retain hypothesis |\n" for f in facts if f['type']=='inferred_name')+'\nRestoreTextState accurately avoids implying unconditional deletion: bit7 mismatch still restores. CalcTextSize is a line-fragment measurement with side effects. Canonical sisFitLineToBox and HSD_SisLib_GlyphWidth are inspected helpers, not new proposed identities.\n')
print(json.dumps(summary))
