from pathlib import Path
import json,hashlib,datetime
p=Path(__file__).parent;r=Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');m=json.loads((r/'manifest.json').read_text());tu='main/sysdolphin/baselib/hsd_4D11';t=next(t for t in m['tasks'] if t['tu']==tu);s=r/'units'/t['id'];src=t['source_path'];rev=m['head_revision'];facts=json.loads((p/'baseline-facts.json').read_text());eh=hashlib.sha256((p/'compiled-evidence.json').read_bytes()).hexdigest()
def ev(f,a,b):return {'kind':'code','locator':f'code://{rev}/{f}#L{a}-L{b}','why':'Owned definitions or independently inspected external declaration and consumer.'}
b='src/sysdolphin/baselib/'
values={('.bss','inferred_type'):'A 9564-byte NOBITS allocation with five global objects in linked order: hsd_804D1138 size 0x10 at offset 0; hsd_804D1148 size 0x1200 at 0x10; hsd_804D2348 size 0x300 at 0x1210; hsd_804D2648 size 0x828 at 0x1510; hsd_804D2E70 size 0x824 at 0x1D38. The definition of hsd_804D2648 is a u8 backing array; the JPEG encoder overlays JpegWork, which includes a jmp_buf at offset zero and coefficient/DC work fields. It is not merely jmp_buf-sized storage.',('.sbss','inferred_type'):'A 32-byte NOBITS allocation containing eight global s32 objects in increasing-address order hsd_804D7980 through hsd_804D799C. The first two are declared volatile. Card consumers use these as command/queue cursors and control/status words. Both existing source and split sections are eight-byte aligned with ALLOC|WRITE flags; zero-initialized storage does not describe later reset values.',('FILE','inferred_type'):'A data-only C translation unit defining five bulk arrays and eight s32 globals, with no functions or owned header. Existing source and split objects agree on 9564-byte .bss and 32-byte .sbss layouts. Consumers reinterpret the bulk storage as card context/command queues and a JPEG encoder JpegWork overlay; canonical hsd_804D2648 remains declared u8[0x828], while the shared header exposes only a __jmp_buf view.',('FILE','purpose'):'Owns shared card work-area storage and JPEG encoder scratch storage outside hsd_3A94.c. Its source comment attributes the split to extern-reference matching requirements. Existing card-object relocations independently reference named hsd_804D1138, hsd_804D1148 and hsd_804D2348 symbols; the JPEG object references hsd_804D2648. This review verifies the current separation and relocation form, without rebuilding an alternative combined translation unit.'}
evidence=[ev(src,1,25),ev(b+'hsd_3A94.c',74,112),ev(b+'hsd_3A94.c',5255,5269),ev(b+'hsd_3A94.h',85,89),ev(b+'hsd_3B34.c',11,23),ev(b+'hsd_3B34.c',530,555),ev(b+'hsd_3B34.c',1053,1067)]
props=[];disp=[]
for f in facts:
 sym='FILE' if f['subject']==src else f['subject'].split(':')[-1]
 props.append({'subject':{'entity_locator' if sym=='FILE' else 'target_stable_key':f['subject']},'type':f['type'],'op':'write','value':values[(sym,f['type'])],'rationale':f'Full owned canonical/rendered EOF read and bounded card/JPEG consumers inspected. Current existing object layouts and named external relocations independently verified; compiled-evidence.json SHA-256 {eh}. Do not confuse byte backing declaration with consumer overlay or comment history with a rebuilt matching experiment.','confidence':.98,'evidence':evidence})
 disp.append({'subject':f['subject'],'fact_id':f['id'],'updated_at':f['updated_at'],'version':f['updated_at'],'type':f['type'],'disposition':'supersede','action':'Refine exact layout, declaration-versus-overlay and current relocation evidence','evidence':evidence})
(p/'proposal.json').write_text(json.dumps({'tu':tu,'proposal':{'facts':props,'links':[],'entities':[],'merges':[],'follow_ups':[]}},indent=2)+'\n')
lp=r/'baseline-links'/f"{t['id']}.json";links=json.loads(lp.read_text());ld={'tu':tu,'revision':rev,'baseline_path':str(lp),'baseline_sha256':hashlib.sha256(lp.read_bytes()).hexdigest(),'link_count':len(links),'retained':1,'rejected':0,'unresolved':0,'db_link_changes':False,'links':[{'link_id':l['id'],'baseline':l,'disposition':'retain','reason':f'Canonical comment explains the isolated-TU extern-addressing requirement, and separate definitions/declarations establish it. Existing consumer relocations directly reference the named symbols, documented in compiled-evidence.json SHA-256 {eh}. Retain the compiler-addressing relationship in this bounded sense; no alternate build or historical PR experiment reproduced.','evidence':[ev(src,1,16),ev(b+'hsd_3A94.c',103,112),ev(b+'hsd_3A94.c',5255,5269)]} for l in links]};(p/'link-dispositions.json').write_text(json.dumps(ld,indent=2)+'\n')
reads=[json.loads(x) for x in (s/'reads.jsonl').read_text().splitlines()];start=min(x['at'] for x in reads if x.get('reader')=='hsd4d11_complete_review');end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z')
foreign={'hsd_3A94.c':[[30,112],[580,604],[5255,5280],[5325,5352]],'hsd_3A94.h':[[74,92]],'hsd_3B34.c':[[1,40],[530,555],[1053,1067]]}
cov={'tu':tu,'subjects':disp,'files':[dict(f,canonical_ranges=[[1,26]],rendered_ranges=[[1,26]]) for f in m['files'] if f['path'] in t['files']],'started_at':start,'research_start':start,'research_end':end,'completed_at':end,'fact_count':4,'reviewed_subject_count':3,'fact_version_kind':'updated_at','render_exceptions':[],'render_metadata':{'source':{'parse_errors':0,'substitutions':0,'next_line':None}},'owned_header_coverage':[],'header_status':'No owned header in exact manifest','foreign_reads':[{'path':b+f,'canonical_ranges':rs} for f,rs in foreign.items()],'search_exceptions':['Broad symbol-use rg output truncated; not counted as full foreign-file coverage. Bounded consumer ranges read separately.'],'links_reviewed':1,'link_dispositions':'link-dispositions.json'};(p/'coverage.json').write_text(json.dumps(cov,indent=2)+'\n')
summary={'tu':tu,'status':'draft_pending_independent_review','started_at':start,'research_start':start,'research_end':end,'completed_at':end,'files_reviewed':1,'canonical_lines':26,'rendered_lines':26,'subjects_reviewed':3,'existing_facts_reviewed':4,'retained_facts':0,'superseded_facts':4,'new_facts':0,'proposal_facts':4,'proposed_names':0,'clears':0,'compiled_evidence_sha256':eh,'report_sha256':m['report_sha256'],'proposal_sha256':hashlib.sha256((p/'proposal.json').read_bytes()).hexdigest(),'links_reviewed':1,'links_retained':1,'links_rejected':0,'links_unresolved':0};(p/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
(p/'unresolved.json').write_text(json.dumps({'tu':tu,'items':[{'topic':'Legacy type views','status':'family_followup','detail':'hsd_3A94.h declares hsd_804D2648 as __jmp_buf while definition is u8[0x828] and JPEG consumers cast it to JpegWork. Card consumers likewise overlay adjacent bulk symbols with CardContext. Definitions remain unchanged.'},{'topic':'Final bulk array','status':'bounded_review','detail':'hsd_804D2E70 size/address is verified; direct semantic consumer role was not established in inspected card/JPEG ranges. Do not assign a specific buffer purpose.'},{'topic':'Matching rationale','status':'source_attested','detail':'Current named external relocation form independently confirmed. Counterfactual matching effect of merging TUs was not tested.'},{'topic':'JPEG terminology','status':'corrected_in_draft','detail':'Owned comment says decoder, but inspected JpegWork consumer encodes JPEG components and emits JPEG output. Proposals use encoder.'}]},indent=2)+'\n')
(p/'naming.md').write_text('# Naming Review\n\nAll thirteen global identifiers and both section target names stay canonical. No inherited or new inferred-name facts. JpegWork is a consumer overlay name, not a replacement for the u8 backing definition.\n')
(p/'functionality.md').write_text(f'''# Card and JPEG Work Storage\n\nPinned revision `{rev}`. This TU defines storage only, with no functions or owned header. Existing source/split objects agree on NOBITS .bss size 9564 and .sbss size 32, both aligned to eight bytes.\n\n## Bulk Layout\n\n| Symbol | Offset | Bytes | Evidence-backed role |\n|---|---:|---:|---|\n| hsd_804D1138 | 0 | 16 | CardContext leading fields |\n| hsd_804D1148 | 0x10 | 4608 | 128 rows of nine u32 words, matching CardCmd area |\n| hsd_804D2348 | 0x1210 | 768 | 32 card queue records in consumer overlay |\n| hsd_804D2648 | 0x1510 | 2088 | Byte backing for JPEG encoder JpegWork/jump environment |\n| hsd_804D2E70 | 0x1D38 | 2084 | Byte array; specific role deferred |\n\nConsumer CardContext spans the first three adjacent symbols through casts from hsd_804D1138. This describes the existing target layout, not portable C object-bounds validation. The JPEG header exposes only __jmp_buf, while encoder code uses the larger JpegWork union including coefficient and prior-DC fields. The owned comment says decoder; inspected code encodes JPEG components.\n\n## Small State and Lifetime\n\nEight s32 objects run from hsd_804D7980 through hsd_804D799C. The first two are volatile and track command positions in card consumers. Queue cursors hsd_804D7990/94 advance modulo 32. Reset code clears those cursors and the queue, clears both command cursors, writes hsd_804D799C=2, clears the first word of each command row and clears hsd_804D7988. Initial NOBITS zero state therefore differs from explicit subsystem reset. Detailed roles outside the inspected consumer ranges remain with the card TU review.\n\n## Addressing and Provenance\n\nThe source comment documents separate-TU placement for extern-reference matching. Existing card object contains 22 named relocations to hsd_804D1138, eight to hsd_804D1148 and four to hsd_804D2348; existing JPEG object has twelve to hsd_804D2648. This verifies current named external addressing. No compile, matching experiment or alternate merged TU was performed. The single inherited compiler-addressing link is retained with this qualification.\n\nCompiled companion SHA256 `{eh}`. Canonical/rendered lines 1-26 reached EOF with zero errors/substitutions. Immutable page and read receipt are under `{s}`. proposal.json carries pinned canonical citations; coverage.json accounts for every fact and foreign read; link-dispositions.json preserves the exact outgoing record.\n''')
print(json.dumps(summary))
