import json,pathlib,hashlib,datetime,collections,struct
D=pathlib.Path(__file__).parent;S=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');M=json.load(open(S/'manifest.json'));R=M['head_revision'];root=pathlib.Path(M['checkout_root']);tu='main/melee/ft/ftCo_800C739C';P='src/melee/ft/ftCo_800C739C.c';C=json.load(open(D/'context.json'));X=json.load(open(D/'baseline-facts.json'));start='2026-09-08T14:55:09Z'
def c(p,a,b):return f'code://{R}/{p}#L{a}-L{b}'
foreign=[('src/melee/ft/ftCo_800C7070.c',1,13),('src/melee/ft/ftdata.c',157,167),('src/melee/ft/ftdata.c',368,380),('src/melee/ft/ftdemo.c',42,138),('src/melee/ft/kinds/ftKirby/ftkirby.c',2463,2504),('src/melee/ft/types.h',853,883),('src/melee/ft/fighter.c',1177,1181),('src/melee/ft/fighter.c',1370,1374),('src/melee/ft/kinds/ftCommon/forward.h',292,308),('src/melee/ft/ftmotionstates.c',3887,4028)]
fr=[]
for p,a,b in foreign:
 t=(root/p).read_text();fr.append(dict(path=p,start_line=a,end_line=b,sha256=hashlib.sha256(t.encode()).hexdigest(),canonical_read=True,rendered_read=False,ownership='foreign evidence only'));(D/(p.replace('/','__')+f'.{a}-{b}.txt')).write_text('\n'.join(f'{i}: {l}' for i,l in enumerate(t.splitlines(),1) if a<=i<=b))
E=[c(P,9,42)]+[c(p,a,b) for p,a,b in foreign]
report=root/'build/GALE01/report.json';rh=hashlib.sha256(report.read_bytes()).hexdigest();assert rh==M['report_sha256'];u=next(u for u in json.load(open(report))['units'] if u['name']==tu);objects=[]
for typ in ['src','obj']:
 p=root/f'build/GALE01/{typ}/melee/ft/ftCo_800C739C.o';b=p.read_bytes();e='>' if b[5]==2 else '<';off=struct.unpack_from(e+'I',b,32)[0];sz,n,si=struct.unpack_from(e+'HHH',b,46);sh=[struct.unpack_from(e+'10I',b,off+i*sz) for i in range(n)];st=sh[si];names=b[st[4]:st[4]+st[5]]
 for s in sh:
  if names[s[0]:].split(b'\0')[0]==b'.sdata2':objects.append(dict(path=str(p),sha256=hashlib.sha256(b).hexdigest(),section='.sdata2',size=s[5],bytes_hex=b[s[4]:s[4]+s[5]].hex(),float_values=list(struct.unpack(e+'2f',b[s[4]:s[4]+s[5]]))))
json.dump(dict(report_path=str(report),report_sha256=rh,pinned_report_hash_matches=True,unit=u,objects=objects),open(D/'section-evidence.json','w'),indent=2)
O={}
def w(s,t,v):O[(s,t)]=v
entry='Selects state ID 17 (spelled ftCo_MS_WalkFast) for Kirby and delegates all other kinds to ftCo_800C7070, which selects ID 13 (spelled RebirthWait). Both paths enter at frame 0, speed 1, blend 0 and flags 0, then set x2219_b2 and x2219_b1. In the demonstrated demo caller, alternate motion tables map these IDs to Kirby JumpB and common Run, respectively.'
w('ftCo_800C739C','inferred_name','ftCo_DemoEnterKirbyJumpBOrRun')
w('ftCo_800C739C','data_flow',entry)
w('ftCo_800C739C','purpose','Initializes demo mode 14: selects the Kirby-specific motion-table slot for JumpB, or delegates other fighters to the common Run slot. The function passes the numerically reused WalkFast/RebirthWait enum values; their actual animation meaning depends on the active tables.')
w('ftCo_800C739C','game_mapping','The demonstrated use is demo-fighter creation callback index 14. Demo creation installs a 14-entry common table and character-specific extension; state 17 selects Kirby extension index 3 (JumpB), while fallback state 13 selects common Run. This is not evidence of ordinary walking or revival-platform respawn.')
w('ftCo_800C739C','state_behavior','Immediately branches on Fighter.kind. Kirby changes to state ID 17 with flags 0, frame 0, speed 1, blend 0 and NULL alternate source, then sets both x2219 flags. Other kinds return through ftCo_800C7070, which applies the same entry parameters and writes for ID 13. The installed motion tables determine animation and callbacks; no local timer or frame guard exists.')
w('ftCo_800C7414','inferred_name','ftCo_DemoKirbyJumpB_Phys')
w('ftCo_800C7414','purpose','Physics adapter registered in Kirby alternate motion-table index 3 (JumpB). It delegates to ft_8008521C to overwrite self velocity with model-root translation minus fighter position.')
w('ftCo_800C7414','game_mapping','Supplies root-displacement-driven self velocity for the Kirby JumpB entry in the alternate table installed by demo creation. No revival-platform respawn behavior is established by this registration.')
w('ftCo_800C7414','state_behavior','Every invocation unconditionally delegates to ft_8008521C, which recomputes all three self_vel components. This wrapper has no local guard, timer or state transition. The companion entry routine selects state ID 17 for Kirby or delegates to ID 13 for other kinds; demo tables map those IDs to JumpB and Run.')
w('.sdata2','game_mapping','Configures the Kirby branch motion transition at frame zero, speed one and zero blend. The demonstrated demo table maps its numeric state to JumpB rather than the ordinary WalkFast animation.')
w('.sdata2','purpose','Provides pooled 0.0F and 1.0F literals used by the Kirby branch of the demo motion-entry adapter.')
w('source','data_flow',entry+' The second routine delegates root-displacement-to-self-velocity conversion to ft_8008521C.')
w('source','game_mapping','Supports demo-fighter mode 14 with Kirby alternate-table JumpB and common Run fallback. Enum tokens reuse ordinary common-state numbers but do not establish ordinary walking or rebirth behavior under the alternate tables.')
w('source','purpose','Houses the demo mode 14 motion-entry dispatcher and the root-displacement physics adapter used by its Kirby JumpB entry.')
w('source','state_behavior','The entry routine immediately branches on kind and chooses numeric state 17 for Kirby or delegates state 13 for other fighters, with frame 0, speed 1, blend 0 and both x2219 flags set. Active demo tables resolve these to JumpB and Run. The physics wrapper has no local guard or transition.')
rows=[];disp=[];facts=[]
for s in X:
 key=next(iter(s['subject'].values()));name='source' if key==P else key.split(':')[-1];ev=E
 if not s['facts']:rows.append(dict(subject=s['subject'],status='reviewed_no_existing_facts',reason='Single gobj source parameter reviewed; no register mapping promoted.'));continue
 rows.append(dict(subject=s['subject'],status='reviewed',fact_count=len(s['facts']),evidence=ev))
 for f in s['facts']:
  new=O.get((name,f['type']));reason='Existing canonical operation retained without citation-only rewriting.' if new is None else 'Demo caller installs alternate motion tables; ordinary-state enum spelling does not establish the selected animation or a respawn purpose.'
  if name=='.sdata2' and new is None:reason='Existing object sections both contain exactly eight bytes 000000003f800000; pinned report confirms .sdata2 size 8 and canonical call uses 0/1 floats.'
  disp.append(dict(subject=s['subject'],fact_id=f['id'],version=f['updated_at'],type=f['type'],old_value=f['value'],disposition='retain' if new is None else 'supersede',reason=reason,replacement=new,evidence=ev))
  if new:facts.append(dict(subject=s['subject'],type=f['type'],op='write',value=new,rationale=reason,confidence=0.94,evidence=[dict(kind='code',locator=e,why=reason) for e in ev]))
end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');reads=[json.loads(l) for l in open(S/'units/main__melee__ft__ftCo_800C739C/reads.jsonl') if json.loads(l).get('reader')=='ftCo_800C739C'];counts=dict(collections.Counter(d['disposition'] for d in disp))
json.dump(dict(tu=tu,proposal=dict(facts=facts,links=[],entities=[],merges=[],follow_ups=[])),open(D/'proposal.json','w'),indent=2)
json.dump(dict(revision=R,start_utc=start,end_utc=end,counts=counts,dispositions=disp),open(D/'fact-dispositions.json','w'),indent=2)
json.dump(dict(campaign=M['campaign_id'],tu=tu,revision=R,role='TU librarian',model=M['model'],reasoning_effort=M['reasoning_effort'],start_utc=start,end_utc=end,input_files=C['files'],canonical_and_rendered_receipts=reads,foreign_evidence_reads=fr,subjects=rows,counts=dict(targets=3,source_entities=1,parameter_entities=2,existing_facts=len(disp),proposal_facts=len(facts),owned_lines=53),exceptions=[],section_evidence='section-evidence.json'),open(D/'coverage.json','w'),indent=2)
json.dump(dict(unresolved=['The user-facing demo scene meaning of allocation mode 14 is not established; names describe the verified table mapping only.'],family_followups=['Shared MotionState layout and demo state tables were read as foreign evidence only; no shared subjects proposed.']),open(D/'unresolved.json','w'),indent=2)
(D/'functionality.md').write_text(f'# Demo mode 14 fighter adapters\n\nDraft at `{R}`.\n\n`ftCo_800C739C` is callback 14 in demo fighter creation. That creator sets the common-table length to 14, installs the demo common table and per-character alternate table, then invokes the selected callback. Kirby enters numeric state 17, so the motion resolver indexes Kirby extension entry 3. That entry uses JumpB and registers `ftCo_800C7414` as physics. Other fighters delegate to state 13, the common demo Run entry. The source spells these IDs WalkFast and RebirthWait, but those enum names do not describe the alternate-table animations.\n\nBoth entry paths request flags 0, frame 0, speed 1, blend 0 and NULL alternate source, then set x2219_b2 and x2219_b1. The three local inline functions form a forwarding chain only. `ftCo_800C7414` unconditionally forwards gobj to `ft_8008521C`, which sets each self_vel component to model-root translation minus cur_pos. No local timers or additional guards exist.\n\nThe paired header agrees with both definitions. Both existing object files contain an eight-byte .sdata2 with IEEE float 0 and 1; the report hash equals the frozen manifest hash. No build was run. These literals configure the Kirby entry call; they are not independent gameplay data.\n\n## Canonical evidence\n\n'+ '\n'.join('- '+e for e in E)+'\n')
(D/'naming.md').write_text('# Naming review\n\n| Canonical | Existing hypothesis | Proposed hypothesis | Reason |\n|---|---|---|---|\n| ftCo_800C739C | ftCo_KirbyWalkFast | ftCo_DemoEnterKirbyJumpBOrRun | Demo tables map IDs 17/13 to JumpB/Run. |\n| ftCo_800C7414 | ftCo_RebirthWait_KirbyWalkFast_Phys | ftCo_DemoKirbyJumpB_Phys | Actual callback registration is Kirby alternate JumpB entry. |\n\nBoth proposals remain inferred names requiring independent review. Source names are unchanged. .sdata2 and source entity require no proposed-name fact. Local inlineB0/B1/B2 have no manifest subjects and only forward the fallback.\n')
(D/'README.md').write_text(f'# ftCo_800C739C review packet\n\nRevision `{R}`. UTC `{start}` to `{end}`. Model `{M["model"]}`, role TU librarian.\n\nComplete canonical and rendered coverage: C1-43, H1-10. Three targets, source entity and two empty parameter entities covered; {len(disp)} fact IDs/versions accounted for. Dispositions: {counts}. {len(facts)} proposed corrections, pending independent review. No failed/empty renders and zero parser errors.\n\nRead functionality.md and naming.md, inspect proposal.json, and use coverage.json, fact-dispositions.json, section-evidence.json and unresolved.json for audit. No canonical source, shared KB or build edits.\n')
print(counts,'writes',len(facts),'end',end)
