import json,pathlib,re,hashlib,datetime,collections
D=pathlib.Path(__file__).parent;S=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');m=json.load(open(S/'manifest.json'));R=m['head_revision'];P='src/melee/ft/ftaction.c';tu='main/melee/ft/ftaction';src=(pathlib.Path(m['checkout_root'])/P).read_text().splitlines();X=json.load(open(D/'baseline-facts.json'));start='2026-09-08T14:33:11Z'
def c(p,a,b):return f'code://{R}/{p}#L{a}-L{b}'
foreign=[('src/melee/lb/inlines.h',1,23),('src/melee/ft/ftanim.c',1036,1081),('src/melee/ft/ftanim.c',1257,1288),('src/melee/ft/ftcommon.c',1035,1154),('src/melee/ft/ftcommon.c',1158,1240),('src/melee/ft/ftcolanim.c',15,127),('src/melee/ft/ftcolanim.c',197,278),('src/melee/ft/ft_0C88.c',78,109),('src/melee/ft/ft_081B.c',1243,1310),('src/melee/ft/fighter.c',1299,1399),('src/melee/ft/fighter.c',2648,2669),('src/melee/ft/ftdynamics.c',485,523),('src/melee/ft/ftdynamics.c',585,603),('src/melee/ft/ft_0899.c',67,245),('src/melee/ft/ft_0DF0.c',16,46),('src/melee/lb/lb_013B.c',213,253),('src/melee/lb/types.h',586,662),('src/melee/lb/types.h',819,923),('src/melee/it/kinds/itsword.c',77,177),('src/melee/ft/kinds/ftPurin/ftpurin.c',503,531),('src/sysdolphin/baselib/rumble.c',32,81),('src/melee/lb/lb_00F9.c',939,991),('src/melee/lb/lb_00F9.c',1060,1104)]
fr=[]
for p,a,b in foreign:
 text=(pathlib.Path(m['checkout_root'])/p).read_text();fr.append({'path':p,'start_line':a,'end_line':b,'sha256':hashlib.sha256(text.encode()).hexdigest(),'canonical_read':True,'rendered_read':False,'ownership':'foreign evidence only'});(D/(p.replace('/','__')+f'.{a}-{b}.txt')).write_text('\n'.join(f'{i}: {s}' for i,s in enumerate(text.splitlines(),1) if a<=i<=b))
F=lambda p,a,b:[c('src/melee/'+p,a,b)]
EF={
'800726F4':F('ft/ftanim.c',1036,1068),'800727C8':F('ft/ftanim.c',1257,1274)+F('lb/types.h',586,591),'8007283C':F('ft/ftanim.c',1257,1274),'80072894':F('ft/ftcommon.c',1045,1121)+F('lb/types.h',592,596),'800728F8':F('ft/ftcommon.c',1158,1179)+F('lb/lb_013B.c',244,248),'8007297C':F('ft/ftcommon.c',1181,1186)+[c('src/sysdolphin/baselib/rumble.c',67,81)],'800729D4':F('ft/ftcommon.c',1213,1233)+F('it/kinds/itsword.c',77,149)+F('lb/types.h',607,612),'80072A5C':F('ft/ftcolanim.c',113,127)+F('lb/lb_013B.c',224,236),'80072ABC':F('ft/ftcolanim.c',197,227),'80072B14':F('lb/types.h',622,625),'80072B94':F('ft/ftdynamics.c',485,523),'80072BF4':F('ft/fighter.c',2648,2669)+F('lb/types.h',635,638),'80072C6C':F('ft/ft_0899.c',73,245),'80072CB0':F('ft/kinds/ftPurin/ftpurin.c',508,522)+F('lb/types.h',643,646),'80072CD8':F('ft/ft_081B.c',1243,1304)+[c(P,574,658)],'80072E4C':F('ft/ft_081B.c',1243,1308)+[c(P,574,658)]+F('ft/ftcommon.c',1158,1164),'80073008':F('ft/ft_0DF0.c',16,26)+F('lb/types.h',893,901),'800730B8':F('ft/ft_0C88.c',85,109)+F('ft/ftcolanim.c',86,106)+F('ft/ftcolanim.c',267,278),'80073108':F('ft/ft_0C88.c',105,109)+F('ft/ftcolanim.c',86,106)+F('ft/ftcolanim.c',267,278),'80073118':F('ft/ftdynamics.c',585,602)+F('lb/lb_00F9.c',939,978)+F('lb/lb_00F9.c',1065,1080)}
O={}
def change(s,t,v,reason):O[(s,t)]=(v,reason)
change('8007296C','inferred_name','ftAction_SkipRumble','Same-slot alternate handler suppresses the ordinary rumble request; nonzero-frame motion entry invokes this path, so Throw is too specific.')
for typ,v in {'data_flow':'Receives gobj and mutable CommandInfo from the alternate command dispatcher, ignores fighter and payload, and advances cmd->u once.','game_mapping':'Suppresses scripted rumble on the alternate fighter-command path, including nonzero-frame motion-entry catch-up.','purpose':'Alternate-table counterpart of the one-word rumble request; consumes the event without requesting rumble.','state_behavior':'Advances cmd->u once without changing fighter fields, timing or throw_flags. ftAction_80073354 supplies alternate dispatch and handles throw_flags outside this callback.'}.items():change('8007296C',typ,v,'Removes unsupported throw-specific restriction; table pairing and nonzero anim_start caller establish alternate dispatch.')
change('800727C8','inferred_type','void(Fighter_GObj* gobj, CommandInfo* cmd), consuming one packed word. part_anim stores two signed 7-bit indices and an unsigned 12-bit timing operand; the timing operand converts to the callee float argument.','The timing field is an integer bitfield, not floating-point encoded.')
change('80072894','inferred_type','void(Fighter_GObj* gobj, CommandInfo* cmd), consuming one packed word. unk9 carries unsigned 13-bit status and duration operands, converted to the callee s32 and float arguments.','Distinguishes packed operand storage from callee parameter types.')
change('800729D4','inferred_type','void(Fighter_GObj* gobj, CommandInfo* cmd), consuming one packed word. unk12 contains an unsigned 2-bit selector, unsigned 10-bit duration and unsigned 14-bit scale operand. Subtype 0 converts scale with factor 1/256; subtype 1 ignores that operand.','The source scale field is unsigned, not signed fixed point.')
change('80072B14','inferred_type','void(Fighter_GObj* gobj, CommandInfo* cmd), consuming one packed word. The encoded unk15.unk1 operand is unsigned 26-bit and is assigned to Fighter.x221E_b1.','Source payload width is 26 bits, not one bit; destination naming does not establish operand width.')
change('80072B14','purpose','Sets Fighter.x221E_b1 from the command operand and advances cmd->u once.','Removes incorrect one-bit encoded operand claim.')
change('80072BF4','inferred_type','void(Fighter_GObj* gobj, CommandInfo* cmd). Consumes one packed word whose damage_amount is a signed 26-bit integer operand, converted to float for Fighter_TakeDamage_8006CC7C.','The float callee parameter does not make the packed command a floating-point encoding.')
change('80073008','inferred_type','void(Fighter_GObj* gobj, CommandInfo* cmd), consuming two packed words. The first stores unsigned 10-bit charge_frames and unsigned 16-bit charge_rate; the second stores unsigned 8-bit color_anim. Handler float locals convert these integer fields before the final call.','Canonical shared declaration disproves the floating-point-encoded payload claim; no shared type subject is changed.')
change('80072CB0','data_flow','Reads unk20.unk1, stores it in Fighter.x2225_b2, then advances cmd->u. The demonstrated downstream consumer is ftPr_Init_UnkMtxFunc0 in ftPurin: when fp->u.pr.x223C and this flag are set, it copies the left-leg joint matrix to that auxiliary JObj and draws it.','The cited behavior belongs to Purin/Jigglypuff code, not Peach. Source now uses u.pr, not the older fv.pr wording.')
change('80072CB0','game_mapping','Controls a flag used by fighter auxiliary-model rendering. The demonstrated consumer is Purin/Jigglypuff, whose conditional auxiliary JObj follows FtPart_LLegJA and is rendered when x2225_b2 is set.','Corrects the mistaken Peach attribution with the canonical ftPurin consumer.')
change('80072CD8','state_behavior','Grounded valid-floor lookup may supply sound and graphics replacements; each replacement is accepted when its ID differs from -1. A zero control value skips the original three words. Otherwise the original command is delegated to ftAction_80071B50, which consumes three words for supported sound behaviors 0-6 and 10-15, but two for other behavior values.','Tests are != -1, not nonnegative. Unconditional three-word consumption was too broad because the sound delegate has a shorter default path.')
change('80072CD8','inferred_type','void(Fighter_GObj*, CommandInfo*), with nominal three-word footstep payload. Explicit skip consumes three words; sound-delegated advancement is three for supported sound behaviors and two for unrecognized behavior values.','Qualifies the prior every-terminal-path length assertion against the sound helper.')
change('80072E4C','game_mapping','Animation-scripted ground-contact feedback selects a surface-specific or embedded particle, conditionally emits default sound and command audio, and always attempts rumble through the guarded fighter rumble helper.','Rumble attempt is unconditional at the handler level, independent of default indicator; fighter eligibility still gates actual rumble.')
# Definitively unsupported game examples are retained in history but not promoted.
unresolved={('80072894','game_mapping'):'Parasol transition wiring is verified; detailed descent, floating and helplessness outcomes require item-state review.',('80072BF4','game_mapping'):'Self-damage operation is verified; Pichu/Agility move examples were not re-attested in this bounded source review.'}
normal=re.findall(r'ftAction_\w+', '\n'.join(src[174:187]));alternate=re.findall(r'ftAction_\w+', '\n'.join(src[190:203]));allnames=[next(iter(s['subject'].values())).split(':')[-1] for s in X if 'target_stable_key' in s['subject']]
rows=[];disp=[];proposal=[]
for s in X:
 key=next(iter(s['subject'].values()));name=key.split(':')[-1].split('#')[0];short=name.split('_')[-1]
 if 'entity_locator' in s['subject']:
  rows.append({'subject':s['subject'],'status':'reviewed_no_existing_facts','fact_count':0,'roles':'Parent function accepts Fighter_GObj* gobj and mutable CommandInfo* cmd. No register-to-source ABI claim promoted.'});continue
 a=next(i+1 for i,l in enumerate(src) if l.startswith('void '+name+'('));b=a
 while src[b-1]!='}':b+=1
 body='\n'.join(src[a-1:b]);skip=bool(re.fullmatch(r'void[^\n]+\n\{\n    (?:NEXT_CMD\(cmd\)|SKIP_CMD\(cmd, \d+\));\n\}',body))
 slots=[i for i,n in enumerate(normal) if n==name]+[i for i,n in enumerate(alternate) if n==name];slot=slots[0];paired=alternate[slot] if normal[slot]==name else normal[slot]
 ev=[c(P,a,b),c(P,174,210),c(P,1350,1388),c('src/melee/lb/inlines.h',8,19)]+EF.get(short,[])
 if skip:ev+=[c('src/melee/ft/fighter.c',1341,1348)]
 facts=s['facts'];purpose=next((f['value'] for f in facts if f['type']=='purpose'),'See canonical body.')
 if (short,'purpose') in O:purpose=O[(short,'purpose')][0]
 rows.append({'subject':s['subject'],'status':'reviewed','range':[a,b],'opcode':hex(slot+10),'counterpart':paired,'pure_skip':skip,'behavior':purpose,'evidence':ev,'fact_count':len(facts)})
 for f in facts:
  pair=(short,f['type']);old=f['value'];status='retain';reason='Canonical handler, same-slot table entry and cited dependencies support this existing claim.';replacement=None
  if pair in unresolved:status='unresolved';reason=unresolved[pair]
  if pair in O:status='supersede';replacement,reason=O[pair]
  disp.append({'subject':s['subject'],'fact_id':f['id'],'version':f['updated_at'],'type':f['type'],'old_value':old,'disposition':status,'reason':reason,'replacement':replacement,'evidence':ev})
  if replacement:proposal.append({'subject':s['subject'],'type':f['type'],'op':'write','value':replacement,'rationale':reason,'confidence':min(f['confidence'],0.95),'evidence':[{'kind':'code','locator':e,'why':reason} for e in ev]})
end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');counts=dict(collections.Counter(d['disposition'] for d in disp));reads=[json.loads(l) for l in open(S/'units/main__melee__ft__ftaction/reads.jsonl') if json.loads(l).get('reader')=='action_flags']
json.dump({'tu':tu,'proposal':{'facts':proposal,'links':[],'entities':[],'merges':[],'follow_ups':[]}},open(D/'proposal.json','w'),indent=2);json.dump({'campaign':m['campaign_id'],'revision':R,'start_utc':start,'end_utc':end,'dispositions':disp,'counts':counts},open(D/'fact-dispositions.json','w'),indent=2)
json.dump({'campaign':m['campaign_id'],'revision':R,'tu':tu,'cluster':'action_flags','start_utc':start,'end_utc':end,'input_files':json.load(open(D/'context.json'))['files'],'owned_range':[977,1317],'canonical_and_rendered_receipts':reads,'foreign_evidence_reads':fr,'subjects':rows,'counts':{'targets':33,'parameter_entities':66,'facts':185,'owned_lines':341,'proposal_facts':len(proposal)},'exceptions':[],'family_followups':['Shared bitfield layouts are cited only to correct owned handler claims; no shared subjects proposed.','Pichu move examples and full Parasol movement outcomes remain unverified.','Exact recovered function spellings remain hypotheses.']},open(D/'coverage.json','w'),indent=2)
md=f'# Action Flags and Presentation Handlers\n\nDraft. Revision `{R}`. UTC start `{start}`, end `{end}`. Owned lines 977-1317 have complete canonical and separate frozen rendered reads. 33 targets, 66 empty parameter entities and all 185 facts accounted for. No empty or failed renders; zero parser errors in owned pages. Supplemental interpreter, sound helper and table receipts are recorded separately.\n\n## Handler and Pair Findings\n\n'
for row in rows[:33]:md+=f"- `{next(iter(row['subject'].values())).split(':')[-1]}`, opcode `{row['opcode']}`, counterpart `{row['counterpart']}`. {row['behavior']} Evidence: {row['evidence'][0]}.\n\n"
md+='## Cross-Handler Invariants\n\nTexture animation, parasol dispatch, x221E_b1, ground-pose flags and x2225_b2 use the same callback in both fighter tables. Part animation is a modified alternate, forcing zero timing instead of suppressing all effects. Other paired alternate handlers in this cluster advance 1, 2, 3 or 4 command words without fighter/subsystem writes. Timing and throw_flags handling belong to the enclosing resolver. Nonzero-frame motion entry invokes the alternate resolver, so its handlers are not exclusively throw-script handlers.\n\nFootstep and impact replacement sound commands use a temporary cursor; changing it does not advance the original command. The original advances through the sound helper or explicit skips. The sound helper has an unrecognized-behavior path consuming only two words, so three-word terminal claims require valid behavior inputs. Footstep graphics are conditional; impact graphics and rumble requests are attempted unconditionally. The latter still passes through fighter rumble eligibility checks.\n\nWind operand labels are shifted relative to their roles: wind_fx_1.timer supplies x, wind_fx_1.x supplies y, wind_fx_2.y supplies magnitude, wind_fx_2.mag supplies decay, wind_fx_3.angle supplies integer duration, and wind_fx_3.decay supplies angular increment. Five floats use literal 0.003906, not exact 1/256. The handler advances four words before calling the dynamics helper.\n\n## Corrections and Retentions\n\n'+str(counts)+f'. Only {len(proposal)} corrections are proposed; valid facts are retained without rewriting. Corrections distinguish integer command storage from float call arguments, replace the wrong Peach auxiliary-model attribution with Purin/Jigglypuff, remove throw-only rumble naming, and qualify footstep length and rumble conditions. Shared field layouts are foreign evidence only. No new shared entity, link, merge or follow-up is proposed.\n'
(D/'findings.md').write_text(md);print(counts,'proposal',len(proposal),'end',end)
