import json,hashlib
from pathlib import Path
D=Path('docs/.drafts/melee-semantic-20260908/main__melee__lb__lb_0219'); M=Path('games/melee/state/knowledge_v2/semantic-sweep-20260908/manifest.json'); m=json.loads(M.read_text()); fs=json.loads((D/'functions.facts.json').read_text());tu='main/melee/lb/lb_0219'; path='src/melee/lb/lb_0219.c'
rows=[('fn_800219E4',27,30,'Forwards its user-data pointer to HSD_ObjFree with lbl_804336A0. Initialization registers this function as the manager GObj user-data removal callback.'),('lbBgFlash_80021A10',41,44,'Stores the supplied float in lbl_804D63D8. The process callback multiplies enabled overlay RGB channels by this value; alpha uses a separate byte multiplier. No clamping occurs here.'),('lbBgFlash_80021A18',46,69,'Initializes a 0x84-byte object allocator with alignment argument 4 and creates a GObj with arguments 0xE,0xE,0. On user-data allocation success, registers its removal callback, publishes the manager, sets RGB scale to 1, stores the low byte of arg0, loads lbBgFlashColAnimData from LbBf.dat, calls flash setup with 6 and the local overlay initialization wrapper, then installs fn_80021B04 at process argument 1. If user-data allocation fails, it passes the created GObj to HSD_GObjPLink_80390228.'),('fn_80021B04',81,105,'Saves the prior overlay color-enable flag and invokes fn_80021C80. While color output is enabled, scales RGB by lbl_804D63D8, computes alpha as overlay alpha times the initial user-data byte divided by 255, and submits GXColor to lbBgFlash_InitState. On an enabled-to-disabled transition calls fn_800208B0(0); continued disabled state makes no such call.'),('fn_80021C18',110,110,'Empty callback accepting HSD_GObj*, CommandInfo* and int. It reads and writes nothing, and fn_80021C80 supplies it to lb_80014258.'),('fn_80021C1C',112,117,'Reads the global manager GObj user_data and passes its embedded ColorOverlay at byte offset 4 to lb_80014498. It performs no null check and delegates all overlay mutation.'),('lbBgFlash_80021C48',119,126,'Reads the global manager pointer through the local BgFlashGlobal view and its x2C pointer, then passes the embedded ColorOverlay, the loaded lbBgFlashColAnimData pointer, and both u32 arguments to lb_800144C8. Argument meanings and acceptance rules are delegated.'),('fn_80021C80',128,138,'Repeatedly invokes lb_80014258 with the supplied GObj, its user-data ColorOverlay at offset 4, and the empty fn_80021C18 callback. Each nonzero result triggers lb_80014498 on that overlay before another interpreter call; a zero result ends the loop.')]
R={n:(a,b,v) for n,a,b,v in rows}
def ev(n):
 a,b,_=R[n]; ranges=[(a,b)]
 for x in {'fn_800219E4':[(51,56)],'lbBgFlash_80021A10':[(91,99)],'fn_80021C18':[(128,138)],'lbBgFlash_80021C48':[(57,61)]}.get(n,[]):ranges.append(x)
 return [{'kind':'code','locator':f'code://{m["head_revision"]}/{path}#L{a}-L{b}','why':'Canonical local definition and supporting registration or use establish this claim.'} for a,b in ranges]
# Foreign internals and caller mappings are not established by this TU.
retain={('fn_800219E4','inferred_type'),('fn_80021B04','inferred_type'),('fn_80021C1C','inferred_type'),('fn_80021C80','inferred_type'),('lbBgFlash_80021A10','data_flow'),('lbBgFlash_80021A10','inferred_type')}
name_retains={'fn_800219E4','fn_80021B04','fn_80021C80','lbBgFlash_80021A10','lbBgFlash_80021A18'}
replacements={('fn_800219E4','data_flow'):R['fn_800219E4'][2],('fn_800219E4','state_behavior'):'Unconditionally calls HSD_ObjFree with the allocator and pointer. The callback itself contains no null or ownership check. Allocator counters and caller cleanup are foreign implementation details.',('fn_80021B04','data_flow'):R['fn_80021B04'][2],('fn_80021B04','state_behavior'):R['fn_80021B04'][2],('fn_80021C18','data_flow'):R['fn_80021C18'][2],('fn_80021C18','inferred_type'):'Exact signature static void fn_80021C18(HSD_GObj* gobj, CommandInfo* cmd, int arg2). All arguments are unused; the function is passed to lb_80014258.',('fn_80021C18','state_behavior'):'The empty callback has no local state writes or return value. The caller interpreter determines whether and how commands progress.',('fn_80021C1C','data_flow'):R['fn_80021C1C'][2],('fn_80021C80','data_flow'):R['fn_80021C80'][2],('lbBgFlash_80021A18','data_flow'):R['lbBgFlash_80021A18'][2],('lbBgFlash_80021A18','inferred_type'):'Exact signature void lbBgFlash_80021A18(int arg0). Its low byte becomes user-data field x0, used by fn_80021B04 as the alpha multiplier divided by 255.',('lbBgFlash_80021A18','state_behavior'):R['lbBgFlash_80021A18'][2],('lbBgFlash_80021C48','data_flow'):R['lbBgFlash_80021C48'][2],('lbBgFlash_80021C48','inferred_type'):'Exact signature void lbBgFlash_80021C48(u32 arg0, u32 arg1). Both unsigned arguments are forwarded unchanged to lb_800144C8 with the overlay and loaded table.'}
proposal={'tu':tu,'proposal':{'facts':[],'links':[],'entities':[],'merges':[],'follow_ups':[]}}; dispositions=[]; targets=[]
for n,a,b,v in rows:
 s=tu+':'+n
 for f in fs[s]:
  typ=f['type']; d='unresolved'; reason='Claim depends on foreign helper internals, consumer rendering or caller-specific game mapping not independently read in this TU.'; replacement=None
  if typ=='purpose':d='supersede';replacement=v;reason='State exact local behavior and delegated limits.'
  elif (n,typ) in replacements:d='supersede';replacement=replacements[n,typ];reason='Replace inferred foreign details with directly supported local operations.'
  elif (n,typ) in retain:d='retain';reason='Local canonical source supports the type and data flow.'
  elif typ=='inferred_name' and n in name_retains:d='retain';replacement=f['value'];reason='Address-named canonical symbol remains authoritative; this reading aid is supported by local registration and use.'
  dispositions.append({'subject':{'target_stable_key':s},'fact_id':f['id'],'fact_version':{'updated_at':f['updated_at']},'type':typ,'prior_value':f['value'],'disposition':d,'reason':reason,'evidence':ev(n)})
  if replacement is not None:proposal['proposal']['facts'].append({'subject':{'target_stable_key':s},'type':typ,'op':'write','value':replacement,'rationale':reason,'confidence':f['confidence'] if typ=='inferred_name' else 0.96,'evidence':ev(n)})
 targets.append({'canonical_name':n,'stable_key':s,'range':[a,b],'summary':v,'evidence':ev(n),'inherited_names':[f['value'] for f in fs[s] if f['type']=='inferred_name']})
reads=[]
for ext,end in [('c',139),('h',22)]:
 p=M.parent/'units/main__melee__lb__lb_0219/pages'/f'src__melee__lb__lb_0219.{ext}.1-{end}.json';j=json.loads(p.read_text());r=j['rendered'];reads.append({'path':r['path'],'canonical_range':[1,end],'rendered_range':[1,end],'artifact':str(p),'artifact_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'source_sha256':r['source_sha256'],'status':r['status'],'next_line':r['next_line'],'parse_errors':r['parse_errors'],'substitutions':r['substitutions']})
findings={'campaign':m['campaign_id'],'tu':tu,'cluster':'functions','head_revision':m['head_revision'],'manifest_sha256':hashlib.sha256(M.read_bytes()).hexdigest(),'reads':reads,'exceptions':[],'targets':targets,'entity_subjects':[{'entity_locator':s,'facts':len(f),'disposition':'reviewed_empty'} for s,f in fs.items() if '#' in s],'fact_dispositions':dispositions,'uncertainty':['Exact lb_80014498 reset fields, lb_80014258 timing/completion behavior and lb_800144C8 profile arguments/priority require lb_013B family review.','Exact fn_800208B0(0) renderer result and lbBgFlash_InitState renderer mode require lbbgflash family review.','HSD removal and allocator counter details require baselib review.','Stamina defeat, full-screen rendering, playable-match setup and initialization alpha call values remain caller claims pending family evidence.'],'family_followups':['lb_013B ColorOverlay command interpreter and profile selection','lbbgflash output state and rendering','baselib user-data callback and object allocator lifecycle'],'counts':{'canonical_lines':161,'rendered_lines':161,'files':2,'targets':8,'entity_subjects':10,'inherited_facts':44,'proposal_facts':len(proposal['proposal']['facts']),'dispositions':{d:sum(x['disposition']==d for x in dispositions) for d in ['retain','supersede','reject','unresolved']}}}
(D/'functions.findings.json').write_text(json.dumps(findings,indent=2)+'\n');(D/'functions.proposal.json').write_text(json.dumps(proposal,indent=2)+'\n');print(findings['counts'])
