import json,pathlib,hashlib,datetime,struct,shutil
D=pathlib.Path(__file__).parent;S=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');M=json.load(open(S/'manifest.json'));R=M['head_revision'];root=pathlib.Path(M['checkout_root']);tu='main/melee/ft/kinds/ftCommon/ftCo_CargoFall';P='src/melee/ft/kinds/ftCommon/ftCo_CargoFall.c';C=json.load(open(D/'context.json'));X=json.load(open(D/'baseline-facts.json'));start='2026-09-08T15:32:06Z';U=S/'units'/C['task']['id']
def c(p,a,b):return f'code://{R}/{p}#L{a}-L{b}'
foreign=[('src/melee/ft/kinds/ftCommon/ftCo_CargoLanding.c',1,44),('src/melee/ft/kinds/ftCommon/ftCo_CargoThrow.c',24,118),('src/melee/ft/kinds/ftCommon/ftCo_Shouldered.c',28,41),('src/melee/ft/ftanim.c',490,514),('src/melee/ft/fighter.c',1072,1076),('src/melee/ft/fighter.c',1100,1103),('src/melee/ft/fighter.c',1235,1244),('src/melee/ft/ft_081B.c',549,556),('src/melee/ft/ft_081B.c',1363,1375),('src/melee/ft/kinds/ftDonkey/ftdonkey.c',217,227),('src/melee/ft/kinds/ftCommon/ftCo_Fall.c',203,206),('src/melee/ft/ftcommon.c',515,525),('src/melee/ft/kinds/ftCommon/ftCo_Landing.c',38,59),('src/melee/ft/kinds/ftCommon/ftCo_CargoWait.c',30,40),('src/melee/ft/kinds/ftCommon/ftCo_CargoWait.c',66,69)]
fr=[]
for p,a,b in foreign:
 t=(root/p).read_text();fr.append(dict(path=p,start_line=a,end_line=b,sha256=hashlib.sha256(t.encode()).hexdigest(),canonical_read=True,rendered_read=False,ownership='foreign evidence only'));(D/(p.replace('/','__')+f'.{a}-{b}.txt')).write_text('\n'.join(f'{i}: {l}' for i,l in enumerate(t.splitlines(),1) if a<=i<=b))
E=[c(P,16,43)]+[c(p,a,b) for p,a,b in foreign]
report=root/'build/GALE01/report.json';rh=hashlib.sha256(report.read_bytes()).hexdigest();assert rh==M['report_sha256'];unit=next(u for u in json.load(open(report))['units'] if u['name']==tu);objects=[]
for typ in ['src','obj']:
 p=root/f'build/GALE01/{typ}/melee/ft/kinds/ftCommon/ftCo_CargoFall.o';b=p.read_bytes();e='>' if b[5]==2 else '<';off=struct.unpack_from(e+'I',b,32)[0];sz,n,si=struct.unpack_from(e+'HHH',b,46);sh=[struct.unpack_from(e+'10I',b,off+i*sz) for i in range(n)];st=sh[si];names=b[st[4]:st[4]+st[5]]
 for s in sh:
  if names[s[0]:].split(b'\0')[0]==b'.sdata2':objects.append(dict(path=str(p),sha256=hashlib.sha256(b).hexdigest(),section='.sdata2',size=s[5],elf_flags=s[2],elf_flags_hex=hex(s[2]),writable=bool(s[2]&1),allocated=bool(s[2]&2),bytes_hex=b[s[4]:s[4]+s[5]].hex()))
json.dump(dict(report_path=str(report),report_sha256=rh,pinned_report_hash_matches=True,unit=unit,objects=objects),open(D/'section-evidence.json','w'),indent=2)
print('section evidence',objects,unit.get('sections'))
asm=root/'build/GALE01/asm/melee/ft/kinds/ftCommon/ftCo_CargoFall.s';se=json.load(open(D/'section-evidence.json'));se['assembly']=dict(path=str(asm),sha256=hashlib.sha256(asm.read_bytes()).hexdigest(),read='complete',finding='@232 is f32 zero, @233 is f32 one. Entry loads zero for initial frame/blend and later animation rate, one for initial speed.');se['permission_limit']='Source/split ELF flags are separately recorded; neither proves final runtime protection.';json.dump(se,open(D/'section-evidence.json','w'),indent=2)
O={('.sdata2','inferred_type'):'Eight-byte literal pool with consecutive f32 0.0 at offset 0 and 1.0 at offset 4. The observed source object marks .sdata2 WRITE|ALLOC, while the split object marks it ALLOC without SHF_WRITE; runtime protection is not established.',('.sdata2','purpose'):'Supplies float zero and one used to initialize CargoFall at frame zero, speed one and zero blend, then set animation rate zero. This TU reads the literals without writing them; section-name conventions do not determine write permissions.'}
rows=[];disp=[];facts=[]
for s in X:
 key=next(iter(s['subject'].values()));name=key.split(':')[-1];rows.append(dict(subject=s['subject'],status='reviewed' if s['facts'] else 'reviewed_no_existing_facts',fact_count=len(s['facts']),evidence=E,notes='All functions accept one source gobj parameter; no register-to-source correspondence promoted.'))
 for f in s['facts']:
  new=O.get((name,f['type']));reason='Canonical entry and bounded caller, callee and Donkey motion-table evidence support the existing behavior; preserve without citation-only rewriting.' if new is None else 'Observed source ELF flags include SHF_WRITE, unlike split object. Both contain the same zero/one bytes; distinguish read usage from section permissions. Hashed evidence in section-evidence.json.'
  disp.append(dict(subject=s['subject'],fact_id=f['id'],version=f['updated_at'],type=f['type'],old_value=f['value'],disposition='supersede' if new else 'retain',reason=reason,replacement=new,evidence=E))
  if new:facts.append(dict(subject=s['subject'],type=f['type'],op='write',value=new,rationale=reason,confidence=0.95,evidence=[dict(kind='code',locator=c(P,16,27),why=reason)]))
end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');reads=[json.loads(l) for l in open(U/'reads.jsonl') if json.loads(l).get('reader')=='CargoFall'];L=S/'baseline-links'/f'{C["task"]["id"]}.json';links=json.load(open(L));ld=[]
for l in links:
 ev=[c(P,16,43),c('src/melee/ft/kinds/ftDonkey/ftdonkey.c',217,227)]
 if l['to_entity_id'].endswith(':falling'):ev += [c('src/melee/ft/ft_081B.c',1363,1375),c('src/melee/ft/kinds/ftCommon/ftCo_Fall.c',203,206)]
 else:ev += [c('src/melee/ft/kinds/ftCommon/ftCo_CargoThrow.c',24,118),c('src/melee/ft/kinds/ftCommon/ftCo_CargoLanding.c',16,34),c('src/melee/ft/kinds/ftCommon/ftCo_Shouldered.c',28,41)]
 ld.append(dict(link_id=l['id'],baseline_record=l,from_target_id=l['from_target_id'],from_entity_id=l['from_entity_id'],to_target_id=l['to_target_id'],to_entity_id=l['to_entity_id'],role=l['role'],prior_rationale=l['why'],version_or_digest=l.get('digest'),disposition='retain',reconciliation_owner='/root/semantic_coordinator',reason='Canonical CargoFall table registration, aerial physics shared with ordinary Fall, directional cargo-throw dispatch, victim ShoulderedWait update and cargo-landing handoff support the recorded relationship. Empty Anim is a registered inert phase. Historical wiki/old-revision text is preserved, not asserted re-read. Duplicate records remain separately accounted for.',evidence=ev))
json.dump(dict(revision=R,input_path=str(L),input_sha256=hashlib.sha256(L.read_bytes()).hexdigest(),expected_count=len(links),reviewed_count=len(ld),counts=dict(retain=len(ld)),reconciliation_owner='/root/semantic_coordinator',dispositions=ld),open(D/'link-dispositions.json','w'),indent=2)
json.dump(dict(tu=tu,proposal=dict(facts=facts,links=[],entities=[],merges=[],follow_ups=[])),open(D/'proposal.json','w'),indent=2)
json.dump(dict(revision=R,start_utc=start,end_utc=end,counts=dict(retain=len(disp)-len(facts),supersede=len(facts)),dispositions=disp),open(D/'fact-dispositions.json','w'),indent=2)
json.dump(dict(campaign=M['campaign_id'],tu=tu,revision=R,role='TU librarian',model=M['model'],reasoning_effort=M['reasoning_effort'],start_utc=start,end_utc=end,input_files=C['files'],canonical_and_rendered_receipts=reads,foreign_evidence_reads=fr,subjects=rows,counts=dict(targets=6,source_entities=1,parameter_entities=5,existing_facts=len(disp),outgoing_links=len(ld),proposal_facts=len(facts),owned_lines=58),exceptions=[],section_evidence='section-evidence.json',link_dispositions='link-dispositions.json'),open(D/'coverage.json','w'),indent=2)
json.dump(dict(unresolved=[],family_followups=['Source/split ELF flags differ; final runtime memory protection is not established.','Landing timer uses an existing union field spelling mv.ca.specialhi.vel.x; no shared-layout rename proposed.','Root owns any outgoing-link reconciliation/deletion; historical wiki text was not re-read.']),open(D/'unresolved.json','w'),indent=2)
(D/'functionality.md').write_text(f'# Airborne cargo carry\n\nDraft at `{R}`.\n\n`ftCo_8009BC58` enters carrier motion base plus six with KeepFastFall, frame zero, speed one and zero blend. It then sets animation rate zero, converts the carrier to airborne handling only if currently grounded, and invokes the victim ShoulderedWait updater. That updater leaves an already-ShoulderedWait victim untouched. The entry assumes valid cargo attributes and victim pointers. KeepFastFall bypasses the ordinary fast-fall clear, while the animation-freeze flag remains clear, so the rate setter applies zero to both animation hierarchies and frame_speed_mul.\n\nCargoWait collision can dispatch this entry, and CargoWait2 recovery selects it when still airborne. The Donkey ThrowFFall state table installs these four callbacks. Anim does nothing. IASA calls the shared directional cargo-throw selector once; RETURN_IF has no lower-priority checks to suppress here. The selector requires an A-or-B press and directional thresholds; horizontal direction wins over vertical, choosing forward/back by facing, otherwise up/down. A changed selection enters the carrier throw state with an air offset when appropriate and synchronizes the victim thrown state.\n\nPhys calls the same ft_80084DB0 used by ordinary Fall. It checks fast-fall, applies fast-fall or gravity/terminal speed, then delegates remaining aerial movement. Coll calls ft_80082C74 with CargoLanding entry; the shared collision result decides whether to invoke that callback. CargoLanding copies character landing lag, selects base plus eight, freezes animation and keeps the victim shouldered. Its Anim checks the timer before decrementing it; a nonpositive timer enters CargoWait, then the function still executes its decrement.\n\nThe header agrees with all five definitions. The zeroed local array is stack/matching scaffolding without a gameplay role. Existing canonical callback names remain; only the anonymous entry carries an inferred alias.\n\n## Literal pool and links\n\nBoth existing objects contain eight bytes `000000003f800000` (f32 zero and one). Source object flags are WRITE|ALLOC and split object flags ALLOC only. The local code reads the literals, but that fact does not prove nonwritable sections or final runtime protection. Report hash matches the frozen manifest; no build ran.\n\nAll 11 outgoing records are individually retained, with original endpoints, roles, rationale and locator preserved plus current canonical evidence. No links are written or deleted.\n\n## Evidence\n\n'+'\n'.join('- '+e for e in E)+'\n')
(D/'naming.md').write_text('# Naming review\n\n| Canonical subject | Existing hypothesis | Decision |\n|---|---|---|\n| ftCo_8009BC58 | ftCo_CargoFall_Enter | Retain: CargoWait recovery/collision callers and Donkey callback table establish entry. |\n| CargoFall_Anim / IASA / Phys / Coll | None | Preserve canonical names. |\n| Source entity / .sdata2 | None | No name proposal needed. |\n\nNo canonical names or files changed.\n')
(D/'README.md').write_text(f'# CargoFall review packet\n\nRevision `{R}`. UTC `{start}` to `{end}`. Model `{M["model"]}`, role TU librarian.\n\nComplete canonical and rendered coverage: C1-45, H1-13. Six targets, source entity and five empty parameter entities covered. {len(disp)} facts: {len(disp)-len(facts)} retained, {len(facts)} data-permission corrections proposed. All {len(ld)} outgoing link records individually retained. No failed/empty renders or parser errors.\n\nRead functionality.md and naming.md; audit coverage.json, fact-dispositions.json, link-dispositions.json, section-evidence.json and unresolved.json. No source, KB or build edits.\n')
print('facts',len(disp),'links',len(ld),'writes',len(facts),'end',end)
