import json,pathlib,hashlib,datetime,struct,shutil
D=pathlib.Path(__file__).parent;S=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');M=json.load(open(S/'manifest.json'));R=M['head_revision'];root=pathlib.Path(M['checkout_root']);tu='main/melee/ft/kinds/ftCommon/ftCo_ShieldBreakStand';P='src/melee/ft/kinds/ftCommon/ftCo_ShieldBreakStand.c';C=json.load(open(D/'context.json'));X=json.load(open(D/'baseline-facts.json'));start='2026-09-08T15:11:02Z';U=S/'units'/C['task']['id']
def c(p,a,b):return f'code://{R}/{p}#L{a}-L{b}'
foreign=[('src/melee/ft/kinds/ftCommon/ftCo_ShieldBreakDown.c',35,40),('src/melee/ft/kinds/ftCommon/ftCo_Furafura.c',15,55),('src/melee/ft/ft_084E.c',42,53),('src/melee/ft/ft_081B.c',1027,1033),('src/melee/ft/ft_081B.c',393,404),('src/melee/ft/fighter.c',966,985),('src/melee/ft/fighter.c',1105,1107),('src/melee/ft/ftmotionstates.c',2433,2454),('src/melee/ft/ftanim.c',515,538),('src/melee/ft/ftcommon.c',670,718),('src/melee/ft/kinds/ftCommon/ftCo_Fall.c',47,64)]
fr=[]
for p,a,b in foreign:
 t=(root/p).read_text();fr.append(dict(path=p,start_line=a,end_line=b,sha256=hashlib.sha256(t.encode()).hexdigest(),canonical_read=True,rendered_read=False,ownership='foreign evidence only'));(D/(p.replace('/','__')+f'.{a}-{b}.txt')).write_text('\n'.join(f'{i}: {l}' for i,l in enumerate(t.splitlines(),1) if a<=i<=b))
E=[c(P,13,42)]+[c(p,a,b) for p,a,b in foreign]
report=root/'build/GALE01/report.json';rh=hashlib.sha256(report.read_bytes()).hexdigest();assert rh==M['report_sha256'];unit=next(u for u in json.load(open(report))['units'] if u['name']==tu);objects=[]
for typ in ['src','obj']:
 p=root/f'build/GALE01/{typ}/melee/ft/kinds/ftCommon/ftCo_ShieldBreakStand.o';b=p.read_bytes();e='>' if b[5]==2 else '<';off=struct.unpack_from(e+'I',b,32)[0];sz,n,si=struct.unpack_from(e+'HHH',b,46);sh=[struct.unpack_from(e+'10I',b,off+i*sz) for i in range(n)];st=sh[si];names=b[st[4]:st[4]+st[5]]
 for s in sh:
  if names[s[0]:].split(b'\0')[0]==b'.sdata2':objects.append(dict(path=str(p),sha256=hashlib.sha256(b).hexdigest(),section='.sdata2',size=s[5],bytes_hex=b[s[4]:s[4]+s[5]].hex()))
json.dump(dict(report_path=str(report),report_sha256=rh,pinned_report_hash_matches=True,unit=unit,objects=objects),open(D/'section-evidence.json','w'),indent=2)
print('section evidence',objects,unit.get('sections'))
rows=[];disp=[];facts=[]
for s in X:
 rows.append(dict(subject=s['subject'],status='reviewed' if s['facts'] else 'reviewed_no_existing_facts',fact_count=len(s['facts']),evidence=E,notes='One source gobj parameter per function; no speculative register mapping.'))
 for f in s['facts']:
  new=None;reason='Local canonical implementation and caller, callback-table and bounded callee evidence support the existing claim; preserve without citation-only rewrite.'
  if next(iter(s['subject'].values())).endswith(':ftCo_ShieldBreakStand_Anim') and f['type']=='data_flow':
   new='Queries ftAnim_IsFramesRemaining(gobj); a false result forwards the same object to ftCo_80099010. That callee enters Furafura, restores shield_health from common x280, initializes grab_timer to max(common x2F8 - current damage percent, 0) + common x2FC, resets mash history through ftCommon_InitGrab, and calls ftCommon_8007EBAC(fp, 25, 0) and ft_800885A8(fp, 95, 127, 64). Only the damage-dependent term is clamped; the additive common value is not validated here.';reason='The previous nonnegative-duration assertion was broader than the implementation: only the first term is clamped, before adding x2FC.'
  disp.append(dict(subject=s['subject'],fact_id=f['id'],version=f['updated_at'],type=f['type'],old_value=f['value'],disposition='supersede' if new else 'retain',reason=reason,replacement=new,evidence=E))
  if new:facts.append(dict(subject=s['subject'],type=f['type'],op='write',value=new,rationale=reason,confidence=0.95,evidence=[dict(kind='code',locator=e,why=reason) for e in [c(P,25,30),c('src/melee/ft/kinds/ftCommon/ftCo_Furafura.c',15,31),c('src/melee/ft/ftcommon.c',670,680)]]))
end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');reads=[json.loads(l) for l in open(U/'reads.jsonl') if json.loads(l).get('reader')=='ShieldBreakStand']
json.dump(dict(tu=tu,proposal=dict(facts=facts,links=[],entities=[],merges=[],follow_ups=[])),open(D/'proposal.json','w'),indent=2)
json.dump(dict(revision=R,start_utc=start,end_utc=end,counts=dict(retain=len(disp)-len(facts),supersede=len(facts)),dispositions=disp),open(D/'fact-dispositions.json','w'),indent=2)
json.dump(dict(campaign=M['campaign_id'],tu=tu,revision=R,role='TU librarian',model=M['model'],reasoning_effort=M['reasoning_effort'],start_utc=start,end_utc=end,input_files=C['files'],canonical_and_rendered_receipts=reads,foreign_evidence_reads=fr,subjects=rows,counts=dict(targets=6,source_entities=1,parameter_entities=5,existing_facts=len(disp),proposal_facts=len(facts),owned_lines=55),exceptions=[],section_evidence='section-evidence.json'),open(D/'coverage.json','w'),indent=2)
json.dump(dict(unresolved=[],family_followups=['Collision helper condition is preserved literally: ft_80083F88 enters Fall when ft_80082708 returns GA_Ground. That helper maps the mpColl result into GA values; this packet does not infer ledge semantics from those labels.','Shared state tables, flags and Furafura timer machinery are foreign evidence, not owned subjects.']),open(D/'unresolved.json','w'),indent=2)
(D/'functionality.md').write_text(f'# Shield-break standing phase\n\nDraft at `{R}`.\n\nShieldBreakDown animation completion calls `ftCo_80098F3C`. It chooses StandU only when current motion is DownU; every other motion ID selects StandD. Entry starts frame zero, speed one and blend zero. Its flags bypass the common resets for whole-body/hurtbox hit status, model, material animation and color animation. They do not promise preservation of every fighter field: the surrounding motion-entry machinery can still reset specially configured hurtboxes.\n\nThe two stand states register the same animation, IASA, physics and collision callbacks. The animation callback waits while ftAnim_IsFramesRemaining is true, then calls Furafura entry. The helper queries relevant animated model parts or blend joints; it is not a local countdown. Furafura entry restores shield health and initializes the mashable timer to max(x2F8 - damage percent, 0) + x2FC. Only the first term is clamped. Later Furafura updates subtract x300, apply button/stick mash reductions and leave through ft_8008A2BC when the timer reaches zero.\n\nIASA is an unconditional no-op, so that hook provides no input escape. Physics forwards to ft_80084F3C, which applies ground friction (scaled above walk speed) and ground movement. Collision forwards to ft_80083F88, which can call Fall entry when its collision helper returns GA_Ground; the numerical/code condition is retained without inferring ground-loss meaning from the enum spelling. Thus animation completion is not the only possible delegated transition.\n\nAll five functions take one Fighter_GObj pointer and return void. The header agrees with the definitions. The existing entry alias is supported; the four canonical callback names remain unchanged. The .sdata2 pool is corroborated by existing object bytes and the frozen report; no build ran.\n\n## Evidence\n\n'+'\n'.join('- '+e for e in E)+'\n')
(D/'naming.md').write_text('# Naming review\n\n| Canonical subject | Hypothesis | Decision |\n|---|---|---|\n| ftCo_80098F3C | ftCo_ShieldBreakStand_Enter | Retain existing inference: Down callback and Stand table establish entry role. |\n| ShieldBreakStand_Anim / IASA / Phys / Coll | None | Preserve canonical names, no duplicate aliases. |\n| Source entity / .sdata2 | None | No proposed name needed. |\n\nNo canonical names or files changed.\n')
(D/'README.md').write_text(f'# ShieldBreakStand review packet\n\nRevision `{R}`. UTC `{start}` to `{end}`. Model `{M["model"]}`, role TU librarian.\n\nComplete canonical and separate rendered coverage: C1-43, H1-12. Six targets, source entity and five empty parameter entities covered; all {len(disp)} fact IDs/versions reviewed. {len(disp)-len(facts)} retained; {len(facts)} timer-formula correction proposed. Zero parser errors, no failed/empty renders.\n\nRead functionality.md and naming.md; audit coverage.json, fact-dispositions.json, section-evidence.json and unresolved.json. No source, KB or build edits.\n')
print('facts',len(disp),'writes',len(facts),'end',end)
