from pathlib import Path
import json,hashlib,datetime,sqlite3,re,shutil
p=Path(__file__).parent;r=Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');m=json.loads((r/'manifest.json').read_text());tu='main/sysdolphin/baselib/debugconsole_main';task=next(t for t in m['tasks'] if t['tu']==tu);state=r/'units'/task['id'];src=task['source_path'];rev=m['head_revision'];groups=json.loads((p/'baseline-facts.json').read_text());facts=[dict(f,subject=g['subject']) for g in groups for f in g['facts']];eh=hashlib.sha256((p/'compiled-evidence.json').read_bytes()).hexdigest();b='src/sysdolphin/baselib/'
changes={
0:'Initialization fills a 0xD8-byte display state with XFB addresses, dimensions, font and cursor bounds. The debug thread stores an OSContext pointer, draws and submits framebuffers. The adjacent 0x1000-byte array is passed as thread stack with top=array+0xFFC and size0x1000; OSCreateThread writes its stack marker at array-4, the preceding saved-context slot in existing object layout. The entry subsequently clears state and installs its context argument.',
4:'State retains geometry, XFB selection, callback list, cursor, input and saved-context pointer. In the input walk a dirty flag restarts traversal only if no callback returned nonzero first; a nonzero result jumps directly to redraw. Requested redraws rotate the XFB modulo buffer count. This is a mutation-aware cooperative callback loop, not an unconditional restart after every mutation.',
7:'Existing source .data is5131 bytes; split .data is5136 bytes, both writable/allocated with283 relocations. It includes three32-byte glyph tables, a69-entry SPREntry table at offset728 of size1104, strings, menu arrays and mutable callback descriptors. The all-zero SPR entry34 is a separator, not an array terminator. The foreign mfspr helper and overlay camera descriptors now belong to hsd_397E and hsd_3982.',
13:'Each setter unconditionally overwrites its independent slot. Debug level is copied unchanged. Size uses u32 arithmetic (size+15)>>4, so it rounds upward only through0xFFFFFFF0; inputs0xFFFFFFF1 through0xFFFFFFFF wrap and store zero. No validation or accumulation.',
16:'Existing source and split .sdata are680 bytes with identical raw bytes, flags3 and16 relocations. Much of the section is inline short SPR names and other text; named four-byte pointers begin at offset540 and reference memory/BAT/SPR headings and formats. Short byte-format and name-padding arrays also live here. It is not primarily a collection of char-pointer globals.',
23:'Reads ctx->gpr[1] and reports each accepted frame address, sp[0] back chain and sp[1] saved LR through OSReport. Follows sp[0]. The physical-memory upper test adds0x800000000, which exceeds every u32 pointer, so it does not bound the walk to installed RAM.',
26:'Prints a count-limited stack backtrace from ctx->gpr[1]. max_depth is converted to u32, and frame pointers are not proven safe: the lower-address test works, but the nine-hex-digit upper-base constant makes the upper test ineffective for32-bit pointers. Alignment, cycles and readable ranges are not validated.',
27:'Stops for NULL, the source sentinel (u32)(sp+0x4000)==0xFFFF, or count reaching (u32)max_depth. Since sp is u32*, the sentinel adds0x10000 bytes. It rejects addresses below0x80000000; its comparison against physical size+0x800000000 cannot reject any u32 pointer. It dereferences two words and follows sp[0] without alignment or cycle checks. Negative max_depth becomes a large unsigned limit.',
36:'Canonical void(void*) helper interpreted as ExcptNode*. Successful removal changes the supplied next pointer, either global head or predecessor next pointer, and dirty flag. It neither frees the node nor invokes callbacks.',
92:'Provides the empty selected-entry callback for PMC1-PMC4 and UPMC1-UPMC4. The generic SPR browser displays raw values; the empty body establishes no reason why a decoded detail view was omitted.',
107:'Provides the empty setup callback stored in the SPR descriptor at offset4. The separate callbacks draw and process input; the body itself does not initialize or reset the descriptor.',
113:'Navigates the SPR selection and window or closes the node. At the beginning, up wraps to absolute index68; the downward scroll branch advances only while offset+selection<67, otherwise wraps to zero. Thus the two end transitions are asymmetric; small or excessive row counts are not validated.',
114:'Scans actionable bits low to high. Up decrements selection, then offset, or wraps to selection=x1C-4 and offset=68-selection. Down increments selection while below x1C-4, otherwise increments offset only while offset+selection<67, else clears both. Left/right/A/X/Y/Start return1 without a navigation change; B removes the list prefix through this node via ps_remove_node. No dimension or high-bit-mask validation.',
120:'Requires exact masks neutral,0x70,neutral,0x808,neutral,0x104,neutral,0x201,neutral,0x402, paced by retrace with no timeout or reset-on-wrong-mask. Installs context and the initial node, draws one frame, then polls while the list is nonempty. Input callbacks run head to tail; zero results continue and dirty mutations restart the walk, but nonzero results jump directly to redraw before the dirty restart test. Draw callbacks run tail first. Redraw rotates/flushes/submits an XFB; every iteration waits for retrace. Empty list reaches OSPanic.',
121:'Clears state, calls hsd_803941E8 for candidate XFBs and saved last-drawn source, and chooses count2 if slotx28 is nonzero else1. Reads width/height through u16 offsets of HSD_VIData, computes stride=((u16(width)+15)*2)&0x1FFE0 and area=stride*height. Columns=(u32)(width-40)/11 and rows=(u32)(height-80)/14 underflow for dimensions below the margins. The code does not prove either XFB usable.',
125:'Initializes debug-console state with candidate framebuffer addresses, video geometry, font pointer and text-grid dimensions. Buffer count depends only on whether the second slot is nonzero. It does not validate successful buffer acquisition, supported dimensions or resulting draw bounds.',
126:'Begins with memset over all state. Buffer index, input/list fields and scroll stay zero; x4 is0 but x8 is set to framebuffer height. Count is one or two by second-slot presence. Both raster flags remain zero, font is HSD_DebugFontAtlas and palette isNULL. Small dimensions can underflow unsigned grid calculations.',
138:'Snapshots raster flags, seeks history at column,row+r, and subtracts14 from y before drawing each row, including the first. It consumes at most column_count nonzero characters and row_count rows, at11-pixel x spacing. A zero ends that row. It leaves the shared history cursor changed and has no pointer, extent or geometry validation.',
144:'Reads FPSAVED and32 f64 FPR slots. The block labeled PSF then rereads the same FPR storage at context offsets0x90 through0x18F as32 pairs of u32/f32, not ctx->psf. Reporting temporarily disables interrupts and installs a cleared local current context, then restores prior context and interrupt state.',
145:'Supplies floating-point diagnostic output for captured crash state, but the PSF-labeled rows are alternate interpretations of FPR bytes and do not report the separately saved paired-single region.',
147:'Canonical void(OSContext* ctx). Reads ctx->state and ctx->fpr storage; the PSF-labeled loop accesses offsets0x90 onward rather than the separate psf field. It does not directly write the supplied context.',
148:'Prints32 FPR rows as raw words and doubles, followed by32 PSF-labeled rows that reinterpret those same FPR bytes as pairs of single-precision values. The separate saved psf array is not read.',
149:'Returns unless FPSAVED is set. Otherwise disables interrupts, saves current context, installs cleared temporary context and prints two32-row blocks from FPR storage. Clears temporary context, restores old context and interrupt state. No NULL-context guard; the PSF heading does not establish actual paired-single storage access.',
150:'Reads debug level and list head. Disabled or already-head requests do nothing. Otherwise removes a prior occurrence, replaces the current head while preserving its tail, invokes optional activation callback and sets dirty. The flag may cause traversal restart or accompany a nonzero callback result that goes directly to redraw; this helper does not itself draw.',
161:'Uses strlen(entries[0]) for top/bottom rule width, then each row label length for its own right border, so unequal labels misalign borders. Selected row uses reverse palette. Advances menu origin xC8 by4 and reduces xCC byindex+1. It does not guard NULL/empty lists or invalid index. The rule helper draws width+2 cells including plus endpoints.',
180:'Probes absolute history column=x0C+x18,row=x10+x14, moving left until nonzero or negative. It draws at absolute found-column*11+20, without subtracting horizontal scroll x18; y uses visible rowx10. Thus horizontal scroll can displace the highlight from the visible text. It temporarily changes palette and leaves history-cursor side effects from probes.',
184:'Draws a selected report character and the active report-node Start prompt. The glyph x coordinate uses the absolute report column, so it is not generally aligned with the scrolled visible column when x18 is nonzero.',
185:'For a nonnegative starting column, searches left; if no character is found, substitutes a space at column0. A negative starting column skips assignment to local ch, which is subsequently read uninitialized. Draw x uses absolute column while y uses visible row. Restores palette only; probe calls change retained-history cursor.',
186:'Saves the history cursor, seeks visible+scroll coordinates and performs eight parse iterations. Each can read twice after a zero sentinel, so more than eight bytes may be consumed. Hex digits accumulate by left shifts; masks result to0x8xxxxxx0 and restores cursor. The signed accumulator can overflow for high eight-digit values. The input handler stores this in the address-editor descriptor, whose accepted value later initializes the dump view.',
192:'Reads pending input and updates visible+scroll report coordinates. Character probes modify the retained-history cursor. A/X insert the address-editor node, with A parsing a new address first; Start prepends the main command menu. These insertions preserve the old head as next, invoke setup and set dirty, unlike hsd_80394E8C replacement semantics.',
196:'Handles report cursor movement, backward skipping of unavailable characters, or insertion of the address editor/main command menu ahead of the current report node. These command branches prepend nodes; they do not replace and discard the current head.',
198:'Rows0-5 synthesize masks8,4,1,2,0x100,0x400. Row6 reports GPRs, FPRs, a PSF-labeled reinterpretation of FPR bytes, and miscellaneous fields. The GQR0-3 labels actually read ctx u32 indices0-3, which are GPR0-3; GQR4-7 read offsets0x1B4 onward correctly. Capture enable is saved/restored. Row7 activates SPR; row8 clears nodes.',
199:'Provides postmortem command selection, report navigation and diagnostic-node transitions. Its context-report command has mislabeled PSF and GQR0-3 data, so it is not a complete accurate dump of all saved processor state.',
202:'Handles the main diagnostic command menu, translating rows into underlying report actions, switching/removing nodes, or emitting selected saved-context fields. The register output includes FPR bytes mislabeled as PSF and GPR0-3 mislabeled as GQR0-3.',
203:'Navigation returns true. Rows0-3 synthesize directions and return false with menu retained;4-5 remove the prefix through menu and return false with action mask. Row6 conditionally reports context, restores capture mode, removes prefix and returns true. Row7 replaces head with SPR;8 clears list. Cancellation removes the entire prefix through supplied node, not just that node; unmatched input returns false.',
205:'Seeds the internal memory viewer from the retained editor address by modulo reduction and cached-base restoration. This is address normalization, not proof of alignment or safe multiword reads; physical size must be nonzero.',
208:'Initializes the memory-dump cursor with ((editor_address&0x0FFFFFFF)+memsize)%memsize+0x80000000. It does not align the address, validate memsize or prove the following16-byte loads readable.',
216:'Directional bits change the dump address by16 or64 bytes with physical-size modulo wrapping. X emits exactly64 bytes through four rows, four groups per row and four bytes per group, advancing a raw byte pointer without end-of-RAM wrap. A opens the address editor and Start opens the memory-action menu; these are not CPU-context/SPR transitions.',
217:'Implements wrapped address navigation, a64-byte report dump, address-editor entry and memory-action help for the internal memory viewer. CPU-context and SPR commands belong to the separate main command menu.',
220:'Handles memory-view commands: moves the selected cached address, emits a64-byte OSReport dump, opens address editing or its action menu, and closes the current display.',
221:'Scans input low to high, handling one recognized bit. Directions move by16/64 with modulo. X forces capture on, reads64 consecutive bytes without wrap, forces capture off rather than restoring previous mode, removes prefix through current node and resets visible/scroll coordinates. A prepends the editor after copying address; Start prepends memory menu; B removes prefix. No high-bit-mask or memory-range guard.',
227:'Navigation returns1 and preserves menu. Activation maps supported rows0-6, removes list prefix through data and returns0 for downstream command processing. Unsupported row still removes that prefix but leaves command mask unchanged. Cancellation removes prefix and returns1; idle returns0.',
229:'Normalizes the address editor to0x8xxxxxx0 before editing. It does not establish that the physical portion falls within installed RAM; the accept callback performs a separate size comparison.',
237:'Draws a centered address-entry box with the retained cached address formatted8%07X. Highlights buf[19+index]. The paired editor modifies only six digits at indices0-5, bits24 through4; the least significant nibble stays zero after setup.',
238:'Saves/restores palette around box and highlighted-character rendering. The renderer directly indexes buf[19+x14] without validation. Direction handling moves a valid index within0-5, but does not sanitize a corrupt prior index; invalid state can cause an out-of-bounds buffer read or invalid shift in input processing.',
243:'Computes shift=24-index*4 and mask before scanning input; assumes index0-5. Up/down wrap a nibble, left decrements only when>0 and right increments only when<5, so corrupted indices are not generally clamped. Accept switches to parent only if low28 bits<physical size; X clears nibble; B removes prefix; Start prepends help. Invalid shift/state and high-bit masks are not guarded.',
249:'Navigation returns1 with menu retained. Activation maps supported rows0-6 to synthetic commands, removes prefix through menu and returns0; invalid row still removes prefix without replacing mask. Cancellation removes prefix and returns1. Idle returns0.',
250:'Selector changes only DBAT versus IBAT heading. Every call reads DBAT lower SPRs0x219+2*i into misleading local bat_u and upper SPRs0x218+2*i into bat_l. Permission uses lower&2, making R/O unreachable; G is always uppercase; W/I/M tests use upper-word bits. BEPI/BRPN output masks0xFFFC0000 and block length uses upper bits12..2. These are literal displayed fields, not a verified accurate hardware decoder.',
251:'Provides a BAT detail panel for the SPR inspector, with known interpretation limits: IBAT selection still reads DBAT and several permission/cache attributes are incompletely or incorrectly decoded.',
254:'Draws four DBAT pairs under a selector-dependent DBAT or IBAT heading. The page displays block-length/address and flag text, but does not switch reads to IBAT and does not accurately decode every hardware field.',
255:'Saves palette, draws heading, four two-row entries and closing border, restores palette. Reads selectors0x218-0x21F regardless of input. R/O cannot be reached by switch(lower&2); guarded flag always G; several cache tests use the upper word. It changes cursor coordinates and provides no geometry validation.',
263:'Dispatches draw callbacks along the same singly linked display chain used for input, interpreted through PSNode.child at offset0. This is tail-first list rendering before VI presentation, not a separate branching hierarchy.',
266:'Dispatches the display chain from tail to head. PSNode.child aliases the forward link at offset0 and draw callback is at offset8; recursion is unrolled three nodes per invocation. No cycle detection or callback-lifetime protection is provided.',
267:'NULL returns. Descends through offset0 links, recursively processing each third successor, then invokes available callbacks from deepest node toward head. Callbacks are void and cannot stop traversal by result. Cycles do not terminate and callbacks must preserve validity of saved node pointers.',
270:'HSD_DebugConsolePollInput',
274:'Passes ctx unchanged to a thread entry, with stack-local OSThread, top=hsd_804CF8E8+0xFFC, size0x1000, priority0, attr1. OSCreateThread derives stackEnd=top-size and writes0xDEADBABE there, four bytes before the array. Existing object layout places xD4 there. The worker clears screen state and later stores ctx; no general lifetime safety is established for the local control block.',
279:'Calls OSCreateThread then OSResumeThread without checking create result. The OS creates suspend=1 and attr&1, then resume makes runnable. The stack top/size pair causes a marker write at array-4; the entry later clears that location. The local OSThread must remain alive while active, which this wrapper does not independently enforce. Rendering-list exit reaches OSPanic.',
282:'Canonical void(u32 size), storing ((size+15) modulo2^32)>>4 in globalu32. It is ceiling division by16 only for size<=0xFFFFFFF0.',
283:'Stores a size-derived16-byte-unit setting. The u32 addition wraps for the highest15 input values; those store zero rather than the required unit count.',
284:'Unconditionally replaces setting with (size+15)>>4 using u32 addition. Zero stores zero; values1 through0xFFFFFFF0 round up, while0xFFFFFFF1 through0xFFFFFFFF wrap to zero. No guards, accumulation or error path.',
288:'Implements framebuffer-backed exception/developer diagnostics with controller-driven report browsing, memory inspection and live SPR views. This TU retains display state and a saved-context pointer; report-text storage belongs to hsd_393C, read through its cursor APIs.',
}
# Do not infer author intent from empty functions.
for i,f in enumerate(facts):
 if f['subject'].split(':')[-1].startswith('fn_803970') and f['type']=='purpose' and i not in changes:
  changes[i]=f['value'].replace('intentionally inert','empty').replace('intentionally','').replace('deliberately performs','performs').replace('deliberately','')
# Correct the header's permissive placeholder declaration explicitly in prose only.
changes[230]='Canonical definition is void hsd_80396868(void); the owned header still declares UNK_RET/UNK_PARAMS. It is stored as the address-editor initialization callback at descriptor offset4 and changes only its address field.'
# Input scanners shift a u32 single bit; bit31 set and unhandled can wrap to zero forever.
changes[167]=facts[167]['value']+' Requires the ordinary low controller-bit domain: an unhandled bit31 can keep bit<=flags true after the shift wraps bit to zero. Entry pointers and index are not validated.'
# Foreign source ranges are evidence only; ownership stays with their manifest family.
fr={b+'hsd_393C.c':[[64,110],[198,334]],b+'hsd_3982.c':[[1,55]],b+'hsd_397E.c':[[1,30]],'src/melee/db/dberror.c':[[1,81]],'extern/dolphin/include/dolphin/os/OSContext.h':[[1,173]],'extern/dolphin/src/dolphin/os/OSThread.c':[[404,506],[102,204],[563,652]]}
(p/'foreign-ranges.json').write_text(json.dumps(fr,indent=2)+'\n')
ranges={'.bss':[(28,68),(2540,2553),(2687,2721),(2850,2858)],'.data':[(102,218),(314,356),(440,548),(1197,1217),(1646,1656),(1862,1926),(2050,2108),(2533,2538)],'.sbss':[(65,66),(2860,2868)],'.sdata':[(133,152),(1669,1733),(1928,1930),(2110,2115),(2266,2283)],'Exception_ReportCodeline':[(849,959)],'Exception_ReportStackTrace':[(824,847)],'Exception_StoreDebugLevel':[(2860,2863)],'fn_80394DF4':[(961,989)],'fn_80397374':[(2375,2428)],'fn_80397814':[(2540,2568),(2569,2685),(2687,2800),(2801,2848)],'hsd_80394314':[(558,609)],'hsd_80394434':[(611,645)],'hsd_80394544':[(647,682)],'hsd_80394668':[(688,762)],'hsd_80394950':[(767,809)],'hsd_80394E8C':[(1008,1032)],'hsd_80394F48':[(1034,1127)],'hsd_80395550':[(1129,1172)],'hsd_80395644':[(1176,1217)],'hsd_803956D8':[(1219,1250)],'hsd_803957C0':[(1252,1317)],'hsd_80395970':[(1323,1358),(1453,1467)],'hsd_80395A78':[(1391,1501)],'hsd_80395D88':[(1503,1634),(1646,1656)],'hsd_80396130':[(1658,1667),(1862,1864)],'hsd_80396188':[(1669,1725)],'hsd_803962A8':[(1735,1864)],'hsd_803966A0':[(1866,1909),(1916,1926),(1503,1525)],'hsd_80396868':[(1911,1914),(2050,2053)],'hsd_80396884':[(1928,1981),(1985,2012)],'hsd_80396A20':[(1985,2053),(1503,1525)],'hsd_80396C78':[(2055,2108),(1503,1525)],'hsd_80396E40':[(2110,2236)],'hsd_80397110':[(2285,2373)],'hsd_80397520':[(22,26),(2430,2455),(2741,2753)],'hsd_803975D4':[(28,68),(2457,2526)],'hsd_80397DA4':[(2850,2858),(28,68),(2550,2553),(2687,2689)],'hsd_80397DFC':[(65,66),(2865,2868)],'FILE':[(28,107),(558,609),(767,847),(1391,1501),(1735,1864),(2110,2236),(2285,2373),(2540,2568),(2687,2800),(2801,2868)]}
ce=json.load(open(p/'compiled-evidence.json'))
for j,sym in enumerate(['fn_803970D8','fn_803970DC','fn_803970E0','fn_803970E4','fn_803970E8','fn_803970EC','fn_803970F0','fn_803970F4','fn_803970F8','fn_803970FC','fn_80397100','fn_80397104','fn_80397108']):
 ranges[sym]=[(2238+2*j,2238+2*j),(2318,2358)]+[(e['line'],e['line']+5) for e in ce['source_spr_entries'] if e['callback']==sym]
ranges['fn_8039710C']=[(2264,2264),(2533,2538),(1008,1032)]
def ev(f,a,z,why='Pinned canonical behavior and declarations reviewed.'):
 return {'kind':'code','locator':f'code://{rev}/{f}#L{a}-L{z}','why':why}
def evidence(sym):
 es=[ev(src,a,z) for a,z in ranges[sym]]
 if sym in ['.bss','hsd_80397DA4']:es += [ev('extern/dolphin/src/dolphin/os/OSThread.c',407,449,'Stack marker is written at top-size.'),ev('src/melee/db/dberror.c',27,58),ev('extern/dolphin/src/dolphin/os/OSThread.c',563,592)]
 if sym in ['.sbss','Exception_StoreDebugLevel','Exception_ReportStackTrace','Exception_ReportCodeline','hsd_80397DFC','fn_80397814','FILE']:es += [ev('src/melee/db/dberror.c',27,81)]
 if sym in ['hsd_80394950','hsd_80395D88']:es += [ev('extern/dolphin/include/dolphin/os/OSContext.h',133,153,'FPR, GPR, GQR and separate PSF field declaration.')]
 if sym in ['hsd_80394314','.bss']:es += [ev(b+'hsd_393C.c',273,334)]
 if sym in ['.data','FILE']:es += [ev(b+'hsd_3982.c',11,54),ev(b+'hsd_397E.c',9,30)]
 if sym in ['hsd_803957C0','hsd_80395970','hsd_80394544']:es += [ev(b+'hsd_393C.c',222,270)]
 if sym in ['hsd_803962A8','hsd_80395D88']:es += [ev(b+'hsd_393C.c',73,86)]
 if sym=='hsd_80396868':es += [ev(b+'debugconsole_main.h',24,26)]
 return es
props=[];disp=[]
for i,f in enumerate(facts):
 sym='FILE' if f['subject']==src else f['subject'].split(':')[-1];es=evidence(sym);d='supersede' if i in changes else 'retain';why='Current owned canonical/rendered review independently supports the recorded behavior.'
 if d=='supersede':why='Corrected after branch, field-offset, arithmetic or consumer review; see functionality and unresolved records.'
 if sym.startswith('.') or sym in ['FILE','hsd_80397DA4']:why+=f' Existing-object companion compiled-evidence.json SHA-256 {eh}; no rebuild or runtime validation.'
 if f['type']=='inferred_name':why+=' Hypothesis only, pending independent review. No canonical source rename. Baseline collision lookup recorded in naming-collisions.json.'
 props.append({'subject':{'entity_locator' if sym=='FILE' else 'target_stable_key':f['subject']},'type':f['type'],'op':'write','value':changes.get(i,f['value']),'rationale':why,'confidence':.94 if d=='supersede' else f['confidence'],'evidence':es})
 disp.append({'subject':f['subject'],'fact_id':f['id'],'updated_at':f['updated_at'],'version':f['updated_at'],'type':f['type'],'disposition':d,'action':why,'evidence':es})
stale=[]
for subject in task['writable_subjects']:
 k=subject.get('target_stable_key',subject.get('entity_locator'))
 if any(f['subject']==k for f in facts):continue
 sym=k.split(':')[-1].split('#')[0]
 if sym not in ranges:
  stale.append(k);es=[ev(b+('hsd_397E.c' if sym=='baselib_mfspr' else 'hsd_3982.c'),9 if sym=='baselib_mfspr' else 11,30 if sym=='baselib_mfspr' else 54)];d='unresolved';why='No inherited fact; stale parameter identity for function now owned by another TU. Reconcile ownership separately; no write.'
 else:es=evidence(sym);d='retain';why='No inherited fact. Canonical signature/parameter use inspected; no new fact proposed.'
 disp.append({'subject':k,'fact_id':None,'updated_at':None,'version':None,'disposition':d,'action':why,'evidence':es})
(p/'proposal.json').write_text(json.dumps({'tu':tu,'proposal':{'facts':props,'links':[],'entities':[],'merges':[],'follow_ups':[]}},indent=2)+'\n')
# Preserve and individually classify each exact frozen relationship.
lp=r/'baseline-links'/f"{task['id']}.json";links=json.loads(lp.read_text());ld=[]
for l in links:
 sym='FILE' if l['from_entity_id'] else l['from_target_id'].split(':')[-1];d='retain';reason='Owned implementation and its documented consumers support this exact relationship at the pinned revision.';es=evidence(sym)
 if l['to_entity_id'].endswith('developer-performance-overlay'):
  d='reject';reason='Stale ownership: the camera GX callback and overlay constructor/descriptors are now in hsd_3982.c, not this TU or its data section.'
 elif l['id']=='link:dae7b5eb-f2ec-467f-aab2-053e226e1795':
  d='unresolved';reason='SPR-inspector relationship is supported, but stored rationale promises decoded DBAT/IBAT state. Only DBAT is read and decoding has documented errors. Needs reversible rationale reconciliation.'
 elif l['id']=='link:0465abd4-04e8-4c20-9fb6-e5d58e01dac7':
  d='unresolved';reason='Crash-diagnostic relationship is supported, but full saved-state report claim is contradicted: GPR0-3 are labeled GQR0-3 and FPR bytes are labeled PSF.'
 elif l['id']=='link:e183e21d-d5b7-4119-b474-6d7b2ba40ec2':
  d='unresolved';reason='Crash reporting is supported, but paired-single section reads FPR storage. Retain target association only after stored rationale distinguishes headings from actual saved fields.'
 elif l['id']=='link:fc818c2b-ad73-40df-92ad-aab24d66defe':
  d='unresolved';reason='Thread implements diagnostics, but stored rationale says continuously renders. Actual frames are redrawn only for nonzero callback results; idle iterations poll and wait.'
 elif sym.startswith('fn_803970') or sym=='fn_8039710C':
  reason='Retain registered empty callback relationship only. Table/descriptor registration plus selected-row/setup call path support participation; no hardware decoding or author intent is inferred from empty body.'
 ld.append({'link_id':l['id'],'baseline':l,'disposition':d,'reason':reason,'evidence':es})
(p/'link-dispositions.json').write_text(json.dumps({'tu':tu,'revision':rev,'baseline_path':str(lp),'baseline_sha256':hashlib.sha256(lp.read_bytes()).hexdigest(),'link_count':len(ld),'retained':sum(x['disposition']=='retain' for x in ld),'rejected':sum(x['disposition']=='reject' for x in ld),'unresolved':sum(x['disposition']=='unresolved' for x in ld),'db_link_changes':False,'links':ld},indent=2)+'\n')
db=sqlite3.connect('file:'+m['baseline_db']+'?mode=ro',uri=True);coll=[]
for i,f in enumerate(facts):
 if f['type']!='inferred_name':continue
 v=changes.get(i,f['value']);hits=db.execute("SELECT t.stable_key,t.symbol,f.value FROM target t LEFT JOIN fact f ON f.target_id=t.id AND f.type='inferred_name' WHERE t.identity_status='current' AND (t.symbol=? OR f.value=?) AND t.stable_key<>?",(v,v,f['subject'])).fetchall();coll.append({'subject':f['subject'],'candidate':v,'other_current_matches':hits})
(p/'naming-collisions.json').write_text(json.dumps(coll,indent=2)+'\n');assert not any(x['other_current_matches'] for x in coll)
reads=[json.loads(x) for x in (state/'reads.jsonl').read_text().splitlines()];start=min(x['at'] for x in reads if x.get('reader')=='debugconsole_complete_review');end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');files=[dict(f,canonical_ranges=[[1,f['lines']]],rendered_ranges=[[1,f['lines']]]) for f in m['files'] if f['path'] in task['files']]
asset={'path':'build/GALE01/include/sysdolphin/baselib/debug_font.inc','bytes':43008,'sha256':'3dc135aa8475485984141a70e38ce83abafe9fdcf59800cd8ad8590478b69abd','status':'excluded_foreign_generated_asset','inspection':'No glyph artwork review claimed; family owner handles asset.'}
cov={'tu':tu,'subjects':disp,'files':files,'started_at':start,'research_start':start,'research_end':end,'completed_at':end,'fact_count':len(facts),'reviewed_subject_count':len(task['writable_subjects']),'fact_version_kind':'updated_at','render_exceptions':['C parser reports5 errors. Parse-uncertain rule/putc and address-input regions read canonically. Header fn_80397814 is shadowed_binding; header parser errors0. Names only rendering; fields/data remain canonical.'],'render_metadata':{'source_parse_errors':5,'header_parse_errors':0,'next_line':None},'foreign_reads':[{'path':f,'canonical_ranges':rs} for f,rs in fr.items()],'links_reviewed':len(ld),'link_dispositions':'link-dispositions.json','excluded_assets':[asset],'owned_header_coverage':[{'path':b+'debugconsole_main.h','canonical_ranges':[[1,52]],'rendered_ranges':[[1,52]]}]};(p/'coverage.json').write_text(json.dumps(cov,indent=2)+'\n')
summary={'tu':tu,'status':'draft_pending_independent_review','started_at':start,'research_start':start,'research_end':end,'completed_at':end,'files_reviewed':2,'canonical_lines':2921,'rendered_lines':2921,'subjects_reviewed':len(task['writable_subjects']),'existing_facts_reviewed':len(facts),'retained_facts':len(facts)-len(changes),'superseded_facts':len(changes),'new_facts':0,'proposal_facts':len(props),'retained_name_hypotheses':len(coll)-1,'proposed_names':1,'clears':0,'compiled_evidence_sha256':eh,'report_sha256':m['report_sha256'],'proposal_sha256':hashlib.sha256((p/'proposal.json').read_bytes()).hexdigest(),'links_reviewed':len(ld),'links_retained':sum(x['disposition']=='retain' for x in ld),'links_rejected':sum(x['disposition']=='reject' for x in ld),'links_unresolved':sum(x['disposition']=='unresolved' for x in ld)};(p/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
items=[{'topic':'Stale parameter ownership','subjects':stale,'status':'family_reconciliation'},{'topic':'Saved-register labels','status':'source_observed','detail':'PSF output reads FPR bytes; GQR0-3 output reads GPR0-3. OSContext comment says psf0x1C4 while constants say456/0x1C8; no ownership of foreign layout repair.'},{'topic':'BAT decoding','status':'source_observed','detail':'Always DBAT reads. R/O unreachable. Guard flag always uppercase. Cache bits use upper word. Address masks keep bits18..31 only.'},{'topic':'Thread stack and lifetime','status':'cross_file_review_required','detail':'OSCreateThread marker top-size is array-4, matching xD4 in object layout. Entry clears/replaces state later. Local OSThread lifetime depends on scheduling/nonreturning diagnostic path.'},{'topic':'Input domain and list semantics','status':'source_observed','detail':'Several low-to-high bit scans can loop forever after unhandled bit31 shifts to zero. Prefix-removal helper clears all leading nodes through supplied node, or all if absent. Dirty restart is bypassed by nonzero callback result.'},{'topic':'Bounds','status':'source_observed','detail':'Stack upper test ineffective; negative depth huge. Dimensions can underflow; addresses and cursor indices require valid state. Text drawing/history probes mutate different cursor domains. Memory report reads64 raw bytes without wrap.'},{'topic':'Unused size setting','status':'unresolved_consumer','detail':'No read of hsd_804D78CC appears in this owned TU; no operational effect inferred. Addition wraps for top15 u32 sizes.'},{'topic':'Font artwork','status':'excluded','asset':asset},{'topic':'Validation limits','status':'not_executed','detail':'No compile, matching, runtime, hardware SPR, visual glyph or thread scheduling validation. Existing objects inspected only.'}]
(p/'unresolved.json').write_text(json.dumps({'tu':tu,'items':items},indent=2)+'\n')
(p/'naming.md').write_text('# Naming Review\n\nOne correction is proposed: `hsd_803975D4` from `HSD_ParticleScreenRenewInput` to `HSD_DebugConsolePollInput`. The canonical comment identifies ParticleScreenState as a misnomer, and the function polls controller/reset state for the debug-console thread. All names remain hypotheses pending independent review.\n\n| Canonical | Inherited | Proposed | Disposition |\n|---|---|---|---|\n'+''.join(f"| {f['subject'].split(':')[-1]} | {f['value']} | {changes.get(i,f['value'])} | {'supersede hypothesis' if i in changes else 'retain hypothesis'} |\n" for i,f in enumerate(facts) if f['type']=='inferred_name')+'\nFrozen baseline candidate lookups found no competing current canonical or inferred names. See naming-collisions.json. No source names changed.\n')
print(json.dumps(summary))
