import json,pathlib,hashlib,datetime,struct,shutil
D=pathlib.Path('docs/.drafts/melee-semantic-20260908/main__melee__ft__kinds__ftCommon__ftCo_DamageFall');S=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');M=json.load(open(S/'manifest.json'));R=M['head_revision'];root=pathlib.Path(M['checkout_root']);C=json.load(open(D/'context.json'));X=json.load(open(D/'baseline-facts.json'));tu=C['task']['tu'];P=C['task']['source_path'];U=S/'units'/C['task']['id'];start='2026-09-08T15:39:57Z'
def c(p,a,b):
 assert 1<=a<=b<=len((root/p).read_text().splitlines()),(p,a,b)
 return f'code://{R}/{p}#L{a}-L{b}'
foreign=[]
def add(p,*pairs):
 for a,b in pairs:foreign.append(('src/melee/'+p,a,b))
add('ft/ft_081B.c',(125,167),(811,848),(1363,1375));add('ft/ftcommon.c',(640,647),(1088,1121),(1701,1721),(457,460),(515,525));add('ft/fighter.c',(1406,1425),(2951,3002),(1644,1651));add('ft/ft_0881.c',(213,218));add('ft/ftmotionstates.c',(552,562))
for n,pairs in {'HammerWait':[(139,146)],'HammerFall':[(16,67)],'ItemParasolDamageFall':[(14,27)],'DamageIce':[(54,59)],'PassiveStand':[(22,61)],'DownAttack':[(86,106)],'Passive':[(19,31)],'DownBound':[(120,140),(170,188),(211,227)],'PassiveCeil':[(37,56)],'CliffWait':[(60,72)],'Lift':[(45,61)],'Attack100':[(297,325)],'JumpAerial':[(60,71)]}.items():add('ft/kinds/ftCommon/ftCo_'+n+'.c',*pairs)
add('ft/ftCo_800C7CA0.c',(30,57),(80,119))
fr=[]
for p,a,b in foreign:
 c(p,a,b);t=(root/p).read_text();fr.append(dict(path=p,start_line=a,end_line=b,sha256=hashlib.sha256(t.encode()).hexdigest(),canonical_read=True,rendered_read=False,ownership='foreign evidence only'));(D/(p.replace('/','__')+f'.{a}-{b}.txt')).write_text('\n'.join(f'{i}: {l}' for i,l in enumerate(t.splitlines(),1) if a<=i<=b))
E=[c(P,1,143)]+[c(p,a,b) for p,a,b in foreign]
report=root/'build/GALE01/report.json';rh=hashlib.sha256(report.read_bytes()).hexdigest();assert rh==M['report_sha256'];unit=next(u for u in json.load(open(report))['units'] if u['name']==tu);objects=[]
for typ in ['src','obj']:
 p=root/f'build/GALE01/{typ}/melee/ft/kinds/ftCommon/ftCo_DamageFall.o';b=p.read_bytes();e='>' if b[5]==2 else '<';off=struct.unpack_from(e+'I',b,32)[0];sz,n,si=struct.unpack_from(e+'HHH',b,46);sh=[struct.unpack_from(e+'10I',b,off+i*sz) for i in range(n)];st=sh[si];names=b[st[4]:st[4]+st[5]]
 for s in sh:
  if names[s[0]:].split(b'\0')[0]==b'.sdata2':objects.append(dict(path=str(p),sha256=hashlib.sha256(b).hexdigest(),section='.sdata2',size=s[5],elf_flags=s[2],writable=bool(s[2]&1),allocated=bool(s[2]&2),bytes_hex=b[s[4]:s[4]+s[5]].hex()))
asm=root/'build/GALE01/asm/melee/ft/kinds/ftCommon/ftCo_DamageFall.s'
json.dump(dict(report_path=str(report),report_sha256=rh,pinned_report_hash_matches=True,unit=unit,objects=objects,assembly=dict(path=str(asm),sha256=hashlib.sha256(asm.read_bytes()).hexdigest(),read='complete',finding='@259 f32 zero used in entry and IASA ABS comparison; @260 f32 one used in entry. No extra conversion constants.'),permission_limit='Object flags do not prove final runtime protection.'),open(D/'section-evidence.json','w'),indent=2)
O={}
def replace(n,t,v,why,ev):O[n,t]=(v,why,ev)
replace('.sdata2','inferred_type','Eight-byte literal pool containing f32 0.0 at offset 0 and 1.0 at offset 4. The observed source object marks .sdata2 WRITE|ALLOC; the split object marks it ALLOC without SHF_WRITE. Final runtime protection is not established.','Existing objects agree on bytes and size but not SHF_WRITE; the read-only claim conflates section convention with permissions.',[c(P,95,133)])
old={(next(iter(s['subject'].values())).split(':')[-1],f['type']):f['value'] for s in X for f in s['facts']}
replace('ftCo_80090574','data_flow',old['ftCo_80090574','data_flow'].replace('temporarily enlarges and then restores ledge-snap height on the ordinary path','on the ordinary path multiplies the scale-derived ledge-snap height by common x1CC only for ECBSource_JObj and restores its unmultiplied value only for that source kind'),'The callee gates both writes by ECBSource_JObj and does not establish that x1CC always enlarges the value.',[c(P,26,29),c('src/melee/ft/ft_081B.c',125,167)])
replace('ftCo_80090718','data_flow',old['ftCo_80090718','data_flow'].replace('A nonnegative x1908','An x1908 value other than -1'),'The exact local presence test is != -1, not a sign test.',[c(P,83,93),c('src/melee/ft/ft_0881.c',213,218)])
audioev=[c(P,83,93),c('src/melee/ft/fighter.c',2965,2991),c('src/melee/ft/fighter.c',1406,1425)]
replace('ftCo_80090718','game_mapping','Dispatches queued damage audio in immediate or hitlag-deferred processing. The hit-processing caller invokes it immediately when bool1 is zero; with bool1 nonzero, positive computed hitlag and bool2 set mark audio for dispatch when hitlag ends. A computed zero hitlag in the bool1 branch does not itself invoke this routine.','Immediate playback follows the bool1==0 branch, not every interaction with zero hitlag; deferral also requires positive hitlag and bool2.',audioev)
replace('ftCo_80090718','state_behavior','Each pending slot is processed independently: x1908 != -1 plays the direct ID and resets it to -1; non-NULL x190C plays a randomly selected array entry and resets it to NULL. Hit processing calls immediately when bool1==0. With bool1 nonzero, positive hitlag and bool2 set raise x221A_b3; frame processing dispatches when hitlag expires and clears that flag.','The caller has explicit positive-hitlag and bool2 gates on deferral, omitted by the previous unconditional otherwise claim.',audioev)
replace('ftCo_80090780','game_mapping',old['ftCo_80090780','game_mapping'].replace('being pushed from a ledge','ledge-hang timer expiration'),'The verified CliffWait caller checks expiration of its hang timer, not a push.',[c(P,95,109),c('src/melee/ft/kinds/ftCommon/ftCo_CliffWait.c',60,72),c('src/melee/ft/kinds/ftCommon/ftCo_Lift.c',45,61)])
iev=[c(P,113,133),c('src/melee/ft/kinds/ftCommon/ftCo_HammerWait.c',139,146),c('src/melee/ft/kinds/ftCommon/ftCo_HammerFall.c',16,67),c('src/melee/ft/kinds/ftCommon/ftCo_Attack100.c',297,325)]
replace('ftCo_DamageFall_IASA','state_behavior','If ftCo_800C5240 reports no held Hammer, checks in short-circuit order: aerial special input; ftCo_80095328(gobj, 0); ftCo_800D7100; ftCo_800C3B10; airborne attack/item-throw input; ftCo_800D705C; and ftCo_800CB870. If none returns true, absolute horizontal stick >= common x210 and tilt age < common x214 enter Fall and return. Only if no earlier return occurred does it test ftCo_800C5DDC (Hammer release/drop), followed on false by ftCo_800C5CD4 (HammerFall entry). A true predicate need not change motion: ftCo_800D705C sets x209C from common x414.','The guard is a Hammer-held predicate; final checks depend on no prior early return, and handled input need not imply a motion transition.',iev)
replace('ftCo_DamageFall_IASA','inferred_type','Fighter IASA callback with exact signature void ftCo_DamageFall_IASA(HSD_GObj* gobj). It consumes boolean action-handler results through early returns and returns no result itself. A true handler may only update a timer, as ftCo_800D705C does, rather than change motion.','A verified true-return path sets x209C without a motion transition.',iev)
replace('ftCo_DamageFall_IASA','data_flow',old['ftCo_DamageFall_IASA','data_flow'].replace('successful callees, including ftCo_Fall_Enter, mutate the fighter\'s action state','handlers can change motion, including ftCo_Fall_Enter, or consume input by writing a timer (ftCo_800D705C sets x209C from x414)'),'Do not equate all successful predicate returns with motion-state mutation.',iev)
rows=[];disp=[];facts=[]
for s in X:
 name=next(iter(s['subject'].values())).split(':')[-1];rows.append(dict(subject=s['subject'],status='reviewed' if s['facts'] else 'reviewed_no_existing_facts',fact_count=len(s['facts']),evidence=E,notes='Parameter records are empty; no ABI register-to-source mapping promoted.'))
 for f in s['facts']:
  q=O.get((name,f['type']));new,why,ev=q if q else (None,'Complete owned canonical/rendered source and bounded dependencies support the existing value. Historical citations are preserved, not asserted re-read.',E)
  disp.append(dict(subject=s['subject'],fact_id=f['id'],version=f['updated_at'],type=f['type'],old_value=f['value'],disposition='supersede' if q else 'retain',reason=why,replacement=new,evidence=ev))
  if q:facts.append(dict(subject=s['subject'],type=f['type'],op='write',value=new,rationale=why,confidence=0.97,evidence=[dict(kind='code',locator=e,why=why) for e in ev]))
end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');reads=[json.loads(l) for l in open(U/'reads.jsonl') if json.loads(l).get('reader')=='DamageFall'];L=S/'baseline-links'/f'{C["task"]["id"]}.json';links=json.load(open(L));ld=[]
for l in links:
 ld.append(dict(link_id=l['id'],baseline_record=l,from_target_id=l['from_target_id'],from_entity_id=l['from_entity_id'],to_target_id=l['to_target_id'],to_entity_id=l['to_entity_id'],role=l['role'],prior_rationale=l['why'],version_or_digest=l.get('digest'),disposition='retain',reconciliation_owner='/root/semantic_coordinator',reason='DamageFall callback registration, ordered input handling, shared airborne physics, tech/DownBound landing dispatch, Parasol branch, model-shift hitlag calculation and immediate/deferred audio callers support these relationships. Complete original record retained; historical wiki and old-revision resources not asserted re-read.',evidence=E))
def dump(n,v):json.dump(v,open(D/n,'w'),indent=2)
dump('proposal.json',dict(tu=tu,proposal=dict(facts=facts,links=[],entities=[],merges=[],follow_ups=[])))
dump('fact-dispositions.json',dict(revision=R,start_utc=start,end_utc=end,counts=dict(retain=len(disp)-len(facts),supersede=len(facts)),dispositions=disp))
dump('link-dispositions.json',dict(revision=R,input_path=str(L),input_sha256=hashlib.sha256(L.read_bytes()).hexdigest(),expected_count=len(links),reviewed_count=len(ld),counts=dict(retain=len(ld)),reconciliation_owner='/root/semantic_coordinator',dispositions=ld))
dump('coverage.json',dict(campaign=M['campaign_id'],tu=tu,revision=R,role='TU librarian',model=M['model'],reasoning_effort=M['reasoning_effort'],start_utc=start,end_utc=end,input_files=C['files'],canonical_and_rendered_receipts=reads,foreign_evidence_reads=fr,subjects=rows,counts=dict(targets=10,source_entities=1,parameter_entities=15,existing_facts=len(disp),outgoing_links=len(ld),proposal_facts=len(facts),owned_lines=165),exceptions=['Foreign Hammer helper inferred aliases collide in rendered output; canonical identifiers used.','Owned ftCo_80090690 inferred alias is shadowed in header rendering but correctly substituted in C.'],section_evidence='section-evidence.json'))
dump('unresolved.json',dict(unresolved=[],family_followups=['Final runtime permissions not established by object flags.','Rendered alias collisions require coordinator attention; no foreign subject writes proposed.','Parameter records remain empty; exact ABI correspondence not inferred.','Historical wiki resources not re-read; root owns link reconciliation.']))
(D/'functionality.md').write_text(f'''# DamageFall behavior

Draft at `{R}`. All owned C1-144 and H1-21 read canonically and rendered.

The unit combines damage-model shift setup/retrieval, pending audio, a collision-refresh adapter, and DamageFall entry/callbacks. The adapter discards the shared boolean collision result. Its surface-reaction callers already corrected position; the ordinary collision path changes ledge-snap height only for ECBSource_JObj.

Model shifting excludes Cape, Disable, Nap, Sleep and current DamageIce. calcShift converts common x168 times calculated hitlag plus x16C to u16. Index resets to zero. Electric chooses mode 2 before ground/air; air uses 0; ground uses 1 and captures the floor normal. x18FD comes from the pointer-slot encoded count cast through u32 to u8, not a pointer dereference. With frames active, the reader mirrors table X by facing; ground returns (normal.y*x, -normal.x*x + table.y). It returns the buffer without advancing; zero frames returns NULL without writing. Fighter frame processing decrements duration, increments the index, and wraps at x18FD.

Audio independently tests x1908 != -1 and x190C != NULL, plays and clears each slot. Direct playback uses 127/64. Array playback chooses HSD_Randi(num). Immediate caller execution is bool1==0; bool1 nonzero requires positive hitlag and bool2 to flag deferred dispatch. Computed zero hitlag is not an automatic immediate fallback in that branch.

Entry converts ground bookkeeping before checking Parasol. Verified Parasol results are 0..6 or -1, so the existing nonnegative description is valid here. Active Parasol delegates to specialized damaged descent. Otherwise motion 0x26 uses flags 0x18001, frame zero, speed one, zero blend, clamps drift and calls the feedback hook with 8/0. CliffWait expiration and heavy-item ground loss are verified callers.

Anim is inert. IASA checks no held Hammer before its seven ordered handlers and horizontal-stick tumble cancel. ftCo_800D7100 can pick up an item. ftCo_800D705C can set x209C without changing motion; true means handled input, not necessarily transition. JumpAerial dispatch distinguishes multijump. Trailing Hammer release/drop and HammerFall entry checks run only after no previous early return. Phys uses shared fast-fall/gravity/aerial movement. Coll supplies a landing callback that prioritizes directional tech, neutral tech, then DownBound; shared collision also has wall-jump/ledge-grab fallbacks.

Both existing ELF objects contain eight bytes 000000003f800000. Source flags WRITE|ALLOC differ from split ALLOC. Assembly also uses zero for IASA ABS; no additional conversion constants exist in this pool. No build ran; frozen report hash agrees.

Evidence is enumerated with exact ranges in coverage.json and fact-dispositions.json. All {len(ld)} original outgoing link records are retained individually, with endpoints, role, rationale and locators preserved.
''')
(D/'naming.md').write_text('# Naming review\n\nRetain inferred hypotheses ftCo_InitDamageModelShift, ftCo_Damage_GetModelShift, ftCo_PlayPendingDamageSFX and ftCo_DamageFall_Enter. Their source behavior supports each alias. Preserve all canonical identifiers. No new name proposed for the collision adapter. Foreign Hammer helper alias collision and header alias shadowing are rendering issues, not evidence of equivalent functions.\n')
(D/'README.md').write_text(f'# DamageFall review packet\n\nRevision `{R}`. UTC `{start}` to `{end}`. Model `{M["model"]}`, role TU librarian.\n\n26 owned subjects; C144 + H21 lines fully reviewed canonically and rendered. {len(disp)} fact versions: {len(disp)-len(facts)} retain, {len(facts)} corrections. All {len(ld)} outgoing records retained. Two complete owned render receipts; no parser errors.\n\nReview functionality.md, naming.md, coverage.json, fact-dispositions.json, link-dispositions.json and section-evidence.json. Proposal is dry-run only. No source, KB or build edits.\n')
print(len(disp),len(facts),len(ld),end)
