import json,hashlib
from pathlib import Path
D=Path('docs/.drafts/melee-semantic-20260908/main__melee__lb__lbmemory');M=Path('games/melee/state/knowledge_v2/semantic-sweep-20260908/manifest.json');m=json.loads(M.read_text());c=json.loads((D/'context.json').read_text());fs=json.loads((D/'facts.json').read_text());tu=c['task']['tu'];path=c['task']['source_path'];rev=m['head_revision']
rows={
'.bss':(12,50,'Allocator singleton lbMemory_804318B0 has asserted size 0x6F0 and contains arena bounds, 131 MemEntry descriptors, six heap Handles, free lists, current/peak allocation counts, installed heap x69C, copy manager and compaction callback state.'),
'.data':(186,187,'Canonical source contains invalid-free diagnostic text and assertion sites; exact placement and membership in .data require pinned object-section evidence.'),
'.sdata':(63,70,'Canonical source contains assertion expressions, but exact small-data section membership and the inherited 24-byte aggregate claim require pinned object-section evidence.'),
'lbMemory_80014E24':(80,83,'Creates an empty bounded heap through new_handle: requires free_heap, optionally checks sub-0x80000000 bounds against saved arena bounds, pops a descriptor, sets low/high bounds and clears linkage and allocation head.'),
'lbMemory_80014EEC':(85,97,'Asserts a non-null heap, returns every child allocation record to free_mem while decrementing live count, and returns the heap descriptor to free_heap. It does not clear a caller reference or the installed singleton reference.'),
'lbMemory_80014F7C':(99,115,'Sums unsigned gaps before, between and after address-ordered allocations, treating heap x8_hi as the upper bound and child x8_hi as size. Empty heaps return high minus low; no state is written.'),
'lbMemory_80014FC8':(117,170,'Rounds size upward with (size+31)&0xFFFFFFE0, scans list gaps, and selects the least leftover no greater than the initial 0x40000000 threshold. Equal candidates replace earlier ones. Requires a free descriptor and candidate, inserts a child with address and size, increments live count and raises peak count if needed.'),
'lbMemFreeToHeap':(171,188,'Finds a child whose base equals the supplied address, unlinks it, returns its descriptor to free_mem and decrements live count. An absent address is reported and asserted; no payload bytes are cleared.'),
'fn_80015184':(190,214,'Copies min(size-offset,0x19000) bytes through memcpy using singleton transfer state. Completion clears size before invoking cb(0,cb_arg,0,0); otherwise recreates and schedules the alarm for a requested 3ms delay. Alarm/context arguments are unused.'),
'lbMemory_8001529C':(216,237,'Stores the client callback and argument and starts a packed cursor at heap low. Scans contiguous children; the first displaced child enters lbMemory_80015320 and returns1. An empty or fully packed list returns0 without invoking the callback, but the global callback/cursor state has still been replaced.'),
'lbMemory_80015320':(256,299,'Requires cancelflag false. A null handle invokes the retained client callback. An already packed child advances the cursor and recurses synchronously. A displaced child receives its new base before transfer; the cursor advances by size, and rounded transfer length goes to HSD_DevComRequest for destinations below0x80000000 or start_ram_copy otherwise. The next child is completion context.'),
'lbMemory_800154BC':(301,305,'Copies saved a_arenaLo and a_arenaHi into uintptr_t outputs without changing allocator state or checking output pointers.'),
'lbMemory_800154D4':(307,311,'Creates an empty heap through new_handle, overwrites installed handle x69C and returns it. The wrapper itself neither destroys a previous installed heap nor restricts arguments to ARAM addresses.'),
'lbMemory_800155A4':(313,330,'Requires installed handle x69C, returns all its allocation records to free_mem with count decrements, returns the heap to free_heap and clears x69C.'),
'lbMemory_8001564C':(336,371,'Stores ARAlloc(0x20) result as arena low and calls ARFree, chooses min(ARGetSize(),0x01000000) as high, links131 allocation records and six heap records, zeros allocation counts, creates the initial installed heap from saved bounds and clears copy-manager size. Five heap descriptors remain free after creation.'),
'file':(12,371,'Implements pooled bounded heaps, 32-byte size rounding, best-fit allocation, free-capacity accounting, descriptor reclamation and asynchronous compaction. Allocation metadata stores base and size in overloaded Handle fields. One singleton retains installed heap, allocator counts, completion callback, packed cursor and alarm-driven copy state.')}
def ev(n):
 a,b,_=rows[n];ranges=[(path,a,b)];extras={'lbMemory_80014E24':[(path,63,78)],'lbMemory_800154D4':[(path,63,78)],'fn_80015184':[(path,239,254)],'lbMemory_80015320':[(path,239,254)],'lbMemory_8001529C':[(path,256,299)],'.bss':[(path,336,371)],'lbMemory_80014F7C':[('src/melee/lb/lbmemory.h',6,12)],'lbMemory_80014FC8':[('src/melee/lb/lbmemory.h',6,12)]}
 ranges+=extras.get(n,[])
 return [{'kind':'code','locator':f'code://{rev}/{p}#L{a}-L{b}','why':'Canonical definitions, local helper and state writes support the claim.'} for p,a,b in ranges]
foreign={('lbMemory_80014EEC','data_flow'),('lbMemory_80014EEC','state_behavior'),('lbMemory_80014F7C','data_flow'),('lbMemory_80014FC8','data_flow'),('lbMemory_8001529C','state_behavior'),('lbMemory_800154BC','data_flow'),('lbMemory_800154BC','state_behavior'),('lbMemory_800154D4','data_flow'),('lbMemory_800154D4','state_behavior'),('lbMemory_800155A4','data_flow'),('lbMemory_800155A4','state_behavior'),('lbMemory_8001564C','data_flow')}
proposal={'tu':tu,'proposal':{'facts':[],'links':[],'entities':[],'merges':[],'follow_ups':[]}};dd=[];subjects=[]
for s,rr in fs.items():
 subj={'entity_locator':s} if s==path or '#' in s else {'target_stable_key':s};n='file' if s==path else s.split(':')[-1];subjects.append({'subject':subj,'fact_count':len(rr),'disposition':'reviewed_empty' if not rr else 'reviewed','summary':rows[n][2] if n in rows else 'Parameter entity has no inherited facts.'})
 for f in rr:
  typ=f['type'];d='retain';reason='Local canonical implementation supports the claim.';v=None
  if n in ['.data','.sdata']:d='unresolved';reason='Canonical text does not prove exact linker-section assignment or aggregate byte size; section mapping requires pinned object evidence.'
  elif typ=='game_mapping':d='unresolved';reason='Higher-layer consumer, startup ordering, scene or preload roles require caller-family evidence.'
  elif typ=='purpose' or (n,typ) in foreign:d='supersede';v=rows[n][2];reason='State exact local operations without unreviewed caller behavior.'
  elif typ=='inferred_name':
   if n in ['lbMemory_800154D4','lbMemory_800155A4']:d='unresolved';reason='ARAM-specific alias overstates wrappers that operate on whichever heap is installed; consumer restrictions require family review.'
   else:v=f['value'];reason='Address-named canonical symbol remains authoritative; retain this behavior-supported reading aid.'
  elif n=='lbMemory_80015320' and typ=='inferred_type':d='supersede';v='Exact static signature void lbMemory_80015320(int arg0,int _handle,void* arg2,bool cancelflag). _handle is cast to Handle*; arg0 and arg2 are unused, cancelflag must be false, and completion continues from the supplied next allocation.';reason='Use canonical C argument types rather than an inferred integer/pointer callback signature.'
  elif n=='lbMemory_80014FC8' and typ=='state_behavior':d='supersede';v=rows[n][2];reason='Capture finite initial leftover threshold, tie choice and exact rounding instead of unrestricted best-fit wording.'
  elif n in ['file','.bss'] and typ=='state_behavior':d='supersede';v='Descriptor lifecycles and counts follow allocation/free operations. The copy manager permits one nonzero-size transfer; each callback copies at most0x19000 bytes and requests another alarm after3ms if incomplete. The source requests delays but does not establish exact elapsed scheduling intervals.';reason='Distinguish requested alarm delay from guaranteed throughput.'
  dd.append({'subject':subj,'fact_id':f['id'],'fact_version':{'updated_at':f['updated_at']},'type':typ,'prior_value':f['value'],'disposition':d,'reason':reason,'evidence':ev(n)})
  if v is not None:proposal['proposal']['facts'].append({'subject':subj,'type':typ,'op':'write','value':v,'rationale':reason,'confidence':f['confidence'] if typ=='inferred_name' else 0.97,'evidence':ev(n)})
reads=[]
for ext,a,b in [('c',1,240),('c',241,375),('h',1,26)]:
 p=M.parent/'units'/c['task']['id']/'pages'/f'src__melee__lb__lbmemory.{ext}.{a}-{b}.json';r=json.loads(p.read_text())['rendered'];reads.append({'path':r['path'],'canonical_range':[a,b],'rendered_range':[a,b],'artifact':str(p),'artifact_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'source_sha256':r['source_sha256'],'status':r['status'],'next_line':r['next_line'],'parse_errors':r['parse_errors'],'substitutions':r['substitutions']})
counts={'files_expected':2,'files_reviewed':2,'canonical_lines':401,'rendered_lines':401,'targets_expected':15,'targets_reviewed':15,'functions':12,'data_sections':3,'subjects_expected':37,'subjects_reviewed':37,'empty_parameter_entities':21,'inherited_facts':len(dd),'proposal_operations':len(proposal['proposal']['facts']),'dispositions':{d:sum(x['disposition']==d for x in dd) for d in ['retain','supersede','reject','unresolved']}}
followups=[{'topic':'lbHeap and preload integration','status':'pending_family','reason':'Caller lifecycle, scene transition roles, installed-heap address restrictions and compaction completion assumptions require consumer review.'},{'topic':'Linker diagnostic section membership','status':'unresolved','reason':'All eight inherited .data/.sdata facts require pinned object layout evidence beyond canonical string/assertion sites.'},{'topic':'Copy and DevCom semantics','status':'pending_family','reason':'RAM relocation calls memcpy even when downward relocation ranges can overlap; exact Runtime memcpy and DevCom cancellation/failure behavior need separate owners.'},{'topic':'Rendered parser behavior','status':'read_exception_recorded','reason':'Both C pages returned ok with5 parse errors, mostly parse_uncertain aliases. Header has zero parse errors but three shadowed_binding names. Complete canonical and rendered text was reviewed.'}]
findings={'campaign':m['campaign_id'],'tu':tu,'head_revision':rev,'utc_start':(D/'start.txt').read_text().strip(),'manifest_sha256':hashlib.sha256(M.read_bytes()).hexdigest(),'files':c['files'],'reads':reads,'read_exceptions':[followups[-1]],'targets':[{'canonical_name':n,'range':[a,b],'summary':v,'evidence':ev(n)} for n,(a,b,v) in rows.items() if n!='file'],'subjects':subjects,'fact_dispositions':dd,'followups':followups,'counts':counts,'uncertainty':['Single global compaction callback and cursor are overwritten even on no-move requests; no global overlap guard exists in the entry point.','Allocation rounds size, not arena start. Zero requests and size overflow are not rejected here.','Exact diagnostic strings cannot be assigned to .data versus .sdata from C alone.'],'status':'local_review_complete_pending_independent_review'}
for n,j in [('findings.json',findings),('proposal.json',proposal),('followups.json',followups)]: (D/n).write_text(json.dumps(j,indent=2)+'\n')
print(counts)
