import json,pathlib,hashlib,datetime,struct,shutil
D=pathlib.Path(__file__).parent;S=pathlib.Path('games/melee/state/knowledge_v2/semantic-sweep-20260908');M=json.load(open(S/'manifest.json'));R=M['head_revision'];root=pathlib.Path(M['checkout_root']);tu='main/melee/ft/kinds/ftCommon/ftCo_09C4';P='src/melee/ft/kinds/ftCommon/ftCo_09C4.c';C=json.load(open(D/'context.json'));X=json.load(open(D/'baseline-facts.json'));start='2026-09-08T15:07:02Z';U=S/'units'/C['task']['id']
def c(p,a,b):return f'code://{R}/{p}#L{a}-L{b}'
foreign=[('src/melee/ft/kinds/ftCommon/ftCo_Pass.c',26,36),('src/melee/ft/kinds/ftCommon/ftCo_Pass.c',76,87),('src/melee/ft/kinds/ftCommon/ftCo_Shouldered.c',28,41),('src/melee/ft/ftanim.c',490,514),('src/melee/ft/ftcommon.c',515,525),('src/melee/ft/ftcommon.c',457,460),('src/melee/mp/mpcoll.c',4502,4510),('src/melee/ft/kinds/ftCommon/ftCo_CargoWait.c',52,59),('src/melee/ft/kinds/ftCommon/ftCo_CargoWalk.c',42,49),('src/melee/ft/kinds/ftCommon/ftCo_CargoFall.c',16,29),('src/melee/ft/kinds/ftDonkey/ftdonkey.c',151,161),('src/melee/ft/kinds/ftDonkey/ftdonkey.c',217,227),('src/melee/ft/fighter.c',1068,1078),('src/melee/ft/fighter.c',1223,1246)]
fr=[]
for p,a,b in foreign:
 t=(root/p).read_text();fr.append(dict(path=p,start_line=a,end_line=b,sha256=hashlib.sha256(t.encode()).hexdigest(),canonical_read=True,rendered_read=False,ownership='foreign evidence only'));(D/(p.replace('/','__')+f'.{a}-{b}.txt')).write_text('\n'.join(f'{i}: {l}' for i,l in enumerate(t.splitlines(),1) if a<=i<=b))
E=[c(P,11,28)]+[c(p,a,b) for p,a,b in foreign]
report=root/'build/GALE01/report.json';rh=hashlib.sha256(report.read_bytes()).hexdigest();assert rh==M['report_sha256'];unit=next(u for u in json.load(open(report))['units'] if u['name']==tu);objects=[]
for typ in ['src','obj']:
 p=root/f'build/GALE01/{typ}/melee/ft/kinds/ftCommon/ftCo_09C4.o';b=p.read_bytes();e='>' if b[5]==2 else '<';off=struct.unpack_from(e+'I',b,32)[0];sz,n,si=struct.unpack_from(e+'HHH',b,46);sh=[struct.unpack_from(e+'10I',b,off+i*sz) for i in range(n)];st=sh[si];names=b[st[4]:st[4]+st[5]]
 for s in sh:
  if names[s[0]:].split(b'\0')[0]==b'.sdata2':objects.append(dict(path=str(p),sha256=hashlib.sha256(b).hexdigest(),section='.sdata2',size=s[5],bytes_hex=b[s[4]:s[4]+s[5]].hex()))
json.dump(dict(report_path=str(report),report_sha256=rh,pinned_report_hash_matches=True,unit=unit,objects=objects),open(D/'section-evidence.json','w'),indent=2)
print('section evidence',objects,unit.get('sections'))
rows=[];disp=[]
for s in X:
 rows.append(dict(subject=s['subject'],status='reviewed' if s['facts'] else 'reviewed_no_existing_facts',fact_count=len(s['facts']),evidence=E,notes='No speculative source-to-register parameter mapping.'))
 for f in s['facts']:
  reason='Canonical local control flow plus bounded caller/callee evidence supports the existing claim. Preserve without citation-only rewrite.'
  if f['type']=='inferred_name':reason='Retain as a hypothesis: cargo IASA callers, CargoFall sibling and shouldered-victim update support the existing cargo-pass label. No canonical rename proposed.'
  disp.append(dict(subject=s['subject'],fact_id=f['id'],version=f['updated_at'],type=f['type'],old_value=f['value'],disposition='retain',reason=reason,evidence=E))
end=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z');reads=[json.loads(l) for l in open(U/'reads.jsonl') if json.loads(l).get('reader')=='ftCo_09C4']
json.dump(dict(tu=tu,proposal=dict(facts=[],links=[],entities=[],merges=[],follow_ups=[])),open(D/'proposal.json','w'),indent=2)
json.dump(dict(revision=R,start_utc=start,end_utc=end,counts=dict(retain=len(disp)),dispositions=disp),open(D/'fact-dispositions.json','w'),indent=2)
json.dump(dict(campaign=M['campaign_id'],tu=tu,revision=R,role='TU librarian',model=M['model'],reasoning_effort=M['reasoning_effort'],start_utc=start,end_utc=end,input_files=C['files'],canonical_and_rendered_receipts=reads,foreign_evidence_reads=fr,subjects=rows,counts=dict(targets=3,source_entities=1,parameter_entities=2,existing_facts=len(disp),proposal_facts=0,owned_lines=41),exceptions=[],section_evidence='section-evidence.json'),open(D/'coverage.json','w'),indent=2)
json.dump(dict(unresolved=[],family_followups=['Cargo attributes, Fighter flags, platform line flags and animation internals are foreign evidence only; their shared subjects were not assigned here.']),open(D/'unresolved.json','w'),indent=2)
(D/'functionality.md').write_text(f'# Cargo platform drop\n\nDraft at `{R}`.\n\nThe public predicate `ftCo_8009C4F8` delegates to the common Pass input test. That test requires left-stick Y at or below the negative common threshold, tilt age strictly below its threshold, and a platform floor flag. Failure returns false without a local transition. Success invokes the private entry helper and returns true. CargoWait and CargoWalk IASA call this after two higher-priority tests and stop lower-priority dispatch when it succeeds.\n\n`ftCo_8009C540` reads the carrier from gobj, enters cargo motion base plus six through the common Pass setup with no preservation flags and frame zero, requests animation rate zero, and sends victim_gobj to the ShoulderedWait updater. The sibling CargoFall routine uses the same base-plus-six slot. Donkey state-table entries attach CargoWait and CargoFall callbacks to the corresponding carry states.\n\nThe Pass helper makes the carrier airborne, clamps horizontal drift, assigns common x46C to self_vel.y, changes motion at speed one, records the current floor as floor_skip, and sets tilt age to 0xFE. Motion entry clears x2223_b0; only FreezeState re-enables it in the inspected setup, and this caller passes no flags. Therefore the subsequent zero-rate request reaches the active rate setter, which writes both animation hierarchies and frame_speed_mul. The rate API can defer in other contexts; that does not require changing the existing fact for this call.\n\nThe victim updater is idempotent when the victim already occupies ShoulderedWait. Otherwise it changes the victim state, using its linked carrier as alternate animation source, then applies common shouldered setup and accessory callback. The local executor assumes valid cargo attributes and victim pointers; it has no local eligibility or null guard. The zeroed 16-byte local array is not gameplay state.\n\nThe header exposes only the Boolean predicate. A static forward declaration gives the entry helper internal linkage despite the unadorned definition. Existing inferred names and the source-module alias remain hypotheses.\n\nThe .sdata2 claim is corroborated by existing object bytes, the frozen report hash and the two zero arguments. No build was run.\n\n## Evidence\n\n'+'\n'.join('- '+e for e in E)+'\n')
(D/'naming.md').write_text('# Naming review\n\n| Subject | Existing hypothesis | Decision |\n|---|---|---|\n| ftCo_8009C4F8 | ftCo_CargoPass_CheckInput | Retain: cargo IASA command gate. |\n| ftCo_8009C540 | ftCo_CargoPass_Enter | Retain: private cargo-pass executor. |\n| Source entity | ftCo_CargoPass.c | Retain as a module-name hypothesis. |\n| .sdata2 | None | No name needed for the zero literal. |\n\nNo canonical names or files changed.\n')
(D/'README.md').write_text(f'# ftCo_09C4 review packet\n\nRevision `{R}`. UTC `{start}` to `{end}`. Model `{M["model"]}`, role TU librarian.\n\nComplete canonical and separate rendered coverage: C1-30 and H1-11. Three targets, one source entity and two empty parameter entities covered; all {len(disp)} fact IDs/versions retained. No corrections proposed. Zero parser errors and no failed/empty renders.\n\nRead functionality.md and naming.md; audit coverage.json, fact-dispositions.json, section-evidence.json and unresolved.json. No source, KB or build edits.\n')
print('facts',len(disp),'end',end)
